### ISSUE TITLE
Cyclic dependency on macro expansion

### ISSUE THREAD

**Issue by adpi2** [lampepfl/dotty#10012]
## Minimized code

I have this macro definition in one file

```scala
import scala.quoted._

inline def printExpr[T](inline expr: T): Unit =
  ${ printExpr('expr) }

private def printExpr[T](expr: Expr[T])(using QuoteContext): Expr[Unit] =
  '{ println( ${Expr(expr.foo) } ) }
```
And those `foo` and `test` methods in another file.

```scala
extension [T](a: T) def foo: String = a.toString

@main def test = printExpr(Some(1).foo)
```
Note that `foo` is called in `test` and inside the `macro`.

## Output

```
[error] -- Error: /home/adpi2/test/src/main/scala/macros/App.scala:5:26 
[error] 5 |@main def test = printExpr(Some(1).foo)
[error]   |                 ^^^^^^^^^^^^^^^^^^^^^^
[error]   |Exception occurred while executing macro expansion.
[error]   |java.lang.NoClassDefFoundError: alabast/macros/App$package$
[error]   |	at alabast.macros.Assert$package$.printExpr$$anonfun$2$2$$anonfun$1(Assert.scala:11)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:83)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1302)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1367)
[error]   |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1367)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1268)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:122)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleExpr(PickledQuotes.scala:60)
[error]   |	at dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface.unpickleExpr(ReflectionCompilerInterface.scala:42)
[error]   |	at dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface.unpickleExpr(ReflectionCompilerInterface.scala:41)
[error]   |	at scala.internal.quoted.Unpickler$.unpickleExpr(Unpickler.scala:17)
[error]   |	at alabast.macros.Assert$package$.printExpr(Assert.scala:11)
[error]   |	at alabast.macros.Assert$package$.inline$printExpr(Assert.scala:10)
[error]   |Caused by: java.lang.ClassNotFoundException: alabast.macros.App$package$
[error]   |	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]   |	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]   |	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]   |	at alabast.macros.Assert$package$.printExpr$$anonfun$2$2$$anonfun$1(Assert.scala:11)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:83)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1302)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1367)
[error]   |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1367)
[error]   |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1268)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:122)
[error]   |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleExpr(PickledQuotes.scala:60)
[error]   |	at dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface.unpickleExpr(ReflectionCompilerInterface.scala:42)
[error]   |	at dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface.unpickleExpr(ReflectionCompilerInterface.scala:41)
[error]   |	at scala.internal.quoted.Unpickler$.unpickleExpr(Unpickler.scala:17)
[error]   |	at alabast.macros.Assert$package$.printExpr(Assert.scala:11)
[error]   |	at alabast.macros.Assert$package$.inline$printExpr(Assert.scala:10)
[error]   |	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]   |	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]   |	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]   |	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]   |	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretedStaticMethodCall$$anonfun$2$$anonfun$1(Splicer.scala:328)
[error]   |	at dotty.tools.dotc.transform.Splicer$Interpreter.stopIfRuntimeException(Splicer.scala:388)
[error]   |	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretedStaticMethodCall$$anonfun$1(Splicer.scala:328)
[error]   |	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretTree(Splicer.scala:253)
[error]   |	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretTree$$anonfun$4(Splicer.scala:273)
[error]   |	at dotty.tools.dotc.transform.Splicer$.$anonfun$2(Splicer.scala:53)
[error]   |	at scala.Option.fold(Option.scala:263)
[error]   |	at dotty.tools.dotc.transform.Splicer$.splice(Splicer.scala:53)
[error]   |	at dotty.tools.dotc.typer.Inliner.dotty$tools$dotc$typer$Inliner$$expandMacro(Inliner.scala:1413)
[error]   |	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1240)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2456)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error]   |	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:60)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2461)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error]   |	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2583)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.Inliner.op$proxy3$1(Inliner.scala:736)
[error]   |	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:752)
[error]   |	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:125)
[error]   |	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$4(Typer.scala:3254)
[error]   |	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3362)
[error]   |	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3586)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy25$1(Typer.scala:2917)
[error]   |	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2918)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1228)
[error]   |	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1215)
[error]   |	at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1228)
[error]   |	at dotty.tools.dotc.typer.Namer.rhsType$1$$anonfun$1(Namer.scala:1362)
[error]   |	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:217)
[error]   |	at dotty.tools.dotc.typer.Namer.rhsType$2(Namer.scala:1362)
[error]   |	at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1373)
[error]   |	at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1374)
[error]   |	at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1385)
[error]   |	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1393)
[error]   |	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1478)
[error]   |	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:684)
[error]   |	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:801)
[error]   |	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:712)
[error]   |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:166)
[error]   |	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
[error]   |	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
[error]   |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:364)
[error]   |	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2398)
[error]   |	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2423)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2516)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2612)
[error]   |	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2661)
[error]   |	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2118)
[error]   |	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2444)
[error]   |	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2448)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2516)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2612)
[error]   |	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2661)
[error]   |	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2242)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2488)
[error]   |	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error]   |	at dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error]   |	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error]   |	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2705)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
[error]   |	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
[error]   |	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]   |	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]   |	at scala.collection.immutable.List.foreach(List.scala:333)
[error]   |	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
[error]   |	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
[error]   |	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]   |	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]   |	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error]   |	at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
[error]   |	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
[error]   |	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]   |	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
[error]   |	at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
[error]   |	at dotty.tools.dotc.Run.compileUnits(Run.scala:147)
[error]   |	at dotty.tools.dotc.Driver.finish$1(Driver.scala:48)
[error]   |	at dotty.tools.dotc.Driver.doCompile(Driver.scala:51)
[error]   |	at dotty.tools.dotc.Driver.process(Driver.scala:195)
[error]   |	at dotty.tools.dotc.Main.process(Main.scala)
[error]   |	at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error]   |	at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error]   |	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
[error]   |	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]   |	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]   |	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
[error]   |	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:113)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:185)
[error]   |	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:240)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:175)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:156)
[error]   |	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:232)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:156)
[error]   |	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:203)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:571)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:571)
[error]   |	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error]   |	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error]   |	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error]   |	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]   |	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]   |	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]   |	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error]   |	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error]   |	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error]   |	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error]   |	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:571)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:489)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:419)
[error]   |	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]   |	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2139)
[error]   |	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2099)
[error]   |	at sbt.internal.io.Retry$.apply(Retry.scala:40)
[error]   |	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]   |	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error]   |	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2096)
[error]   |	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]   |	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]   |	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]   |	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]   |	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]   |	at sbt.Execute.work(Execute.scala:291)
[error]   |	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]   |	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]   |	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]   |	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   |	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]   |	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   |	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]   |	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]   |	at java.base/java.lang.Thread.run(Thread.java:834)
[error]   |
[error]   | This location contains code that was inlined from App.scala:5
```

## Expectation

I dont really know what is the expected output.
If I move the definition of `foo` to a separate file it does compile and run as expected.

**Comment by nicolasstucki** [comment]
@adpi2 how did you compile it? I could not reproduce it. I did update to the new extension methods, maybe that was the issue.

**Comment by adpi2** [comment]
@nicolasstucki I reproduced the bug with the code you pushed as a regression test.

See https://github.com/adpi2/dotty-10012
