### ISSUE TITLE
Select.overloaded tasty API. is incomplete.

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#10053]
## Minimized example

Assume, we have the next classes:

```Scala
object X:

  def andThen[A,B](a:A)(f: A => B): B =
     println("totalFunction")
     f(a)

  def andThen[A,B](a:A)(f: PartialFunction[A,B]): Option[B] =
     println("partialFunction")
     f.lift.apply(a)

object Main:

 def main(args:Array[String]):Unit =
    // compiled
    val x1 = X.andThen(1){case x if (x%2 == 0) => x}
    val x2 = Macro.mThen{case x:Int if (x%2 == 0) => x}
```

and we want in macro add overload functions, which are different in the second param list: 

```
package x

import scala.quoted._

object Macro:

    inline def mThen[A,B](inline x:A=>B):B = ${
       mThenImpl[A,B,A=>B,B]('x)
    }

    inline def mThen[A,B](inline x:PartialFunction[A,B]): Option[B] = ${
       mThenImpl[A,B,PartialFunction[A,B],Option[B]]('x)
    }
   
    def mThenImpl[A:Type, B:Type, S<:(A=>B) :Type, R:Type](x:Expr[S])(using qctx: QuoteContext):Expr[R]=
       import qctx.reflect._
       val fun = '{X}.unseal
       val wildcard = TypeBounds(quoted.Type[Nothing].unseal.tpe, quoted.Type[Any].unseal.tpe)
       val firstPart = Select.overloaded(fun,"andThen",
                                 List(TypeIdent(defn.IntClass).tpe, TypeIdent(defn.IntClass).tpe),
                                 List(Literal(Constant.Int(1))),
                       )   
       Apply(firstPart,List(x.unseal)).seal.cast[R]


```

Oops --- no difference in the first argument. overloading by the second list of arguments is impossible

## Output

```scala
[info] Compiling 2 Scala sources to /Users/rssh/tests/dotty/partial-function-overload/target/scala-3.0.0-M1/classes ...
[error] -- Error: /Users/rssh/tests/dotty/partial-function-overload/src/main/scala/x/Main.scala:19:24 
[error] 19 |    val x2 = Macro.mThen{case x:Int if (x%2 == 0) => x}
[error]    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: multiple overloads available for andThen on x.X$ with targs: Int, Int; args: <1:(1 : Int)>; expectedType: PartialFunction[Any, Int] => ?.all alternatives: def andThen: [A, B](a: A)(f: PartialFunction[A, B]): Option[B], def andThen: [A, B](a: A)(f: A => B): B
[error]    |matching alternatives: def andThen: [A, B](a: A)(f: PartialFunction[A, B]): Option[B], def andThen: [A, B](a: A)(f: A => B): B.
[error]    |	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance.applyOverloaded(Trees.scala:1580)
[error]    |	at dotty.tools.dotc.quoted.QuoteContextImpl.dotty$tools$dotc$quoted$QuoteContextImpl$reflect$Select$$$_$overloaded$$anonfun$1(QuoteContextImpl.scala:416)
[error]    |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$.dotty$tools$dotc$quoted$QuoteContextImpl$reflect$$$withDefaultPos(QuoteContextImpl.scala:2608)
[error]    |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$Select$.overloaded(QuoteContextImpl.scala:416)
[error]    |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$Select$.overloaded(QuoteContextImpl.scala:415)
[error]    |	at x.Macro$.mThenImpl(Macro.scala:22)
[error]    |
[error]    | This location contains code that was inlined from Main.scala:19
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

If we add to Select.overloaded argument for return part, it will be possible to search such functions:
```
package x

import scala.quoted._

object Macro:

    inline def mThen[A,B](inline x:A=>B):B = ${
       mThenImpl[A,B,A=>B,B]('x)
    }

    inline def mThen[A,B](inline x:PartialFunction[A,B]): Option[B] = ${
       mThenImpl[A,B,PartialFunction[A,B],Option[B]]('x)
    }
   
    def mThenImpl[A:Type, B:Type, S<:(A=>B) :Type, R:Type](x:Expr[S])(using qctx: QuoteContext):Expr[R]=
       import qctx.reflect._
       val fun = '{X}.unseal
       val wildcard = TypeBounds(quoted.Type[Nothing].unseal.tpe, quoted.Type[Any].unseal.tpe)
       val firstPart = Select.overloaded(fun,"andThen",
                                 List(TypeIdent(defn.IntClass).tpe, TypeIdent(defn.IntClass).tpe),
                                 List(Literal(Constant.Int(1))),
                                 quoted.Type[(S) => R].unseal.tpe
                       )
       Apply(firstPart,List(x.unseal)).seal.cast[R]
```

**Comment by rssh** [comment]
fixed by #10053
