### ISSUE TITLE
user defined anonymous PolyFunction causes crash at ElimPolyFunction, GenBCode

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10075]
## Minimized code

```Scala
val foo = new PolyFunction {}
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at dotty.tools.dotc.transform.ElimPolyFunction.functionTypeOfPoly(ElimPolyFunction.scala:48)
	at dotty.tools.dotc.transform.ElimPolyFunction.transform(ElimPolyFunction.scala:34)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.goForward$1(Denotations.scala:803)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:852)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.goForward$1(Denotations.scala:823)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:852)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.goForward$1(Denotations.scala:823)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:852)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:2043)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:2006)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:265)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:154)
	at dotty.tools.dotc.ast.Trees$.dotty$tools$dotc$ast$Trees$Instance$TreeAccumulator$$_$localCtx$2(Trees.scala:1395)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1478)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1385)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1387)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1420)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1475)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1385)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1387)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1482)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1479)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1385)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1387)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1486)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.traverse(CapturedVars.scala:69)
	at dotty.tools.dotc.transform.CapturedVars$CollectCaptured.runOver(CapturedVars.scala:72)
	at dotty.tools.dotc.transform.CapturedVars.prepareForUnit(CapturedVars.scala:79)
	at dotty.tools.dotc.transform.MegaPhase.prepUnit(MegaPhase.scala:1039)
	at dotty.tools.dotc.transform.MegaPhase.prepUnit(MegaPhase.scala:1039)
	at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:446)
	at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:459)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:147)
	at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:151)
	at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:161)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:233)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:196)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:129)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:132)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:151)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:132)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

**Comment by bishabosha** [comment]
more cases also crash but for different reasons:

```scala
val foo = new PolyFunction {} // error
val bar = new PolyFunction { def bar = 23 } // error
val baz = new PolyFunction { def apply = 23 } // error
val qux = new PolyFunction { def apply[T] = 47 } // error
```

**Comment by bishabosha** [comment]
@nicolasstucki these still crash, I changed assignment because you made changes to PolyFunction recently
