### ISSUE TITLE
Tasty stdlib cannot be loaded by the doctool

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#10143]
When we try to load .tasty files generated by the `stdlib-bootstrapped` project in the doctool, we get a Tasty parse (!) exception:

https://github.com/lampepfl/dotty/runs/1341421259?check_suite_focus=true#step:10:970

```
scala.MatchError: 137 (of class java.lang.Integer)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.readNames$1(TastyClassName.scala:46)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.unpickle(TastyClassName.scala:57)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.unpickle(TastyClassName.scala:26)
	at dotty.tools.dotc.core.tasty.TastyUnpickler.unpickle$$anonfun$1(TastyUnpickler.scala:96)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.dotc.core.tasty.TastyUnpickler.unpickle(TastyUnpickler.scala:96)
	at dotty.tools.dotc.core.tasty.TastyClassName.readName(TastyClassName.scala:22)
	at dotty.tools.dotc.fromtasty.TastyFileUtil$.getClassName(TastyFileUtil.scala:29)
	at dotty.tools.dotc.Driver.$anonfun$1(Driver.scala:104)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at dotty.tools.dotc.Driver.fromTastySetup(Driver.scala:108)
	at dotty.tools.dotc.Driver.setup(Driver.scala:81)
	at dotty.tools.dotc.Driver.process(Driver.scala:193)
	at dotty.tools.dotc.Driver.process(Driver.scala:163)
	at dotty.tools.dotc.Driver.process(Driver.scala:175)
	at scala.tasty.inspector.TastyInspector.inspectFiles(TastyInspector.scala:95)
…
```
/cc @nicolasstucki

**Comment by abgruszecki** [comment]
See changes in the linked PR to find the task responsible for loading stdlib .tasty files.

**Comment by nicolasstucki** [comment]
Maybe you should depend on it the same way we do on the tests

https://github.com/lampepfl/dotty/blob/master/project/Build.scala#L882

**Comment by abgruszecki** [comment]
I don't think that's likely to be the source of the problem. What we do is that we pass Scala3doc the directory with the result of compiling `stdlib-bootstrapped`, and then we effectively pass every `.tasty` file there to TastyInspector. The error happens even if all other projects in the task are commented out.

I think it'd help if we discussed this tomorrow.

**Comment by nicolasstucki** [comment]
There is a failure when trying to get the name of the class of `scala/package.tasty`

**Comment by nicolasstucki** [comment]
Can be reproduced with
```
scalac -from-tasty out/bootstrap/stdlib-bootstrapped/scala-3.0.0-M2/classes/scala/package.tasty
```

**Comment by abgruszecki** [comment]
@nicolasstucki is this expected? I don't remember seeing this error when we tested from-tasty compilation. Is there a gap in how we test `stdlib-bootstrapped`?

I guess that we can circumvent this by manually handling `scala/package`, but I think it's important to know why exactly this wasn't caught by anything other than the doctool.

**Comment by nicolasstucki** [comment]
@abgruszecki I have a fix for this issue in #10153, but some other things fail afterward. Could you have a look at the new issues?

In `stdlib-bootstrapped` we used the jar an input which does not hit this code path. I'm going to extend `stdlib-bootstrapped` to also tests when we pass each `.tasty` individually. I will probably add it on top of #10154.

**Comment by abgruszecki** [comment]
@nicolasstucki what do you exactly mean when you say "things fail afterward"? The CI succeeds and I can't see any commented-out tests, so I guess you mean that running the documentation task still fails when one enables it?

**Comment by nicolasstucki** [comment]
Yes, running the documentation tests still fails if we uncomment 
https://github.com/lampepfl/dotty/commit/ea0deda9db6a41219753cc1888306262ca841ea6#diff-539d15a8d5ba9a01a1724604b56cadf6851c57ec68dcf75a5073b6255d182de7R1498

**Comment by abgruszecki** [comment]
@nicolasstucki alright, I hit a snag with trying to read flags of symbol of `Function`, which asplodes after saying "unsupported operation: complete". Do you expect this is because I tried to read .tasty files for `Function`? Do you have hints on what the actual problem is?

**Comment by nicolasstucki** [comment]
Does not ring a bell
