### ISSUE TITLE
Fail to launch Scala REPL (3.0.0-M1)

### ISSUE THREAD

**Issue by duncanmak** [lampepfl/dotty#10219]
On a Mac, using the Homebrew package:

```
$ scala -version
Starting scala3 REPL...
Dotty compiler version 3.0.0-M1 -- Copyright 2002-2020, LAMP/EPFL
Exception in thread "main" scala.MatchError: ClassInfo(ThisType(TypeRef(NoPrefix,module class lang)), class Enum, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object), TypeRef(ThisType(TypeRef(NoPrefix,module class constant)),trait Constable), AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),trait Comparable),List(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Enum)),type E))), TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable))) (of class dotty.tools.dotc.core.Types$CachedClassInfo)
	at dotty.tools.dotc.core.Definitions.JavaEnumClass(Definitions.scala:723)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:1666)
	at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:830)
	at dotty.tools.repl.ReplDriver.initialCtx(ReplDriver.scala:71)
	at dotty.tools.repl.ReplDriver.resetToInitial(ReplDriver.scala:85)
	at dotty.tools.repl.ReplDriver.<init>(ReplDriver.scala:99)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by smarter** [comment]
JDK 14+ is broken on 3.0.0-M1 (see https://github.com/lampepfl/dotty/issues/10131), use an older release of the JDK or switch to a nightly build of Scala 3.
