### ISSUE TITLE
Simple class hierarchy causes a `OutOfMemoryError: Metaspace` error

### ISSUE THREAD

**Issue by jto** [lampepfl/dotty#10597]
The issue was found while using the REPL and Scala `3.0.0-M2`

### java version:

```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```

## Minimized code

```Scala
trait Foo0 { def encode(i: String): Array[Byte] }
class Foo1(b: Array[Byte]) extends Foo0 { override def encode(i: String): Array[Byte] = b }
final class Foo2 extends Foo1(Array()) {  override def encode(i: String): Array[Byte] = Array('c') }
```

## Output (click arrow to expand)
```scala
[error] (run-main-15) java.lang.OutOfMemoryError: Metaspace
[error] java.lang.OutOfMemoryError: Metaspace
[error]         at java.base/jdk.internal.misc.Unsafe.defineAnonymousClass0(Native Method)
[error]         at java.base/jdk.internal.misc.Unsafe.defineAnonymousClass(Unsafe.java:1225)
[error]         at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:321)
[error]         at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:189)
[error]         at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:504)
[error]         at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
[error]         at java.base/java.lang.invoke.DelegatingMethodHandle$Holder.delegate(DelegatingMethodHandle$Holder)
[error]         at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
[error]         at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:138)
[error]         at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
[error]         at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:259)
[error]         at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:249)
[error]         at dotty.tools.dotc.core.Symbols$.newTypeParams(Symbols.scala:764)
[error]         at dotty.tools.dotc.typer.Applications.isAsSpecific$4(Applications.scala:1525)
[error]         at dotty.tools.dotc.typer.Applications.winsType2$1(Applications.scala:1622)
[error]         at dotty.tools.dotc.typer.Applications.compareWithTypes$1(Applications.scala:1630)
[error]         at dotty.tools.dotc.typer.Applications.compare(Applications.scala:1640)
[error]         at dotty.tools.dotc.typer.Applications.compare$(Applications.scala:236)
[error]         at dotty.tools.dotc.typer.Typer.compare(Typer.scala:92)
[error]         at dotty.tools.dotc.typer.Applications.survivors$1(Applications.scala:1663)
[error]         at dotty.tools.dotc.typer.Applications.narrowMostSpecific(Applications.scala:1670)
[error]         at dotty.tools.dotc.typer.Applications.narrowMostSpecific$(Applications.scala:236)
[error]         at dotty.tools.dotc.typer.Typer.narrowMostSpecific(Typer.scala:92)
[error]         at dotty.tools.dotc.typer.Applications.resolveOverloaded1(Applications.scala:1957)
[error]         at dotty.tools.dotc.typer.Applications.resolve$1(Applications.scala:1741)
[error]         at dotty.tools.dotc.typer.Applications.resolveOverloaded(Applications.scala:1782)
[error]         at dotty.tools.dotc.typer.Applications.resolveOverloaded$(Applications.scala:236)
[error]         at dotty.tools.dotc.typer.Typer.resolveOverloaded(Typer.scala:92)
[error]         at dotty.tools.dotc.typer.Typer.adaptOverloaded$1(Typer.scala:2961)
[error]         at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3582)
[error]         at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2932)
[error]         at dotty.tools.dotc.typer.Typer.tryApply$1(Typer.scala:2844)
```
</details>

**Comment by jto** [comment]
nvm this was just SBT leaking metaspace
