### ISSUE TITLE
Idempotency check failing on dotty

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10739]
We introduced some non-determinism that affects that makes the compilation of dotty itself produce 2 slightly different versions of the bytecode. This is not critical for the generated bytecode but we should find the source of it a patch it.
```
20-12-10T08:37:40.8662546Z [info] Test dotty.tools.dotc.CompilationTests.tastyBootstrap started
2020-12-10T08:39:32.6336091Z Test 'idempotency from tastyBootstrap/tests' failed with output:                
2020-12-10T08:39:32.6339175Z Idempotency test failed between out/tastyBootstrap/dotty1/dotty1/dotty/tools/dotc/core/Definitions.class and out/tastyBootstrap/dotty2/dotty2/dotty/tools/dotc/core/Definitions.class (same tasty)
2020-12-10T08:39:32.6342679Z Exception in thread "main" java.lang.reflect.InvocationTargetException
2020-12-10T08:39:32.6346076Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-10T08:39:32.6350695Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2020-12-10T08:39:32.6355620Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-10T08:39:32.6359294Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-10T08:39:32.6361659Z 	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
2020-12-10T08:39:32.6364207Z 	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
2020-12-10T08:39:32.6366595Z Caused by: java.lang.AssertionError: assertion failed: Failed 1 idempotency checks (out of 756)
2020-12-10T08:39:32.6368988Z 	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
2020-12-10T08:39:32.6371341Z 	at IdempotencyCheck$.checkIdempotency(IdempotencyCheck.scala:70)
2020-12-10T08:39:32.6373232Z 	at Test$.main(BootstrapChecker.scala:4)
2020-12-10T08:39:32.6374830Z 	at Test.main(BootstrapChecker.scala)
2020-12-10T08:39:32.6375857Z 	... 6 more
2020-12-10T08:39:32.6376312Z 
```
https://pipelines.actions.githubusercontent.com/4bcmbJONMmDXxkuH72SOCIIuqA9fMe5SUNnZXFOLaZJl7EmtHA/_apis/pipelines/1/runs/10814/signedlogcontent/10?urlExpires=2020-12-10T10%3A24%3A49.7910925Z&urlSigningMethod=HMACV1&urlSignature=nNO9xx0PvsQpo0C1REMfHRLj4hF8W3UUR%2BlhDx28tCA%3D

**Comment by nicolasstucki** [comment]
```diff
 private scala.collection.immutable.List<dotty.tools.dotc.typer.ImportInfo$RootRef> ScalaRootImportFns();
    Code:
       0: aload_0
       1: getfield      #5612               // Field ScalaRootImportFnsbitmap$1:Z
       4: ifne          112
       7: aload_0
       8: getstatic     #2752               // Field dotty/tools/dotc/config/Settings$Setting$.MODULE$:Ldotty/tools/dotc/config/Settings$Setting$;
      11: aload_0
      12: invokevirtual #1567               // Method dotty$tools$dotc$core$Definitions$$currentContext:()Ldotty/tools/dotc/core/Contexts$Context;
      15: astore_1
      16: aload_1
      17: invokevirtual #2756               // Method dotty/tools/dotc/core/Contexts$Context.settings:()Ldotty/tools/dotc/config/ScalaSettings;
      20: invokevirtual #5606               // Method dotty/tools/dotc/config/ScalaSettings.YnoImports:()Ldotty/tools/dotc/config/Settings$Setting;
      23: aload_0
      24: invokevirtual #1567               // Method dotty$tools$dotc$core$Definitions$$currentContext:()Ldotty/tools/dotc/core/Contexts$Context;
      27: invokevirtual #2766               // Method dotty/tools/dotc/config/Settings$Setting$.value:(Ldotty/tools/dotc/config/Settings$Setting;Ldotty/tools/dotc/core/Contexts$Context;)Ljava/lang/Object;
      30: invokestatic  #2772               // Method scala/runtime/BoxesRunTime.unboxToBoolean:(Ljava/lang/Object;)Z
      33: ifeq          45
      36: getstatic     #1349               // Field scala/package$.MODULE$:Lscala/package$;
      39: invokevirtual #1771               // Method scala/package$.Nil:()Lscala/collection/immutable/Nil$;
      42: goto          94
      45: getstatic     #2752               // Field dotty/tools/dotc/config/Settings$Setting$.MODULE$:Ldotty/tools/dotc/config/Settings$Setting$;
      48: aload_0
      49: invokevirtual #1567               // Method dotty$tools$dotc$core$Definitions$$currentContext:()Ldotty/tools/dotc/core/Contexts$Context;
      52: astore_2
      53: aload_2
      54: invokevirtual #2756               // Method dotty/tools/dotc/core/Contexts$Context.settings:()Ldotty/tools/dotc/config/ScalaSettings;
      57: invokevirtual #5615               // Method dotty/tools/dotc/config/ScalaSettings.YnoPredef:()Ldotty/tools/dotc/config/Settings$Setting;
      60: aload_0
      61: invokevirtual #1567               // Method dotty$tools$dotc$core$Definitions$$currentContext:()Ldotty/tools/dotc/core/Contexts$Context;
      64: invokevirtual #2766               // Method dotty/tools/dotc/config/Settings$Setting$.value:(Ldotty/tools/dotc/config/Settings$Setting;Ldotty/tools/dotc/core/Contexts$Context;)Ljava/lang/Object;
      67: invokestatic  #2772               // Method scala/runtime/BoxesRunTime.unboxToBoolean:(Ljava/lang/Object;)Z
      70: ifeq          80
      73: aload_0
      74: getfield      #1391               // Field ScalaImportFns:Lscala/collection/immutable/List;
      77: goto          94
      80: aload_0
      81: getfield      #1391               // Field ScalaImportFns:Lscala/collection/immutable/List;
      84: aload_0
      85: getfield      #1403               // Field PredefImportFns:Lscala/collection/immutable/List;
      88: invokevirtual #5618               // Method scala/collection/immutable/List.$plus$plus:(Lscala/collection/IterableOnce;)Ljava/lang/Object;
      91: checkcast     #1379               // class scala/collection/immutable/List
      94: putfield      #5620               // Field ScalaRootImportFns$lzy1:Lscala/collection/immutable/List;
      97: aload_0
      98: iconst_1
      99: putfield      #5612               // Field ScalaRootImportFnsbitmap$1:Z
     102: aload_0
     103: aconst_null
-     104: putfield      #1403               // Field PredefImportFns:Lscala/collection/immutable/List;
+     104: putfield      #1391               // Field ScalaImportFns:Lscala/collection/immutable/List;
     107: aload_0
     108: aconst_null
-     109: putfield      #1391               // Field ScalaImportFns:Lscala/collection/immutable/List;
+     109: putfield      #1403               // Field PredefImportFns:Lscala/collection/immutable/List;
     112: aload_0
     113: getfield      #5620               // Field ScalaRootImportFns$lzy1:Lscala/collection/immutable/List;
     116: areturn
```
