### ISSUE TITLE
StaleSymbolError when defining class in REPL

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1088]
Start repl and define a class:

    > doti
    scala> class A

You get:

    dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol; class A#4307 in module class line0$object$$iw$$iw$, defined in Period(1..4, run = 2), is referred to in run Period(46..46, run = 3)
            at dotty.tools.dotc.core.Denotations$SingleDenotation.staleSymbolError(Denotations.scala:753)
            at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:593)
            at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:621)
            at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:682)
            at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:384)
            at dotty.tools.dotc.core.Symbols$.toDenot(Symbols.scala:574)
            at dotty.tools.backend.jvm.DottyBackendInterface$$anon$9.isJavaDefined(DottyBackendInterface.scala:593)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$2.apply(BTypesFromSymbols.scala:128)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$2.apply(BTypesFromSymbols.scala:127)
            at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
            at scala.collection.immutable.List.foreach(List.scala:381)
            at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
            at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
            at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols.scala$tools$nsc$backend$jvm$BTypesFromSymbols$$setClassInfo(BTypesFromSymbols.scala:127)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:63)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:57)
            at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
            at scala.collection.AbstractMap.getOrElse(Map.scala:59)
            at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:57)
            at scala.tools.nsc.backend.jvm.BCodeHelpers$BCInnerClassGen$class.getClassBTypeAndRegisterInnerClass(BCodeHelpers.scala:243)
            at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.getClassBTypeAndRegisterInnerClass(BCodeSkelBuilder.scala:51)
            at dotty.tools.backend.jvm.DottyBackendInterface$$anon$10$$anonfun$primitiveOrClassToBType$1$3.apply(DottyBackendInterface.scala:816)
            at dotty.tools.backend.jvm.DottyBackendInterface$$anon$10$$anonfun$primitiveOrClassToBType$1$3.apply(DottyBackendInterface.scala:816)
            at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
            at scala.collection.AbstractMap.getOrElse(Map.scala:59)
            at dotty.tools.backend.jvm.DottyBackendInterface$$anon$10.primitiveOrClassToBType$1(DottyBackendInterface.scala:815)
            at dotty.tools.backend.jvm.DottyBackendInterface$$anon$10.toTypeKind(DottyBackendInterface.scala:835)
            at scala.tools.nsc.backend.jvm.BCodeHelpers$BCInnerClassGen$class.toTypeKind(BCodeHelpers.scala:272)
            at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.toTypeKind(BCodeSkelBuilder.scala:51)
            at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.symInfoTK(BCodeSkelBuilder.scala:81)

Here is the code seen by the REPL at phase frontend:

    result of <console> after frontend:
    package <empty> {
      final lazy module val line0$object: line0$object$ = new line0$object$()
      final module class line0$object$() extends Object() { 
        this: line0$object.type =>

        final lazy module val $iw: line0$object.$iw$ = new line0$object.$iw$()
        final module class $iw$() extends Object() { this: line0$object.$iw.type => 
          final lazy module val $iw: $iw$ = new $iw$()
          final module class $iw$() extends Object() { this: $iw.type => 
            class A() extends Object() {}
          }
        }
      }
    }
    result of <console> after frontend:
    package <empty> {
      final lazy module val RequestResult$line0$object: RequestResult$line0$object$
         = 
      new RequestResult$line0$object$()
      final module class RequestResult$line0$object$() extends Object() { 
        this: RequestResult$line0$object.type =>

        val result: String = {
          line0$object.$iw.$iw
          "".+("defined class A\n")
        }
      }
    }

It seems that during the second compilation the backend wants to install an inner class, yet
the symbol is not current.  But I am not sure why it want to install the inner class, since neither
the class nor its owning object are compiled during the 2nd run.

**Comment by odersky** [comment]
This is fixed by 973ba2c. Still I wonder why the backend accesses class `A` in the second run. Leaving open for now to give us a chance to find out.

**Comment by DarkDimius** [comment]
> But I am not sure why it want to install the inner class, since neither
the class nor its owning object are **compiled** during the 2nd run.

With current implementation of BTypes, you don't need to compile class to force it's inner classes. Referring to it is already enough.  That's an artifact of current implementation: backend converts the tree of types\scopes to own representation of `BType`s. Converting every particular class to a BType happens lazily, but all fields needed for a `BType` are filled eagerly after BType is requested.

In this case, the second compilation run refers to `line0$object.$iw.$iw` from first compilation run. Converting Dotty representation to `ClassBType` forces computing the list of inner classes, including A that is an inner class of `line0$object.$iw.$iw`.

**Comment by DarkDimius** [comment]
After a discussion we agreed that 973ba2c is an actual bug that required a fix.
It would be good to have back-end force less symbols in future.
