### ISSUE TITLE
REPL: missing span with valid code and -Xprint:<some phase>

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10883]
## Minimized code

The following only crashes when using the REPL with the option `-Xprint:typer`:
```Scala
object Foo {
  object Bar // must be an object
  export Bar._
}
```

## Output (click arrow to expand)
<details>

```scala
scala> object Foo {                                                                                                         
     |   object Bar
     |   export Bar._
     | }
     | 
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at dotty.tools.dotc.util.Spans$Span$.point$extension(Spans.scala:56)
	at dotty.tools.dotc.util.SourcePosition.point(SourcePosition.scala:26)
	at dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:28)
	at dotty.tools.repl.ReplDriver.$anonfun$5(ReplDriver.scala:261)
	at scala.math.Ordering$$anon$1.compare(Ordering.scala:140)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.collection.SeqOps.sorted(Seq.scala:700)
	at scala.collection.SeqOps.sorted$(Seq.scala:692)
	at scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted$(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.List.sorted(List.scala:79)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:264)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:269)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:197)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:133)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:152)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

**Comment by ansvonwa** [comment]
I get the same error in the REPL for `-Xprint:` with any (existing) compiler phase and any (valid) expression.

<details>
<summary>
i.e. `scala -Xprint:erasure` with input `1+1`
</summary>

```scala
$ scala -Xprint:erasure
Starting scala3 REPL...
scala> 1+1
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at dotty.tools.dotc.util.Spans$Span$.point$extension(Spans.scala:56)
	at dotty.tools.dotc.util.SourcePosition.point(SourcePosition.scala:26)
	at dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:28)
	at dotty.tools.repl.ReplDriver.$anonfun$5(ReplDriver.scala:261)
	at scala.math.Ordering$$anon$1.compare(Ordering.scala:140)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1232)
	at scala.collection.SeqOps.sorted(Seq.scala:700)
	at scala.collection.SeqOps.sorted$(Seq.scala:692)
	at scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted$(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.List.sorted(List.scala:79)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:264)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:269)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:197)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:133)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:152)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

**Comment by som-snytt** [comment]
Minimized, it fails on `42`. :)

**Comment by bishabosha** [comment]
thanks both, if there is a type error then apparently there is no issue with printing the trees
