### ISSUE TITLE
Scala Repl crashing when tab completing

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#10937]
## Minimized code

Enter the repl and type the following:

```Scala
scala> import scala.collection._
scala> SortedMap.empty[Int,String] ++ SortedMap(3 -> "hello", 2 -> "world")
scala> // now place cursor after `SortedMap.empty[Int,String]` and start typing `(Ordering[` and press tab
scala> SortedMap.empty[Int,String](Ordering[<Press Tab here ++ SortedMap(3 -> "hello", 2 -> "world")
```

## Output

```scala
scala> SortedMap.empty[Int,String](Ordering[Exception in thread "main" java.lang.AssertionError: assertion failed: denotation module class experimental$ invalid in run 7. ValidFor: Period(1..4, run = 11)
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.updateValidity(Denotations.scala:692)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:717)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.toNewRun$1(Denotations.scala:778)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:852)
        at dotty.tools.dotc.core.Symbols$Symbol.recomputeDenot(Symbols.scala:122)
        at dotty.tools.dotc.core.Symbols$Symbol.computeDenot(Symbols.scala:116)
        at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:109)
        at dotty.tools.dotc.core.Symbols$.toDenot(Symbols.scala:494)
        at dotty.tools.dotc.config.Feature$.toPrefix$1(Feature.scala:28)
        at dotty.tools.dotc.config.Feature$.enabledBySetting(Feature.scala:30)
        at dotty.tools.dotc.config.Feature$.enabled(Feature.scala:55)
        at dotty.tools.dotc.config.Feature$.dependentEnabled(Feature.scala:65)
        at dotty.tools.dotc.parsing.Parsers$Parser.singletonArgs$1(Parsers.scala:1621)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleType(Parsers.scala:1624)
        at dotty.tools.dotc.parsing.Parsers$Parser.annotType(Parsers.scala:1566)
        at dotty.tools.dotc.parsing.Parsers$Parser.withType(Parsers.scala:1550)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$2(Parsers.scala:1537)
        at dotty.tools.dotc.parsing.Parsers$Parser.recur$3(Parsers.scala:979)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixOps(Parsers.scala:992)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixTypeRest(Parsers.scala:1533)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixType(Parsers.scala:1523)
        at dotty.tools.dotc.parsing.Parsers$Parser.typ(Parsers.scala:1470)
        at dotty.tools.dotc.parsing.Parsers$Parser.argType$1(Parsers.scala:1725)
        at dotty.tools.dotc.parsing.Parsers$Parser.argTypes(Parsers.scala:1745)
        at dotty.tools.dotc.parsing.Parsers$Parser.typeArgs$$anonfun$1(Parsers.scala:1781)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:559)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBrackets(Parsers.scala:568)
        at dotty.tools.dotc.parsing.Parsers$Parser.typeArgs(Parsers.scala:1781)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2297)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2287)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:2219)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2203)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2049)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1924)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$7(Parsers.scala:2357)
        at dotty.tools.dotc.parsing.Parsers$Parser.tokenSeparated(Parsers.scala:591)
        at dotty.tools.dotc.parsing.Parsers$Parser.commaSeparated(Parsers.scala:599)
        at dotty.tools.dotc.parsing.Parsers$Parser.parArgumentExprs$$anonfun$1(Parsers.scala:2343)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:559)
        at dotty.tools.dotc.parsing.Parsers$Parser.inParens(Parsers.scala:566)
        at dotty.tools.dotc.parsing.Parsers$Parser.parArgumentExprs(Parsers.scala:2344)
        at dotty.tools.dotc.parsing.Parsers$Parser.argumentExprs(Parsers.scala:2350)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2300)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2298)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2295)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2287)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:2219)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2203)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2049)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1924)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:3890)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:500)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:3904)
        at dotty.tools.dotc.printing.SyntaxHighlighting$.highlight(SyntaxHighlighting.scala:124)
        at dotty.tools.repl.JLineTerminal$Highlighter.highlight(JLineTerminal.scala:79)
        at org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:4059)
        at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3999)
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3867)
        at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2554)
        at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2545)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:713)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
        at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:71)
        at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:118)
        at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:128)
        at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:133)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:152)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:133)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)
```

## Expectation

Not crashing.

Currently this happens with 3.0.0-M3

**Comment by Swoorup** [comment]
Appears to be fixed in 3.0.0-RC1
