### ISSUE TITLE
Dotty Repl OOM's on one-liner input

### ISSUE THREAD

**Issue by emilypi** [lampepfl/dotty#10983]
## Minimized code

```Scala
scala> val I1: Int = 0 * * * 8 * 1 - 1 + 1 +                                    
```

## Output

```scala
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.runtime.IntRef.create(IntRef.java:22)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:182)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize$$anonfun$1(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$786/1712635211.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$1$$anonfun$1(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$853/2081703861.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize$$anonfun$1(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$786/1712635211.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$1$$anonfun$1(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$853/2081703861.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
```

## Expectation

REPL does not OOM. 

For more information, see: https://github.com/lampepfl/dotty/issues/9344.

**Comment by emilypi** [comment]
For context, this is a stock Dotty install, installed via `brew` on the following laptop: 

```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	429.60.3.0.0
  ```

**Comment by odersky** [comment]
@emilipy Some programs OOM. This one is particularly short. That has curiosity value, but is not by itself a bug. If you want to help, it would be good to try to get to the bottom why there is a OOM, and whether that's something that can be fixed.

**Comment by som-snytt** [comment]
Trying it out on the old MacBook with only 8GB, so 2GB heap, OOM with M3, head, scala or scalac, `./bin/scalac` or launched by sbt. Somewhere in the middle, I paused binge-watching episodes of Monk to kill -3, in case anyone looks at the stack and sees something obviously out of sorts.
```
Full thread dump OpenJDK 64-Bit Server VM (15.0.1+9 mixed mode, sharing):

"main" #1 prio=5 os_prio=31 cpu=28548.73ms elapsed=195.61s tid=0x00007fa179008a00 nid=0x1903 runnable  [0x000070000e473000]
   java.lang.Thread.State: RUNNABLE
	at scala.util.control.NonFatal$.apply(NonFatal.scala:41)
	at scala.util.control.NonFatal$.unapply(NonFatal.scala:47)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1273)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:177)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:187)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:128)
	at dotty.tools.dotc.core.TypeComparer.necessarySubType(TypeComparer.scala:139)
	at dotty.tools.dotc.core.TypeComparer$.necessarySubType(TypeComparer.scala:2604)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.necessarilyCompatible(ProtoTypes.scala:47)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.necessarilyCompatible$(ProtoTypes.scala:26)
	at dotty.tools.dotc.typer.Typer.necessarilyCompatible(Typer.scala:101)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult(ProtoTypes.scala:87)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult$(ProtoTypes.scala:26)
	at dotty.tools.dotc.typer.Typer.constrainResult(Typer.scala:101)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult(ProtoTypes.scala:107)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.constrainResult$(ProtoTypes.scala:26)
	at dotty.tools.dotc.typer.Typer.constrainResult(Typer.scala:101)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:357)
	at dotty.tools.dotc.typer.Applications$TestApplication.<init>(Applications.scala:672)
	at dotty.tools.dotc.typer.Applications$ApplicableToTrees.<init>(Applications.scala:679)
	at dotty.tools.dotc.typer.Applications.isApp$1(Applications.scala:1341)
	at dotty.tools.dotc.typer.Applications.isApplicableMethodRef(Applications.scala:1342)
	at dotty.tools.dotc.typer.Applications.isApplicableMethodRef$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.isApplicableMethodRef(Typer.scala:101)
	at dotty.tools.dotc.typer.Applications.narrowByTrees$2$$anonfun$1(Applications.scala:1882)
	at dotty.tools.dotc.typer.Applications$$Lambda$602/0x0000000800f00540.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$2(Decorators.scala:128)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$2(Decorators.scala:131)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$2(Decorators.scala:131)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$2(Decorators.scala:131)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$2(Decorators.scala:131)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.filterConserve$extension(Decorators.scala:142)
	at dotty.tools.dotc.typer.Applications.narrowByTrees$1(Applications.scala:1882)
	at dotty.tools.dotc.typer.Applications.resolveOverloaded1(Applications.scala:1900)
	at dotty.tools.dotc.typer.Applications.resolve$1(Applications.scala:1734)
	at dotty.tools.dotc.typer.Applications.resolveOverloaded(Applications.scala:1773)
	at dotty.tools.dotc.typer.Applications.resolveOverloaded$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.resolveOverloaded(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.adaptOverloaded$1(Typer.scala:2968)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3625)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2939)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2422)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:575)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:600)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2422)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:575)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:600)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2422)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:575)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:600)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2422)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:575)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:600)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2422)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:575)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:600)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2577)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.Typer.$anonfun$33(Typer.scala:2035)
	at dotty.tools.dotc.typer.Typer$$Lambda$537/0x0000000800ece530.apply(Unknown Source)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:216)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2035)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2508)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2688)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2738)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2181)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2519)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2523)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2592)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2688)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2738)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2316)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2564)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2666)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2782)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd$$Lambda$384/0x0000000800e59410.apply$mcV$sp(Unknown Source)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
	at dotty.tools.dotc.typer.FrontEnd$$Lambda$383/0x0000000800e59008.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:185)
	at dotty.tools.dotc.Run$$Lambda$294/0x0000000800e08650.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:195)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:203)
	at dotty.tools.dotc.Run$$Lambda$256/0x0000000800deb3b8.apply$mcV$sp(Unknown Source)
	at scala.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:210)
	at dotty.tools.dotc.Run.compileSources(Run.scala:146)
	at dotty.tools.dotc.Run.compile(Run.scala:130)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:186)
	at dotty.tools.dotc.Driver.process(Driver.scala:155)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.main(Driver.scala:194)
	at dotty.tools.dotc.Main.main(Main.scala)

Heap
 garbage-first heap   total 2097152K, used 2095090K [0x0000000780000000, 0x0000000800000000)
  region size 1024K, 0 young (0K), 0 survivors (0K)
 Metaspace       used 31338K, capacity 33712K, committed 34352K, reserved 1079296K
  class space    used 3890K, capacity 4224K, committed 4224K, reserved 1048576K

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by emilypi** [comment]
@odersky Interesting take! Unfortunately, I am not the one to assign this to, as I have no free time to look at this within anything resembling a meaningful time frame. However, if you wanted to grief a friend, I'm sure @hrhino would love to attack this :)

**Comment by som-snytt** [comment]
Pandemic time means time frames are no longer meaningful.

**Comment by odersky** [comment]
@emilypi It's fine. I had another look. The root cause is that errors get propagated too far. They should truncate implicit searches but don't do it sufficiently well. The compiler is very lenient in that it does not report a type mismatch error if some participant is already erroneous. That's good to cut down on noise. But it also means that implicit searches can get out of hand, because too much is eligible.

**Comment by emilypi** [comment]
Thanks for looking into that @odersky
