### ISSUE TITLE
Crash when passing a noncontextual argument to a context function returning a PolyFunction

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#11166]
## Minimized code

```Scala
trait Foo
given foo: Foo with {}

val f = (foo: Foo) ?=> [A] => (a: A) => a
val x = f("")
```

## Output (click arrow to expand)
<details>

```scala
exception while typing f.apply(tmp$package.foo).apply of class class dotty.tools.dotc.ast.Trees$Select # -1
exception while typing f.apply(tmp$package.foo).apply[String] of class class dotty.tools.dotc.ast.Trees$TypeApply # -1
exception while typing f.apply(tmp$package.foo).apply[String]("") of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing def x: String = f.apply(tmp$package.foo).apply[String]("") of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @scala.annotation.internal.SourceFile(
  "/var/folders/rp/f9y80jvs54lcy26rxnt2y2kw0000gn/T/tmp.scala"
) final module class tmp$package$() extends Object() {
  private def writeReplace(): AnyRef = 
    new scala.runtime.ModuleSerializationProxy(classOf[tmp$package.type])
  final lazy module given val foo: foo$ = new foo$()
  final module class foo$() extends Object(), Foo {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[tmp$package.foo.type])
  }
  def f: (Foo) ?=> PolyFunction{apply: [A](a: A): A} = 
    {
      def $anonfun(using foo: Foo): PolyFunction{apply: [A](a: A): A} = 
        {
          final class $anon() extends Object(), PolyFunction {
            def apply[A](a: A): A = a
          }
          new Object with PolyFunction {...}():PolyFunction{apply: [A](a: A): A}
        }
      closure($anonfun)
    }
  def x: String = f.apply(tmp$package.foo).apply[String]("")
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package <empty> {
  @scala.annotation.internal.SourceFile(
    "/var/folders/rp/f9y80jvs54lcy26rxnt2y2kw0000gn/T/tmp.scala"
  ) trait Foo() extends Object {}
  final lazy module val tmp$package: tmp$package$ = new tmp$package$()
  @scala.annotation.internal.SourceFile(
    "/var/folders/rp/f9y80jvs54lcy26rxnt2y2kw0000gn/T/tmp.scala"
  ) final module class tmp$package$() extends Object() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[tmp$package.type])
    final lazy module given val foo: foo$ = new foo$()
    final module class foo$() extends Object(), Foo {
      private def writeReplace(): AnyRef = 
        new scala.runtime.ModuleSerializationProxy(classOf[tmp$package.foo.type]
          )
    }
    def f: (Foo) ?=> PolyFunction{apply: [A](a: A): A} = 
      {
        def $anonfun(using foo: Foo): PolyFunction{apply: [A](a: A): A} = 
          {
            final class $anon() extends Object(), PolyFunction {
              def apply[A](a: A): A = a
            }
            new Object with PolyFunction {...}():
              PolyFunction{apply: [A](a: A): A}
          }
        closure($anonfun)
      }
    def x: String = f.apply(tmp$package.foo).apply[String]("")
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
exception occurred while compiling /var/folders/rp/f9y80jvs54lcy26rxnt2y2kw0000gn/T/tmp.scala
Exception in thread "main" java.lang.AssertionError: assertion failed:  <none>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:698)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2522)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2613)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2799)
        at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:792)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2571)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2614)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2799)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:814)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2552)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2614)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2799)
        at dotty.tools.dotc.typer.Typer.$anonfun$33(Typer.scala:2056)
        at dotty.tools.dotc.typer.Typer$$Lambda$10260/000000000000000000.apply(Unknown Source)
        at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:219)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2056)
        at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:929)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2529)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2613)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2705)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2755)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2202)
        at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1026)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2540)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2544)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2613)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2705)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2755)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2337)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2585)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2614)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2679)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2799)
        at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:124)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:300)
        at dotty.tools.dotc.core.Phases$Phase$$Lambda$677/000000000000000000.apply(Unknown Source)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:301)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:185)
        at dotty.tools.dotc.Run$$Lambda$357/000000000000000000.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:195)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:203)
        at dotty.tools.dotc.Run$$Lambda$317/000000000000000000.apply$mcV$sp(Unknown Source)
        at scala.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:210)
        at dotty.tools.dotc.Run.compileSources(Run.scala:146)
        at dotty.tools.dotc.Run.compile(Run.scala:130)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:186)
        at dotty.tools.dotc.Driver.process(Driver.scala:155)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.main(Driver.scala:194)
        at dotty.tools.dotc.Main.main(Main.scala)
java.lang.AssertionError: assertion failed:  <none> while compiling /var/folders/rp/f9y80jvs54lcy26rxnt2y2kw0000gn/T/tmp.scal
```
</details>

**Comment by prolativ** [comment]
Seems to be fixed in 3.1.1
