### ISSUE TITLE
Cannot pickle Array of IArrays

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#11353]
## Compiler version

Dotty master 6a5565d5f90050a24451e078901e77dbb22d405a

## Minimized code

```Scala
def iarr = IArray(
  IArray(1, 2, 3),
  IArray(4, 5, 6),
  IArray(7, 8, 9)
)
def arr = Array( // same issue
  IArray(1, 2, 3),
  IArray(4, 5, 6),
  IArray(7, 8, 9)
)
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" scala.MatchError: JavaArrayType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)) (of class dotty.tools.dotc.core.Types$CachedJavaArrayType) while compiling Foo.scala
scala.MatchError: JavaArrayType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)) (of class dotty.tools.dotc.core.Types$CachedJavaArrayType)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:302)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:171)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleConstant(TreePickler.scala:153)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:453)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$38$$anonfun$1(TreePickler.scala:438)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$3(TreePickler.scala:438)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:439)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$38$$anonfun$1(TreePickler.scala:438)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$3(TreePickler.scala:438)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:439)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTreeUnlessEmpty(TreePickler.scala:330)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$1(TreePickler.scala:345)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:347)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:566)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:371)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:371)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$26(TreePickler.scala:592)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:593)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$1(TreePickler.scala:342)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:347)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:568)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:371)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:371)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$29(TreePickler.scala:608)
        at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:69)
        at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:608)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle$$anonfun$1(TreePickler.scala:778)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:778)
        at dotty.tools.dotc.transform.Pickler.run$$anonfun$3$$anonfun$2(Pickler.scala:69)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:106)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:106)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
        at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:111)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
        at dotty.tools.dotc.Run.compileSources(Run.scala:166)
        at dotty.tools.dotc.Run.compile(Run.scala:150)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:186)
        at dotty.tools.dotc.Driver.process(Driver.scala:155)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.main(Driver.scala:194)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by nicolasstucki** [comment]
Self contained
```scala
opaque type A = Array[Int]
object A:
  def a: A = Array(1)

def arr = Array(A.a)
```
