### ISSUE TITLE
Unnoticed syntax error results in ExceptionInInitializerError at runtime

### ISSUE THREAD

**Issue by marcinzh** [lampepfl/dotty#11395]
## Compiler version

3.0.0-M3
3.0.0-M4-bin-20210211-ae7bbd8-NIGHTLY

## Minimized code

```Scala
enum Foo:
  case Bar

  override def toString: String    // <--- Important note: missing '='
    this match
      case Bar => "BAR"

@main def bug: Unit =
  val bar = Foo.Bar    // <--  java.lang.ExceptionInInitializerError
  println(bar)
```

If we change the `toString` method body to different expression, then the program will get compiled without warnings, but will produce result different from intended: as if `toString` wasn't overridden.

```Scala
  override def toString: String    // <--- Important note: still missing '='
    "BAR" + 42                     // <--- Simpler expression (e.g. just "BAR") will trigger unrelated warning.
```

## Output

```scala
java.lang.ExceptionInInitializerError
    at Bug$package$.bug(Bug.scala:10)
    at bug.main(Bug.scala:9)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: scala.MatchError: Bar (of class Foo$$anon$1)
    at Foo.<init>(Bug.scala:6)
    at Foo$$anon$1.<init>(Bug.scala:2)
    at Foo$.$new(Bug.scala:2)
    at Foo$.<clinit>(Bug.scala:2)
    at Bug$package$.bug(Bug.scala:10)
    at bug.main(Bug.scala:9)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

## Expectation

Report some error. Candidates are:

- Complain about abstract method in concrete object ("object creation impossible ...").

- Complain about misaligned indentation.

**Comment by odersky** [comment]
We can't complain about a missing abstract method since `toString` is implemented in `Object`. We might want to complain about the indentation but not now. There's still a lot of Scala 2 code out there that does not respect indentation.
