### ISSUE TITLE
simplified vararg example error

### ISSUE THREAD

**Issue by kpbochenek** [lampepfl/dotty#11419]
## Compiler version

3.0.0-M4-bin-20210214-80befc3-NIGHTLY

## Minimized code
(from docs on unified varargs syntax)

```Scala
    val arr = Array(1, 2, 3)
    val lst = List(0, arr*)                  // vararg splice argument
    lst match {
      case List(0, 1, xs*) => println(xs)   // binds xs to Seq(2, 3)
      case List(1, _*) =>                   // wildcard pattern
    }

```

## Output (click arrow to expand)
<details>

```scala
[error] (run-main-0) java.lang.ClassCastException: [I cannot be cast to scala.collection.immutable.Seq
[error] java.lang.ClassCastException: [I cannot be cast to scala.collection.immutable.Seq
[error] 	at Main$.main(Main.scala:8)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)

```
</details>

It is simple main with code above. Also tried in dotty REPL built from master - same exception.

**Comment by tgodzik** [comment]
`val lst = List(0, arr*)  ` just adds the array as a last element, so probably something we should fix before the release.

**Comment by smarter** [comment]
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val arr: Array[String] = Array("foo")
    val lst: List[String] = List("x", arr: _*)  
    println(lst)
  }
}
```
Scala 2:
```scala
arri.scala:4: error: no `: _*' annotation allowed here
(such annotations are only allowed in arguments to *-parameters)
    val lst: List[String] = List("x", arr: _*)
                                         ^
1 error
```
Scala 3:
```scala
4 |    val lst: List[String] = List("x", arr*)
  |                                      ^^^
  |                                      Found:    (arr : Array[String])
  |                                      Required: String
```

I thought this was fixed by https://github.com/lampepfl/dotty/pull/9963, but somehow that's not enough here.
