### ISSUE TITLE
Compiler inserting `???` with inline and erased terms

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11996]
## Compiler version

`3.0.1-RC1-bin-20210402-775d881-NIGHTLY`

## Minimized code

```Scala
final class UnivEq[A]

object UnivEq:
  erased def force[A]: UnivEq[A] =
    compiletime.erasedValue

extension [A](a: A)
  inline def ==*[B >: A](b: B)(using erased UnivEq[B]): Boolean = a == b
  inline def !=*[B >: A](b: B)(using erased UnivEq[B]): Boolean = a != b

case class I(i: Int)

@main def main = {
  def test[A](a: A, b: A): Unit = {
    erased given UnivEq[A] = UnivEq.force[A]
    assert(a ==* a)
    assert(a !=* b)
  }
  println("Test starting...")
  test(I(1), I(2)) // error
  test(1, 2)
  test(true, false)
}
```

## Output

```
> sbt run

[info] compiling 1 Scala source to ~/scala3bug/sbt/target/scala-3.0.1-RC1/classes ...
[info] done compiling
[info] running main 
Test starting...
[error] (run-main-c) scala.NotImplementedError: an implementation is missing
[error] scala.NotImplementedError: an implementation is missing
[error] 	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:345)
[error] 	at BUG$package$.test$1(BUG.scala:16)
[error] 	at BUG$package$.main(BUG.scala:20)
[error] 	at main.main(BUG.scala:13)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 0 s, completed 6 Apr. 2021, 12:04:35 pm
```

## Expectation

No runtime exception should be thrown. The compiler has inserted a `???` somewhere.

**Comment by odersky** [comment]
I believe the inliner replaces erased definitions with `???`. Before inlining:
```scala
            final lazy given erased val given_UnivEq_A: UnivEq[A] = 
              UnivEq.force[A]
            if ==*[A](a)[A](a)(given_UnivEq_A).unary_! then 
              scala.runtime.Scala3RunTime.assertFailed()
             else ()
```
After inlining:
```scala
            final lazy given erased def given_UnivEq_A: UnivEq[A] = ???
            if 
              {
                val x$3$proxy1: UnivEq[A] = ???
                (a.==(a):Boolean)
              }.unary_!
             then scala.runtime.Scala3RunTime.assertFailed() else ()
```
Inliner should keep the erased references so that they can be flagged as errors in erasure.

**Comment by nicolasstucki** [comment]
`x$3$proxy1` should have been marked as erased as it is the proxy of an erased parameter. That would in turn remove the `???` that was left in the bytecode.
