### ISSUE TITLE
Stack traces and error messages in compiler output when using scaladoc

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#12081]
If I look at the output of a recent CI run like https://github.com/lampepfl/dotty/runs/2332692960, I see stuff like:
```scala
2021-04-13T11:39:49.0926170Z [info] cannot take signature of MethodType(List(sym), List(TypeRef(TermRef(TermRef(TypeRef(ThisType(TypeRef(NoPrefix,module class tasty)),trait BasicSupport),qctx),reflect),Symbol)), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Boolean))
2021-04-13T11:39:49.0933983Z Problem parsing scaladoc/src/dotty/tools/scaladoc/tasty/BasicSupport.scala:[0..20..1991], documentation may not be generated.
2021-04-13T11:39:49.0936647Z dotty.tools.dotc.core.MissingType: 
2021-04-13T11:39:49.0938863Z Variable e1 undefined in comment for method ofTupleFromSeq in module class Expr$
2021-04-13T11:39:49.0941064Z Variable e2 undefined in comment for method ofTupleFromSeq in module class Expr$
2021-04-13T11:39:49.0944015Z 	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:776)
2021-04-13T11:39:49.0947199Z 	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:204)
2021-04-13T11:39:49.0949840Z 	at dotty.tools.dotc.core.Signature.$anonfun$2(Signature.scala:113)
2021-04-13T11:39:49.0952088Z 	at scala.collection.immutable.List.map(List.scala:246)
2021-04-13T11:39:49.0955178Z 	at dotty.tools.dotc.core.Signature.prependTermParams(Signature.scala:113)
2021-04-13T11:39:49.0958503Z 	at dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3398)
2021-04-13T11:39:49.0961321Z 	at dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3415)
2021-04-13T11:39:49.0963987Z 	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:612)
2021-04-13T11:39:49.0966095Z 	at dotty.tools.dotc.core.Denotations$SingleDenotation.matchesLoosely(Denotations.scala:1032)
2021-04-13T11:39:49.0967920Z 	at dotty.tools.dotc.core.Denotations$SingleDenotation.matches(Denotations.scala:1016)
2021-04-13T11:39:49.0969585Z 	at dotty.tools.dotc.core.Denotations$Denotation.mergeDenot$1(Denotations.scala:407)
2021-04-13T11:39:49.0970816Z Variable e1 undefined in comment for method ofSeq in module class Expr$
2021-04-13T11:39:49.0971740Z Variable e2 undefined in comment for method ofSeq in module class Expr$
2021-04-13T11:39:49.0973601Z 	at dotty.tools.dotc.core.Denotations$Denotation.meet(Denotations.scala:493)
2021-04-13T11:39:49.0976461Z 	at dotty.tools.dotc.core.Denotations$DenotUnion.toDenot(Denotations.scala:1212)
2021-04-13T11:39:49.0978188Z 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1985)
2021-04-13T11:39:49.0979705Z 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:671)
2021-04-13T11:39:49.0980777Z 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:858)
2021-04-13T11:39:49.0982131Z 	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:654)
2021-04-13T11:39:49.0983335Z 	at dotty.tools.dotc.core.Types$Type.member(Types.scala:638)
2021-04-13T11:39:49.0984516Z 	at dotty.tools.dotc.core.Types$Type.allMembers$$anonfun$1(Types.scala:999)
2021-04-13T11:39:49.0985885Z 	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
2021-04-13T11:39:49.0987445Z 	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
2021-04-13T11:39:49.0988850Z 	at dotty.tools.dotc.core.Types$Type.memberDenots$$anonfun$1(Types.scala:904)
2021-04-13T11:39:49.0990289Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
2021-04-13T11:39:49.0991806Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
2021-04-13T11:39:49.0993751Z 	at scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:937)
2021-04-13T11:39:49.0995646Z 	at scala.collection.immutable.HashSet.foreach(HashSet.scala:944)
2021-04-13T11:39:49.0997063Z 	at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:904)
2021-04-13T11:39:49.0998239Z 	at dotty.tools.dotc.core.Types$Type.allMembers(Types.scala:999)
2021-04-13T11:39:49.1000200Z 	at dotty.tools.scaladoc.tasty.SyntheticsSupport.hackGetmembers(SyntheticSupport.scala:72)
2021-04-13T11:39:49.1002449Z Variable e1 undefined in comment for method ofList in module class Expr$
2021-04-13T11:39:49.1004302Z Variable e2 undefined in comment for method ofList in module class Expr$
2021-04-13T11:39:49.1017658Z Variable e1 undefined in comment for method ofTupleFromSeq in module class Expr$
2021-04-13T11:39:49.1036520Z Variable e2 undefined in comment for method ofTupleFromSeq in module class Expr$
2021-04-13T11:39:49.1099170Z 	at dotty.tools.scaladoc.tasty.SyntheticsSupport.hackGetmembers$(SyntheticSupport.scala:6)
2021-04-13T11:39:49.1104459Z 	at dotty.tools.scaladoc.tasty.TastyParser.hackGetmembers(TastyParser.scala:171)
2021-04-13T11:39:49.1108846Z 	at dotty.tools.scaladoc.tasty.SyntheticsSupport.getmembers(SyntheticSupport.scala:39)
2021-04-13T11:39:49.1113460Z 	at dotty.tools.scaladoc.tasty.SyntheticsSupport.getmembers$(SyntheticSupport.scala:6)
2021-04-13T11:39:49.1117619Z 	at dotty.tools.scaladoc.tasty.TastyParser.getmembers(TastyParser.scala:171)
2021-04-13T11:39:49.1123407Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.getNonTrivialInheritedMemberTrees(ClassLikeSupport.scala:215)
2021-04-13T11:39:49.1130873Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.getNonTrivialInheritedMemberTrees$(ClassLikeSupport.scala:7)
2021-04-13T11:39:49.1137378Z 	at dotty.tools.scaladoc.tasty.TastyParser.getNonTrivialInheritedMemberTrees(TastyParser.scala:171)
2021-04-13T11:39:49.1142997Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.extractMembers(ClassLikeSupport.scala:220)
2021-04-13T11:39:49.1147916Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.extractMembers$(ClassLikeSupport.scala:7)
2021-04-13T11:39:49.1152598Z 	at dotty.tools.scaladoc.tasty.TastyParser.extractMembers(TastyParser.scala:171)
2021-04-13T11:39:49.1157603Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.extractPatchedMembers(ClassLikeSupport.scala:230)
2021-04-13T11:39:49.1163479Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.extractPatchedMembers$(ClassLikeSupport.scala:7)
2021-04-13T11:39:49.1168979Z Variable  sumExpr('args)  undefined in comment for method unapply in module class Exprs$
2021-04-13T11:39:49.1187031Z Variable  sumExpr('args)  undefined in comment for method unapply in module class Exprs$
2021-04-13T11:39:49.1224769Z 	at dotty.tools.scaladoc.tasty.TastyParser.extractPatchedMembers(TastyParser.scala:171)
2021-04-13T11:39:49.1229940Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.mkClass(ClassLikeSupport.scala:88)
2021-04-13T11:39:49.1234417Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.mkClass$(ClassLikeSupport.scala:7)
2021-04-13T11:39:49.1238498Z 	at dotty.tools.scaladoc.tasty.TastyParser.mkClass(TastyParser.scala:171)
2021-04-13T11:39:49.1242978Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.parseClasslike(ClassLikeSupport.scala:290)
2021-04-13T11:39:49.1247891Z 	at dotty.tools.scaladoc.tasty.ClassLikeSupport.parseClasslike$(ClassLikeSupport.scala:7)
2021-04-13T11:39:49.1252654Z 	at dotty.tools.scaladoc.tasty.TastyParser.parseClasslike(TastyParser.scala:171)
2021-04-13T11:39:49.1256830Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.traverseTree(TastyParser.scala:204)
2021-04-13T11:39:49.1260044Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.foldTree(Quotes.scala:4269)
2021-04-13T11:39:49.1262685Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.foldTree$(Quotes.scala:4265)
2021-04-13T11:39:49.1265689Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTree(TastyParser.scala:192)
2021-04-13T11:39:49.1268966Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTree(TastyParser.scala:192)
2021-04-13T11:39:49.1272216Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees$$anonfun$1(Quotes.scala:4166)
2021-04-13T11:39:49.1275138Z 	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2021-04-13T11:39:49.1278154Z 	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2021-04-13T11:39:49.1281050Z 	at scala.collection.immutable.List.foldLeft(List.scala:79)
2021-04-13T11:39:49.1283997Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees(Quotes.scala:4166)
2021-04-13T11:39:49.1286789Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees$(Quotes.scala:4161)
2021-04-13T11:39:49.1290021Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTrees(TastyParser.scala:192)
2021-04-13T11:39:49.1293366Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldOverTree(Quotes.scala:4227)
2021-04-13T11:39:49.1296434Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldOverTree$(Quotes.scala:4161)
2021-04-13T11:39:49.1300236Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldOverTree(TastyParser.scala:192)
2021-04-13T11:39:49.1303881Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTreeChildren(Quotes.scala:4271)
2021-04-13T11:39:49.1307317Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTreeChildren$(Quotes.scala:4265)
2021-04-13T11:39:49.1311103Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.traverseTreeChildren(TastyParser.scala:192)
2021-04-13T11:39:49.1314554Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTree(Quotes.scala:4267)
2021-04-13T11:39:49.1317598Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTree$(Quotes.scala:4265)
2021-04-13T11:39:49.1320805Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.traverseTree(TastyParser.scala:200)
2021-04-13T11:39:49.1324019Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.foldTree(Quotes.scala:4269)
2021-04-13T11:39:49.1326787Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.foldTree$(Quotes.scala:4265)
2021-04-13T11:39:49.1329950Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTree(TastyParser.scala:192)
2021-04-13T11:39:49.1333438Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTree(TastyParser.scala:192)
2021-04-13T11:39:49.1336745Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees$$anonfun$1(Quotes.scala:4166)
2021-04-13T11:39:49.1339745Z 	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2021-04-13T11:39:49.1342737Z 	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2021-04-13T11:39:49.1345567Z 	at scala.collection.immutable.List.foldLeft(List.scala:79)
2021-04-13T11:39:49.1348447Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees(Quotes.scala:4166)
2021-04-13T11:39:49.1351848Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldTrees$(Quotes.scala:4161)
2021-04-13T11:39:49.1355085Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldTrees(TastyParser.scala:192)
2021-04-13T11:39:49.1358351Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldOverTree(Quotes.scala:4227)
2021-04-13T11:39:49.1361527Z 	at scala.quoted.Quotes$reflectModule$TreeAccumulator.foldOverTree$(Quotes.scala:4161)
2021-04-13T11:39:49.1364835Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.foldOverTree(TastyParser.scala:192)
2021-04-13T11:39:49.1368293Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTreeChildren(Quotes.scala:4271)
2021-04-13T11:39:49.1371715Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTreeChildren$(Quotes.scala:4265)
2021-04-13T11:39:49.1375484Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.traverseTreeChildren(TastyParser.scala:192)
2021-04-13T11:39:49.1378745Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTree(Quotes.scala:4267)
2021-04-13T11:39:49.1381731Z 	at scala.quoted.Quotes$reflectModule$TreeTraverser.traverseTree$(Quotes.scala:4265)
2021-04-13T11:39:49.1384941Z 	at dotty.tools.scaladoc.tasty.TastyParser$Traverser$1$.traverseTree(TastyParser.scala:200)
2021-04-13T11:39:49.1389040Z 	at dotty.tools.scaladoc.tasty.TastyParser.parseRootTree(TastyParser.scala:209)
2021-04-13T11:39:49.1393161Z 	at dotty.tools.scaladoc.tasty.ScaladocTastyInspector.$anonfun$4(TastyParser.scala:120)
2021-04-13T11:39:49.1396777Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
2021-04-13T11:39:49.1399860Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
2021-04-13T11:39:49.1404075Z 	at dotty.tools.scaladoc.tasty.ScaladocTastyInspector.postProcess$$anonfun$2(TastyParser.scala:39)
2021-04-13T11:39:49.1408023Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
2021-04-13T11:39:49.1411017Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
2021-04-13T11:39:49.1414069Z 	at scala.collection.immutable.List.foreach(List.scala:333)
2021-04-13T11:39:49.1418034Z 	at dotty.tools.scaladoc.tasty.ScaladocTastyInspector.postProcess(TastyParser.scala:39)
2021-04-13T11:39:49.1422666Z 	at scala.tasty.inspector.OldTastyInspector$TastyInspectorFinishPhase$1.runOn(OldTastyInspector.scala:91)
2021-04-13T11:39:49.1426547Z 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
2021-04-13T11:39:49.1429138Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
2021-04-13T11:39:49.1432265Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
2021-04-13T11:39:49.1434973Z 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
2021-04-13T11:39:49.1437254Z 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
2021-04-13T11:39:49.1439448Z 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
2021-04-13T11:39:49.1441958Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2021-04-13T11:39:49.1444326Z 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
2021-04-13T11:39:49.1446672Z 	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
2021-04-13T11:39:49.1448901Z 	at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
2021-04-13T11:39:49.1451574Z 	at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:11)
2021-04-13T11:39:49.1454570Z 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
2021-04-13T11:39:49.1456895Z 	at dotty.tools.dotc.Driver.process(Driver.scala:199)
2021-04-13T11:39:49.1460866Z 	at scala.tasty.inspector.OldTastyInspector.inspectFilesInContext(OldTastyInspector.scala:72)
2021-04-13T11:39:49.1466444Z 	at scala.tasty.inspector.OldTastyInspector.inspectFilesInContext$(OldTastyInspector.scala:22)
2021-04-13T11:39:49.1472057Z 	at scala.tasty.inspector.DocTastyInspector.inspectFilesInContext(DocTastyInspector.scala:5)
2021-04-13T11:39:49.1477196Z 	at dotty.tools.scaladoc.tasty.ScaladocTastyInspector.result(TastyParser.scala:151)
2021-04-13T11:39:49.1481780Z 	at dotty.tools.scaladoc.ScalaModuleProvider$.mkModule(ScalaModuleCreator.scala:11)
2021-04-13T11:39:49.1484644Z 	at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:191)
2021-04-13T11:39:49.1486911Z 	at dotty.tools.scaladoc.Scaladoc$.run$$anonfun$1(Scaladoc.scala:72)
2021-04-13T11:39:49.1489596Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
2021-04-13T11:39:49.1492734Z 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
2021-04-13T11:39:49.1495169Z 	at scala.Option.map(Option.scala:242)
2021-04-13T11:39:49.1497100Z 	at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:74)
2021-04-13T11:39:49.1499077Z 	at dotty.tools.dottydoc.Main$.process(Main.scala:25)
2021-04-13T11:39:49.1501242Z 	at dotty.tools.dottydoc.Main.process(Main.scala)
2021-04-13T11:39:49.1504469Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-13T11:39:49.1508915Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
2021-04-13T11:39:49.1514046Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-13T11:39:49.1518054Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2021-04-13T11:39:49.1520244Z 	at xsbt.DottydocRunner.run(DottydocRunner.java:61)
2021-04-13T11:39:49.1522597Z 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
2021-04-13T11:39:49.1525909Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-13T11:39:49.1530713Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
2021-04-13T11:39:49.1536342Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-13T11:39:49.1540579Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2021-04-13T11:39:49.1543542Z 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
2021-04-13T11:39:49.1547016Z 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
2021-04-13T11:39:49.1550269Z 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
2021-04-13T11:39:49.1552520Z 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
2021-04-13T11:39:49.1553898Z 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
2021-04-13T11:39:49.1556329Z 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
2021-04-13T11:39:49.1558821Z 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
2021-04-13T11:39:49.1561394Z 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
2021-04-13T11:39:49.1563682Z 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
2021-04-13T11:39:49.1565975Z 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
2021-04-13T11:39:49.1568046Z 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
2021-04-13T11:39:49.1570438Z 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
2021-04-13T11:39:49.1572580Z 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2147)
2021-04-13T11:39:49.1574855Z 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2021-04-13T11:39:49.1576831Z 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2021-04-13T11:39:49.1577824Z 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
2021-04-13T11:39:49.1579218Z 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
2021-04-13T11:39:49.1581363Z 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
2021-04-13T11:39:49.1583571Z 	at sbt.Execute.work(Execute.scala:291)
2021-04-13T11:39:49.1585097Z 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
2021-04-13T11:39:49.1587576Z 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
2021-04-13T11:39:49.1590388Z 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
2021-04-13T11:39:49.1593084Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-13T11:39:49.1596608Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-04-13T11:39:49.1599642Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-13T11:39:49.1603310Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2021-04-13T11:39:49.1607592Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2021-04-13T11:39:49.1610327Z 	at java.base/java.lang.Thread.run(Thread.java:831)
```
Not only does this make it hard to find actual errors in the output, it also probably means that there's some underlying problem that needs to be fixed here.

**Comment by abgruszecki** [comment]
Those are Tasty issues. We should minimise them and assign them to Nico.

**Comment by abgruszecki** [comment]
We could also just turn off warnings on unexpanded Scaladoc variables. It tickles me the wrong way, but judging from the amount of warnings we got in stdlib, convincing the community to properly escape all those variables will be a hard sell. Part of the issue is that staging macros make us emit warnings, and I'm not sure if there's much we can do aside from reworking how Scaladoc variables work.

**Comment by smarter** [comment]
I'm not convinced they're tasty issues since I see `hackGetmembers` in the stacktrace, so scaladoc is bypassing tasty to do something

**Comment by abgruszecki** [comment]
Hm, that's actually correct, in this particular stack trace that's the first non-Dotty method called.

**Comment by smarter** [comment]
I don't know what's going on here (somehow the parameter type of a method ends up being a MethodType itself?), but my guess is that it's related to extension methods and/or exports:in BasicSupport.scala where the crash is happening, there's an extension method `isLeftAssoc` which is defined, but there's another extension method with the same name which is exported from SymOps (by the way, that method doesn't look like it should be an extension method at all: https://github.com/lampepfl/dotty/blob/f3c1468dba28da63df381be0b748f781d3cc2fa4/scaladoc/src/dotty/tools/scaladoc/tasty/SymOps.scala#L114)

**Comment by smarter** [comment]
> We could also just turn off warnings on unexpanded Scaladoc variables. 

Please yes, the current level of noise is unbearable.

**Comment by smarter** [comment]
Related: the community-docs job is failing on many commits in https://github.com/lampepfl/dotty/commits/master currently, I tried to look in the log for the source of the problem, but I couldn't find it among all the noise.

**Comment by griggt** [comment]
I think it's OOMing while trying to build the docs for the new version of ScalaTest.

**Comment by smarter** [comment]
Good catch, would you mind trying to increase the (already enormous) heap? (Long term, I hope we can fix the memory usage issue, I've been trying to implement something like https://github.com/scala/scala/pull/2901 but it's a challenge to get working in dotty).

**Comment by griggt** [comment]
I suspect we may be exhausting the RAM provided by the cloud runner, which says 7GB: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

The scalatest heap is set to 11GB

**Comment by smarter** [comment]
Hmm, and the mac runners have 14 GB of ram, are those free too?

**Comment by griggt** [comment]
> Hmm, and the mac runners have 14 GB of ram, are those free too?

It appears so!

https://github.community/t/are-macos-actions-free-for-public-repositories/167315

I wonder if high usage is throttled or has long wait times in the queue.
