### ISSUE TITLE
`inline` together with private object might generate code that throws IllegalAccessError

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12160]
## Compiler version

3.0.0-RC3

## Minimized code

https://github.com/scf37/fpscala2/tree/scala3-bug

checkout and run `sbt run`

## Output

```scala
java.lang.IllegalAccessError: failed to access class tethys.readers.JsonReaderInternal$ProductArray$ from class me.scf37.fpscala2.controller.TodoRequest$ (tethys.readers.JsonReaderInternal$ProductArray$ and me.scf37.fpscala2.controller.TodoRequest$ are in unnamed module of loader 'app')

```

## Expectation
Successful execution

**Comment by griggt** [comment]
A self-contained example:

```scala
import scala.deriving._

trait Show[A]:
  extension (a: A) def show: String

object Show:
  inline def derived[A](using m: Mirror.Of[A]): Show[A] = inline m match
    case p: Mirror.ProductOf[A] => internal.Shower.showProduct[A]
    case s: Mirror.SumOf[A] => ???

package internal:
  object Shower:
    inline def showProduct[A]: Show[A] =
      new Show[A] { extension (a: A) def show = P(a.toString).s }

    private case class P(str: String) { def s = str }  // must be a case class
end internal

case class Foo(s: String) derives Show

@main def Test =
  println(Foo("bar").show)
```

```
$ dotc -version
Scala compiler version 3.0.3-RC1-bin-SNAPSHOT-git-cc47c56 -- Copyright 2002-2021, LAMP/EPFL

$ dotc i12160.scala 
$ dotr Test
Exception in thread "main" java.lang.IllegalAccessError: tried to access class internal.Shower$P$ from class Foo$$anon$1
	at Foo$$anon$1.show(i12160.scala:14)
	at Foo$$anon$1.show(i12160.scala:14)
	at i12160$package$.Test(i12160.scala:22)
	at Test.main(i12160.scala:21)
```

**Comment by nicolasstucki** [comment]
Minimized to
```scala
package internal:
  object Foo:
    inline def foo: Unit = P.s

    private object P { def s = "b" }
end internal

@main def Test = internal.Foo.foo
```
