### ISSUE TITLE
Export Java Symbols compiles, but fails at runtime with `NoClassDefFoundError`.

### ISSUE THREAD

**Issue by agilesteel** [lampepfl/dotty#12249]
## Compiler version

3.0.0-RC3 (also fails in the earlier versions)

## Minimized code

```Scala
export java.util.UUID

println(UUID.randomUUID())
```

## Output

```scala
[error] (run-main-0) java.lang.NoClassDefFoundError: java/util/UUID$
[error] java.lang.NoClassDefFoundError: java/util/UUID$
[error]         at dev.insideyou.delete3me.Main$package$.UUID(Main.scala:4)
[error]         at dev.insideyou.delete3me.Main$.<clinit>(Main.scala:9)
[error]         at dev.insideyou.delete3me.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: java.util.UUID$
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```

## Expectation
I either expect it NOT to compile in the first place or even better actually work.

**Comment by rtyley** [comment]
I wonder if this is related to https://github.com/scala/bug/issues/12396, where I got a `NoClassDefFoundError` calling a method on a Java library from Scala 3 - reported there before realising that it seems that's only for Scala 2 bugs.

**Comment by agilesteel** [comment]
I guess this "fixes" it, but any chance this could be improved in the future? It would be cool if all the static members were exported into a Scala `UUID` object as in:
```scala
export java.util.UUID
```
could be equivalent to:
```scala
type UUID = java.util.UUID
object UUID:
  inline def randomUUID(): UUID =
    java.util.UUID.randomUUID()
    
  // followed by other members
```
