### ISSUE TITLE
ICE: scala.MatchError: MacroTree(TypeApply(Select(Ident(Impls),foo),List(Ident(U)))) (of class dotty.tools.dotc.ast.untpd$MacroTree) while compiling mutant.scala

### ISSUE THREAD

**Issue by chengniansun** [lampepfl/dotty#12361]
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

```
Scala compiler version 3.0.1-RC1-bin-SNAPSHOT-git-8957e51 -- Copyright 2002-2021, LAMP/EPFL
```

## Minimized code

```Scala
object Test {
    foo = macro Impls . foo [ U ] +=
}
```

## Output (click arrow to expand)
<details>

```scala
-- [E006] Not Found Error: mutant.scala:2:4 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 |    foo = macro Impls . foo [ U ] +=
  |    ^^^
  |    Not found: foo

longer explanation available when compiling with `-explain`
-- Error: mutant.scala:2:16 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 |    foo = macro Impls . foo [ U ] +=
  |                ^^^^^^^^^^^^^^^^^
  |                postfix operator `+=` needs to be enabled
  |                by making the implicit value scala.language.postfixOps visible.
  |                ----
  |                This can be achieved by adding the import clause 'import scala.language.postfixOps'
  |                or by setting the compiler option -language:postfixOps.
  |                See the Scaladoc for value scala.language.postfixOps for a discussion
  |                why the feature needs to be explicitly enabled.
exception occurred while typechecking mutant.scala
exception occurred while compiling mutant.scala
scala.MatchError: MacroTree(TypeApply(Select(Ident(Impls),foo),List(Ident(U)))) (of class dotty.tools.dotc.ast.untpd$MacroTree) while compiling mutant.scala
Exception in thread "main" scala.MatchError: MacroTree(TypeApply(Select(Ident(Impls),foo),List(Ident(U)))) (of class dotty.tools.dotc.ast.untpd$MacroTree)
	at dotty.tools.dotc.ast.desugar$.apply(Desugar.scala:1720)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2727)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2743)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2808)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2812)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2928)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:605)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:655)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2651)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2742)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2727)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2743)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2808)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2812)
	at dotty.tools.dotc.typer.Typer.reassignmentToVal$1(Typer.scala:943)
	at dotty.tools.dotc.typer.Typer.typedAssign(Typer.scala:1010)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2688)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2743)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2808)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2812)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2861)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2884)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2340)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2669)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2673)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2742)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2808)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2812)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2834)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2884)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2463)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2714)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2743)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2808)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2812)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2928)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by griggt** [comment]
The crash looks like #9285
