### ISSUE TITLE
shadowing `this` is allowed

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#12406]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
class ShadowIt {
  def foo = {
    val this = "shadow"
    this
  }
}
```

## Output

```scala
scala.MatchError: shadow (of class java.lang.String)
	at ShadowIt.foo(main.scala:3)
	at main$package$.main(main.scala:8)
	at main.main(main.scala:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:133)
	at sbt.Run.execute$1(Run.scala:82)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.lang.Thread.run(Thread.java:748)
```

## Expectation

Probably a parse error `"expected: Identifier, found: this"` or something along those lines.

**Comment by odersky** [comment]
`this` counts as a pattern, so it is allowed syntactically.

**Comment by som-snytt** [comment]
`val this = this` is Dotty's `val 1 = 2`.

**Comment by bjornregnell** [comment]
There is also a kind of irregularity with `def this = this`. Normally you can turn a val into a def but not the strange `val this = this`. 
```
$ scala3-repl -version
Scala code runner version 3.0.0-RC3 -- Copyright 2002-2021, LAMP/EPFL
$ scala3-repl
scala> object Ok { val this = this }
// defined object Ok

scala> object NotOk { def this = this }
1 |object NotOk { def this = this }
  |                      ^
  |                   Auxiliary constructor needs non-implicit parameter list
1 |object NotOk { def this = this }
  |                             ^
  |                             '(' expected, but '}' found
```

**Comment by som-snytt** [comment]
@bjornregnell I don't think that is a rule of thumb. `val List(x) = 42 :: Nil`. The syntaxes align at `List(x: Int)`.

**Comment by bjornregnell** [comment]
Ah, ok yes @som-snytt ; I was thinking of a simple name and not pat mat after `val`.

**Comment by som-snytt** [comment]
warns since 3.2.0
```
4 |    val this = "shadow"
  |               ^^^^^^^^
  |pattern's type (ShadowIt.this : ShadowIt) does not match the right hand side expression's type ("shadow" : String)
  |
  |If the narrowing is intentional, this can be communicated by adding `: @unchecked` after the expression,
  |which may result in a MatchError at runtime.
  |This patch can be rewritten automatically under -rewrite -source 3.2-migration.
```
