### ISSUE TITLE
ICE: java.lang.AssertionError: assertion failed: Non-sensical cast between unrelated types ErasedValueType(I0, Double) and ErasedValueType(I0, Double), at dotty.tools.dotc.transform.Erasure$Boxing$.cast(Erasure.scala:335)

### ISSUE THREAD

**Issue by chengniansun** [lampepfl/dotty#12447]
## Compiler Version

```
Scala compiler version 3.0.1-RC1-bin-SNAPSHOT-git-4410752 -- Copyright 2002-2021, LAMP/EPFL
```

## System Information

```
Linux 5.4.0-66-generic x86_64 GNU/Linux
```

## Minimized Code

```scala
class I0(I0: Double with I0) extends AnyVal
```

## Output (click arrow to expand)

<details>

```scala
exception while typing I0.hashCode$extension(this) of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing I0.hashCode$extension(this)() of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing override def hashCode(): Int = I0.hashCode$extension(this)() of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @scala.annotation.internal.SourceFile("mutant.scala") final class I0(I0: Double & I0) extends AnyVal() {
  override def hashCode(): Int = I0.hashCode$extension(this)()
  override def equals(x$0: Any): Boolean = I0.equals$extension(this)(x$0)
  private def I0: Double & I0
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package <empty> {
  @scala.annotation.internal.SourceFile("mutant.scala") final class I0(I0: Double & I0) extends AnyVal() {
    override def hashCode(): Int = I0.hashCode$extension(this)()
    override def equals(x$0: Any): Boolean = I0.equals$extension(this)(x$0)
    private def I0: Double & I0
  }
  final lazy module val I0: I0$ = new I0$()
  @scala.annotation.internal.SourceFile("mutant.scala") final module class I0$() extends AnyRef() {
    private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[I0.type])
    final def hashCode$extension($this: I0)(): Int = I0.hashCode$extension($this.I0)()
    final def equals$extension($this: I0)(x$0: Any): Boolean =
      matchResult1[Boolean]:
        {
          case val x1: (x$0 : Object) = x$0
          if x1.$isInstanceOf$[I0 @unchecked] then
            {
              case val x$0: I0 = x1.$asInstanceOf$[I0 @unchecked]
              return[matchResult1] $this.I0.==(x$0.I0)
            }
           else ()
          return[matchResult1] false
        }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
exception occurred while compiling mutant.scala
java.lang.AssertionError: assertion failed: Non-sensical cast between unrelated types ErasedValueType(I0, Double) and ErasedValueType(I0, Double) while compiling mutant.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Non-sensical cast between unrelated types ErasedValueType(I0, Double) and ErasedValueType(I0, Double)
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.Erasure$Boxing$.cast(Erasure.scala:335)
	at dotty.tools.dotc.transform.Erasure$Boxing$.unbox(Erasure.scala:303)
	at dotty.tools.dotc.transform.Erasure$Boxing$.adaptToType(Erasure.scala:379)
	at dotty.tools.dotc.transform.Erasure$Typer.adapt(Erasure.scala:1065)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2933)
	at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$4(Erasure.scala:850)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:153)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:850)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2685)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2748)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2933)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:837)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2685)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2748)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2933)
	at dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:2158)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2158)
	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:955)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2747)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2839)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2889)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2344)
	at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1043)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2673)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2677)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2747)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2839)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2889)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2467)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2718)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2748)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2813)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2817)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2933)
	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:132)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by KacperFKorban** [comment]
A minimization with slightly less `IO` and different stack trace:
```scala
//> using scala 3.nightly

class A
class I0(io: Double with A) extends AnyVal
```

Stack trace:

<details>

```scala
-- [E003] Syntax Warning: wiadro/crash_my_scala.scala:4:20 -----------
4 |class I0(io: Double with A) extends AnyVal
  |                    ^^^^
  |with as a type operator has been deprecated; use & instead
  |This construct can be rewritten automatically under -rewrite -source 3.4-migration.
  |
  | longer explanation available when compiling with `-explain`
java.util.NoSuchElementException: key not found: Ljava/lang/Double;
        at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:674)
        at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:809)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:385)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:303)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:297)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1191)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:834)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:385)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:899)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:922)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:699)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:705)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:705)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:293)
        at dotty.tools.backend.jvm.CodeGen.genClass(CodeGen.scala:161)
        at dotty.tools.backend.jvm.CodeGen.genClassDef$1(CodeGen.scala:62)
        at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:118)
        at dotty.tools.backend.jvm.CodeGen.genClassDefs$1$$anonfun$1(CodeGen.scala:116)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:116)
        at dotty.tools.backend.jvm.CodeGen.genUnit(CodeGen.scala:121)
        at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:90)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:383)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:376)
        at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:98)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:345)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:338)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:385)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:397)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:397)
        at dotty.tools.dotc.Run.compileSources(Run.scala:284)
        at dotty.tools.dotc.Run.compile(Run.scala:269)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:201)
        at dotty.tools.dotc.Driver.process(Driver.scala:169)
        at dotty.tools.dotc.Driver.process(Driver.scala:181)
        at dotty.tools.dotc.Driver.main(Driver.scala:211)
        at dotty.tools.dotc.Main.main(Main.scala)
Error while emitting wiadro/crash_my_scala.scala
key not found: Ljava/lang/Double;
1 warning found
1 error found
Compilation failed
```

</details>
