### ISSUE TITLE
Mixing curly braces and backticks codeblocks causes scaladoc failure

### ISSUE THREAD

**Issue by BarkingBad** [lampepfl/dotty#12477]
Consider this markdown part of code:
```md
Some markdown text with my snippet `{{{ ... }}}` that is important to me
```

It should create inline code with `{{{ ... }}}` content, however it fails with this error:
`caused by: java.lang.RuntimeException: MismatchedTokenException(32!=77)`

I guess there is some problems with priorities in parser tables after adding `WikiCodeBlockParser`

@abgruszecki do you know how to fix tat easily?

**Comment by abgruszecki** [comment]
@BarkingBad what's the stacktrace? IIRC the code in `WikiCodeBlockParser` shouldn't even let other parsers touch whatever it is parsing.

**Comment by BarkingBad** [comment]
Sorry for a late response, I was busy recently

There are two different bahaviours:
for regular docstring, the output is

![obraz](https://user-images.githubusercontent.com/32793002/118954989-956dd680-b95e-11eb-80eb-23c91fc0de9c.png)

for part of blogpost/static site documentation it throws an exception 

<details>
  <summary>Exception</summary>
  
```
-- Error: docs/blog/_posts/2015-10-23-dotty-compiler-bootstraps.md ------------------------------------------------------------------------------------------------------------------
/home/aratajczak/Dokumenty/Praca/Scala/dotty/docs/blog/_posts/2015-10-23-dotty-compiler-bootstraps.md: [ERROR] Unable to process brief for /home/aratajczak/Dokumenty/Praca/Scala/dotty/docs/blog/_posts/2015-10-23-dotty-compiler-bootstraps.md 
caused by: java.lang.RuntimeException: MismatchedTokenException(32!=77)
        at liqp.parser.LiquidParser.reportError(LiquidParser.java:171)
        at liqp.parser.LiquidParser.output(LiquidParser.java:4605)
        at liqp.parser.LiquidParser.atom(LiquidParser.java:453)
        at liqp.parser.LiquidParser.block(LiquidParser.java:296)
java.lang.RuntimeException: MismatchedTokenException(32!=77)
        at liqp.parser.LiquidParser.reportError(LiquidParser.java:171)
        at liqp.parser.LiquidParser.output(LiquidParser.java:4605)
        at liqp.parser.LiquidParser.atom(LiquidParser.java:453)
        at liqp.parser.LiquidParser.block(LiquidParser.java:296)
        at liqp.parser.LiquidParser.parse(LiquidParser.java:202)
        at liqp.Template.<init>(Template.java:80)
        at liqp.Template.<init>(Template.java:65)
        at liqp.Template.parse(Template.java:133)
        at dotty.tools.scaladoc.site.TemplateFile.resolveInner(templates.scala:74)
        at dotty.tools.scaladoc.site.LoadedTemplate.resolveToHtml(LoadedTemplate.scala:54)
        at dotty.tools.scaladoc.renderers.ResolvedTemplate.<init>(SiteRenderer.scala:17)
        at dotty.tools.scaladoc.renderers.ResolvedTemplate$.apply(SiteRenderer.scala:16)
        at dotty.tools.scaladoc.renderers.SiteRenderer.templateToPage(SiteRenderer.scala:24)
        at dotty.tools.scaladoc.renderers.SiteRenderer.templateToPage$(SiteRenderer.scala:20)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.templateToPage(HtmlRenderer.scala:26)
        at dotty.tools.scaladoc.renderers.SiteRenderer.templateToPage$$anonfun$1(SiteRenderer.scala:25)
        at scala.collection.immutable.List.map(List.scala:250)
        at dotty.tools.scaladoc.renderers.SiteRenderer.templateToPage(SiteRenderer.scala:25)
        at dotty.tools.scaladoc.renderers.SiteRenderer.templateToPage$(SiteRenderer.scala:20)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.templateToPage(HtmlRenderer.scala:26)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.$anonfun$3(HtmlRenderer.scala:49)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.<init>(HtmlRenderer.scala:49)
        at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:201)
        at dotty.tools.scaladoc.Scaladoc$.run$$anonfun$1(Scaladoc.scala:72)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.Option.map(Option.scala:242)
        at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:74)
        at dotty.tools.scaladoc.Main.run(Main.scala:18)
        at dotty.tools.scaladoc.Main$.main(Main.scala:24)
        at dotty.tools.scaladoc.Main.main(Main.scala)
Caused by: MismatchedTokenException(32!=77)
        at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:617)
        at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:115)
        at liqp.parser.LiquidParser.output(LiquidParser.java:4551)
        ... 31 more
```
</details>

**Comment by abgruszecki** [comment]
Unless I screwed something up, `WikiCodeBlockParser` should only work for docstrings, not standalone markdown files. That's at least what I wanted to do. First thing I'd check is if there isn't some sort of problem with flexmark parser by itself - it seems like it doesn't recognize `` `{{{ `` as a starting token for monospace text. In docstrings it seems like that lets `WikiCodeBlockParser` kick in, and in standalone markdown it seems like it leads to an error further down the road.

**Comment by BarkingBad** [comment]
I thought we use the same flexmark parser for both docstrings and static sites, however, it is interesting how this phrase fails in flexmark. Will you try to fix it? I'm just asking wheter should I consider it taken or fix it myself when I'd have more time

**Comment by abgruszecki** [comment]
I can take a look, but feel free to dive in and fix it if you find the time.

**Comment by abgruszecki** [comment]
@BarkingBad I checked it out and it seems that the error actually comes from the Liquid template parser. I'm not sure if there's anything to be done about that.

**Comment by BarkingBad** [comment]
Oh ok, thank you for the insight. I did not have time to look into that yet. As it comes to the issue origin, I actually wanted to create code block presenting potential syntax of writing codeblocks in scaladoc, since it accepts curly braces, then the compilation failed with forementioned exception

**Comment by abgruszecki** [comment]
I suppose one problem is that someone may legitimately want to expand a template inside quotes. Apparently it's possible to escape Liquid syntax in a few ways, none of them pretty: https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags.

Should we close the issue?

**Comment by BarkingBad** [comment]
I'll check if escaping really works when I'll have some more time, but we can close it for now indeed
