### ISSUE TITLE
ICE: dotty.tools.dotc.transform.Erasure$Boxing$.unbox(Erasure.scala:291)

### ISSUE THREAD

**Issue by chengniansun** [lampepfl/dotty#12483]
## Compiler Version

```
Scala compiler version 3.0.1-RC1-bin-SNAPSHOT-git-b9773d6 -- Copyright 2002-2021, LAMP/EPFL
```

## System Information

```
Linux 5.4.0-66-generic x86_64 GNU/Linux
```

## Minimized Code

```scala
object Test {
  case class IntAnyVal(x: Int) extends AnyVal
  def test(x: IntAnyVal) = (x match {
    case IntAnyVal(1) => 1
    case IntAnyVal(2) => 2
  }) match {
    case IntAnyVal(1) => 1
  }
}
```

## Output (click arrow to expand)

<details>

```scala
-- [E029] Pattern Match Exhaustivity Warning: mutant.scala:4:19 -----------------------------------------------------------------------
4 |    case IntAnyVal(1) => 1
  |                   ^
  |                   match may not be exhaustive.
  |
  |                   It would fail on pattern case: 1, 2
5 |    case IntAnyVal(2) => 2

longer explanation available when compiling with `-explain`
-- Error: mutant.scala:7:9 ------------------------------------------------------------------------------------------------------------
7 |    case IntAnyVal(1) => 1
  |         ^^^^^^^^^^^^
  |         cannot test if value of type (1 : Int) | (2 : Int) is a reference of class IntAnyVal
exception while typing x10.$asInstanceOf$[Test.IntAnyVal] of class class dotty.tools.dotc.ast.Trees$TypeApply # -1
exception while typing Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal]) of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal]) of class class dotty.tools.dotc.ast.Trees$ValDef # -1
exception while typing {
  case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
  case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
  if 1.==(x13) then return[matchResult5] 1 else ()
} of class class dotty.tools.dotc.ast.Trees$Block # -1
exception while typing if x10.$isInstanceOf$[Test.IntAnyVal] then
  {
    case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
    case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
    if 1.==(x13) then return[matchResult5] 1 else ()
  }
 else () of class class dotty.tools.dotc.ast.Trees$If # -1
exception while typing {
  case val x10: (1 : Int) | (2 : Int) =
    matchResult4[Int]:
      {
        case val x5: (x : ErasedValueType(Test.IntAnyVal, Int)) = x
        {
          case val x8: Test.IntAnyVal = Test.IntAnyVal.unapply(x5)
          case val x9: Int = Test.IntAnyVal._1$extension(x8).$asInstanceOf$[(x8._1 : (): Int)]
          if 1.==(x9) then return[matchResult4] 1 else ()
          if 2.==(x9) then return[matchResult4] 2 else ()
        }
        throw new MatchError(x5)
      }
  if x10.$isInstanceOf$[Test.IntAnyVal] then
    {
      case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
      case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
      if 1.==(x13) then return[matchResult5] 1 else ()
    }
   else ()
  throw new MatchError(x10)
} of class class dotty.tools.dotc.ast.Trees$Block # -1
exception while typing matchResult5[Int]:
  {
    case val x10: (1 : Int) | (2 : Int) =
      matchResult4[Int]:
        {
          case val x5: (x : ErasedValueType(Test.IntAnyVal, Int)) = x
          {
            case val x8: Test.IntAnyVal = Test.IntAnyVal.unapply(x5)
            case val x9: Int = Test.IntAnyVal._1$extension(x8).$asInstanceOf$[(x8._1 : (): Int)]
            if 1.==(x9) then return[matchResult4] 1 else ()
            if 2.==(x9) then return[matchResult4] 2 else ()
          }
          throw new MatchError(x5)
        }
    if x10.$isInstanceOf$[Test.IntAnyVal] then
      {
        case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
        case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
        if 1.==(x13) then return[matchResult5] 1 else ()
      }
     else ()
    throw new MatchError(x10)
  } of class class dotty.tools.dotc.ast.Trees$Labeled # -1
exception while typing def test(x: Test.IntAnyVal): Int =
  matchResult5[Int]:
    {
      case val x10: (1 : Int) | (2 : Int) =
        matchResult4[Int]:
          {
            case val x5: (x : ErasedValueType(Test.IntAnyVal, Int)) = x
            {
              case val x8: Test.IntAnyVal = Test.IntAnyVal.unapply(x5)
              case val x9: Int = Test.IntAnyVal._1$extension(x8).$asInstanceOf$[(x8._1 : (): Int)]
              if 1.==(x9) then return[matchResult4] 1 else ()
              if 2.==(x9) then return[matchResult4] 2 else ()
            }
            throw new MatchError(x5)
          }
      if x10.$isInstanceOf$[Test.IntAnyVal] then
        {
          case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
          case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
          if 1.==(x13) then return[matchResult5] 1 else ()
        }
       else ()
      throw new MatchError(x10)
    } of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @scala.annotation.internal.SourceFile("mutant.scala") final module class Test$() extends Object() {
  private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Test.type])
  final case class IntAnyVal(x: Int) extends AnyVal(), Product, Serializable {
    override def hashCode(): Int = Test.IntAnyVal.hashCode$extension(this)()
    override def equals(x$0: Any): Boolean = Test.IntAnyVal.equals$extension(this)(x$0)
    override def toString(): String = Test.IntAnyVal.toString$extension(this)()
    override def canEqual(that: Any): Boolean = Test.IntAnyVal.canEqual$extension(this)(that)
    override def productArity: Int = Test.IntAnyVal.productArity$extension(this)
    override def productPrefix: String = Test.IntAnyVal.productPrefix$extension(this)
    override def productElement(n: Int): Any = Test.IntAnyVal.productElement$extension(this)(n)
    override def productElementName(n: Int): String = Test.IntAnyVal.productElementName$extension(this)(n)
    def x: Int
    def copy(x: Int): Test.IntAnyVal = Test.IntAnyVal.copy$extension(this)(x)
    def copy$default$1: Int @uncheckedVariance = Test.IntAnyVal.copy$default$1$extension(this)
    def _1: Int = Test.IntAnyVal._1$extension(this)
  }
  final lazy module val IntAnyVal: Test.IntAnyVal$ = new Test.IntAnyVal$()
  final module class IntAnyVal$() extends AnyRef() {
    private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Test.IntAnyVal.type])
    def apply(x: Int): Test.IntAnyVal = new Test.IntAnyVal(x)
    def unapply(x$1: Test.IntAnyVal): Test.IntAnyVal = x$1
    override def toString: String = "IntAnyVal"
    final def hashCode$extension($this: Test.IntAnyVal)(): Int = $this.x.hashCode()
    final def equals$extension($this: Test.IntAnyVal)(x$0: Any): Boolean =
      matchResult1[Boolean]:
        {
          case val x1: (x$0 : Object) = x$0
          if x1.$isInstanceOf$[Test.IntAnyVal @unchecked] then
            {
              case val x$0: Test.IntAnyVal = x1.$asInstanceOf$[Test.IntAnyVal @unchecked]
              return[matchResult1] $this.x.==(x$0.x)
            }
           else ()
          return[matchResult1] false
        }
    final def toString$extension($this: Test.IntAnyVal)(): String = scala.runtime.ScalaRunTime._toString($this)
    final def canEqual$extension($this: Test.IntAnyVal)(that: Any): Boolean = that.isInstanceOf[Test.IntAnyVal @unchecked]
    final def productArity$extension($this: Test.IntAnyVal): Int = 1
    final def productPrefix$extension($this: Test.IntAnyVal): String = "IntAnyVal"
    final def productElement$extension($this: Test.IntAnyVal)(n: Int): Any =
      matchResult2[Int]:
        {
          case val x3: (n : Int) = n
          if 0.==(x3) then return[matchResult2] Test.IntAnyVal._1$extension($this) else ()
          throw new IndexOutOfBoundsException(n.toString())
        }
    final def productElementName$extension($this: Test.IntAnyVal)(n: Int): String =
      matchResult3[String]:
        {
          case val x4: (n : Int) = n
          if 0.==(x4) then return[matchResult3] "x" else ()
          throw new IndexOutOfBoundsException(n.toString())
        }
    final def copy$extension($this: Test.IntAnyVal)(x: Int): Test.IntAnyVal = new Test.IntAnyVal(x)
    final def copy$default$1$extension($this: Test.IntAnyVal): Int @uncheckedVariance = $this.x
    final def _1$extension($this: Test.IntAnyVal): Int = $this.x
  }
  def test(x: Test.IntAnyVal): Int =
    matchResult5[Int]:
      {
        case val x10: (1 : Int) | (2 : Int) =
          matchResult4[Int]:
            {
              case val x5: (x : ErasedValueType(Test.IntAnyVal, Int)) = x
              {
                case val x8: Test.IntAnyVal = Test.IntAnyVal.unapply(x5)
                case val x9: Int = Test.IntAnyVal._1$extension(x8).$asInstanceOf$[(x8._1 : (): Int)]
                if 1.==(x9) then return[matchResult4] 1 else ()
                if 2.==(x9) then return[matchResult4] 2 else ()
              }
              throw new MatchError(x5)
            }
        if x10.$isInstanceOf$[Test.IntAnyVal] then
          {
            case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
            case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
            if 1.==(x13) then return[matchResult5] 1 else ()
          }
         else ()
        throw new MatchError(x10)
      }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package <empty> {
  final lazy module val Test: Test$ = new Test$()
  @scala.annotation.internal.SourceFile("mutant.scala") final module class Test$() extends Object() {
    private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Test.type])
    final case class IntAnyVal(x: Int) extends AnyVal(), Product, Serializable {
      override def hashCode(): Int = Test.IntAnyVal.hashCode$extension(this)()
      override def equals(x$0: Any): Boolean = Test.IntAnyVal.equals$extension(this)(x$0)
      override def toString(): String = Test.IntAnyVal.toString$extension(this)()
      override def canEqual(that: Any): Boolean = Test.IntAnyVal.canEqual$extension(this)(that)
      override def productArity: Int = Test.IntAnyVal.productArity$extension(this)
      override def productPrefix: String = Test.IntAnyVal.productPrefix$extension(this)
      override def productElement(n: Int): Any = Test.IntAnyVal.productElement$extension(this)(n)
      override def productElementName(n: Int): String = Test.IntAnyVal.productElementName$extension(this)(n)
      def x: Int
      def copy(x: Int): Test.IntAnyVal = Test.IntAnyVal.copy$extension(this)(x)
      def copy$default$1: Int @uncheckedVariance = Test.IntAnyVal.copy$default$1$extension(this)
      def _1: Int = Test.IntAnyVal._1$extension(this)
    }
    final lazy module val IntAnyVal: Test.IntAnyVal$ = new Test.IntAnyVal$()
    final module class IntAnyVal$() extends AnyRef() {
      private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Test.IntAnyVal.type])
      def apply(x: Int): Test.IntAnyVal = new Test.IntAnyVal(x)
      def unapply(x$1: Test.IntAnyVal): Test.IntAnyVal = x$1
      override def toString: String = "IntAnyVal"
      final def hashCode$extension($this: Test.IntAnyVal)(): Int = $this.x.hashCode()
      final def equals$extension($this: Test.IntAnyVal)(x$0: Any): Boolean =
        matchResult1[Boolean]:
          {
            case val x1: (x$0 : Object) = x$0
            if x1.$isInstanceOf$[Test.IntAnyVal @unchecked] then
              {
                case val x$0: Test.IntAnyVal = x1.$asInstanceOf$[Test.IntAnyVal @unchecked]
                return[matchResult1] $this.x.==(x$0.x)
              }
             else ()
            return[matchResult1] false
          }
      final def toString$extension($this: Test.IntAnyVal)(): String = scala.runtime.ScalaRunTime._toString($this)
      final def canEqual$extension($this: Test.IntAnyVal)(that: Any): Boolean = that.isInstanceOf[Test.IntAnyVal @unchecked]
      final def productArity$extension($this: Test.IntAnyVal): Int = 1
      final def productPrefix$extension($this: Test.IntAnyVal): String = "IntAnyVal"
      final def productElement$extension($this: Test.IntAnyVal)(n: Int): Any =
        matchResult2[Int]:
          {
            case val x3: (n : Int) = n
            if 0.==(x3) then return[matchResult2] Test.IntAnyVal._1$extension($this) else ()
            throw new IndexOutOfBoundsException(n.toString())
          }
      final def productElementName$extension($this: Test.IntAnyVal)(n: Int): String =
        matchResult3[String]:
          {
            case val x4: (n : Int) = n
            if 0.==(x4) then return[matchResult3] "x" else ()
            throw new IndexOutOfBoundsException(n.toString())
          }
      final def copy$extension($this: Test.IntAnyVal)(x: Int): Test.IntAnyVal = new Test.IntAnyVal(x)
      final def copy$default$1$extension($this: Test.IntAnyVal): Int @uncheckedVariance = $this.x
      final def _1$extension($this: Test.IntAnyVal): Int = $this.x
    }
    def test(x: Test.IntAnyVal): Int =
      matchResult5[Int]:
        {
          case val x10: (1 : Int) | (2 : Int) =
            matchResult4[Int]:
              {
                case val x5: (x : ErasedValueType(Test.IntAnyVal, Int)) = x
                {
                  case val x8: Test.IntAnyVal = Test.IntAnyVal.unapply(x5)
                  case val x9: Int = Test.IntAnyVal._1$extension(x8).$asInstanceOf$[(x8._1 : (): Int)]
                  if 1.==(x9) then return[matchResult4] 1 else ()
                  if 2.==(x9) then return[matchResult4] 2 else ()
                }
                throw new MatchError(x5)
              }
          if x10.$isInstanceOf$[Test.IntAnyVal] then
            {
              case val x12: Test.IntAnyVal = Test.IntAnyVal.unapply(x10.$asInstanceOf$[Test.IntAnyVal])
              case val x13: Int = Test.IntAnyVal._1$extension(x12).$asInstanceOf$[(x12._1 : (): Int)]
              if 1.==(x13) then return[matchResult5] 1 else ()
            }
           else ()
          throw new MatchError(x10)
        }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
exception occurred while compiling mutant.scala
java.lang.AssertionError: assertion failed while compiling mutant.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at dotty.tools.dotc.transform.Erasure$Boxing$.unbox(Erasure.scala:291)
	at dotty.tools.dotc.transform.Erasure$Boxing$.adaptToType(Erasure.scala:379)
	at dotty.tools.dotc.transform.Erasure$Typer.adapt(Erasure.scala:1065)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2936)
	at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:822)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2936)
	at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$4(Erasure.scala:850)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:153)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:850)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2688)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2936)
	at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2097)
	at dotty.tools.dotc.transform.Erasure$Typer.typedValDef(Erasure.scala:908)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2662)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2750)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2842)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2892)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1023)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1027)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2696)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.$anonfun$11(Typer.scala:1086)
	at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2178)
	at dotty.tools.dotc.typer.Applications.harmonic$(Applications.scala:303)
	at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:106)
	at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:1089)
	at dotty.tools.dotc.transform.Erasure$Typer.typedIf(Erasure.scala:884)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2697)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2869)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2892)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1023)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1027)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2696)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedLabeled(Typer.scala:1631)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2681)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2750)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2936)
	at dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:2161)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2161)
	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:955)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2665)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2750)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2842)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2892)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2347)
	at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1043)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2676)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2680)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2750)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2842)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2892)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2470)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2721)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2751)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2816)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2820)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2936)
	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:132)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by odersky** [comment]
Looks like a problem related to value classes. I don't think it's a fuzzball.
