### ISSUE TITLE
NoSuchMethodError when overriding a trait constructor val parameter

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#1263]
Consider the following code:

~~~ scala
trait Foo(val s: String)

val foo = new Foo { override val s = "bar" }
~~~

It compiles fine. Maybe it should raise a compilation error?

At run-time we get the following exception:

~~~
java.lang.NoSuchMethodError: Initialization$Foo.initial$s()Ljava/lang/String;
        at Initialization$$anon$1.<init>(Initialization.scala:8)
        at Initialization$.<init>(Initialization.scala:8)
        at Initialization$.<clinit>(Initialization.scala)
        at Main$.main(Main.scala:5)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
~~~

**Comment by DarkDimius** [comment]
Thanks for submitting a bug.
I seems related to `PureInterface` flag.
