### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by xuwei-k** [lampepfl/dotty#12759]
## Compiler version

`3.0.2-RC1-bin-20210609-fdbb94f-NIGHTLY`, `3.0.1-RC1` and `3.0.0`

## Minimized code

```Scala
package example


class A1
class A2
class A3

class TypeClass[A](val value: A) {
  def map[B](f: A => B): TypeClass[B] = new TypeClass(f(value))
  def flatMap[B](f: A => TypeClass[B]): TypeClass[B] = f(value)
}

object TypeClass {
  def apply[A](implicit a: TypeClass[A]): TypeClass[A] = a

  def get2[A1: TypeClass, A2: TypeClass]: (A1, A2) = {
    (TypeClass[A1].value, TypeClass[A2].value)
  }

  implicit def a1: TypeClass[A1] = new TypeClass[A1](new A1)
  implicit def a2: TypeClass[A2] = new TypeClass[A2](new A2)
  implicit def a3: TypeClass[A3] = new TypeClass[A3](new A3)
}

trait Foo {

  val (
    a2,
    a3
  ) = TypeClass.get2[
    A2,
    A3
  ]

  val (
    x1,
    x2,
    x3
  ) = (for {
    y1 <- TypeClass[A1]
    y2 <- TypeClass[A1]
    y3 <- TypeClass[A1]
  } yield (
    y1,
    y2,
    y3
  )).value

}

object Main {
  def main(args: Array[String]): Unit = {
    new Foo {}
  }
}


```

## Output

```
[error] (run-main-9) java.lang.AbstractMethodError: example.Main$$anon$1.example$Foo$_setter_$example$Foo$$$1_$eq(Lscala/Tuple2;)V
[error] java.lang.AbstractMethodError: example.Main$$anon$1.example$Foo$_setter_$example$Foo$$$1_$eq(Lscala/Tuple2;)V
[error] 	at example.Foo.$init$(Main.scala:30)
[error] 	at example.Main$$anon$1.<init>(Main.scala:53)
[error] 	at example.Main$.main(Main.scala:53)
[error] 	at example.Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

**Comment by smarter** [comment]
Minimized:
```scala
package example

trait Foo {
  val (a2, a3) = ("", "")
  val (x1, x2, x3) = ("", "", "")
}

class A extends Foo

object Main {
  def main(args: Array[String]): Unit = {
    new A
  }
}
```
```scala
Exception in thread "main" java.lang.AbstractMethodError: example.A.example$Foo$_setter_$example$Foo$$$1_$eq(Lscala/Tuple2;)V
        at example.Foo.$init$(i12759.scala:4)
        at example.A.<init>(i12759.scala:8)
        at example.Main$.main(i12759.scala:12)
        at example.Main.main(i12759.scala)
```

After mixin we have:
```scala
trait Foo {
  // ...
  def example$Foo$_setter_$example$Foo$$$1_$eq(x$0: Tuple2): Unit
  def example$Foo$_setter_$example$Foo$$$2_$eq(x$0: Tuple3): Unit
}
class A extends Foo {
  // ...
  def example$Foo$_setter_$example$Foo$$$1_$eq(x$0: Tuple2): Unit =
    this.example$Foo$$$1 = x$0
  def example$Foo$_setter_$example$Foo$$$2_$eq(x$0: Tuple3): Unit =
    this.example$Foo$$$2 = x$0
}
```
which looks fine, but after RenameLifted we get:
```scala
class A extends Foo {
  // ..
  def example$Foo$_setter_$example$Foo$$$2_$eq(x$0: Tuple2): Unit =
    this.example$Foo$$$1 = x$0
  def example$Foo$_setter_$example$Foo$$$1_$eq(x$0: Tuple3): Unit =
    this.example$Foo$$$2 = x$0
```
Notice how the method names (but not their body) have been swapped: RenameLifted has incorrectly decided to rename them.
