### ISSUE TITLE
DottyTypeStealer doesn't work from console

### ISSUE THREAD

**Issue by tanishiking** [lampepfl/dotty#12830]
Related: https://github.com/lampepfl/dotty/issues/3969

The `DottyTypeStealer` explained in the document https://dotty.epfl.ch/docs/contributing/workflow.html#inspecting-trees-with-type-stealer doesn't work from `console`.

## Compiler version
```bash
$ sbt
sbt:scala3> scalac -version
[info] running (fork) dotty.tools.dotc.Main -classpath /Users/tanishiking/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/Users/tanishiking/src/github.com/tanishiking/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.0.2-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.0.2-RC1-bin-SNAPSHOT.jar -version
Scala compiler version 3.0.2-RC1-bin-SNAPSHOT-nonbootstrapped-git-a880769 -- Copyright 2002-2021, LAMP/EPFL
[success] Total time: 1 s, completed Jun 15, 2021, 10:51:09 PM
```

## Minimized code

```sh
sbt:scala3> scala3-compiler-bootstrapped/Test/console

scala> import dotty.tools.DottyTypeStealer.*; import dotty.tools.dotc.core.*; import Contexts.*,Types.*

scala> val s = stealType("class O { type X }", "O#X")
java.lang.NullPointerException
  at java.base/java.io.File.<init>(File.java:278)
  at dotty.tools.vulpix.TestConfiguration$.mkClasspath$$anonfun$1(TestConfiguration.scala:54)
  at scala.collection.immutable.List.map(List.scala:246)
  at dotty.tools.vulpix.TestConfiguration$.mkClasspath(TestConfiguration.scala:56)
  at dotty.tools.vulpix.TestConfiguration$.<clinit>(TestConfiguration.scala:26)
  at dotty.tools.DottyTest.initializeCtx(DottyTest.scala:44)
  at dotty.tools.DottyTest.initializeCtx$(DottyTest.scala:20)
  at dotty.tools.DottyTypeStealer$.initializeCtx(DottyTypeStealer.scala:18)
  at dotty.tools.DottyTest.initialCtx(DottyTest.scala:30)
  at dotty.tools.DottyTest.initialCtx$(DottyTest.scala:20)
  at dotty.tools.DottyTypeStealer$.initialCtx(DottyTypeStealer.scala:18)
  at dotty.tools.DottyTest.$init$(DottyTest.scala:24)
  at dotty.tools.DottyTypeStealer$.<clinit>(DottyTypeStealer.scala:18)
  at repl$.rs$line$2$.<clinit>(rs$line$2:1)
  at repl$.rs$line$2.s(rs$line$2)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:115)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.Rendering.valueOf(Rendering.scala:115)
  at dotty.tools.repl.Rendering.renderVal(Rendering.scala:152)
  at dotty.tools.repl.ReplDriver.$anonfun$13(ReplDriver.scala:323)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.collection.immutable.List.flatMap(List.scala:79)
  at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:323)
  at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:346)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:349)
  at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:268)
  at scala.util.Either.fold(Either.scala:189)
  at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:285)
  at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:212)
  at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:146)
  at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:149)
  at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:168)
  at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:149)
  at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
  at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:233)
  at sbt.Console.console0$1(Console.scala:64)
  at sbt.Console.$anonfun$apply$5(Console.scala:74)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
  at sbt.TrapExit$App.run(TrapExit.scala:258)
  at java.base/java.lang.Thread.run(Thread.java:834)
```

- This error happens because, in [TestConfguration](https://github.com/lampepfl/dotty/blob/a880769d6bc60a95cf6162b88fe4b9cfefab13b2/compiler/test/dotty/tools/vulpix/TestConfiguration.scala#L24-L27) that is called from `DottyTest`, `Properties.scalaLibrary` and `Properties.dottyLibrary` (which are defined [here](https://github.com/lampepfl/dotty/blob/a880769d6bc60a95cf6162b88fe4b9cfefab13b2/compiler/test/dotty/Properties.scala#L49) are null in console.
- They are null in console, because those javaOptions are defined in [commonDottyCompilerSettings](https://github.com/lampepfl/dotty/blob/a880769d6bc60a95cf6162b88fe4b9cfefab13b2/project/Build.scala#L544-L555), but `console` doesn't fork. Therefore we can't receive those javaOptions from console.

## Run DottyTypeStealer from run
Since `DottyTypeStealer` works perfectly in `run`, with the following diff

```diff
diff --git a/compiler/test/dotty/tools/DottyTypeStealer.scala b/compiler/test/dotty/tools/DottyTypeStealer.scala
index 0a80205fba..e613a576f0 100644
--- a/compiler/test/dotty/tools/DottyTypeStealer.scala
+++ b/compiler/test/dotty/tools/DottyTypeStealer.scala
@@ -7,6 +7,13 @@ import dotc.core.Contexts.Context
 import dotc.core.Decorators._
 import dotc.core.Types.Type
 
+@main def steal() = {
+  val s = DottyTypeStealer.stealType("class O { type X }", "O#X")
+  implicit val ctx: Context = s._1
+  val t = s._2(0)
+  println(t)
+}
+
 object DottyTypeStealer extends DottyTest {
   def stealType(source: String, typeStrings: String*): (Context, List[Type]) = {
     val dummyName = "x_x_x"
```

```sh
sbt:scala3> scala3-compiler-bootstrapped/Test/runMain dotty.tools.steal
[info] running (fork) dotty.tools.steal 
TypeRef(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class O),type X)
[success] Total time: 3 s, completed Jun 15, 2021, 11:02:02 PM
```

it works.

## Proposal
Update document https://dotty.epfl.ch/docs/contributing/workflow.html#inspecting-trees-with-type-stealer to use `DottyTypeStealer` from `run` (like the above diff) instead of `console`.

**Comment by tanishiking** [comment]
Closing for https://github.com/lampepfl/dotty/pull/12833
