### ISSUE TITLE
private objects are inaccessible from classes in same package

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1287]
`Foo.scala`:

``` scala
private object Foo {
  val x: Int = 1
}                
```

`Test.scala`:

``` scala
object Test {
  val a = Foo.x
}
```

``` scala
% ./bin/dotc Foo.scala Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed:
private object Foo in Foo.scala accessed from
constructor Test$ in object Test$ in Test.scala
        at scala.Predef$.assert(Predef.scala:165)
        at dotty.tools.dotc.transform.ExpandPrivate.ensurePrivateAccessible(ExpandPrivate.scala:75)
```

Note: here's how `scalac` compiles `Foo.scala`:

``` java
public final class Foo {
    public static int x() {
        return Foo$.MODULE$.x();
    }
}

public final class Foo$ {
    public static final Foo$ MODULE$;
    private final int x;

    public static {
        new Foo$();
    }

    public int x() {
        return this.x;
    }

    private Foo$() {
        MODULE$ = this;
        this.x = 1;
    }
}
```

And here's how dotty does it:

``` java
public final class Foo {
    public static int x() {
        return Foo$.MODULE$.x();
    }
}

private final class Foo$ {
    public static final Foo$ MODULE$;
    private final int x$$local;

    public static {
        new Foo$();
    }

    public Foo$() {
        MODULE$ = this;
        this.x$$local = 1;
    }

    public int x() {
        return this.x$$local;
    }
}
```

**Comment by olafurpg** [comment]
I'm able to reproduce this error on the latest Dotty master (318700fdaacd7e6707519e03f15a5ede99ca558a).

I bumped into this error while trying to compile https://github.com/johnynek/paiges with Dotty. The bug manifests in an uncaught exception during compilation
```

exception occurred while compiling tests/pos/private-object/Chunk.scala, tests/pos/private-object/Doc.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: private object Chunk in package bar in tests/pos/private-object/Chunk.scala accessed from constructor Doc$ in object Doc in tests/pos/private-object/Doc.scala
	at scala.Predef$.assert(Predef.scala:165)
	at dotty.tools.dotc.transform.ExpandPrivate.ensurePrivateAccessible(ExpandPrivate.scala:90)
	at dotty.tools.dotc.transform.ExpandPrivate.transformIdent(ExpandPrivate.scala:96)
	at dotty.tools.dotc.transform.ExpandPrivate.transformIdent(ExpandPrivate.scala:39)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goIdent(TreeTransform.scala:562)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:944)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1182)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1175)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
```

Removing the private modifier "fixed" the problem.

**Comment by smarter** [comment]
@olafurpg Could you check if the crash still happens in paiges? It doesn't happen in dotty master for the testcase I gave in my original comment.
