### ISSUE TITLE
Compiler accepts class as non-abstract, then runtime system fails saying the class is abstract

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#13087]
## Compiler version

3.0.1

## Minimized code

```Scala
import scala.collection.mutable.Builder

class DDD[S,T,A]

trait NN[S, T, A, K[_], +D <: DDD[Set[S],T,K[A]]]
class NNN[S, T, K[_], A] extends NN[S, T, A, K, DDD[Set[S],T,K[A]]]

object NN {
  def newBuilder[S, T, A, K[_]]:
      NNbuilder[S, T, K, A, DDD[Set[S],T,K[A]], NN[S,T,A,K,?], Unit] =
    new NNNbuilder[S, T, K, A]
}

// Remove the type parameter E, hardcoding in E := Unit, and the issue
// goes away.
trait NNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends Builder[Unit, N] {
  def clear(): Unit = throw new UnsupportedOperationException()
  final def addOne(builder: E): this.type = this
}

// Unfold this class defn, and the issue goes away
abstract class AbstractNNNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends NNbuilder[S,T,K,A,D,N,E]

class NNNbuilder[S, T, K[_], A] extends AbstractNNNbuilder[
  S, T, K, A, DDD[Set[S], T, K[A]], NNN[S, T, K, A], Unit
] {
  override def result(): NNN[S, T, K, A] = new NNN[S, T, K, A]
}

@main def run: Unit = {
  val builder = NN.newBuilder[String, Char, Int, Set]
  builder += ()
  builder.result()
}
```

## Output (from `sbt`)

```scala
[info] compiling 1 Scala source to /home/jm/Lib/Scala/scratch/target/scala-3.0.1/classes ...
[info] done compiling
[info] running run 
[error] (run-main-56) java.lang.AbstractMethodError: Receiver class NNNbuilder does not define or inherit an implementation of the resolved method 'abstract scala.collection.mutable.Growable addOne(java.lang.Object)' of interface scala.collection.mutable.Growable.
[error] java.lang.AbstractMethodError: Receiver class NNNbuilder does not define or inherit an implementation of the resolved method 'abstract scala.collection.mutable.Growable addOne(java.lang.Object)' of interface scala.collection.mutable.Growable.
[error] 	at scala.collection.mutable.Growable.$plus$eq(Growable.scala:36)
[error] 	at scala.collection.mutable.Growable.$plus$eq$(Growable.scala:36)
[error] 	at AbstractNNNbuilder.$plus$eq(Main.scala:29)
[error] 	at Main$package$.run(Main.scala:45)
[error] 	at run.main(Main.scala:43)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
```

## Expectation

The compiler and RTS should agree that class `NNNbuilder` is not abstract.

**Comment by jphmrst** [comment]
(Original edited with a few more minimalizations to the example.)

**Comment by smarter** [comment]
Fascinating. Looks like Scala 2 has the same issue (had to replace `?` by `_` and drop an explicit result type to get it to compile): https://scastie.scala-lang.org/124mRu2nRkCaLeoqGRJreQ, could you report the issue at https://github.com/scala/bug/issues too? Hopefully they can figure it out so I don't have to :grin:.

**Comment by jphmrst** [comment]
Will do.

**Comment by jphmrst** [comment]
Actually, this works for me under 2.13.6:

```
import scala.collection.mutable.Builder

class DDD[S,T,A]

trait NN[S, T, A, K[_], +D <: DDD[Set[S],T,K[A]]]
class NNN[S, T, K[_], A] extends NN[S, T, A, K, DDD[Set[S],T,K[A]]]

object NN {
  def newBuilder[S, T, A, K[_]] = new NNNbuilder[S, T, K, A]
}

// Remove the type parameter E, hardcoding in E := Unit, and the issue
// goes away.
trait NNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends Builder[Unit, N] {
  def clear(): Unit = throw new UnsupportedOperationException()
  final def addOne(builder: E): this.type = this
}

// Unfold this class defn, and the issue goes away
abstract class AbstractNNNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends NNbuilder[S,T,K,A,D,N,E]

class NNNbuilder[S, T, K[_], A] extends AbstractNNNbuilder[
  S, T, K, A, DDD[Set[S], T, K[A]], NNN[S, T, K, A], Unit
] {
  override def result(): NNN[S, T, K, A] = new NNN[S, T, K, A]
}

object Main extends App {
  def main: Unit = {
    val builder = NN.newBuilder[String, Char, Int, Set]
    builder += ()
    builder.result()
  }
}
```
The main change is dropping the return type from `newBuilder` --- but that still gives the problem in 3.0.1.

**Comment by smarter** [comment]
You wrote `object Main extends App { def main = ...  }`, this won't execute the code in the main method, if using extends App, only the code written directly in the object outside of a def will be executed, you can also drop the extends App and use `def main(args: Array[String]): Unit` as in https://scastie.scala-lang.org/124mRu2nRkCaLeoqGRJreQ

**Comment by jphmrst** [comment]
> You wrote `object Main extends App { def main = ... }`, this won't execute the code in the main method, if using extends App, only the code written directly in the object outside of a def will be executed, you can also drop the extends App and use `def main(args: Array[String]): Unit` as in https://scastie.scala-lang.org/124mRu2nRkCaLeoqGRJreQ

Ah sorry --- I'm already not used to version 2 anymore!

**Comment by joroKr21** [comment]
Related? scala/bug#8681, scala/bug#12209, #10079

**Comment by smarter** [comment]
Thanks @joroKr21, the seven years old (!) https://github.com/scala/bug/issues/8681 looks like a good minimization:
```scala
trait SimpleTrait[T] {
  def myMethod(t: T): Int
  def doIt(t: T): Unit = {
    myMethod(t) // java.lang.AbstractMethodError: Method BadClass.myMethod(Ljava/lang/Object;)I is abstract
 }
}

abstract class SimpleClass[T] extends SimpleTrait[T] {
  def myMethod(t: String): Int = 5
}

class BadClass extends SimpleClass[String]

object Test {
  def main(args: Array[String]): Unit =
    (new BadClass).doIt("foobar")
}
```

@odersky would you have time to take a look at this?
