### ISSUE TITLE
Self application of polymorphic type leads to Ycheck errors

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#13143]
## Compiler version 

3.0.2

## Minimized code

```Scala
object O{
  val v = [T] => (y:T) => (x:y.type) => 3
  def m = v(v)   // works
}

object O2{
  val v = [T] => (y:T) => (x:y.type) => 3
  def m = v(identity(v))  // error
}
```

## Output

When compiling with -Ycheck:

```scala
exception occurred while compiling i6682a.scala
java.lang.AssertionError: assertion failed: Found:    [T] => (y: T) => y.type => Int
Required: [T] => (y: Any) => y².type => Int

where:    y  is a reference to a value parameter
          y² is a reference to a value parameter```
```

## Expectation

No errors

**Comment by SolalPirelli** [comment]
Still an issue on main:

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Type Mismatch (while checking typedUnadapted):
Position: /tmp/x.scala:8:21
Found:    [T] => (y: T) => (y : T) => Int
Required: [T] => (y: Nothing) => (y : Nothing) => Int
I tried to show that
  [T] => (y: T) => (y : T) => Int
conforms to
  [T] => (y: Nothing) => (y : Nothing) => Int
but none of the attempts shown below succeeded:

  ==> [T] => (y: T) => (y : T) => Int  <:  [T] => (y: Nothing) => (y : Nothing) => Int
    ==> hasMatchingMember([T] => (y: T) => (y : T) => Int . apply, [T](y: Nothing): (y : Nothing) => Int), member = [T](y: T): (y : T) => Int
      ==> [T](y: T): (y : T) => Int  <:  [T](y: Nothing): (y : Nothing) => Int  = false

The tests were made under a constraint with:
 uninstantiated variables: (param)3, (param)4
 constrained types:
  [(param)3 <: ([T] => (y: T) => (y : T) => Int) & Singleton]:
    (y : [T] => (y: T) => (y : T) => Int),
  [(param)4 <: ([T] => (y: Nothing) => (y : Nothing) => Int) & Singleton]:
    (y : [T] => (y: Nothing) => (y : Nothing) => Int)
 bounds:
     (param)3
     >: (O.v : [T] => (y: T) => (y : T) => Int) <: ([T] => (y: T) => (y : T) =>
      Int) & Singleton
     (param)4 <: ([T] => (y: Nothing) => (y : Nothing) => Int) & Singleton
 ordering:
 co-deps:
 contra-deps:

tree = identity[[T] => (y: T) => (y : T) => Int](O2.v) Apply
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:10)
	at dotty.tools.dotc.transform.TreeChecker$Checker.checkType(TreeChecker.scala:864)
```
