### ISSUE TITLE
StackOverflowError when matching on union of enums and a sealed trait without subclass

### ISSUE THREAD

**Issue by aumann** [lampepfl/dotty#13235]
## Compiler version

3.0.0 (stack trace), 3.0.1 (still reproducible)

## Minimized code

```Scala
sealed trait A
// class A1 extends A // uncomment and SOE goes away (even in the original, non-minimized case)

enum B:
  case B1

enum C:
  case C1

type Msg = A | B | C

def oops(msg: Msg): String = msg match
  case B.B1 => "b"
  case C.C1 => "c" // removing this line does not crash anymore
  //case _: A => "a" // this one makes no difference

```

## Output (click arrow to expand)
<details>

```scala
java.lang.StackOverflowError while compiling soe-empty-sealed.scala
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:182)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:190)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:128)
	at dotty.tools.dotc.core.TypeComparer$.topLevelSubType(TypeComparer.scala:2606)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:1003)
	at dotty.tools.dotc.core.TypeOps$.instantiateToSubType(TypeOps.scala:773)
	at dotty.tools.dotc.core.TypeOps$.refineUsingParent(TypeOps.scala:658)
	at dotty.tools.dotc.core.TypeComparer.decompose$2$$anonfun$1(TypeComparer.scala:2427)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.TypeComparer.decompose$1(TypeComparer.scala:2427)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint(TypeComparer.scala:2450)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint(TypeComparer.scala:2526)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint$$anonfun$1(TypeComparer.scala:2450)
	at scala.collection.immutable.List.forall(List.scala:386)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint(TypeComparer.scala:2450)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint(TypeComparer.scala:2526)
	at dotty.tools.dotc.core.TypeComparer.provablyDisjoint$$anonfun$1(TypeComparer.scala:2450)
	at scala.collection.immutable.List.forall(List.scala:386)
[... and so on]
```
</details>

## Comment
It seems to be mostly related to the sealed trait without a sub class. At least for my original, non-minimized code, adding a sub-class (or rather changing A to an enum with one case) hacks around the issue even for larger unions of more enums.

If the `trait A` is not sealed, adding a sub class does not make a difference anymore

**Comment by smarter** [comment]
It looks like this is fixed in 3.0.2-RC1.

**Comment by aumann** [comment]
Ah, yes. Sorry for the noise, sdkman and scastie could not provide me with that version - what would have been the easiest way to get an RC version of scalac, coursier?

**Comment by smarter** [comment]
Yes, or alternatively  `scala -3.0.2-RC1` using https://github.com/dwijnand/scala-runners, you could also raise an issue at https://github.com/scalacenter/scastie/ about the missing 3.0.2-RC1.
