### ISSUE TITLE
inlined given resulting in runtime error java.lang.NoSuchFieldError: $outer

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13334]
## Compiler version

v3.0.2-RC1 (also tried on master branch)

## Minimized code

```Scala
trait DFC
given DFC = new DFC {}

trait TC
object TC:
  def foo()(using DFC): Unit = {}

  inline given (using DFC): TC = new TC:
    foo()

class Foo(using DFC):
  summon[TC]

val top = new Foo
```

## Output
See scastie: https://scastie.scala-lang.org/yZG6miffRf6f4O6od68i2w
```scala
java.lang.NoSuchFieldError: $outer
	at Playground$$anon$2.<init>(main.scala:11)
	at Playground$Foo.<init>(main.scala:11)
	at Playground$.<clinit>(main.scala:16)
	at Main$.<clinit>(main.scala:20)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:133)
	at sbt.Run.execute$1(Run.scala:82)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.lang.Thread.run(Thread.java:748)
```

## Expectation
No runtime error.

**Comment by dwijnand** [comment]
Running with `-Ycheck:all` shows:

```
checking tests/run/i13334.scala after phase inlining
exception while typing Foo.this.x$1 of class class dotty.tools.dotc.ast.Trees$Ident # -1
exception while typing Foo.this.x$1 of class class dotty.tools.dotc.ast.Trees$Inlined # -1
exception while typing TC.foo()(Foo.this.x$1) of class class dotty.tools.dotc.ast.Trees$Apply # -1
...
Exception in thread "main" java.lang.AssertionError: assertion failed: bad type (Foo.this.x$1 : DFC) for Foo.this.x$1 # -1
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedIdent(TreeChecker.scala:363)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2664)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2757)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
```

**Comment by odersky** [comment]
It seems inlining local classes has lots of problems. Can we outlaw it completely?

**Comment by nicolasstucki** [comment]
This is the foundation we need to specialize by inclining. Probably many libraries use it already.

**Comment by odersky** [comment]
After #14568 the "bad type problem" is fixed. But we now get a new problem for the original code from @soronpo:
```
*** error while checking i13334a.scala after phase inlining ***
exception occurred while compiling i13334a.scala
java.lang.AssertionError: assertion failed: wrong source set for Baz.this.x$1 # -1 of class dotty.tools.dotc.ast.Trees$Select, set to library/src/scala/runtime/stdLibPatches/Predef.scala but context had i13334a.scala
 private[this] <paramaccessor> <synthetic> given <touched> while compiling i13334a.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: wrong source set for Baz.this.x$1 # -1 of class dotty.tools.dotc.ast.Trees$Select, set to library/src/scala/runtime/stdLibPatches/Predef.scala but context had i13334a.scala
```
I verified that the same error occurs even without #14568 if we disable the "bad type problem" check.
