### ISSUE TITLE
Crasher in Term.show for Skolem type

### ISSUE THREAD

**Issue by jrudolph** [lampepfl/dotty#13422]
## Compiler version

3.0.1

## Reproducer

With branch https://github.com/jrudolph/parboiled2/tree/skkolem-crasher run `parboiledCoreJVM/Test/compile` in sbt.

## Output

```
scala.MatchError: Skolem(1943876506) (of class dotty.tools.dotc.core.Types$SkolemType)
	at scala.quoted.runtime.impl.printers.Extractors$ExtractorsPrinter.visitType(Extractors.scala:233)
	at scala.quoted.runtime.impl.printers.Extractors$.showType(Extractors.scala:12)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$17.show(QuotesImpl.scala:2898)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$17.show(QuotesImpl.scala:2897)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1660)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1660)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printType(SourceCode.scala:1228)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printType(SourceCode.scala:1102)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTypeAndAnnots$1(SourceCode.scala:1003)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTypeTree(SourceCode.scala:1005)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree(SourceCode.scala:528)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTrees$$anonfun$1(SourceCode.scala:656)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printSeparated$3(SourceCode.scala:647)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printList(SourceCode.scala:651)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTrees(SourceCode.scala:656)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree$$anonfun$8(SourceCode.scala:418)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.inSquare(SourceCode.scala:88)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree(SourceCode.scala:418)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printQualTree(SourceCode.scala:546)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree(SourceCode.scala:399)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printQualTree(SourceCode.scala:546)
	at scala.quoted.runtime.impl.printers.SourceCode$SourceCodePrinter.printTree(SourceCode.scala:399)
	at scala.quoted.runtime.impl.printers.SourceCode$.showTree(SourceCode.scala:10)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$10.show(QuotesImpl.scala:2870)
	at scala.quoted.runtime.impl.QuotesImpl$$anon$10.show(QuotesImpl.scala:2869)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.show(QuotesImpl.scala:95)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.show(QuotesImpl.scala:95)
```

**Comment by nicolasstucki** [comment]
I could not start SBT on that project
```
error: error while loading AnnotatedElement, class file '/usr/local/Cellar/openjdk@8/1.8.0+282/libexec/openjdk.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(bad constant pool tag 18 at byte 76)
error: error while loading CharSequence, class file '/usr/local/Cellar/openjdk@8/1.8.0+282/libexec/openjdk.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
```

@jrudolph what version of the JDK are you using? Or could you help me minimize the issue?
