### ISSUE TITLE
crash -from-tasty when method goes from no-parens to empty-parens

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#13501]
## Compiler version

3.1.0-RC1

## Minimized code

compile the following to `b-input`

```Scala
// a/A.scala
package a

object A {
  def values: Array[Int] = Array(1,2,3)
}
```

with `b-input` on classpath, compile to `c-input`

```Scala
// b/B.scala
package b

import a.*

object B extends App {
  assert(A.values(1) == 2)
}
```

we will change `A.values`, compile the following to `c-input`

```Scala
// changes/a/A.scala
package a

object A {
  def values(): Array[Int] = Array(1,2,3)
}
```

then run
```
> scalac -from-tasty -d c-output -classpath c-input c-input/b/B.tasty
```

## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: invalid prefix MethodType(List(), List(), AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Array),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Int)))) while compiling c-input/b/B.tasty
Exception in thread "main" java.lang.AssertionError: assertion failed: invalid prefix MethodType(List(), List(), AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Array),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Int))))
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.Types$NamedType.<init>(Types.scala:2066)
	at dotty.tools.dotc.core.Types$TermRef.<init>(Types.scala:2608)
	at dotty.tools.dotc.core.Types$CachedTermRef.<init>(Types.scala:2687)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.newType$1(Uniques.scala:44)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.enterIfNew(Uniques.scala:46)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2738)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2744)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.dotty$tools$dotc$core$tasty$TreeUnpickler$TreeReader$$_$makeSelect$1(TreeUnpickler.scala:1078)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1228)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1139)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1200)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1139)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1058)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1164)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.completeSelect$1(TreeUnpickler.scala:1083)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readSimpleTerm$1(TreeUnpickler.scala:1108)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1172)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1058)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1164)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1299)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:1000)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats$$anonfun$1(TreeUnpickler.scala:1038)
	at dotty.tools.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1038)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.$anonfun$17$$anonfun$1(TreeUnpickler.scala:956)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1438)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy(Trees.scala:1027)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy$(Trees.scala:1022)
	at dotty.tools.dotc.ast.Trees$Template.forceIfLazy(Trees.scala:870)
	at dotty.tools.dotc.ast.Trees$Template.body(Trees.scala:876)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1617)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1648)
	at dotty.tools.dotc.CompilationUnit$Force.traverse(CompilationUnit.scala:144)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1647)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1647)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1614)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1648)
	at dotty.tools.dotc.CompilationUnit$Force.traverse(CompilationUnit.scala:144)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1647)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1647)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1522)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1524)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1623)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1528)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1648)
	at dotty.tools.dotc.CompilationUnit$Force.traverse(CompilationUnit.scala:144)
	at dotty.tools.dotc.CompilationUnit$.apply(CompilationUnit.scala:108)
	at dotty.tools.dotc.CompilationUnit$.apply(CompilationUnit.scala:99)
	at dotty.tools.dotc.fromtasty.ReadTasty.compilationUnit$1(ReadTasty.scala:42)
	at dotty.tools.dotc.fromtasty.ReadTasty.readTASTY(ReadTasty.scala:70)
	at dotty.tools.dotc.fromtasty.ReadTasty.runOn$$anonfun$1(ReadTasty.scala:25)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at dotty.tools.dotc.fromtasty.ReadTasty.runOn(ReadTasty.scala:25)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:228)
	at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:12)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by bishabosha** [comment]
the relevant TASTy of B:
```
108: APPLY(15)
110:   SELECTin(11) 36 [apply[Signed Signature(List(scala.Int),java.lang.Object) @apply]]
113:     SELECT 37 [values]
115:       TERMREF 38 [A]
117:         SHAREDtype 7
119:     TYPEREF 39 [Array]
121:       SHAREDtype 68
123:   INTconst 1
```

**Comment by odersky** [comment]
The question is whether from-tasty should support incremental compilation like this. I don't think that has been mandated. If we want that to happen, we should change most assertions in TreeUnpickler to reported errors.
