### ISSUE TITLE
Crash when overriding an inline method under specific conditions

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#13586]
## Compiler version

Master.

## Minimized code

```Scala
// scratch0.scala
import scala.quoted._

case class Position(fileName: String, filePathname: String, lineNumber: Int)

object Position {

  implicit inline def here: Position = ${ genPosition }

  private def genPosition(using Quotes): Expr[Position] = {
    val pos = quotes.reflect.Position.ofMacroExpansion
    val file = pos.sourceFile
    val fileName: String = Option(file.jpath).map(_.getFileName.toString).getOrElse("<unknown>")
    val filePath: String = file.toString
    val lineNo: Int = pos.startLine + 1
    '{ Position(${Expr(fileName)}, ${Expr(filePath)}, ${Expr(lineNo)}) }
  }

  def withPosition[T](fun: Expr[Position => T])(using quotes: Quotes, typeOfT: Type[T]): Expr[T] = {
    val pos = quotes.reflect.Position.ofMacroExpansion
    val file = pos.sourceFile
    val fileName: String = file.jpath.getFileName.toString
    val filePath: String = file.toString
    val lineNo: Int = pos.startLine + 1
   '{${fun}.apply(Position(${Expr(fileName)}, ${Expr(filePath)}, ${Expr(lineNo)}))}
  }

}
```

```scala
// scratch.scala
import scala.quoted._

class Foo {
  private final def testImpl(testName: String, testTags: String*)(testFun: => Any /* Assertion */, pos: Position): Unit = {
    val stackDepth = 4
    val stackDepthAdjustment = -2
    ()
  }

 inline def test(testName: String, testTags: String*)(testFun: => Any /* Assertion */): Unit = {
   ${ Position.withPosition[Unit]('{(pos: Position) => testImpl(testName, testTags: _*)(testFun, pos) }) } 
 }
 
}

class Bar extends Foo {
  def test(testCat: String, testName: String) =
    super.test("a, b") { () }
}
```

## Output (click arrow to expand)

Compiling the files crashes. The crash is caused by the `super.test` call in `test`.

<details>

```
// scalac scratch0.scala scratch.scala
Unexpected tree in genLoad: Super(This(Ident()),Ident())/class dotty.tools.dotc.ast.Trees$Super at: [517..522]
Exception in thread "main" java.lang.RuntimeException: Unexpected tree in genLoad: Super(This(Ident()),Ident())/class dotty.tools.dotc.ast.Trees$Super at: [517..522]
	at dotty.tools.backend.jvm.BCodeHelpers.abort(BCodeHelpers.scala:949)
	at dotty.tools.backend.jvm.BCodeHelpers.abort$(BCodeHelpers.scala:43)
	at dotty.tools.backend.jvm.GenBCodePipeline.abort(GenBCode.scala:111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:454)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:285)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:638)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:452)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:305)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock$$anonfun$1(BCodeBodyBuilder.scala:1019)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1019)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:432)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:766)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:801)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:609)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:615)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:615)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:230)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:259)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:224)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:559)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:525)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:63)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:71)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:228)
	at dotty.tools.dotc.Driver.finish(Driver.scala:60)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:40)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
Error while emitting scratch.scala
java.lang.RuntimeException: Unexpected tree in genLoad: Super(This(Ident()),Ident())/class dotty.tools.dotc.ast.Trees$Super at: [517..522] while compiling scratch0.scala, scratch.scala
```
</details>

**Comment by abgruszecki** [comment]
@nicolasstucki sorry for the unminimised example - I just wanted to get this off my mind. I'll minimise it as soon as I find the time.

**Comment by abgruszecki** [comment]
Ok, turns out I have some time now - the examples are minimised.

**Comment by nicolasstucki** [comment]
Minimized to
```scala
class Foo:
 inline def test(): Unit = this

class Bar extends Foo:
  def test(s: String) = super.test()
```

This issue is that when we inline we generate the binding `val Foo_this: Bar.this = super` instead of `val Foo_this: Bar.this = this`.
