### ISSUE TITLE
repl: memory leak

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1376]
```scala
Welcome to Scala.next (pre-alpha)  (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.
scala> List("1", "2").toSet
res0: scala.collection.immutable.Set[String] = Set(1, 2)
scala> List("1", "2").toSet()
                    ^
List("1", "2").toSet()
<console>:5: error: missing argument for parameter elem of method apply: (elem: String')Boolean
scala> List("1", "2").toSet
res2: scala.collection.immutable.Set[String] = Set(1, 2)
scala> res2(())
     ^
res2(())
<console>:6: error: type mismatch:
 found   : Unit
 required: String
scala> 1 + "3"
res4: String = 13
scala> 1 + "3"
res5: String = 13
scala> List("1", "2") + "2"
res6: String = List(1, 2)2
scala> List("1", "2").toSet.apply()
                          ^
List("1", "2").toSet.apply()
<console>:5: error: missing argument for parameter elem of method apply: (elem: String')Boolean
scala> List("1", "2").toSet.apply(())
res8: Boolean = false
scala> import math.signum
import math.signum
scala> import Double.NegativeInfinity
import Double.NegativeInfinity
scala> import Double.PositiveInfinity
import Double.PositiveInfinity
scala>
scala> val Underflow_+ = +0.0  // 1.0 / PositiveInfinity
Underflow_+: <notype> = 0.0
scala> val Underflow_- = -0.0  // 1.0 / NegativeInfinity
Underflow_-: <notype> = -0.0
scala> def check(d: Double) = signum(d) match {
         case +1.0        => "positive"
        ^
  case +1.0        => "positive"
<console>:2: error: '=>' expected but double literal found
scala>   case Underflow_+ => "underflow from the right"
  ^
  case Underflow_+ => "underflow from the right"
<console>:1: error: illegal start of definition
scala>   case Underflow_- => "underflow from the left"
  ^
  case Underflow_- => "underflow from the left"
<console>:1: error: illegal start of definition
scala>   case -1.0        => "negative"
  ^
  case -1.0        => "negative"
<console>:1: error: illegal start of definition
scala> }
 ^
;}
<console>:8: error: eof expected but '}' found
scala>
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:622)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:267)
	at scala.collection.mutable.StringBuilder.$plus$eq(StringBuilder.scala:175)
	at dotty.tools.dotc.printing.SyntaxHighlighting$.apply(SyntaxHighlighting.scala:110)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$4.apply(AmmoniteReader.scala:61)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$4.apply(AmmoniteReader.scala:59)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.x$3$lzycompute$1(Terminal.scala:219)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.x$3$1(Terminal.scala:219)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.transformedBuffer0$lzycompute$1(Terminal.scala:219)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.transformedBuffer0$1(Terminal.scala:219)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.transformedBuffer$lzycompute$1(Terminal.scala:224)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.transformedBuffer$1(Terminal.scala:224)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.readChar$1(Terminal.scala:279)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.readLine(Terminal.scala:299)
	at dotty.tools.dotc.repl.AmmoniteReader.readLine(AmmoniteReader.scala:54)
	at dotty.tools.dotc.repl.InterpreterLoop.repl$default$1(InterpreterLoop.scala:74)
	at dotty.tools.dotc.repl.InterpreterLoop.repl(InterpreterLoop.scala:80)
	at dotty.tools.dotc.repl.InterpreterLoop.run(InterpreterLoop.scala:210)
	at dotty.tools.dotc.repl.REPL.doCompile(REPL.scala:43)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.Driver.process(Driver.scala:105)
	at dotty.tools.dotc.Driver.main(Driver.scala:132)
	at dotty.tools.dotc.repl.Main.main(Main.scala)
```

**Comment by kcsongor** [comment]
Can you still reproduce this? I feel like #1375 might have been related and that's fixed now

**Comment by cswinter** [comment]
I have not managed to reproduce this, I propose closing the issue.
