### ISSUE TITLE
Crasher when inline argument is missing

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#13893]
## Compiler version

3.1

## Minimized example

```
scalac foo.scala -Xmax-inlines
```

## Output

```scala
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
	at dotty.tools.dotc.config.Settings$Setting.doSet$1(Settings.scala:140)
	at dotty.tools.dotc.config.Settings$Setting.tryToSet(Settings.scala:170)
	at dotty.tools.dotc.config.Settings$SettingGroup.loop$1(Settings.scala:231)
	at dotty.tools.dotc.config.Settings$SettingGroup.processArguments(Settings.scala:236)
	at dotty.tools.dotc.config.Settings$SettingGroup.processArguments(Settings.scala:243)
	at dotty.tools.dotc.config.CliCommand.distill(CliCommand.scala:51)
	at dotty.tools.dotc.config.CliCommand.distill$(CliCommand.scala:12)
	at dotty.tools.dotc.config.CompilerCommand.distill(CompilerCommand.scala:12)
	at dotty.tools.dotc.Driver.setup(Driver.scala:78)
	at dotty.tools.dotc.Driver.process(Driver.scala:197)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.process(Driver.scala:179)
	at dotty.tools.dotc.Driver.main(Driver.scala:209)
	at dotty.tools.dotc.Main.main(Main.scala)
```

## Expectation

No crash

**Comment by odersky** [comment]
I believe this was introduced in 363c0d6
