### ISSUE TITLE
GraalVM Native Image Requires Config for lazy vals

### ISSUE THREAD

**Issue by jamesward** [lampepfl/dotty#13985]
## Compiler version

`3.1.0`

## Background

GraalVM Native Image Ahead-of-Time compiles JVM apps into native executables.  To do the AOT compilation, reflection points must be specified.

## Issue 1

Scala's `scala.runtime.LazyVals` uses reflection so it must be declared.  This could be done in the Scala stdlib so that others don't need to do it themselves.  But this approach is a bit brittle.  Any chance of removing the use of `sun.misc.Unsafe` there?  If not, then I can send a PR to include the GraalVM reflection config:
```
  {
    "name":"sun.misc.Unsafe",
    "allDeclaredFields":true
  }
```

## Issue 2

Code generated by the compiler for lazy vals also uses reflection and must be declared, like:
```
  {
    "name":"App$package$",
    "fields":[{"name":"0bitmap$1"}]
  }
```

Also, ideally reflection is not required.  But I haven't looked into what the reflection is doing.  If someone uses a Scala library that uses lazy vals, and does NOT provide their reflection config for GraalVM, then the user must specify the config for the library on their own.  Ideally the library authors nor the users need to specify this info.

## Steps to Reproduce

1. Clone `https://github.com/jamesward/scala3-graalvm-tester.git`
1. Switch to the `lazy-reflect-broke` branch
1. Run `./sbt nativeImage nativeImageRun`

You will see a runtime error showing Issue 1:
```
Exception in thread "main" scala.runtime.LazyVals$$anon$1
	at scala.runtime.LazyVals$.$init$$$anonfun$3(LazyVals.scala:18)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.runtime.LazyVals$.<clinit>(LazyVals.scala:19)
	at App$package$.<clinit>(App.scala:2)
	at run.main(App.scala:4)
```

(Note: It should be possible to fail the build in this case instead of producing a runtime error but there seems to be a bug: https://github.com/oracle/graal/issues/4010)

If you switch to the `lazy-reflect-works` branch and re-run `./sbt nativeImage nativeImageRun` you will see that it works given [the requisite config](https://github.com/jamesward/scala3-graalvm-tester/blob/lazy-reflect-works/src/main/resources/META-INF/native-image/reflect-config.json) for the app in that repo that has one lazy val.

## One Approach (If Reflection Must Stay)

The Spring team has developed a set of annotations which provide the reflection info, like:
https://docs.spring.io/spring-native/docs/0.9.1-SNAPSHOT/api/org/springframework/nativex/hint/TypeHint.html

There has been talk that this work will merge in some way into GraalVM itself.  In that case, the Scala compiler could generate the necessary `TypeHint` annotations for places it generates code that uses reflection.

**Comment by xuwei-k** [comment]
- https://github.com/lampepfl/dotty/issues/9013

**Comment by nicolasstucki** [comment]
This reflective call was added in https://github.com/lampepfl/dotty/commit/0f7d25166d51684e1839c7df8275135d51656910.

**Comment by michelou** [comment]
Long standing issue that should have received more attention.
See for instance article (2015) [*Java’s Unsafe class: “There is certainly also a way without it!”*](https://jaxenter.com/javas-unsafe-class-there-is-certainly-also-a-way-without-it-119084.html).

**Comment by francisdb** [comment]
Some more context here: https://www.reddit.com/r/scala/comments/rzvkmi/graalvm_nativeimage_with_scala_3_reflection_hell/

**Comment by TheElectronWill** [comment]
I believe that this is fixed by #14780 (and the new scheme implemented by #15296 should keep the fix)

**Comment by Dispersia** [comment]
hello, i tried with scala 3.2.0-RC3 and it's still happening. I don't see what release that one is supposed to be a part of, but it was checked in much before that date, is there any way I can confirm if it's in by that one or not?

**Comment by sideeffffect** [comment]
This fixing commit is present since `3.2.0-RC1`.

**Comment by xuwei-k** [comment]
Maybe need re-compile with new Scala 3 version all libraries 🤔

**Comment by jamesward** [comment]
I bumped the `https://github.com/jamesward/scala3-graalvm-tester.git` branch `lazy-reflect-broke` to `3.2.0-RC3` and still have the issue.

**Comment by Dispersia** [comment]
As @jamesward example, I have no libraries, it's happening from just having a lazy in my own code

**Comment by smarter** [comment]
Let's re-open the issue then, maybe @romanowski could have a look since he implemented the original fix in https://github.com/lampepfl/dotty/pull/14780 ?

**Comment by szymon-rd** [comment]
There could be a native implementation of lazy vals for Scala Native. Unsafe only provides us immediate access to the memory on JVM, so that is an unnecessary step in this case. However, it would need minor adjustments to the schema, but we can coordinate that with implementing https://github.com/lampepfl/dotty/pull/15296.   @WojciechMazur

**Comment by TheElectronWill** [comment]
IMO the best solution is to stop using sun.misc.Unsafe on Java 9+, i.e. fixing #9013.

This will fix GraalVM problems because it's only Java 11 and Java 17.

**Comment by smarter** [comment]
That would help too, but it won't completely solve the issue until Scala libraries that use lazy vals stop supporting Java 8.

**Comment by carlosedp** [comment]
I have a sample project using ZIO and Scala 3 and this issue happens. Running the Native Image binary gave me:

```
❯ /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/out/backend/nativeImage.dest/backend
Exception in thread "main" scala.runtime.LazyVals$$anon$1
	at scala.runtime.LazyVals$.$init$$$anonfun$3(LazyVals.scala:18)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.runtime.LazyVals$.<clinit>(LazyVals.scala:19)
	at zio.ZLayer.<clinit>(ZLayer.scala:42)
	at java.lang.Class.ensureInitialized(DynamicHub.java:525)
	at zio.ZLayer$Suspend$.apply(ZLayer.scala:437)
	at zio.ZLayer$.suspend(ZLayer.scala:667)
	at zio.ZLayer$.fromZIOEnvironment(ZLayer.scala:613)
	at zio.ZLayer$.<clinit>(ZLayer.scala:558)
	at zio.ZIOAppDefault.$init$(ZIOAppDefault.scala:43)
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:11)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
```

I tried @jamesward workaround by creating `/backend/resources/META-INF/native-image/reflect-config.json` with:

```json
[
  {
    "name":"sun.misc.Unsafe",
    "allDeclaredFields":true
  },
  {
    "name":"App$package$",
    "fields":[{"name":"0bitmap$1"}]
  }
]
```

and then had the error:

```
❯ /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/out/backend/nativeImage.dest/backend
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.ensureInitialized(DynamicHub.java:525)
	at zio.ZLayer$Suspend$.apply(ZLayer.scala:437)
	at zio.ZLayer$.suspend(ZLayer.scala:667)
	at zio.ZLayer$.fromZIOEnvironment(ZLayer.scala:613)
	at zio.ZLayer$.<clinit>(ZLayer.scala:558)
	at zio.ZIOAppDefault.$init$(ZIOAppDefault.scala:43)
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:11)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$1
	at java.lang.Class.getDeclaredField(DynamicHub.java:968)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:103)
	at zio.ZLayer.<clinit>(ZLayer.scala:42)
	... 8 more
```

Also tried removing the `bitmal$1` field but same happens. I'm using Scala 3.2.0. Anything I missed?

**Comment by smarter** [comment]
It seems there's still something missing, @szymon-rd in https://github.com/lampepfl/dotty/issues/13985#issuecomment-1216775338 suggested we need to go through `theUnsafe` to get the unsafe instance, has anyone tried that?

**Comment by carlosedp** [comment]
Thanks @szymon-rd I'm out today on local holy day returning tomorrow afternoon. Gonna test as soon as I get in computer.

**Comment by carlosedp** [comment]
Hey @szymon-rd , thanks a lot for the PR. I tried to go as deep as possible on this since the sample from above (simple LazyVal) worked but my sample app in Zio didn't.

I went on adding the unsafe fields to `reflect-config.json` for each error I found but stopped since it went on and on. 

One thing in common is that all of them refers to the `getOffset` method from `LazyVals.scala` so seems some fix on it might fix it all.

Below the reflect-config:

```json
[
    {
        "name": "izumi.reflect.macrortti.LightTypeTag",
        "fields": [
            {
                "name": "0bitmap$1",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag210",
        "fields": [
            {
                "name": "0bitmap$5",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "zhttp.http.Method$PUT$",
        "fields": [
            {
                "name": "0bitmap$6",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "zhttp.http.Method$DELETE$",
        "fields": [
            {
                "name": "0bitmap$8",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "zhttp.http.Method$POST$",
        "fields": [
            {
                "name": "0bitmap$5",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "zhttp.http.Method$GET$",
        "fields": [
            {
                "name": "0bitmap$3",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "izumi.reflect.macrortti.LightTypeTagRef$NameReference",
        "fields": [
            {
                "name": "0bitmap$5",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "izumi.reflect.macrortti.LightTypeTagInheritance",
        "fields": [
            {
                "name": "0bitmap$1",
                "allowUnsafeAccess": true
            }
        ]
    },
    {
        "name": "izumi.reflect.internal.fundamentals.platform.console.TrivialLogger$Config",
        "fields": [
            {
                "name": "0bitmap$1",
                "allowUnsafeAccess": true
            }
        ]
    }
]
```

And the errors I found each execution:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base@17.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:528)
	at izumi.reflect.macrortti.LightTypeTag$.parse(LightTypeTag.scala:271)
	at zio.ZIOAppDefault.$init$(ZIOAppDefault.scala:45)
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:10)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$1
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at izumi.reflect.macrortti.LightTypeTag.<clinit>(LightTypeTag.scala:49)
	... 5 more

--------------------------------------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at izumi.reflect.macrortti.LightTypeTag$.parse(LightTypeTag.scala:271)
	at zio.ZIOAppDefault.$init$(ZIOAppDefault.scala:45)
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:10)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$5
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag210.<clinit>(LightTypeTag.scala:375)
	... 4 more

--------------------------------------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:15)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$6
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at zhttp.http.Method$PUT$.<clinit>(Method.scala:58)
	... 2 more

--------------------------------------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:15)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$8
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at zhttp.http.Method$DELETE$.<clinit>(Method.scala:60)
	... 2 more

--------------------------------------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:15)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$5
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at zhttp.http.Method$POST$.<clinit>(Method.scala:57)
	... 2 more

--------------------------------------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.carlosedp.zioscalajs.backend.MainApp$.<clinit>(MainApp.scala:15)
	at com.carlosedp.zioscalajs.backend.MainApp.main(MainApp.scala)
Caused by: java.lang.NoSuchFieldException: 0bitmap$3
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
	at zhttp.http.Method$GET$.<clinit>(Method.scala:55)
	... 2 more

--------------------------------------------------------------------------------
timestamp=2022-11-16T18:37:56.009881Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.ExceptionInInitializerError: null
	at izumi.reflect.macrortti.LightTypeTag$$anon$8.unpickle(LightTypeTag.scala:490)
	at izumi.reflect.macrortti.LightTypeTag$$anon$8.unpickle(LightTypeTag.scala:487)
	at izumi.reflect.thirdparty.internal.boopickle.CompositePickler.unpickle(CompositePicklers.scala:56)
	at izumi.reflect.macrortti.LightTypeTag$.deserializeRefString(LightTypeTag.scala:395)
	at izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag210.ref(LightTypeTag.scala:377)
	at izumi.reflect.macrortti.LightTypeTag.decompose(LightTypeTag.scala:69)
	at zio.VersionSpecific.taggedGetServices(VersionSpecific.scala:75)
	at zio.VersionSpecific.taggedGetServices$(VersionSpecific.scala:26)
	at zio.package$.taggedGetServices(package.scala:23)
	at zio.ZEnvironment.prune(ZEnvironment.scala:65)
	at zio.ZEnvironment.union(ZEnvironment.scala:95)
	at zio.Scope$ExtendPartiallyApplied$.apply$extension$$anonfun$1(Scope.scala:172)
	at zio.ZIO.provideSomeEnvironment$$anonfun$1$$anonfun$1(ZIO.scala:1240)
	at zio.ZIO.provideEnvironment(ZIO.scala:1220)
	at zio.ZIO.provideEnvironment$(ZIO.scala:52)
	at zio.ZIO$OnSuccess.provideEnvironment(ZIO.scala:5533)
	at zio.ZIO.provideSomeEnvironment$$anonfun$1(ZIO.scala:1240)
	Suppressed: java.lang.NoSuchFieldException: 0bitmap$5
		at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
		at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
		at izumi.reflect.macrortti.LightTypeTagRef$NameReference.<clinit>(LightTypeTagRef.scala:343)
		at izumi.reflect.macrortti.LightTypeTag$$anon$8.unpickle(LightTypeTag.scala:490)
		at izumi.reflect.macrortti.LightTypeTag$$anon$8.unpickle(LightTypeTag.scala:487)
		at izumi.reflect.thirdparty.internal.boopickle.CompositePickler.unpickle(CompositePicklers.scala:56)
		at izumi.reflect.macrortti.LightTypeTag$.deserializeRefString(LightTypeTag.scala:395)
		at izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag210.ref(LightTypeTag.scala:377)
		at izumi.reflect.macrortti.LightTypeTag.decompose(LightTypeTag.scala:69)
		at zio.VersionSpecific.taggedGetServices(VersionSpecific.scala:75)
		at zio.VersionSpecific.taggedGetServices$(VersionSpecific.scala:26)
		at zio.package$.taggedGetServices(package.scala:23)
		at zio.ZEnvironment.prune(ZEnvironment.scala:65)
		at zio.ZEnvironment.union(ZEnvironment.scala:95)
		at zio.Scope$ExtendPartiallyApplied$.apply$extension$$anonfun$1(Scope.scala:172)
		at zio.ZIO.provideSomeEnvironment$$anonfun$1$$anonfun$1(ZIO.scala:1240)
		at zio.ZIO.provideEnvironment(ZIO.scala:1220)
		at zio.ZIO.provideEnvironment$(ZIO.scala:52)
		at zio.ZIO$OnSuccess.provideEnvironment(ZIO.scala:5533)
		at zio.ZIO.provideSomeEnvironment$$anonfun$1(ZIO.scala:1240)"

--------------------------------------------------------------------------------
timestamp=2022-11-16T18:43:25.741961Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.ExceptionInInitializerError: null
	at izumi.reflect.internal.fundamentals.platform.console.TrivialLogger$Config$.console(TrivialLogger.scala:71)
	at izumi.reflect.macrortti.LightTypeTagInheritance.isChild(LightTypeTagInheritance.scala:61)
	at izumi.reflect.macrortti.LightTypeTag.$less$colon$less(LightTypeTag.scala:61)
	at zio.VersionSpecific.taggedIsSubtype$$anonfun$1(VersionSpecific.scala:63)
	at java.base@17.0.5/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at zio.VersionSpecific.taggedIsSubtype(VersionSpecific.scala:63)
	at zio.VersionSpecific.taggedIsSubtype$(VersionSpecific.scala:26)
	at zio.package$.taggedIsSubtype(package.scala:23)
	at zio.ZEnvironment.$anonfun$1$$anonfun$1(ZEnvironment.scala:68)
	at scala.collection.IterableOnceOps.exists(IterableOnce.scala:603)
	at scala.collection.IterableOnceOps.exists$(IterableOnce.scala:600)
	at scala.collection.AbstractIterable.exists(Iterable.scala:933)
	at zio.ZEnvironment.$anonfun$1(ZEnvironment.scala:68)
	at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:172)
	at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:156)
	at scala.collection.StrictOptimizedIterableOps.filterNot(StrictOptimizedIterableOps.scala:220)
	at scala.collection.StrictOptimizedIterableOps.filterNot$(StrictOptimizedIterableOps.scala:220)
	at scala.collection.immutable.Set$Set1.filterNot(Set.scala:156)
	at zio.ZEnvironment.prune(ZEnvironment.scala:68)
	at zio.ZEnvironment.union(ZEnvironment.scala:95)
	at zio.Scope$ExtendPartiallyApplied$.apply$extension$$anonfun$1(Scope.scala:172)
	at zio.ZIO.provideSomeEnvironment$$anonfun$1$$anonfun$1(ZIO.scala:1240)
	at zio.ZIO.provideEnvironment(ZIO.scala:1220)
	at zio.ZIO.provideEnvironment$(ZIO.scala:52)
	at zio.ZIO$OnSuccess.provideEnvironment(ZIO.scala:5533)
	at zio.ZIO.provideSomeEnvironment$$anonfun$1(ZIO.scala:1240)
	Suppressed: java.lang.NoSuchFieldException: 0bitmap$1
		at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
		at scala.runtime.LazyVals$.getOffset(LazyVals.scala:138)
		at izumi.reflect.internal.fundamentals.platform.console.TrivialLogger$Config.<clinit>(TrivialLogger.scala:71)
		at izumi.reflect.internal.fundamentals.platform.console.TrivialLogger$Config$.console(TrivialLogger.scala:71)
		at izumi.reflect.macrortti.LightTypeTagInheritance.isChild(LightTypeTagInheritance.scala:61)
		at izumi.reflect.macrortti.LightTypeTag.$less$colon$less(LightTypeTag.scala:61)
		at zio.VersionSpecific.taggedIsSubtype$$anonfun$1(VersionSpecific.scala:63)
		at java.base@17.0.5/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
		at zio.VersionSpecific.taggedIsSubtype(VersionSpecific.scala:63)
		at zio.VersionSpecific.taggedIsSubtype$(VersionSpecific.scala:26)
		at zio.package$.taggedIsSubtype(package.scala:23)
		at zio.ZEnvironment.$anonfun$1$$anonfun$1(ZEnvironment.scala:68)
		at scala.collection.IterableOnceOps.exists(IterableOnce.scala:603)
		at scala.collection.IterableOnceOps.exists$(IterableOnce.scala:600)
		at scala.collection.AbstractIterable.exists(Iterable.scala:933)
		at zio.ZEnvironment.$anonfun$1(ZEnvironment.scala:68)
		at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:172)
		at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:156)
		at scala.collection.StrictOptimizedIterableOps.filterNot(StrictOptimizedIterableOps.scala:220)
		at scala.collection.StrictOptimizedIterableOps.filterNot$(StrictOptimizedIterableOps.scala:220)
		at scala.collection.immutable.Set$Set1.filterNot(Set.scala:156)
		at zio.ZEnvironment.prune(ZEnvironment.scala:68)
		at zio.ZEnvironment.union(ZEnvironment.scala:95)
		at zio.Scope$ExtendPartiallyApplied$.apply$extension$$anonfun$1(Scope.scala:172)
		at zio.ZIO.provideSomeEnvironment$$anonfun$1$$anonfun$1(ZIO.scala:1240)
		at zio.ZIO.provideEnvironment(ZIO.scala:1220)
		at zio.ZIO.provideEnvironment$(ZIO.scala:52)
		at zio.ZIO$OnSuccess.provideEnvironment(ZIO.scala:5533)
		at zio.ZIO.provideSomeEnvironment$$anonfun$1(ZIO.scala:1240)"
```

The project I've been testing on is at https://github.com/carlosedp/zio-scalajs-stack and it's configured to build with GraalVM and Scala 2.13 here https://github.com/carlosedp/zio-scalajs-stack/blob/main/build.sc#L57. I build with `./mill show backend.nativeImage`. 

Let me know if I can help by providing any additional info.
Hope it helps.

**Comment by szymon-rd** [comment]
@carlosedp I think it is because these libraries were not compiled with the newer lazy vals. My PR should fix initialization of LazyVals runtime class. However, I don't think that we are able to  change the runtime to make the libraries compiled with older Scala run without these exceptions. There are some solutions that can be implemented to make it work (any of these steps should help):
 - compile library with new Scala compiler
 - make an utility that traverses bytecode and extracts these bitmap fields and prepares the config 
 - make an utility that modifies bytecode in libraries to avoid using the old approach (a bit hacky)

**Comment by carlosedp** [comment]
Thanks for the feedback Szymon. I don't think I have the knowledge to attempt solutions 2 and 3 so I'll try to test building the libs locally with new compiler and wait until they get published to have it upstream.

Glad to know it should work from now on. Thanks a lot!

**Comment by makingthematrix** [comment]
I can confirm it works for my small Scala 3 + JavaFX project. Thanks! <3
https://github.com/makingthematrix/scalaonandroid/tree/main/calculator3

**Comment by carlosedp** [comment]
An FYI, scala-cli does one of the options mentioned by @szymon-rd. It manipulates the bytecode and patches the jars to "fix" lazyvals on current libraries.

https://github.com/VirtusLab/scala-cli/tree/main/modules/scala3-graal/src/main/scala/scala/cli/graal

**Comment by carlosedp** [comment]
I'm happy to add that since using Scala 3.3 (3.3.0-RC2), my ZIO project works perfectly with NativeImage.
Again thanks @szymon-rd for this!

**Comment by szymon-rd** [comment]
@carlosedp 3.3.0-RC2 has a bug for GraalVM, it sadly occurs fairly commonly and crashes the whole image. We will be backporting the fix for it: https://github.com/lampepfl/dotty/pull/16800

**Comment by jamesward** [comment]
Thanks @szymon-rd! I've verified this fix: https://github.com/jamesward/scala3-graalvm-tester/tree/lazy-reflect-fixed
