### ISSUE TITLE
ClassFormatError when `targetName`'s name is an empty string

### ISSUE THREAD

**Issue by timaliberdov** [lampepfl/dotty#14062]
## Compiler version

3.1.1-RC1

## Minimized code

```Scala
package com.example

import scala.annotation.targetName

class TargetName:
  @targetName("") def ^ = 1
```

Usage from Java:
```Java
package com.example.javausage;

import com.example.TargetName;

public class TargetNameUsage {
    public static void main(String[] args) {
        TargetName targetName = new TargetName();
    }
}
```

## Output

javap TargetName:

```java
Compiled from "TargetName.scala"
public class com.example.TargetName {
  public com.example.TargetName();
  public int ();
}
```

At runtime:

```stacktrace
Exception in thread "main" java.lang.ClassFormatError: Illegal method name "" in class com/example/TargetName
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.example.javausage.TargetNameUsage.main(TargetNameUsage.java:7)
```

## Expectation

Empty target name should probably be a compile error.

**Comment by odersky** [comment]
We should also check that other illegal target names are rejected. E.g. following:
```scala
import annotation.targetName

object Test extends App:

  @targetName("<init>") def test = ???
```
There are lots of other examples like this. One needs to consult the docs what constitutes a legal method name.

Some of this might be checked somewhere else already. Need to watch out for other illegal method names, whether they are rejected by some code.

**Comment by odersky** [comment]
@anatoliykmetyuk was this picked up by the last spree?
