### ISSUE TITLE
Regression with LambdaConversionException

### ISSUE THREAD

**Issue by jamesward** [lampepfl/dotty#14135]
## Compiler version

3.1.0

## Minimized code

https://github.com/jamesward/hello-zio-http/tree/collectM

## Output

When running:
```
./sbt run
```

And then making an http request to [localhost:8080](localhost:8080), I get:
```
An unchecked error was produced.
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
	at zhttp.service.HttpRuntime.unsafeRun$$anonfun$4$$anonfun$2$$anonfun$2(HttpRuntime.scala:24)
	at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2868)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:350)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:787)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for instantiated parameter 0: class java.lang.Object is not a subtype of interface io.netty.util.concurrent.Future
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.checkDescriptor(AbstractValidatingLambdaMetafactory.java:308)
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:294)
	at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:503)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:138)
	... 10 more
```

## Expectation

No error.

This might be a regression:
https://github.com/lampepfl/dotty/issues/9769

**Comment by jamesward** [comment]
Note sure why my searches didn't find this, but it looks like this is a bug in zio-http:
https://github.com/dream11/zio-http/issues/655
