### ISSUE TITLE
Crash when expanding value class extension method with annotation referencing `this`

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#14575]
## Compiler version

3.1.3 RC1

## Minimized example

```Scala
class ann(xs: Any*) extends annotation.StaticAnnotation

class C

class D:
  def m: C = ???

trait Ops extends Any {
  def m: C @ann(this)
}

class Ops1(s: String) extends AnyVal with Ops:
  def a = new D
  def m = a.m
```

## Output

Compiling with -Ycheck:all gives
```
exception while typing def m: C @ann(this) = Ops1.m$extension(this) of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @SourceFile("cc-anyval.scala") final class Ops1(s: String) extends AnyVal(), Ops
   {
  override def hashCode(): Int = Ops1.hashCode$extension(this)()
  override def equals(x$0: Any): Boolean = Ops1.equals$extension(this)(x$0)
  private val s: String
  def a: D = Ops1.a$extension(this)
  def m: C @ann(this) = Ops1.m$extension(this)
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package <empty> {
  @SourceFile("cc-anyval.scala") class ann(xs: Any) extends 
    scala.annotation.Annotation
  (), annotation.StaticAnnotation {
    private[this] val xs: Any
  }
  @SourceFile("cc-anyval.scala") class C() extends Object() {}
  @SourceFile("cc-anyval.scala") class D() extends Object() {
    def m: C = ???
  }
  @SourceFile("cc-anyval.scala") trait Ops() extends Any {
    def m: C @ann(this)
  }
  @SourceFile("cc-anyval.scala") final class Ops1(s: String) extends AnyVal(), 
    Ops
   {
    override def hashCode(): Int = Ops1.hashCode$extension(this)()
    override def equals(x$0: Any): Boolean = Ops1.equals$extension(this)(x$0)
    private val s: String
    def a: D = Ops1.a$extension(this)
    def m: C @ann(this) = Ops1.m$extension(this)
  }
  final lazy module val Ops1: Ops1 = new Ops1()
  @SourceFile("cc-anyval.scala") final module class Ops1() extends AnyRef() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[Ops1.type])
    final def hashCode$extension($this: Ops1)(): Int = $this.s.hashCode()
    final def equals$extension($this: Ops1)(x$0: Any): Boolean = 
      matchResult1[Boolean]: 
        {
          case val x1: (x$0 : Any) = x$0
          if x1.$isInstanceOf[Ops1 @unchecked] then 
            {
              case val x$0: Ops1 = x1.$asInstanceOf[Ops1 @unchecked]
              return[matchResult1] $this.s.==(x$0.s)
            }
           else ()
          return[matchResult1] false
        }
    final def a$extension($this: Ops1): D = new D()
    final def m$extension($this: Ops1): C @ann(this) = Ops1.a$extension($this).m
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
*** error while checking cc-anyval.scala after phase patternMatcher ***
exception occurred while compiling cc-anyval.scala
java.lang.AssertionError: assertion failed: orphan param: $this.type, hash of binder = 81269359, tree = <empty>, type = AnnotatedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class C),ConcreteAnnotation(Apply(Select(New(Ident(ann)),<init>),List(This(Ident()))))) while compiling cc-anyval.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: orphan param: $this.type, hash of binder = 81269359, tree = <empty>, type = AnnotatedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class C),ConcreteAnnotation(Apply(Select(New(Ident(ann)),<init>),List(This(Ident())))))
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.TreeChecker$$anon$2.apply(TreeChecker.scala:640)

```
I verified that the tree goes in fact wrong after miniphase `ExtensionMethods`.

## Expectation

Successful compile

**Comment by nicolasstucki** [comment]
Minimized to
```scala
class ann(xs: Any) extends annotation.StaticAnnotation

class Ops1(s: String) extends AnyVal:
  def m: Int @ann(this) = 1
```

**Comment by nicolasstucki** [comment]
```scala
[[syntax trees at end of MegaPhase{crossVersionChecks, protectedAccessors, extmethods, uncacheGivenAliases, elimByName, hoistSuperArgs, forwardDepChecks, specializeApplyMethods, tryCatchPatterns, patternMatcher}]] // Foo.scala
package <empty> {
  @SourceFile("Foo.scala") class ann(xs: Any) extends 
    scala.annotation.Annotation
  (), annotation.StaticAnnotation {
    private[this] val xs: Any
  }
  @SourceFile("Foo.scala") final class Ops1(s: String) extends AnyVal() {
    override def hashCode(): Int = Ops1.hashCode$extension(this)()
    override def equals(x$0: Any): Boolean = Ops1.equals$extension(this)(x$0)
    private val s: String
    def m: Int @ann(this) = Ops1.m$extension(this)
  }
  final lazy module val Ops1: Ops1 = new Ops1()
  @SourceFile("Foo.scala") final module class Ops1() extends AnyRef() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[Ops1.type])
    final def hashCode$extension($this: Ops1)(): Int = $this.s.hashCode()
    final def equals$extension($this: Ops1)(x$0: Any): Boolean = 
      matchResult1[Boolean]: 
        {
          case val x1: (x$0 : Any) = x$0
          if x1.$isInstanceOf[Ops1 @unchecked] then 
            {
              case val x$0: Ops1 = x1.$asInstanceOf[Ops1 @unchecked]
              return[matchResult1] $this.s.==(x$0.s)
            }
           else ()
          return[matchResult1] false
        }
    final def m$extension($this: Ops1): Int @ann(this) = 1 // Reference to those should be transformed to $this
  }
}
```

**Comment by nicolasstucki** [comment]
Similar issue with 
```scala
class ann(xs: Any) extends annotation.StaticAnnotation

class Ops1(val s: String) extends AnyVal:
  def m: Int @ann(s) = 1
```
```scala
Exception in thread "main" scala.MatchError: TermParamRef($this) (of class dotty.tools.dotc.core.Types$TermParamRefImpl) while compiling Foo.scala
scala.MatchError: TermParamRef($this) (of class dotty.tools.dotc.core.Types$TermParamRefImpl)
        at dotty.tools.dotc.ast.tpd$.singleton(tpd.scala:432)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:412)
        at dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:106)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1494)
        at scala.collection.immutable.List.mapConserve(List.scala:472)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1494)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1388)
        at dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:141)
        at dotty.tools.dotc.ast.TreeTypeMap.apply(TreeTypeMap.scala:163)
        at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5654)
        at dotty.tools.dotc.core.Annotations$Annotation.mapWith(Annotations.scala:64)
        at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5580)
        at dotty.tools.dotc.core.Substituters$.substThis(Substituters.scala:117)
        at dotty.tools.dotc.core.Types$Type.substThisUnlessStatic(Types.scala:1772)
        at dotty.tools.dotc.transform.FullParameterization.resultType$1$$anonfun$2(FullParameterization.scala:106)
        at dotty.tools.dotc.core.Types$MethodType.<init>(Types.scala:3701)
        at dotty.tools.dotc.core.Types$CachedMethodType.<init>(Types.scala:3722)
        at dotty.tools.dotc.core.Types$MethodTypeCompanion.apply(Types.scala:3793)
        at dotty.tools.dotc.transform.FullParameterization.resultType$1(FullParameterization.scala:106)
        at dotty.tools.dotc.transform.FullParameterization.fullyParameterizedType(FullParameterization.scala:127)
        at dotty.tools.dotc.transform.FullParameterization.fullyParameterizedType$(FullParameterization.scala:50)
        at dotty.tools.dotc.transform.ExtensionMethods.fullyParameterizedType(ExtensionMethods.scala:39)
        at dotty.tools.dotc.transform.ExtensionMethods.createExtensionMethod(ExtensionMethods.scala:137)
        at dotty.tools.dotc.transform.ExtensionMethods.transform$$anonfun$1(ExtensionMethods.scala:83)
```

**Comment by nicolasstucki** [comment]
It looks like a limitation in `FullParameterization.fullyParameterizedType`.
