### ISSUE TITLE
BoxedUnit cannot be cast to class scala.Function0

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#14700]
## Minimized code

```Scala
Welcome to Scala 3.1.3-RC1-bin-SNAPSHOT-git-d38e10e (17.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> def g(args: Int*)(block: => Unit): Unit = println(s"Well, ${args.sum} and $block")
def g(args: Int*)(block: => Unit): Unit

scala> def f = g()
def f: (=> Unit) => Unit

scala> f(println("x"))
x
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class scala.Function0 (scala.runtime.BoxedUnit and scala.Function0 are in unnamed module of loader java.net.URLClassLoader @535b8c24)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  ... 33 elided
```

## Expectation

```scala
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 17.0.2).
Type in expressions for evaluation. Or try :help.

scala> def g(args: Int*)(block: => Unit): Unit = println(s"Well, ${args.sum} and $block")
def g(args: Int*)(block: => Unit): Unit

scala> def f = g()
                ^
       error: missing argument list for method g
       Unapplied methods are only converted to functions when a function type is expected.
       You can make this conversion explicit by writing `g _` or `g(_)(_)` instead of `g`.

scala> def f = g() _
def f: (=> Unit) => Unit

scala> f(println("x"))
x
Well, 0 and ()
```

**Comment by odersky** [comment]
I can't reproduce this in 3.1.2-RC2.

**Comment by griggt** [comment]
> I can't reproduce this in 3.1.2-RC2.

It only happens on main, seems to be a result of #14295

**Comment by som-snytt** [comment]
Thanks, I was just about to identify a commit.

**Comment by odersky** [comment]
It only happens in the repl of main as far as I can see. The following program works as expected:
```scala
object l1:
  def g(args: Int*)(block: => Unit): Unit = println(s"Well, ${args.sum} and $block")
object l2:
  import l1.*
  def f = g()
@main def Test =
  import l1.*
  import l2.*
  f(println("x"))
```

**Comment by som-snytt** [comment]
I confirmed it also compiles under separate compilation, so I'll try to see what's wrong with REPL.

**Comment by som-snytt** [comment]
I picked this up. I'll try to PR before it catches odersky's attention. It's only the REPL.

Currently, with `g` and `f` precompiled:
```
scala> f(println("x"))
x
x
Well, 0 and (), ()

scala> f(println("x"))
x
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class scala.Function0 (scala.runtime.BoxedUnit and scala.Function0 are in unnamed module of loader java.net.URLClassLoader @4bee18dc)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  ... 34 elided
```
Until now, I compared various permutations, but forgot to ask if it works twice, a classic question for resident compiler.

First time,
```
// elimByName
    val res0: Unit =
      f.apply(
        {
          def $anonfun(): Unit = println("x")
          closure($anonfun:() ?=> Unit)
        }
      )
// erasure
    def res0(): scala.runtime.BoxedUnit =
      f().apply(
        {
          def $anonfun(): Unit = println("x")
          {
            def $anonfun$adapted(): Object =
              {
                $anonfun()
                scala.runtime.BoxedUnit#UNIT
              }
            closure($anonfun$adapted:Function0)
          }
        }
      ).asInstanceOf[scala.runtime.BoxedUnit]
```
where erasure is too boxy. Second time, elimByName sits on the bench.
```
// erasure
    def res0(): scala.runtime.BoxedUnit =
      f().apply(
        {
          println("x")
          scala.runtime.BoxedUnit#UNIT
        }
      ).asInstanceOf[scala.runtime.BoxedUnit]
```
scalac says
```
// erasure
    def main(args: String[]): Unit =
      {
        f().apply(
          {
            def $anonfun(): Unit = println("x")
            {
              def $anonfun$adapted(): Object =
                {
                  $anonfun()
                  scala.runtime.BoxedUnit#UNIT
                }
              closure($anonfun$adapted:Function0)
            }
          }
        )
        ()
      }
```
Also scalac under some regime:
```
@main def test(): Int = f[Unit](println("x"))
```

**Comment by som-snytt** [comment]
Fixed at least since 3.3 LTS.
