### ISSUE TITLE
`recoverWith` does not work correctly when the first future fails

### ISSUE THREAD

**Issue by Confixuan** [lampepfl/dotty#14706]
## Explain
Codes with the same semantics have different results in scala3(3.1.1) and scala2(2.13.8):
- the result of scala3: throw exception
- the result of scala2: return "Nothing" 
(The codes are below)

## Minimized code of scala 3.1.1

```Scala
// scala 3.1.1

// Code:
import java.util.concurrent.TimeUnit
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.DurationInt
import scala.concurrent.{Await, Future}
import scala.util.{Failure, Random, Success}

object Test extends App:
  val future1 = Future {
    TimeUnit.SECONDS.sleep(1)
    throw new Exception
  }

  val future2 = Future {
    TimeUnit.SECONDS.sleep(3)
    "Nothing"
  }

  val future = future1.recoverWith(_ => future2)
  println(Await.result(future, 20.seconds))

// Output:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Test.main(Solution.scala)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [20 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at Test$.<clinit>(Solution.scala:24)
	... 1 more
java.lang.NoClassDefFoundError: Could not initialize class Test$
```

## Minimized code of scala 2.13.8
```scala
// scala 2.13.8

// Code:
import java.util.concurrent.TimeUnit
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.DurationInt
import scala.concurrent.{Await, Future}

object Test extends App {
  val future1 = Future {
    TimeUnit.SECONDS.sleep(1)
    throw new Exception
  }

  val future2 = Future {
    TimeUnit.SECONDS.sleep(3)
    "Nothing"
  }

  val future = future1.recoverWith(_ => future2)
  println(Await.result(future, 20.seconds))
}

// Output:
"Nothing"
```

**Comment by som-snytt** [comment]
What is the actual behavior and what is the expected behavior? What is the working code?
```
import concurrent._, ExecutionContext.Implicits._, duration._
import java.util.concurrent.TimeUnit

object Test extends App {

  val future1 = Future {
    TimeUnit.SECONDS.sleep(1)
    throw new Exception
  }

  val future2 = Future {
    TimeUnit.SECONDS.sleep(3)
    "Nothing"
  }

  val future = future1.recoverWith(_ => future2)
  println(Await.result(future, 20.seconds))
}
```
says for scala 2 vs 3
```
➜  snips scala i14706.scala
Nothing
➜  snips ~/projects/dotty/bin/scala  i14706.scala
java.lang.NoClassDefFoundError: Could not initialize class Test$
        at Test$$anon$1.applyOrElse(i14706.scala:17)
        at Test$$anon$1.applyOrElse(i14706.scala:17)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Test.main(i14706.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:36)
        at dotty.tools.scripting.Main$.main(Main.scala:45)
        at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:248)
        at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:267)
        at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [20 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.Await$.result(package.scala:124)
        at Test$.<clinit>(i14706.scala:18)
        ... 10 more
```
OK, what about idiomatic
```
import concurrent._, ExecutionContext.Implicits._, duration._
import java.util.concurrent.TimeUnit

val future1 = Future {
  TimeUnit.SECONDS.sleep(1)
  throw new Exception
}

val future2 = Future {
  TimeUnit.SECONDS.sleep(3)
  "Nothing"
}

val future = future1.recoverWith(_ => future2)

@main def test() = println(Await.result(future, 20.seconds))
```
that says
```
➜  snips ~/projects/dotty/bin/scala i14706b.scala
Nothing
```

**Comment by odersky** [comment]
If there is a problem (I can't tell) it looks like it's related to the code in Future. Or is the behavior different when run in Scala 2.13?

**Comment by bishabosha** [comment]
@Confixuan would you be able to share how to run the program that causes the behaviour you observe - as the comment from @som-snytt shows, you get different behaviour depending on if you wrap with `scala.App` or not.

**Comment by Confixuan** [comment]
> @Confixuan would you be able to share how to run the program that causes the behaviour you observe? - as the comment from @som-snytt shows, you get different behaviour depending on if you wrap with `scala.App` or not.
> 
> Currently your code is just top level statements that can't be run without either putting them into the repl, or creating a main method

I changed the description and make codes runnable. I got different behavior depending on the version of scala.

**Comment by bishabosha** [comment]
I would say that this is a known feature change - i.e. dropping special handling for `DelayedInit`: https://docs.scala-lang.org/scala3/reference/dropped-features/delayed-init.html
