### ISSUE TITLE
Compiling without stdlib on bootclasspath

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1478]
Running on 5e917498cfae480349ac18b11a680b3e73b14c50

```
dark@tsf-452-wpa-6-123 ~/workspace/dotty/src/dotty/tools (fix-bootstrap-3) $ java -cp .:/Users/dark/workspace/dotty/interfaces/target/dotty-interfaces-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/org.scala-sbt/interface/jars/interface-0.13.9.jar dotty.tools.dotc.Main package.scala
java.lang.Exception
    at dotty.tools.dotc.core.Denotations$MissingRef.<init>(Denotations.scala:952)
    at dotty.tools.dotc.core.Denotations$DenotationsBase$class.recur$1(Denotations.scala:1107)
    at dotty.tools.dotc.core.Denotations$DenotationsBase$class.staticRef(Denotations.scala:1112)
    at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:522)
    at dotty.tools.dotc.core.Symbols$class.requiredPackage(Symbols.scala:341)
    at dotty.tools.dotc.core.Contexts$Context.requiredPackage(Contexts.scala:56)
    at dotty.tools.dotc.core.Definitions.ScalaPackageVal$lzycompute(Definitions.scala:133)
    at dotty.tools.dotc.core.Definitions.ScalaPackageVal(Definitions.scala:133)
    at dotty.tools.dotc.core.Definitions.ScalaPackageClass$lzycompute(Definitions.scala:135)
    at dotty.tools.dotc.core.Definitions.ScalaPackageClass(Definitions.scala:135)
    at dotty.tools.dotc.core.Definitions.AnyClass$lzycompute(Definitions.scala:165)
    at dotty.tools.dotc.core.Definitions.AnyClass(Definitions.scala:165)
    at dotty.tools.dotc.core.Definitions.syntheticCoreClasses$lzycompute(Definitions.scala:757)
    at dotty.tools.dotc.core.Definitions.syntheticCoreClasses(Definitions.scala:756)
    at dotty.tools.dotc.core.Definitions.init(Definitions.scala:779)
    at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:568)
    at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:117)
    at dotty.tools.dotc.Compiler.newRun(Compiler.scala:155)
    at dotty.tools.dotc.Driver.doCompile(Driver.scala:25)
    at dotty.tools.dotc.Driver.process(Driver.scala:124)
    at dotty.tools.dotc.Driver.process(Driver.scala:93)
    at dotty.tools.dotc.Driver.process(Driver.scala:105)
    at dotty.tools.dotc.Driver.main(Driver.scala:132)
    at dotty.tools.dotc.Main.main(Main.scala)
creating stub for scala, owner = module class <root>#2, file = null
decls = module sun#3
  module class sun#4
  module com#5
  module class com#6
  module java#7
  module class java#8
  module javax#9
  module class javax#10
  module org#11
  module class org#12
  module apple#13
  module class apple#14
  module jdk#15
  module class jdk#16
  module oracle#17
  module class oracle#18
  module netscape#19
  module class netscape#20
  module javafx#21
  module class javafx#22
  module analisys#23
  module class analisys#24
  module backend#25
  module class backend#26
  module dotc#27
  module class dotc#28
  module io#29
  module class io#30
error: bad symbolic reference. A signature
refers to scala$ in package <root> which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.
Exception in thread "main" java.lang.UnsupportedOperationException: class dotty.tools.dotc.core.Scopes$EmptyScope$.openForMutations
    at dotty.tools.dotc.util.DotClass.unsupported(DotClass.scala:10)
    at dotty.tools.dotc.core.Scopes$Scope.openForMutations(Scopes.scala:142)
    at dotty.tools.dotc.core.SymDenotations$ClassDenotation.enter(SymDenotations.scala:1505)
    at dotty.tools.dotc.core.Symbols$Symbol.entered(Symbols.scala:430)
    at dotty.tools.dotc.core.Definitions.newCompleteClassSymbol(Definitions.scala:51)
    at dotty.tools.dotc.core.Definitions.AnyClass$lzycompute(Definitions.scala:165)
    at dotty.tools.dotc.core.Definitions.AnyClass(Definitions.scala:165)
    at dotty.tools.dotc.core.Definitions.syntheticCoreClasses$lzycompute(Definitions.scala:757)
    at dotty.tools.dotc.core.Definitions.syntheticCoreClasses(Definitions.scala:756)
    at dotty.tools.dotc.core.Definitions.init(Definitions.scala:779)
    at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:568)
    at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:117)
    at dotty.tools.dotc.Compiler.newRun(Compiler.scala:155)
    at dotty.tools.dotc.Driver.doCompile(Driver.scala:25)
    at dotty.tools.dotc.Driver.process(Driver.scala:124)
    at dotty.tools.dotc.Driver.process(Driver.scala:93)
    at dotty.tools.dotc.Driver.process(Driver.scala:105)
    at dotty.tools.dotc.Driver.main(Driver.scala:132)
    at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by odersky** [comment]
Try with -Ylog-classpath?

**Comment by nicolasstucki** [comment]
Now the compiler stops early if the stdlib is not present and emits an error message indicating that it is missing.
