### ISSUE TITLE
Confusing behavior with usage instructions

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#14793]
## Compiler version

`3.2.0-RC1-bin-20220308-29073f1-NIGHTLY-git-29073f1`

## Minimized code

When you look at the output of `--help` you see the following:

```
Usage: scala <options> <source files>
```
`source files` implies that multiple can be passed in. However, in reality it's super unclear how this works or if it even works. I played around with this today with no success, so I'm either missing something or this is an inaccurate usage message.

```scala
// Test.scala
package example

@main def Test =
  Test2.foo
```

```scala
// Test2.scala
package example

object Test2:
  val foo = "foo"
```
Which leads to

```
❯ scala Test.scala Test2.scala
-- [E006] Not Found Error: /Users/ckipp/Documents/scala-workspace/error-examples/Test.scala:4:2
4 |  Test2.foo
  |  ^^^^^
  |  Not found: Test2

longer explanation available when compiling with `-explain`
1 error found
Error: Errors encountered during compilation
```

Ok, so maybe I'm assuming that it would work so I'll try something more basic and just create two objects and see if they compile
```scala
// Test1.scala
package example

object Test1:
  val test = "test"
```

```scala
// Test2.scala
object Test2:
  blah blah blah
```

This results in
```
❯ scala Test.scala Test2.scala
Error: No main methods detected in script Test.scala
```

No error message from `Test2.scala`.

## Expectation

When I see `source files` I'd expect somewhat obvious behavior about how this is supposed to work. Does this work? If it does but I'm doing it wrong, how can we make it more clear for a newcomer to Scala that I'm assuming would try the above things like I just did and leave confused.

**Comment by som-snytt** [comment]
The Scala 2 instructions on the "package insert" you're supposed to read instead of throwing out with the box are quite labored:

```
Usage: scala <options> [<script|class|object|jar> <arguments>]
   or  scala -help

All options to scalac (see scalac -help) are also allowed.

The first argument to scala after the options designates what to run.

If no argument is given, the Scala REPL, an interactive shell, is started.

Otherwise, the Scala runner will try to run the named target, either as
a compiled class with a main method, a jar file with a Main-Class manifest
header, or as a Scala source file to compile and run.

The REPL accepts expressions to evaluate. Try `:help` to see more commands.

The script runner will invoke the main method of a top-level object if
it finds one; otherwise, the script code is run locally to a synthetic
main method with arguments available in a variable `args`.

Options to scala which reach the Java runtime:

 -Dname=prop  passed directly to Java to set system properties
 -J<arg>      -J is stripped and <arg> passed to Java as-is
 -nobootcp    do not put the Scala jars on the boot classpath (slower)

Other startup options:

 -i <file>    preload <file> before starting the REPL
 -I <file>    preload <file>, enforcing line-by-line interpretation
 -e <string>  execute <string> as if it were in a source file
 -save        save the compiled script in a jar for future use

If the runner does not correctly guess how to run the target:

 -howtorun    what to run <script|object|jar|repl|guess> (default: guess)

```
The use case for scripting is that you get command line args, but that doesn't seem to work yet on Scala 3:
```
➜  snips scala c1.scala world
hello, world
➜  snips cat c1.scala

object Test extends App {
  println(s"hello, ${args.head}")
}
➜  snips sdk use scala 3.1.1

Using scala version 3.1.1 in this shell.
➜  snips scala c1.scala world
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Test.main(c1.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:42)
        at dotty.tools.scripting.Main$.main(Main.scala:43)
        at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:230)
        at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:239)
        at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.NullPointerException
        at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:67)
        at scala.collection.ArrayOps$.head$extension(ArrayOps.scala:222)
        at Test$.<clinit>(c1.scala:3)
        ... 10 more
```
