### ISSUE TITLE
trait AllSyntax has non-class parent: val <none>

### ISSUE THREAD

**Issue by peter-jerry-ye** [lampepfl/dotty#14798]
## Compiler version

Scala code runner version 3.1.1 -- Copyright 2002-2022, LAMP/EPFL

## Minimized code

[repository is here](https://github.com/peter-jerry-ye/dotty-bug-report)

Run `sbt compile`

## Output

```
[info] exception occurred while compiling /home/zihang/Documents/dotty-bug-report/src/main/scala/Main.scala
java.lang.AssertionError: assertion failed: trait AllSyntax has non-class parent: val <none> while compiling /home/zihang/Documents/dotty-bug-report/src/main/scala/Main.scala
```

## Expectation
It compiles

## Additional information

It was originally reported here: https://github.com/typelevel/cats-effect/issues/2923

I've tried with two different platforms and multiple JDKs. (jdk and sbt are all installed with sdkman)

- Ubuntu WSL2 + sbt 1.6.2 (GraalVM Community Java 17.0.1), the problem doesn't exist.
- Ubuntu WSL2 + sbt 1.6.2 (Oracle Corporation Java 18), the problem doesn't exist.
- Manjaro + sbt 1.6.2 (BellSoft Java 18), the problem exist.
- Manjaro + sbt 1.6.2 (Oracle Corporation Java 17.0.2), the problem exist.
- Manjaro + sbt 1.6.2 (Oracle Corporation Java 18), the problem exist.

Complete error trace:
```
[error] ## Exception when compiling 1 sources to /home/zihang/Documents/dotty-bug-report/target/scala-3.1.1/classes
[error] java.lang.AssertionError: assertion failed: trait AllSyntax has non-class parent: val <none>
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.traverse$1(SymDenotations.scala:1907)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1912)
[error] dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2886)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1878)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1885)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.traverse$1(SymDenotations.scala:1906)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1912)
[error] dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2886)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1878)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1885)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.isNoInitsRealClass(SymDenotations.scala:748)
[error] dotty.tools.dotc.ast.TypedTreeInfo.refPurity(TreeInfo.scala:510)
[error] dotty.tools.dotc.ast.TypedTreeInfo.refPurity$(TreeInfo.scala:394)
[error] dotty.tools.dotc.ast.tpd$.refPurity(tpd.scala:22)
[error] dotty.tools.dotc.ast.TypedTreeInfo.exprPurity(TreeInfo.scala:435)
[error] dotty.tools.dotc.ast.TypedTreeInfo.exprPurity$(TreeInfo.scala:394)
[error] dotty.tools.dotc.ast.tpd$.exprPurity(tpd.scala:22)
[error] dotty.tools.dotc.ast.TypedTreeInfo.isIdempotentExpr(TreeInfo.scala:477)
[error] dotty.tools.dotc.ast.TypedTreeInfo.isIdempotentExpr$(TreeInfo.scala:394
[error] dotty.tools.dotc.ast.tpd$.isIdempotentExpr(tpd.scala:22)
[error] dotty.tools.dotc.typer.Checking.checkLegalImportOrExportPath(Checking.scala:844)
[error] dotty.tools.dotc.typer.Checking.checkLegalImportPath(Checking.scala:850
[error] dotty.tools.dotc.typer.Checking.checkLegalImportPath$(Checking.scala:770)
[error] dotty.tools.dotc.typer.Typer.checkLegalImportPath(Typer.scala:107)
[error] dotty.tools.dotc.typer.Typer.typedImport(Typer.scala:2533)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2791)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2842)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2907)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2911)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2923)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2983)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2553)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2812)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2842)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2907)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2911)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3027)
[error] dotty.tools.dotc.typer.TyperPhase.liftedTree1$1(TyperPhase.scala:56)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:62)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:411)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:63)
[error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$1(TyperPhase.scala:106
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:106)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:261)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:272)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] dotty.tools.dotc.Run.compile(Run.scala:206)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]            
[error] java.lang.AssertionError: assertion failed: trait AllSyntax has non-class parent: val <none>
[error] 	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.traverse$1(SymDenotations.scala:1907)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1912)
[error] 	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2886)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1878)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1885)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.traverse$1(SymDenotations.scala:1906)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1912)
[error] 	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2886)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1878)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1885)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isNoInitsRealClass(SymDenotations.scala:748)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.refPurity(TreeInfo.scala:510)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.refPurity$(TreeInfo.scala:394)
[error] 	at dotty.tools.dotc.ast.tpd$.refPurity(tpd.scala:22)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.exprPurity(TreeInfo.scala:435)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.exprPurity$(TreeInfo.scala:394)
[error] 	at dotty.tools.dotc.ast.tpd$.exprPurity(tpd.scala:22)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.isIdempotentExpr(TreeInfo.scala:477)
[error] 	at dotty.tools.dotc.ast.TypedTreeInfo.isIdempotentExpr$(TreeInfo.scala:394)
[error] 	at dotty.tools.dotc.ast.tpd$.isIdempotentExpr(tpd.scala:22)
[error] 	at dotty.tools.dotc.typer.Checking.checkLegalImportOrExportPath(Checking.scala:844)
[error] 	at dotty.tools.dotc.typer.Checking.checkLegalImportPath(Checking.scala:850)
[error] 	at dotty.tools.dotc.typer.Checking.checkLegalImportPath$(Checking.scala:770)
[error] 	at dotty.tools.dotc.typer.Typer.checkLegalImportPath(Typer.scala:107)
[error] 	at dotty.tools.dotc.typer.Typer.typedImport(Typer.scala:2533)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2791
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2842
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2907)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2911)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2923)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2983)
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2553)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2812
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2842
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2907)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2911)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3027)
[error] 	at dotty.tools.dotc.typer.TyperPhase.liftedTree1$1(TyperPhase.scala:56)
[error] 	at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:62)
[error] 	at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:411)
[error] 	at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:63)
[error] 	at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$1(TyperPhase.scala:106)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:106
[error] 	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:261)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$1(Run.scala:272)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:206)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] 	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] 	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] 	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed: trait AllSyntax has non-class parent: val <none>
[error] Total time: 3 s, completed Mar 28, 2022, 6:26:20 PM
```

**Comment by Kordyjan** [comment]
I have tried but I cannot reproduce the issue. The code in your repository just compiles and works for me.

We can reopen the issue if there is some new info.
