### ISSUE TITLE
Scala compile error with JDK 18

### ISSUE THREAD

**Issue by anamak9** [lampepfl/dotty#14814]
## Compiler version
Scala=3.1.1
Java = JDK 18

## Minimized code
Link/setup JDK 18 with any Scala project in Intellij Idea, immediately we get the following error,

## Output

6:22 PM	Scala Compile Server
				Exception in thread "NGServer(localhost/127.0.0.1, 3200,bd7ee4a8-05d5-48ab-9fae-04107a61c3fd)" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
				at java.base/java.lang.System.setSecurityManager(System.java:416)
				at com.martiansoftware.nailgun.NGServer.run(NGServer.java:396)
				at java.base/java.lang.Thread.run(Thread.java:833)

## Expectation
Should not get that error

**Comment by SethTisue** [comment]
looks like https://youtrack.jetbrains.com/issue/SCL-20064, so not a Scala 3 problem per se

**Comment by KacperFKorban** [comment]
I checked just to be sure and `scalac` seems to work correctly with JDK 18.

**Comment by normana400** [comment]
this happens outside Intelij as well (aka calling sbt from terminal)

**Comment by normana400** [comment]
https://stackoverflow.com/questions/57438033/how-can-i-configure-disable-or-override-the-sbt-securitymanager/67940001#67940001

**Comment by nornagon** [comment]
fwiw i'm running sbt 1.6.2 and running into something similar:

```
$ sbt -version
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:416)
	at sbt.TrapExit$.installManager(TrapExit.scala:54)
	at sbt.StandardMain$.runManaged(Main.scala:184)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:540)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:335)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:530)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:530)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:335)
	at sbt.xMain$.run(Main.scala:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
sbt script version: 1.6.2
```

**Comment by normana400** [comment]
i'm on a much earlier sbt, still 0.13 (until I can update all the plugins we use to scala 2.12)
