### ISSUE TITLE
`scala` must not exit with 0 if the program threw an uncaught exception

### ISSUE THREAD

**Issue by sevaseva** [lampepfl/dotty#15022]
## Compiler version

3.1.0, 3.1.1, 3.1.2 as well as the [tip](4e41a4c1bf5502f73798c087032a4a340cd4abb0) of the main branch at the time of writing this.

On the other hand, this isn't affecting scala 2.13.4 (verified) and many/all other 2.x versions.

## Minimized code
```Scala
object Main {
    def main(args: Array[String]) = {
    	throw new RuntimeException()
   }
}
```

More concretely, in bash shell after building scala into `scala3-3.2.0-RC1-bin-SNAPSHOT` (with `bin` and `lib` in there):

```bash
scala3-3.2.0-RC1-bin-SNAPSHOT$ export SCALA_HOME=$(pwd)

scala3-3.2.0-RC1-bin-SNAPSHOT$ cat > a.scala << EOF
object Main {
    def main(args: Array[String]) = {
    	throw new RuntimeException()
   }
}
EOF

scala3-3.2.0-RC1-bin-SNAPSHOT$ cat a.scala
object Main {
    def main(args: Array[String]) = {
    	throw new RuntimeException()
   }
}

scala3-3.2.0-RC1-bin-SNAPSHOT$ bin/scalac a.scala

scala3-3.2.0-RC1-bin-SNAPSHOT$ bin/scala Main
java.lang.RuntimeException
	at Main$.main(a.scala:3)
	at Main.main(a.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at dotty.tools.runner.RichClassLoader$.run$extension$$anonfun$1(ScalaClassLoader.scala:36)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.runner.RichClassLoader$.dotty$tools$runner$RichClassLoader$$$asContext$extension(ScalaClassLoader.scala:18)
	at dotty.tools.runner.RichClassLoader$.run$extension(ScalaClassLoader.scala:36)
	at dotty.tools.runner.CommonRunner.run(ObjectRunner.scala:23)
	at dotty.tools.runner.CommonRunner.run$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.run(ObjectRunner.scala:48)
	at dotty.tools.runner.CommonRunner.runAndCatch(ObjectRunner.scala:30)
	at dotty.tools.runner.CommonRunner.runAndCatch$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.runAndCatch(ObjectRunner.scala:48)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:212)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:267)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)

scala3-3.2.0-RC1-bin-SNAPSHOT$ echo $?
0
```

## Output
That last output of `0` is the issue.

## Expectation
The last command `echo $?` must print `1` or some other non-zero.
scala 2.13.4 does that.

**Comment by sevaseva** [comment]
After applying the one-line change https://github.com/sevaseva/dotty/commit/6493ba86dc3ed3e729fd132d79682a88c0f9a298 , `scala` does exit with `1` (and `echo $?` prints `1`) as expected for the particular program mentioned in the issue. That's just a demo to help demonstrate the issue.

**Comment by som-snytt** [comment]
It would be a small nice thing to have a [dedicated exception](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/util/SystemExit.scala) maybe in `scala.runtime` for now.
