### ISSUE TITLE
Assertions in Quotes Api

### ISSUE THREAD

**Issue by cornerman** [lampepfl/dotty#15051]
## Compiler version

3.1.2

## Minimized code

```Scala
import quotes.reflect.*

val classSymbol = Symbol.newClass(Symbol.spliceOwner, "Something", parents = List(TypeTree.of[AnyRef].tpe), _ => Nil, selfType = None)
val method = DefDef(classSymbol, argss => Some('{${r}()}.asTerm))
```

## Output

```
[error]      Exception occurred while executing macro expansion.
[error]      java.lang.AssertionError: assertion failed: expected a term symbol but received class Something
[error]      	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]      	at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:270)
[error]      	at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:269)
[error]      	at test.MyMacro$.clientImpl(Test.scala:86)
```

## Expectation

I would expect to get a type error that a `ClassSymbol` is not a `MethodSymbol`. This just one example, but there are many such assertions inside the Quotes Api. And I find it hard to debug these errors. In the end, I often have to look into the source code of the compiler to find out what the assertion is actually checking. Code-completion and api-docs cannot help here.

The reason seems to be that we only expose `Symbol` as a type in the public API and do not expose the possible sub-classes for public usage.

Is there anything we can do to improve the error messages? Or is there a plan on exposing the types, so we can write correct signatures for the public functions?

**Comment by nicolasstucki** [comment]
The error message must be improved. Also the documentation.

There are no plans to expose subclasses for different kinds of symbols. This would not help as we cannot change the API of methods such as DefDef.apply.

**Comment by cornerman** [comment]
We cannot change the method signature because of compatibility right? But we maybe could add new methods that are more type-safe and offer them as alternatives, maybe later deprecate the old ones.

I am just wondering, because proper type signature would give much better feedback when compiling and editing code. What is the motivation for having asserts instead?
