### ISSUE TITLE
Unable to create a system terminal with Scala on Windows on ARM64

### ISSUE THREAD

**Issue by rubin55** [lampepfl/dotty#15150]
## Compiler version
Scala compiler version 3.1.2 -- Copyright 2002-2022, LAMP/EPFL

## Issue
Simply running `scala` command to get to REPL fails with an exception on Windows on ARM64:
```
~\> scala
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:323)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:265)
        at dotty.tools.repl.JLineTerminal.<init>(JLineTerminal.scala:23)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:136)
        at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:127)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)
```
## Expectation
I expect scala to work as any Java application on Windows on ARM64. The issue might be related to Jansi support (or lack thereof) for this specific os.name/os.arch combination, or it may be an initialization issue in `scala` itself.

**Comment by griggt** [comment]
Somewhat related to #11978. I don't know if the `TERM=dumb` workaround is applicable on Windows.
