### ISSUE TITLE
Possible regression for infering types when using macros

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#15215]
## Compiler version
3.1.2
Present in 3.1.3-RC3
Present in 3.2.0-RC1-bin-20220517-e5abec0-NIGHTLY

## Minimized code
Failure found in the community build, needs minimization: 
Macros generating errors:
https://github.com/kory33/s2mc-test/blob/3962ff70f81d5cbdd8938b551794c652b45d6072/protocol-impl/src/main/scala/io/github/kory33/s2mctest/impl/connection/codec/decode/macros/GenByteDecode.scala#L196-L243

Project repo: https://github.com/kory33/s2mc-test/tree/v0.2.3
Compilation logs: https://scala3.westeurope.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/buildCommunityProject/runs/4394/nodes/16/steps/81/log/?start=0
## Output

```scala
[error] -- Error: /home/wmazur/projects/virtuslab/community-build3/repo/protocol-impl/src/main/scala/io/github/kory33/s2mctest/impl/connection/codec/ByteCodecs.scala:174:31 
[error] 174 |    given ByteCodec[MapIcon] = autogenerateFor[MapIcon]
[error]     |                               ^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |java.lang.Exception: Expr cast exception: cats.free.Free.catsFreeMonadForFree[[A >: scala.Nothing <: scala.Any] => cats.data.EitherK[[R >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadBytesInstruction[R], [T >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadFiniteBytesInstruction[T], A]].pure[scala.None.type](scala.None)
[error]     |of type: cats.free.Free[[A >: scala.Nothing <: scala.Any] => cats.data.EitherK[[R >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadBytesInstruction[R], [T >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadFiniteBytesInstruction[T], A], scala.None]
[error]     |did not conform to type: cats.free.Free[io.github.kory33.s2mctest.core.connection.codec.dsl.DecodeFiniteBytes$package.DecodeFiniteBytesInstructions, scala.Option[java.lang.String]]
[error]     |
[error]     |   at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:73)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:220)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.$anonfun$8(GenByteDecode.scala:232)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:806)
[error]     |   at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:289)
[error]     |   at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:2906)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:804)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:239)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.$anonfun$8(GenByteDecode.scala:232)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:806)
[error]     |   at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:289)
[error]     |   at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:2906)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:804)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:239)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.$anonfun$8(GenByteDecode.scala:232)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:806)
[error]     |   at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:289)
[error]     |   at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:2906)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:804)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:239)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.$anonfun$8(GenByteDecode.scala:232)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:806)
[error]     |   at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:289)
[error]     |   at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:2906)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:804)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:239)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.$anonfun$8(GenByteDecode.scala:232)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:806)
[error]     |   at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:289)
[error]     |   at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:2906)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:806)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:804)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.recurse$1(GenByteDecode.scala:239)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.genImpl(GenByteDecode.scala:246)
[error]     |   at io.github.kory33.s2mctest.impl.connection.codec.decode.macros.GenByteDecode$.inline$genImpl(GenByteDecode.scala:32)
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from GenByteDecode.scala:16
[error]  16 |    ${ genImpl[A] }
[error]     |    ^^^^^^^^^^^^^^^
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from GenByteDecode.scala:16
[error]  60 |    ByteCodec(GenByteDecode.gen[T], ByteEncode.forADT[T])
[error]     |              ^^^^^^^^^^^^^^^^^^^^
```

**Comment by nicolasstucki** [comment]
Is 
```scala
cats.free.Free[[A >: scala.Nothing <: scala.Any] => cats.data.EitherK[[R >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadBytesInstruction[R], [T >: scala.Nothing <: scala.Any] => io.github.kory33.s2mctest.core.connection.codec.dsl.ReadFiniteBytesInstruction[T], A], scala.None]
``` 
supposed to be a subtype of 
```scala
cats.free.Free[io.github.kory33.s2mctest.core.connection.codec.dsl.DecodeFiniteBytes$package.DecodeFiniteBytesInstructions, scala.Option[java.lang.String]]
```

If not, there is a bug in the implementation of that macro.

**Comment by joroKr21** [comment]
Disregarding the big type I already see an issue with `Option[String]` and `None` - because `Free[S[_], A]` is invariant. Although `scala.None` is not a type 🤔
