### ISSUE TITLE
Abstract members wrongly implemented by class arguments

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1531]
The following code compiles:

```scala
trait T {
  def f: Int
}

class A(f: Int) extends T
```

I would expect to fail with following error like it does in scalac:

`error: class A needs to be abstract, since def f: => Int is not defined`

**Comment by OlivierBlanvillain** [comment]
Example of it failing at runtime:

```scala
scala> trait T {
         def f: Int
       } 
defined trait T
scala>  
scala> class A(f: Int) extends T 
defined class A
scala> new A(1) 
res0: A = A@ca263c2
scala> res0.f 
java.lang.AbstractMethodError: Method A.f()I is abstract
        at A.f(<console>)
        at .<init>(<console>:8)
        at .<clinit>(<console>)
        at RequestResult$.<init>(<console>:3)
        at RequestResult$.<clinit>(<console>)
        at RequestResult$result(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
