### ISSUE TITLE
Overloaded `isDefined` or `get` breaks option-less pattern matching

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1540]
Overloading `isDefined` or `get` as in the following example crashes dotc on this [assertion](https://github.com/lampepfl/dotty/blob/80cbe114cc5d641d66512c58402eca4ae69f9f2a/src/dotty/tools/dotc/transform/Erasure.scala#L335):

```scala
class Casey1(val a: Int) {
  def isDefined: Boolean = true
  def isDefined(x: Int): Boolean = ???
  def get: Int = a
  def get(x: Int): String = ???
}
object Casey1 { def unapply(a: Casey1) = a }

object Test {
  def main(args: Array[String]): Unit = {
    val c @ Casey1(x) = new Casey1(0)
    assert(x == c.get)
  }
}
```

**Comment by odersky** [comment]
It actually fails before, if one does a -Ycheck:pat. @liufengyun or @DarkDimius can one of you have a look?

    *** error while checking i1540.scala after phase patternMatcher ***

    exception occurred while compiling i1540.scala
    Exception in thread "main" java.lang.UnsupportedOperationException: multi-denotation with alternatives List(method isDefined, method isDefined) does not implement operation info
	at dotty.tools.dotc.core.Denotations$MultiDenotation.multiHasNot(Denotations.scala:604)
	at dotty.tools.dotc.core.Denotations$MultiDenotation.infoOrCompleter(Denotations.scala:565)
	at dotty.tools.dotc.core.Denotations$MultiDenotation.info(Denotations.scala:566)
	at dotty.tools.dotc.core.Denotations$MultiDenotation.info(Denotations.scala:564)

**Comment by liufengyun** [comment]
OK, I'll have look at it.
