### ISSUE TITLE
AbstractMethodError in SAM lambdas when SAM contains method overrided with narrowed type

### ISSUE THREAD

**Issue by Odomontois** [lampepfl/dotty#15402]
## Compiler version
3.1.2
and 
3.2.0-RC1-bin-20220607-76a0b29-NIGHTLY
If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
trait Named:
  def name: String

  def me: Named
end Named

trait Foo extends Named:
  def name = "foo"

  def me: Foo = this

  def foo(x: String): String
end Foo

class Names(xs: List[Named]):
  def mkString = xs.iterator.map(_.me.name).mkString(",")

object Names:
  def single[T <: Named](t: T): Names = Names(List(t))

@main def Repro() =
  val names = Names.single[Foo](x => x)
  println(names.mkString)
```

## Output

```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class Moons$package$$$Lambda$15/0x0000000800c074f8 does not define or inherit an implementation of the resolved method 'abstract .Named me()' of interface Named.
	at Names.mkString$$anonfun$1(Moons.scala:18)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1293)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1293)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1142)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1142)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1293)
	at Names.mkString(Moons.scala:18)
	at $package$.Repro(Moons.scala:25)
	at Repro.main(Moons.scala:23)

```

##Scastie link
https://scastie.scala-lang.org/Odomontois/kzIirdZ1RRaDr1Wm8QN9TA/1

**Comment by odersky** [comment]
@WojciechMazur Do you think you could take this on?

**Comment by tpunder** [comment]
I just ran into this issue.

Here is another minimized example:

```scala
trait Adapter[T] extends Function1[T, Unit]

object Example {
  def main(args: Array[String]): Unit = {
    // In Scala 3 this causes a java.lang.AbstractMethodError
    makeAdapter[Integer](123)
  }

  // Works in Scala 2.12 and 2.13 but generates wrong bytecode for Scala 3
  // due to using `(arg: Number) => ()` instead of `(arg: T) => ()`
  def makeAdapter[T <: Number]: Adapter[T] = (arg: Number) => ()
```

https://scastie.scala-lang.org/cRqYj3CiSpWxGrGJNeV2Ww

**Comment by irfanstract** [comment]
@tpunder's example failed on `3.3.8` with:

```scala
object creation impossible, since def apply(v1: T1): R in trait Function1 in package scala is not defined 
(Note that
 parameter T1 in def apply(v1: T1): R in trait Function1 in package scala does not match
 parameter Number in final def apply(arg: Number): Unit in anonymous class Object with Playground.Adapter[T] {...}
 )
```
