### ISSUE TITLE
NPE when running command line args with `extends App`

### ISSUE THREAD

**Issue by spamegg1** [lampepfl/dotty#15469]
## Compiler version
3.1.2

## Minimized code
Taken from [the docs](https://docs.scala-lang.org/overviews/scala-book/hello-world-2.html#extra-credit)

```Scala
// in file HelloYou.scala
object HelloYou extends App {
    if (args.size == 0)
        println("Hello, you")
    else
        println("Hello, " + args(0))
}
```
Compile with `scalac HelloYou.scala` then run with `scala HelloYou Spam`

## Output
Compilation succeeds, but running `scala HelloYou Spam` crashes:

<details>
<summary>CLICK TO EXPAND</summary>

```
 ➜ scala HelloYou Spam
java.lang.NullPointerException
	at java.base/java.lang.reflect.Array.getLength(Native Method)
	at scala.collection.ArrayOps$.size$extension(ArrayOps.scala:202)
	at Hello$.<clinit>(Hello.scala:2)
	at Hello.main(Hello.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dotty.tools.runner.RichClassLoader$.run$extension$$anonfun$1(ScalaClassLoader.scala:36)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.runner.RichClassLoader$.dotty$tools$runner$RichClassLoader$$$asContext$extension(ScalaClassLoader.scala:18)
	at dotty.tools.runner.RichClassLoader$.run$extension(ScalaClassLoader.scala:36)
	at dotty.tools.runner.CommonRunner.run(ObjectRunner.scala:23)
	at dotty.tools.runner.CommonRunner.run$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.run(ObjectRunner.scala:48)
	at dotty.tools.runner.CommonRunner.runAndCatch(ObjectRunner.scala:30)
	at dotty.tools.runner.CommonRunner.runAndCatch$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.runAndCatch(ObjectRunner.scala:48)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:212)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:267)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```

</details>

## Expectation
`scala HelloYou Spam` should work correctly and print `Hello, Spam`.

Works as expected when compiled and run with Scala 2.

**Comment by bishabosha** [comment]
Thank you for reporting, however this is known to fail: https://docs.scala-lang.org/scala3/reference/dropped-features/delayed-init.html

**Comment by bishabosha** [comment]
Also, I noticed that the example you used is from the scala 2 book, the equivalent is here: https://docs.scala-lang.org/scala3/book/taste-hello-world.html

**Comment by spamegg1** [comment]
OK, I also thought that it's probably not a bug, but changed in Scala 3. Weird, it still does compile though! So it's natural to expect it to work.

Just to mention: some newcomers [come across these examples](https://users.scala-lang.org/t/args-is-null-while-extending-app-even-when-runtime-args-are-provided) in the docs, and they don't know the difference between Scala 2 and 3, or why a piece of code (a Hello world example at that!) straight from the official docs fails. It's not a good look for the language! The [docs page](https://docs.scala-lang.org/) starts with Scala 2, and you have to scroll all the way down to see Scala 3.

**Comment by bishabosha** [comment]
> Just to mention: some newcomers [come across these examples](https://users.scala-lang.org/t/args-is-null-while-extending-app-even-when-runtime-args-are-provided) in the docs, and they don't know the difference between Scala 2 and 3, or why a piece of code (a Hello world example at that!) straight from the official docs fails. It's not a good look for the language! The [docs page](https://docs.scala-lang.org/) starts with Scala 2, and you have to scroll all the way down to see Scala 3.

We definitely have heard your concerns so hopefully the situation will begin to improve soon with https://github.com/scala/docs.scala-lang/pull/2430
