### ISSUE TITLE
`i14623.scala` fails on Scala.js as of 3.1.3

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#15494]
## Compiler version

`3.1.3`

## Minimized code

https://github.com/lampepfl/dotty/blob/75d8eea1e943bbd2c605d8411c2d52d69974d6f3/tests/run/i14623.scala#L1-L15

## Output

```
$ scala-cli -S 3.1.3 --js i14623.scala 
/tmp/main6684577165524698363.js:838
      throw e
      ^

<ref *1> $c_jl_AssertionError [java.lang.AssertionError]: assertion failed
    at $c_sr_Scala3RunTime$.assertFailed__E (/tmp/main6684577165524698363.js:1539:9)
    at $c_Li14623$package$.Test__V (/tmp/main6684577165524698363.js:899:28)
    at $s_LTest__main__AT__V (/tmp/main6684577165524698363.js:832:27)
    at Object.<anonymous> (/tmp/main6684577165524698363.js:2283:1)
    at Object.<anonymous> (/tmp/main6684577165524698363.js:2284:4)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  jl_Throwable__f_s: 'assertion failed',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}
```

## Expectation

It works in 3.1.2:
```
$ scala-cli -S 3.1.2 --js i14623.scala
# (no output)
```

And in JVM for 3.1.3:
```
$ scala-cli -S 3.1.3 i14623.scala
# (no output)
```

**Comment by griggt** [comment]
First bad commit is 81cbe32f2ad478bfd8b1223fe1c1e38daffdf3a4 from #14295

**Comment by armanbilge** [comment]
Thanks for tracking that down!

**Comment by sjrd** [comment]
I started digging into this. It happens because `EtaReduce` does not work for non-specialized functions. And Scala.js disables function specialization altogether.

I can reproduce the issue on Scala/JVM if I disable the `SpecializeFunctions` phase. I also suspect that `EtaReduce` would fail even in regular Scala/JVM for `Function3`+ as well as for `Function2` with non-specializable param types. But the test here is about by-names, so they are `Function0`s by construction.
