### ISSUE TITLE
Incorrect type for match tree when it contains constant and null cases

### ISSUE THREAD

**Issue by noti0na1** [lampepfl/dotty#15516]
## Compiler version

3.2.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-5a8a61d

## Minimized code

https://scastie.scala-lang.org/cqajj5mmQS21xMpDZ63n3Q

```Scala
def f(i: Int) = i match
  case 0 => 0
  case 1 => true
  case 2 => "2"
  case _ => null
```

```
scalac -Ycheck:all Stest.scala
```

## Output

```scala
*** error while checking Stest.scala after phase typer ***
exception occurred while compiling Stest.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Types differ
Original type : (0 : Int) | (true : Boolean) | ("2" : String)
After checking: (0 : Int) | (true : Boolean) | (("2" : String) | Null)
Original tree : i match 
  {
    case 0 => 
      0
    case 1 => 
      true
    case 2 => 
      "2"
    case _ => 
      null
  }
After checking: i match 
  {
    case 0 => 
      0
    case 1 => 
      true
    case 2 => 
      "2"
    case _ => 
      null
  }
Why different :
             Subtype trace:
  ==> (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  (0 : Int) | (true : Boolean) | ("2" : String)
    ==> (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  Nothing
      ==> Int | Boolean | String  <:  Nothing in frozen constraint
        ==> Int | Boolean  <:  Nothing in frozen constraint
          ==> Int  <:  Nothing in frozen constraint
          <== Int  <:  Nothing in frozen constraint = false
        <== Int | Boolean  <:  Nothing in frozen constraint = false
      <== Int | Boolean | String  <:  Nothing in frozen constraint = false
      ==> (0 : Int) | (true : Boolean)  <:  Nothing
        ==> Int | Boolean  <:  Nothing in frozen constraint
          ==> Int  <:  Nothing in frozen constraint
          <== Int  <:  Nothing in frozen constraint = false
        <== Int | Boolean  <:  Nothing in frozen constraint = false
        ==> (0 : Int)  <:  Nothing
          ==> Int  <:  Nothing (left is approximated)
          <== Int  <:  Nothing (left is approximated) = false
        <== (0 : Int)  <:  Nothing = false
      <== (0 : Int) | (true : Boolean)  <:  Nothing = false
    <== (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  Nothing = false
  <== (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  (0 : Int) | (true : Boolean) | ("2" : String) = false
java.lang.AssertionError: assertion failed: Types differ
Original type : (0 : Int) | (true : Boolean) | ("2" : String)
After checking: (0 : Int) | (true : Boolean) | (("2" : String) | Null)
Original tree : i match 
  {
    case 0 => 
      0
    case 1 => 
      true
    case 2 => 
      "2"
    case _ => 
      null
  }
After checking: i match 
  {
    case 0 => 
      0
    case 1 => 
      true
    case 2 => 
      "2"
    case _ => 
      null
  }
Why different :
             Subtype trace:
  ==> (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  (0 : Int) | (true : Boolean) | ("2" : String)
    ==> (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  Nothing
      ==> Int | Boolean | String  <:  Nothing in frozen constraint
        ==> Int | Boolean  <:  Nothing in frozen constraint
          ==> Int  <:  Nothing in frozen constraint
          <== Int  <:  Nothing in frozen constraint = false
        <== Int | Boolean  <:  Nothing in frozen constraint = false
      <== Int | Boolean | String  <:  Nothing in frozen constraint = false
      ==> (0 : Int) | (true : Boolean)  <:  Nothing
        ==> Int | Boolean  <:  Nothing in frozen constraint
          ==> Int  <:  Nothing in frozen constraint
          <== Int  <:  Nothing in frozen constraint = false
        <== Int | Boolean  <:  Nothing in frozen constraint = false
        ==> (0 : Int)  <:  Nothing
          ==> Int  <:  Nothing (left is approximated)
          <== Int  <:  Nothing (left is approximated) = false
        <== (0 : Int)  <:  Nothing = false
      <== (0 : Int) | (true : Boolean)  <:  Nothing = false
    <== (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  Nothing = false
  <== (0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  (0 : Int) | (true : Boolean) | ("2" : String) = false while compiling Stest.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:338)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3007)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3011)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:309)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3127)
        at dotty.tools.dotc.typer.Typer.$anonfun$48(Typer.scala:2313)
        at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2313)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef$$anonfun$1(TreeChecker.scala:512)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:191)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:515)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2855)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2941)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:325)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3007)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3011)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:309)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3033)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3083)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:555)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2518)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:490)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2867)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2871)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2941)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:325)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3007)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3011)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:309)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3033)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3083)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:555)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2649)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedPackageDef(TreeChecker.scala:581)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2912)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2942)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:325)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3007)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3011)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:309)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3127)
        at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:143)
        at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:110)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:311)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:312)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:234)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:245)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:253)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:262)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:262)
        at dotty.tools.dotc.Run.compileSources(Run.scala:186)
        at dotty.tools.dotc.Run.compile(Run.scala:170)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
        at dotty.tools.dotc.Driver.process(Driver.scala:195)
        at dotty.tools.dotc.Driver.process(Driver.scala:163)
        at dotty.tools.dotc.Driver.process(Driver.scala:175)
        at dotty.tools.dotc.Driver.main(Driver.scala:205)
        at dotty.tools.dotc.Main.main(Main.scala)
```

The error also happens with explicit nulls.

## Expectation

The correct type for the `Match` tree should be `(0 : Int) | (true : Boolean) | ("2" : String) | Null`

**Comment by noti0na1** [comment]
Related discussion in #3958 and #15069

Although the type of the Match tree is incorrect, the actual bug causes this error is at subtying.

If we look at the subtype trace, we can see the issue:
`(0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  (0 : Int) | (true : Boolean) | ("2" : String)` 
becomes 
`(0 : Int) | (true : Boolean) | (("2" : String) | Null)  <:  Nothing`, 
which is wrong.

A simpler example is:

```scala
val a: "s" | Null = "s"
// given Null is subtype of String literal types currently,
// we expect no error below
val b: "s" = a2 
```

The compiling fails. If we trun on `Config.checkAtomsComparisons`:

```
assertion failure for ("s" : String) | Null <:< ("s" : String), frozen = false
assertion failure for (a : ("s" : String) | Null) <:< ("s" : String), frozen = false
exception occurred while typechecking Stest.scala
exception occurred while compiling Stest.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Atoms inconsistency for ("s" : String) | Null <:< ("s" : String)
atoms predicted false
atoms1 = Unknown
atoms2 = Range(Set(ConstantType(Constant(s))),Set(ConstantType(Constant(s)))) while compiling Stest.scala
java.lang.AssertionError: assertion failed: Atoms inconsistency for ("s" : String) | Null <:< ("s" : String)
atoms predicted false
atoms1 = Unknown
atoms2 = Range(Set(ConstantType(Constant(s))),Set(ConstantType(Constant(s))))
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.TypeComparer.verified$1(TypeComparer.scala:1449)
```

This is due to we know the atoms of `"s"`, but don't know the atoms for `"s" | Null`, so the `compareAtoms` assumes the subtyping is true if only if the left type is a subtype of `Nothing` .

To fix all the messy issues, I think the correct solution should be:
* Make Null no longer a subtype of literal types (this is already true in explicit nulls)
* Treat Null as a SingletonType, so `NullType.atoms == Range(Set(ConstantType(Constant(null))), Set(ConstantType(Constant(null))))`, because `null` is the only value of `Null` type.

**Comment by noti0na1** [comment]
Another related bug:

```scala
val a: "s" = null
val a2: "s" | Nothing = null // similar error
```

**Comment by noti0na1** [comment]
Closing this issue since the error is no longer reproducible.
