### ISSUE TITLE
Failure to collect coverage in the presence of the `derives` keyword

### ISSUE THREAD

**Issue by nikololiahim** [lampepfl/dotty#15580]
## Compiler version
3.2.0-RC1

## Minimized code
I encountered this issue when using `sbt-scoverage`. 
The full reproduction is available [here](https://gist.github.com/nikololiahim/50ed09c1c501dcad72e6c255b9394a29), however the main file is `User.scala`:
```scala
import io.circe._

case class User(name: String, address: Address) derives Codec.AsObject
case class Address(country: String, city: String) derives Codec.AsObject

object User {
  def fromString(s: String): Option[User] = {
    s.split(",[ ]?") match {
      case Array(name, country, city) =>
        Some(User(name, Address(country, city)))
      case _ => None
    }
  }
}

```

## Output
Running `sbt clean coverage test coverageReport` fails with an error:

```scala
[error] java.lang.RuntimeException: No source root found for '/home/nikololiahim/scala/scoverage-bug/modules/core/shared/src/main/scala-3/io/circe/Derivation.scala' (source roots: '/home/nikololiahim/scala/scoverage-bug/src/main/scala/')
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:35)
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:23)
[error]         at scoverage.reporter.ScoverageHtmlWriter.classRow(ScoverageHtmlWriter.scala:249)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$classesTable$2(ScoverageHtmlWriter.scala:239)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at scoverage.reporter.ScoverageHtmlWriter.classesTable(ScoverageHtmlWriter.scala:239)
[error]         at scoverage.reporter.ScoverageHtmlWriter.overview(ScoverageHtmlWriter.scala:460)
[error]         at scoverage.reporter.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:65)
[error]         at scoverage.ScoverageSbtPlugin$.writeReports(ScoverageSbtPlugin.scala:324)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1(ScoverageSbtPlugin.scala:220)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1$adapted(ScoverageSbtPlugin.scala:195)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (coverageReport) No source root found for '/home/nikololiahim/scala/scoverage-bug/modules/core/shared/src/main/scala-3/io/circe/Derivation.scala' (source roots: '/home/nikololiahim/scala/scoverage-bug/src/main/scala/')
```
## Expectation
The report should be generated. 

## Notes
The error goes away when I remove the `derives Codec.AsObject` parts:
```scala
case class User(name: String, address: Address)
case class Address(country: String, city: String)
```
and the coverage is collected:
![image](https://user-images.githubusercontent.com/45356788/177172816-8bf82ffb-3c46-4d08-a947-9ce68526b325.png)

**Comment by nikololiahim** [comment]
https://github.com/lampepfl/dotty/issues/15490 seems related, can close if it is indeed so.

**Comment by rochala** [comment]
The following issue that you submitted is not exactly the problem here as `derives` keyword is working as intended.

I minimized it to 
```scala
import scala.deriving.*

case class Foo(x: Int) derives Show

trait Show[A]:
  def show(a: A): String

object Show:
  inline given derived[T](using m: Mirror.Of[T]): Show[T] = ???

```

Compilation also passes "-coverage-out:." flag on project you created by running `sbt test compile`. This issue is thou on scoverage side and you should create issue there as coverage generation on dotty part seems to be working correctly.
