### ISSUE TITLE
Scala.JS sandbox is broken

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1574]
On master doing: `sbt sjsSandbox/compile` results in:

```
[info] Loading project definition from /home/fixel/Projects/dotty-master/project
[info] Set current project to dotty (in build file:/home/fixel/Projects/dotty-master/)
> sjsSandbox/compile
[info] Resolving org.scala-js#scalajs-ir_2.11;0.6.8 ...
[info] Compiling 1 Scala sources to /home/fixel/Projects/dotty-master/sandbox/scalajs/target/scala-2.11/classes...
[error] exception occurred while compiling /home/fixel/Projects/dotty-master/sandbox/scalajs/hello.scala
[error] Exception in thread "main" java.lang.AssertionError: assertion failed: phase getClass has unmet requirement: class dotty.tools.dotc.transform.FunctionalInterfaces should precede this phase
[error]     at scala.Predef$.assert(Predef.scala:165)
[error]     at dotty.tools.dotc.core.Phases$PhasesBase$class.checkRequirements$1(Phases.scala:164)
[error]     at dotty.tools.dotc.core.Phases$PhasesBase$$anonfun$usePhases$2.apply(Phases.scala:177)
[error]     at dotty.tools.dotc.core.Phases$PhasesBase$$anonfun$usePhases$2.apply(Phases.scala:176)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error]     at dotty.tools.dotc.core.Phases$PhasesBase$class.usePhases(Phases.scala:176)
[error]     at dotty.tools.dotc.core.Contexts$ContextBase.usePhases(Contexts.scala:527)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:66)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:62)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:62)
[error]     at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
[error]     at dotty.tools.dotc.Run.compileUnits(Run.scala:62)
[error]     at dotty.tools.dotc.Run.compileSources(Run.scala:59)
[error]     at dotty.tools.dotc.Run.compile(Run.scala:43)
[error]     at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:124)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:93)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:105)
[error]     at dotty.tools.dotc.Driver.main(Driver.scala:132)
[error]     at dotty.tools.dotc.Main.main(Main.scala)
[trace] Stack trace suppressed: run last sjsSandbox/compile:compile for the full output.
[error] (sjsSandbox/compile:compile) Nonzero exit code returned from runner: 1
[error] Total time: 4 s, completed Oct 10, 2016 9:53:55 AM
```

ping: @sjrd

**Comment by nicolasstucki** [comment]
Currently it results in
```
[error] 
[error] bad option '-scalajs' was ignored
[error] 
[error] result of /Users/nicolasstucki/GitHub/dotty/sandbox/scalajs/src/hello.scala after TreeTransform:{moveStatic, expandPrivate, selectStatic, collectEntryPoints, collectSuperCalls, dropInlined, labelDef}:
[error] 
[error] package hello {
[error]   @scala.annotation.internal.SourceFile(
[error]     "/Users/nicolasstucki/GitHub/dotty/sandbox/scalajs/src/hello.scala"
[error]   ) <trait> trait MyTrait extends Object { 
[error]     def $init$(): Unit = ()
[error]     <accessor> def x(): Int
[error]     protected def initial$x(): Int = 5
[error]     def foo(y: Int): Int = this.x()
[error]   }
[error]   @scala.annotation.internal.SourceFile(
[error]     "/Users/nicolasstucki/GitHub/dotty/sandbox/scalajs/src/hello.scala"
[error]   ) final module class world$ extends Object with scala.scalajs.js.JSApp with 
[error]     hello
[error]   .MyTrait { 
[error]     def <init>(): Unit = 
[error]       {
[error]         super()
[error]         scala.scalajs.js.JSApp$class#$init$(this)
[error]         hello.world.x = super[MyTrait].initial$x()
[error]         ()
[error]       }
[error]     private val x: Int
[error]     <accessor> def x(): Int = hello.world.x
[error]     def $js$exported$meth$main(): Object = 
[error]       scala.scalajs.js.JSApp$class#$js$exported$meth$main(this)
[error]     def main(): Unit = 
[error]       {
[error]         println("hello dotty.js!")
[error]         println(scala.Int.box(hello.world.foo(4)))
[error]       }
[error]   }
[error]   final lazy module val world: hello.world$ = new hello.world$()
[error] }
[error] 
[error] one warning found
```

**Comment by felixmulder** [comment]
It has been taken out of the main sources. It currently sits in `./compiler/scalaJS` (not indexed by sbt) waiting for @sjrd's return.
