### ISSUE TITLE
Initialisation Exception

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#15832]
## Compiler version
3.1.3 and 3.2.0-RC1 on Scastie

## Minimized code

```Scala
object A {
  class Builder[K, V](creator: K => V) {
    def build(k: K): V = creator(k)
  }
  case class Foo(id: Int) extends AnyVal
  object Foo extends Builder[Int, Foo](k => new Foo(k)) {
    def apply(str: String): Foo = str match {
      case "Foo1" => foo1
    }
  }
  val foo1: Foo = Foo.build(1)
}

object B {
  val foo = A.Foo.apply("Foo1")
}

B.foo
```

## Output

```scala
java.lang.ExceptionInInitializerError
	at Playground$A$Foo$.<init>(main.scala:8)
	at Playground$A$Foo$.<clinit>(main.scala:8)
	at Playground$B$.<clinit>(main.scala:17)
	at Playground$.<clinit>(main.scala:20)
	at Main$.<clinit>(main.scala:24)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:259)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "Playground$A$Foo$.build(Object)" because "Playground$A$Foo$.MODULE$" is null
	at Playground$A$.<clinit>(main.scala:13)
	... 21 more
```

## Expectation

My initialisation ordering might be dubious but this works in Scala 2.

Works if I change `val foo1` to `lazy val foo1` or if I put all the code into`object A`

**Comment by WojciechMazur** [comment]
Stacktrace from Scala 2 suggests it was using delayed init to handle this situation, this feature was removed from Scala 3. 
```
        at A$Foo$.apply(test.scala:9)
        at B$.<clinit>(test.scala:17)
        at Test$.delayedEndpoint$Test$1(test.scala:21)
        at Test$delayedInit$body.apply(test.scala:20)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
```

**Comment by WojciechMazur** [comment]
`object A.Foo` is initialized before `object A` - it's an example of classic cyclic dependency. @odersky I wonder if it is designed. Cannot we change the order of initialization to force initialization of outer object `A`, before initialization of `A.Foo`? 

```
object A {
  class Builder[K, V](val build: K => V)
  object Foo extends Builder[Int, Int](identity) {
    def apply(str: String): Int = 1
  }
  val foo1 = Foo.build(1)
}

@main def Test =
  // A // prevents java.lang.ExceptionInInitializerError
  A.Foo.apply("Foo1")
```

**Comment by Arthurm1** [comment]
@WojciechMazur Thanks for looking into it so quickly.

If it can't be changed then it would be nice if there was a compiler error rather than hitting this at runtime

**Comment by som-snytt** [comment]
The cycle is induced by the superarg, which is supplied by a method in `A` in Scala 3 but is a `A$Foo$$anonfun$$lessinit$greater$1.class` in Scala 2.

**Comment by som-snytt** [comment]
@Arthurm1 I've never actually used this before, but:
```
➜  scalac -Ysafe-init i15832.scala
-- Warning: i15832.scala:4:32 ------------------------------------------------------------------------------------------
4 |    def build(k: K): V = creator(k)
  |                         ^^^^^^^^^^
  |               Call method Builder.this.creator.apply(k) on a value with an unknown initialization. Calling trace:
  |               -> val foo1: Foo = Foo.build(1)       [ i15832.scala:12 ]
  |                                  ^^^^^^^^^^^^
1 warning found
```

**Comment by Arthurm1** [comment]
@som-snytt That's handy thanks.  I can see why it's not on by default - lots of false positives.

**Comment by liufengyun** [comment]
The code is related to the safe initialization of _global objects_, for which we are still searching for a solution that balances safety, expressiveness, and performance. Related #9176.

One design invariant for global objects we are considering is _initialization-time irrelevance_: the time when a global object is initialized should not change program semantics.

/cc: @olhotak

**Comment by liufengyun** [comment]
> Edit: I tried it with HEAD but no warning, although it fails the same way.

Thanks for looking into it @som-snytt . The behavior of the HEAD is expected, it's due to a recent improvement #15467.
