### ISSUE TITLE
"Cannot get tree of no symbol" for an enum case extending a trait

### ISSUE THREAD

**Issue by adamw** [lampepfl/dotty#15833]
## Compiler version

3.1.2

## Minimized code

Macro:
 
```scala
import scala.deriving.*
import scala.quoted.*
import scala.compiletime.*

object TestMacro2 {

  inline given test[T](using m: Mirror.Of[T]): String =
    inline m match 
      case s: Mirror.SumOf[T] =>
        inline erasedValue[s.MirroredElemTypes] match
          case _: (first *: _) => typeSymbolTree[first]

  inline def typeSymbolTree[T]: String = ${typeSymbolTreeImpl[T]}

  def typeSymbolTreeImpl[T: Type](using Quotes): Expr[String] = {
    import quotes.reflect.*
    println("TREE = " + TypeRepr.of[T].typeSymbol.tree)
    Expr(TypeRepr.of[T].toString)
  }
}
```

Invocation:

```scala
trait One
enum ExtendingTraits:
  case FirstCase extends ExtendingTraits with One

object Test extends App {
  import ExtendingTraits.*
  TestMacro2.test[ExtendingTraits]
}
```

## Output

```scala
[error] 12 |  TestMacro2.test[ExtendingTraits]
[error]    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: Cannot get tree of no symbol
[error]    |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]    |	at dotty.tools.dotc.quoted.reflect.FromSymbol$.definitionFromSym(FromSymbol.scala:16)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2501)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2501)
[error]    |	at TestMacro2$.typeSymbolTreeImpl(TestMacro2.scala:19)
[error]    |
```

## Expectation

The problem is the `TypeRepr.of[T].typeSymbol.tree` invocation. Things work fine if the enum case doesn't extend a trait - that is, if the enum definition is changed to:

```scala
enum ExtendingTraits:
  case FirstCase extends ExtendingTraits
```

**Comment by KacperFKorban** [comment]
Minimized to:

```scala
// _1.scala
import scala.quoted.*

inline def typeSymbolTree[T]: String = ${ typeSymbolTreeImpl[T] }

def typeSymbolTreeImpl[T: Type](using Quotes): Expr[String] = {
  import quotes.reflect.*
  Expr(TypeRepr.of[T].typeSymbol.tree.toString())
}
```

```scala
// _2.scala
trait One
trait ExtendingTraits

val fc: ExtendingTraits & One =
  new ExtendingTraits with One {}

@main
def main =
  println(
    typeSymbolTree[fc.type]
  )
```

**Comment by KacperFKorban** [comment]
I don't think this is a bug. `fc.type` does not have a `typeSymbol` because `fc` doesn't declare any types, it only has one `Singleton` type definition - it's `TermRef`.
This worked before (without the other trait) because the underlying type was a `NamedType`, but now it is a Proxy - `AndType` (`ExtendingTraits & One`). You can see this by printing `TypeRepr.of[T].widen.show`.

A workaround on the user side (until the macro handles proxy types) is to change the original declaration to:
```scala
trait One
enum ExtendingTraits:
  case FirstCase() extends ExtendingTraits with One // notice parentheses after FirstCase
```
In that case there will always be a typeSymbol, since `FirstCase` will be desugared to a `class` instead of a `val`

**Comment by adamw** [comment]
Indeed, not a bug - thanks for the explanation and the fix in magnolia :)
