### ISSUE TITLE
Compiler crashes with java.util.NoSuchElementException: class Class when compiling case class with java annotated field

### ISSUE THREAD

**Issue by megri** [lampepfl/dotty#15955]
## Compiler version

3.1.3. Seems to affect Scala 3+ in general

## Minimized code

I tried minimising the issue by reimplementing the `DataTypeHint` interface and other dependencies but it wouldn't trigger the crash. Using scala-cli was the next best thing.

Bugreport.scala:
```Scala
//> using scala "3.1.3"
//> using lib "org.apache.flink:flink-table-runtime:1.15.2"
//> using lib "io.findify::flink-adt:0.6.1"

package com.stuff

import io.findify.flinkadt.api.*
import org.apache.flink.table.annotation.DataTypeHint // is a Java @interface definition
import org.apache.flink.api.common.typeinfo.TypeInformation

case class Test(@DataTypeHint("BIGINT") timestamp: Long)

@main def run() =
  summon[TypeInformation[Test]]
```

Trigger the issue by issuing `> scala-cli compile Bugreport.scala`

## Output (click arrow to expand)
<details>
java.util.NoSuchElementException: class Class
	at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:508)
	at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:507)
	at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:207)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:505)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:416)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1128)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:739)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genArray(BCodeBodyBuilder.scala:836)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genArrayValue(BCodeBodyBuilder.scala:821)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:444)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1128)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genArray(BCodeBodyBuilder.scala:836)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genArrayValue(BCodeBodyBuilder.scala:821)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:444)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:639)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:453)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:437)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:772)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:639)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:453)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:306)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:112)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock$$anonfun$1(BCodeBodyBuilder.scala:1019)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1019)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1127)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:773)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:362)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1111)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:639)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:453)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:306)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:112)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock$$anonfun$1(BCodeBodyBuilder.scala:1019)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1019)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:437)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1020)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1020)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:437)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1020)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:437)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1020)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:437)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:1020)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:763)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:798)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:606)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:612)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:612)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:227)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:264)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:229)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:565)
exception occurred while compiling /tmp/Bugreport.scala
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:531)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:67)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:311)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:312)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:75)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:225)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:236)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:244)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:253)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:253)
	at dotty.tools.dotc.Run.compileSources(Run.scala:186)
	at dotty.tools.dotc.Run.compile(Run.scala:170)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:133)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$7(BloopHighLevelCompiler.scala:151)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:71)
	at bloop.tracing.BraveTracer.traceInternal(BraveTracer.scala:65)
	at bloop.tracing.BraveTracer.trace(BraveTracer.scala:39)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:70)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$6(BloopHighLevelCompiler.scala:151)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Error compiling project (Scala 3.1.3, JVM)
Error: Unexpected error when compiling project_e9b5bff89c_e9b5bff89c-49d6b1ee03: 'class Class'
Compilation failed
</details>

Possibly related to the mechanics mentioned in https://github.com/lampepfl/dotty/issues/12840

**Comment by prolativ** [comment]
It's really hard to say what the problem could be here without a proper minimization without external dependencies. This could even be a bug in `flinkadt` or `magnolia` itself

**Comment by megri** [comment]
> It's really hard to say what the problem could be here without a proper minimization without external dependencies. This could even be a bug in `flinkadt` or `magnolia` itself

I reported the problem with findify/flinkadt to start with but they thought it might be a compiler error too.
What makes me think it may be a compiler problem is prominence of `dotty.tools.backend.jvm.BCodeBodyBuilder` references in the stack trace.

Perhaps macro- and magnolia-references are excluded due to the way they work with compile-time code generation? I could try to dig into this some more but I'm not sure how I enable deeper traces during compilation.

**Comment by xeppaka** [comment]
Hi, I'm getting the same problem with Java annotations. Please see here simplified code of what magnolia is doing with Macro: https://github.com/scala/scala3/issues/19303#issuecomment-2295290329

**Comment by prolativ** [comment]
Minimized without external dependencies:

Bugreport.scala:
```scala
import magnolia1.Macro.*

trait Tc[T]
inline implicit def ti[T]: Tc[T] =
  val _ = paramAnns[T]
  ???

case class Test(@MyHint timestamp: Long)

val _ = summon[Tc[Test]]
```

MyHint.java:
```java
public @interface MyHint {
  Class<?> rawType() default Object.class;
}
```

magnolia.scala:
```scala
package magnolia1

import scala.quoted.*

object Macro:
  inline def paramAnns[T]: List[(String, List[Any])] = ${ paramAnns[T] }

  def paramAnns[T: Type](using Quotes): Expr[List[(String, List[Any])]] =
    import quotes.reflect.*
    val tpe = TypeRepr.of[T]
    val anns = tpe.typeSymbol.primaryConstructor.paramSymss.flatten.map { field =>
      field.name -> field.annotations
        .filter(a => a.tpe.typeSymbol.maybeOwner.isNoSymbol || a.tpe.typeSymbol.owner.fullName != "scala.annotation.internal")
        .map(_.asExpr.asInstanceOf[Expr[Any]])
    }.filter(_._2.nonEmpty)
    Expr.ofList(anns.map { (name, as) => Expr.ofTuple(Expr(name), Expr.ofList(as)) })
```

I'm building the codebase using scala-cli. Checked scala 3.1.3 (as reported), 3.3.7 (latest LTS) and 3.8.3 (latest stable Next). Depending on whether I use the `--server=false` or not, the outputs vary

|  | server=true | server=false  | 
|----------|----------|----------|
| scala 3.1.3   |  Crash with stack trace   | Crash with stack trace |
| scala 3.3.7   |   Crash, no stacktrace  | Crash with stack trace
| scala 3.8.3   | Crash, no stack trace | Crash with stack trace + compilation error with positions

Note the warning from scala-cli:

```scala
[warn] With --server=false, .java files are not compiled to .class files.
scalac parses .java sources for type information (cross-compilation), but without the build server (Bloop/Zinc) nothing compiles them to bytecode.
Affected .java files:
  /Users/mpalka/Projects/scala3/local/repro/i15955/source/MyHint.java
Remove --server=false or compile Java files separately to avoid runtime NoClassDefFoundError
```

**Comment by prolativ** [comment]
Issue summary from my LLM agent:

# Issue Summary: #15955 — Compiler crash when macro lifts a Java annotation with a `Class<?>` field

## What the bug is

When a Scala 3 macro calls `.asExpr` on a `quotes.reflect.Term` that represents a Java annotation whose fields include a `Class<?>`-typed element (e.g., `Class<?> rawType() default Object.class`), the compiler crashes at bytecode-generation time with:

```
java.util.NoSuchElementException: key not found: class Class   # 3.3.7+
java.util.NoSuchElementException: class Class                   # 3.1.3
```

The crash has been reproducible on every Scala 3 release from 3.1.3 through at least 3.8.3 — it has never been fixed.

## Minimal reproducer (three files, zero external dependencies)

The reproducer is self-contained in three files. The key triangle is:

1. **`MyHint.java`** — a Java annotation with a `Class<?>` field carrying a default value:
   ```java
   public @interface MyHint { Class<?> rawType() default Object.class; }
   ```

2. **`magnolia.scala`** — an 18-line macro in package `magnolia1` that collects constructor-parameter annotations and lifts each one with `.asExpr.asInstanceOf[Expr[Any]]`.

3. **`Bugreport.scala`** — a case class `Test(@MyHint timestamp: Long)` and a call to `summon[Tc[Test]]`, which triggers the macro at compile time.

The crash fires even if the macro body never does anything with the lifted annotations. As soon as `.asExpr` is called on the annotation `Term` and the result is embedded in the generated `Expr`, the code the macro emits is enough to crash the backend.

## Where the crash lives

The crash originates in the JVM backend, specifically in `BCodeSkelBuilder` / `BCodeBodyBuilder` (`compiler/src/dotty/tools/backend/jvm/`). These classes maintain a `locals` map from symbol to local-variable slot. When emitting code for a `class` literal at the JVM level, the backend normally emits an `ldc` ("load constant") instruction. However, for a class literal that refers to `java.lang.Class` *itself* — as opposed to a class that merely *uses* `Class` as a type — the backend takes a different code path and attempts to look the symbol up in `locals`. Because `class Class` is never a local variable, the map lookup fails with `NoSuchElementException`.

The condition is specific to `Class<?>` fields (class literals *of* `java.lang.Class`). An annotation field typed as, say, `String` or `int` does not trigger the crash.

## Why macro-generated code triggers it when hand-written code does not

When a user writes `@MyHint(rawType = classOf[Object])` directly in Scala source, the frontend processes and canonicalises the annotation reference before it reaches the backend. The class-literal AST node produced for `classOf[Object]` in user code goes through a well-tested path that correctly emits `ldc Object.class`.

When a macro calls `.asExpr` on the raw annotation `Term`, the backend receives an AST that represents the annotation's default value (`Object.class` on the Java side). The representation of that default value in the Scala 3 macro IR is a `Literal(ClassOf(...))` node where the class is `java.lang.Class` itself — a reflexive class literal. That specific form appears not to have been exercised in the normal compilation path for user-written code, so the backend code that maps it to `ldc` is either absent or unreachable, and the fallback mistakenly tries `locals.load`.

## Hints for the implementor

1. **Find the `ClassOf` → `ldc` path in the backend.** Look for where the JVM backend handles `Literal(ClassOf(tpe))` nodes. There should be a case that emits `ldc` for class literals. Verify that it handles the reflexive case (`tpe` == `java.lang.Class`) and does not fall through to a locals lookup.

2. **Check the fallback in `locals`.** The `NoSuchElementException` is thrown by a `locals(sym)` call (or equivalent map access). Find that call site and understand under what conditions a `ClassOf` node ends up there. Add a guard or a dedicated case before the fallback.

3. **Look at how Java annotation default values are reified.** The macro IR produced by `.asExpr` on an annotation `Term` may differ subtly from what the typer produces for user-written annotations. Tracing the two paths through `ReifyQuotes` / `PickleQuotes` and into the backend may reveal where they diverge.

4. **Compare with `classOf[java.lang.Class[_]]` in user code.** Writing `@MyHint(rawType = classOf[java.lang.Class[_]])` directly in Scala source (not via a macro) may or may not reproduce the crash. If it does, the bug is entirely in the backend's handling of the reflexive class literal. If it doesn't, the bug is in how the macro IR encodes annotation default values before the backend sees them.

5. **Test the fix across the version range.** The crash is present in 3.1.3 (AnyRefMap backend) through 3.8.3 (HashMap backend) — the only difference is the exception message format. A fix should be verified on at least 3.1.x, 3.3.x, and the current main to ensure no silent regressions.

**Comment by SolalPirelli** [comment]
Same issue as #19303 I think, the backend receives a weird defdef that uses an undeclared `_` identifier for a default value.
