### ISSUE TITLE
NullPointerException at weird intersection of mutually referential =:=s

### ISSUE THREAD

**Issue by s5bug** [lampepfl/dotty#16019]
## Compiler version

3.2.0

## Minimized code

```Scala
extension[X <: Tuple, Y <: Tuple, F[_]](x: X)(using Y =:= Tuple.InverseMap[X, F], X =:= Tuple.Map[Y, F]) {
  def mapN[B]: F[B] =
    x match {
      case (_ *: t): (ht *: tt) =>
        t.mapN[ht => B](???)
    }
}
```

I feel like this can be minimized further, but I'm out of ideas as to what to change.

## Output (click arrow to expand)
<details>

```scala
java.lang.NullPointerException: Cannot invoke "dotty.tools.dotc.core.Types$Type.hash()" because "tp" is null
	at dotty.tools.dotc.core.Hashable.typeHash(Hashable.scala:51)
	at dotty.tools.dotc.core.Hashable.typeHash$(Hashable.scala:42)
	at dotty.tools.dotc.core.Uniques$AppliedUniques.typeHash(Uniques.scala:66)
	at dotty.tools.dotc.core.Hashable.finishHash(Hashable.scala:72)
	at dotty.tools.dotc.core.Hashable.finishHash$(Hashable.scala:42)
	at dotty.tools.dotc.core.Uniques$AppliedUniques.finishHash(Uniques.scala:66)
	at dotty.tools.dotc.core.Hashable.finishHash(Hashable.scala:84)
	at dotty.tools.dotc.core.Hashable.finishHash$(Hashable.scala:42)
	at dotty.tools.dotc.core.Uniques$AppliedUniques.finishHash(Uniques.scala:66)
	at dotty.tools.dotc.core.Hashable.doHash(Hashable.scala:110)
	at dotty.tools.dotc.core.Hashable.doHash$(Hashable.scala:42)
	at dotty.tools.dotc.core.Uniques$AppliedUniques.doHash(Uniques.scala:66)
	at dotty.tools.dotc.core.Uniques$AppliedUniques.enterIfNew(Uniques.scala:70)
	at dotty.tools.dotc.core.Types$AppliedType$.apply(Types.scala:4554)
	at dotty.tools.dotc.core.TypeApplications$.appliedTo$extension(TypeApplications.scala:388)
	at dotty.tools.dotc.core.Types$AppliedType.derivedAppliedType(Types.scala:4528)
	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.derivedAppliedType(Types.scala:5952)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5627)
	at dotty.tools.dotc.core.TrackingTypeComparer$$anon$5.apply(TypeComparer.scala:2929)
	at dotty.tools.dotc.core.TrackingTypeComparer.redux$1(TypeComparer.scala:2955)
	at dotty.tools.dotc.core.TrackingTypeComparer.matchCase$1(TypeComparer.scala:2968)
	at dotty.tools.dotc.core.TrackingTypeComparer.recur$2(TypeComparer.scala:2981)
	at dotty.tools.dotc.core.TrackingTypeComparer.op$proxy73$1(TypeComparer.scala:3014)
	at dotty.tools.dotc.core.TrackingTypeComparer.matchCases(TypeComparer.scala:3015)
	at dotty.tools.dotc.core.Types$MatchType.matchCases$1(Types.scala:4918)
	at dotty.tools.dotc.core.Types$MatchType.reduced$$anonfun$1(Types.scala:4927)
	at dotty.tools.dotc.core.TypeComparer.inSubComparer(TypeComparer.scala:2688)
	at dotty.tools.dotc.core.TypeComparer.tracked(TypeComparer.scala:2698)
	at dotty.tools.dotc.core.TypeComparer$.tracked(TypeComparer.scala:2855)
	at dotty.tools.dotc.core.Types$MatchType.reduced(Types.scala:4927)
	at dotty.tools.dotc.core.Types$MatchType.tryNormalize(Types.scala:4876)
	at dotty.tools.dotc.core.Types$Type.normalized(Types.scala:1434)
	at dotty.tools.dotc.core.Types$AppliedType.superType(Types.scala:4207)
	at dotty.tools.dotc.core.TypeComparer.compareAppliedType1$1(TypeComparer.scala:1258)
	at dotty.tools.dotc.core.TypeComparer.fourthTry$1(TypeComparer.scala:809)
	at dotty.tools.dotc.core.TypeComparer.fallback$2$$anonfun$1(TypeComparer.scala:1173)
	at scala.Function0.apply$mcZ$sp(Function0.scala:39)
	at dotty.tools.dotc.core.TypeComparer.sufficientEither(TypeComparer.scala:1658)
	at dotty.tools.dotc.core.TypeComparer.either(TypeComparer.scala:1619)
	at dotty.tools.dotc.core.TypeComparer.fallback$2(TypeComparer.scala:1173)
	at dotty.tools.dotc.core.TypeComparer.compareLower$1(TypeComparer.scala:1189)
	at dotty.tools.dotc.core.TypeComparer.compareAppliedType2$1(TypeComparer.scala:1213)
	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:573)
	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:506)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:383)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1336)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:194)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:204)
	at dotty.tools.dotc.core.TypeComparer.isSubArg$1(TypeComparer.scala:1556)
	at dotty.tools.dotc.core.TypeComparer.recurArgs$1(TypeComparer.scala:1559)
	at dotty.tools.dotc.core.TypeComparer.isSubArgs(TypeComparer.scala:1562)
	at dotty.tools.dotc.core.TypeComparer.loop$1(TypeComparer.scala:1123)
	at dotty.tools.dotc.core.TypeComparer.isMatchingApply$1(TypeComparer.scala:1138)
	at dotty.tools.dotc.core.TypeComparer.compareAppliedType2$1(TypeComparer.scala:1208)
	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:573)
	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:395)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:383)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1336)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:194)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:204)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:128)
	at dotty.tools.dotc.core.TypeComparer$.topLevelSubType(TypeComparer.scala:2752)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:1044)
	at dotty.tools.dotc.core.Types$Type.relaxed_$less$colon$less(Types.scala:1076)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.isCompatible(ProtoTypes.scala:38)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.isCompatible$(ProtoTypes.scala:25)
	at dotty.tools.dotc.typer.ProtoTypes$NoViewsAllowed$.isCompatible(ProtoTypes.scala:119)
	at dotty.tools.dotc.typer.Implicits$ImplicitRefs.candidateKind$1(Implicits.scala:237)
	at dotty.tools.dotc.typer.Implicits$ImplicitRefs.tryCandidate$1(Implicits.scala:251)
	at dotty.tools.dotc.typer.Implicits$ImplicitRefs.filterMatching$$anonfun$2(Implicits.scala:260)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.Implicits$ImplicitRefs.filterMatching(Implicits.scala:260)
	at dotty.tools.dotc.typer.Implicits$ContextualImplicits.computeEligible(Implicits.scala:365)
	at dotty.tools.dotc.typer.Implicits$ContextualImplicits.eligible(Implicits.scala:357)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1485)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1520)
	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:1014)
	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:797)
	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:117)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:863)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:797)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:117)
	at dotty.tools.dotc.typer.Typer.implicitArgs$1(Typer.scala:3490)
	at dotty.tools.dotc.typer.Typer.addImplicitArgs$1(Typer.scala:3526)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$1(Typer.scala:3602)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3800)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4038)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3368)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Applications.extMethodApply(Applications.scala:2263)
	at dotty.tools.dotc.typer.Applications.extMethodApply$(Applications.scala:327)
	at dotty.tools.dotc.typer.Typer.extMethodApply(Typer.scala:117)
	at dotty.tools.dotc.typer.Typer.tryExtension$1(Typer.scala:3279)
	at dotty.tools.dotc.typer.Typer.tryExtensionOrConversion(Typer.scala:3292)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:620)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:647)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:684)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2828)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.Applications.typedTypeApply(Applications.scala:1104)
	at dotty.tools.dotc.typer.Applications.typedTypeApply$(Applications.scala:327)
	at dotty.tools.dotc.typer.Typer.typedTypeApply(Typer.scala:117)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2878)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:910)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2859)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1062)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2867)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.Typer.caseRest$1(Typer.scala:1719)
	at dotty.tools.dotc.typer.Typer.typedCase(Typer.scala:1735)
	at dotty.tools.dotc.typer.Typer.typedCases$$anonfun$1(Typer.scala:1665)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:90)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:106)
	at dotty.tools.dotc.typer.Typer.typedCases(Typer.scala:1667)
	at dotty.tools.dotc.typer.Typer.$anonfun$27(Typer.scala:1657)
	at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2229)
	at dotty.tools.dotc.typer.Applications.harmonic$(Applications.scala:327)
	at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:117)
	at dotty.tools.dotc.typer.Typer.typedMatchFinish(Typer.scala:1657)
	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1591)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2873)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.Typer.$anonfun$48(Typer.scala:2295)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2295)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2835)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2500)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2847)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2851)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2629)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2892)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
	at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:43)
	at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:50)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:417)
	at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:50)
	at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:84)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:84)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:234)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:245)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:253)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:262)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:262)
	at dotty.tools.dotc.Run.compileSources(Run.scala:186)
	at dotty.tools.dotc.Run.compile(Run.scala:170)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2364)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2312)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
</details>

**Comment by odersky** [comment]
Fixed in main? I get:
```
-- [E008] Not Found Error: i16019.scala:5:10 -----------------------------------
5 |        t.mapN[ht => B](???)
  |        ^^^^^^
  |   value mapN is not a member of tt.
  |   An extension method was tried, but could not be fully constructed:
  |
  |       mapN[tt, Y, F](t)(<:<.refl[Tuple.InverseMap[tt, F]], 
  |         /* missing */summon[tt =:= Tuple.Map[Tuple.InverseMap[tt, F], F]]
  |       )    failed with
  |
  |           Cannot prove that tt
  |           
  |           where:    tt is a type in method mapN with bounds <: Tuple
  |            =:= Tuple.Map[Y, F]
  |           
  |           where:    F is a type variable with constraint <: [_] =>> Any
  |                     Y is a type variable with constraint <: Tuple
  |           .
  |           
  |           Note: a match type could not be fully reduced:
  |           
  |             trying to reduce  Tuple.Map[Y, F]
  |             failed since selector  Y
  |             does not match  case EmptyTuple => EmptyTuple
  |             and cannot be shown to be disjoint from it either.
  |             Therefore, reduction cannot advance to the remaining case
  |           
  |               case h *: t => F[h] *: scala.Tuple.Map[t, F]
  |
  |   where:    tt is a type in method mapN with bounds <: Tuple
```

**Comment by s5bug** [comment]
I don't know how to test mainline, but I can verify the code crashes both in and outside of the REPL on 3.2.0; if it can't be reproduced in mainline then I would consider it solved.

**Comment by som-snytt** [comment]
I see the NPE on 3.2.0 (thanks, I'd forgotten to update my sdkman) and the error on HEAD.

@s5bug you can mainline `mainline` by checking out the project and just running `./bin/scalac`, which will build itself. That is convenient for occasional tests.

**Comment by SethTisue** [comment]
> I don't know how to test mainline

it's normally sufficient to test the latest nightly, which is available via `scala-cli -S 3.nightly`

**Comment by som-snytt** [comment]
I keep forgetting to be sufficiently annoyed by `sdk update` to start using `scala-cli` as my daily test tool.

**Comment by s5bug** [comment]
Can confirm I get a proper error instead of a crash on the latest nightly.
