### ISSUE TITLE
Class cast exception when creating a new 2.13-defined class accepting a by-name parameter

### ISSUE THREAD

**Issue by alexarchambault** [lampepfl/dotty#16351]
## Compiler version

`3.2.1` (`3.2.0` also suffers from this, but not `3.1.3`)

## Minimized code

(Edit: fully standalone reproduction in comment below)

Can be reproduced with Scala CLI. In `Test.scala`:
```scala
//> using lib "com.lihaoyi:ammonite-cross-3.2.1-interp_2.13.10:2.5.5-17-df243e14"
//> using lib "com.lihaoyi:ammonite-compiler_3.2.1:2.5.5-17-df243e14"
//> using scala "3.2.1"

import ammonite.compiler.*
import ammonite.interp.*
import ammonite.runtime.*
import ammonite.util.*

object Test {
  def main(args: Array[String]): Unit = {
    val frame = Frame.createInitial()
    new Interpreter(
      CompilerBuilder,
      Parsers, // this is the by-name parameter that triggers the class cast exception
      Printer(System.out, System.err, System.out, _ => (), _ => (), _ => ()),
      Storage.InMemory(),
      os.pwd,
      Ref(Colors.Default),
      getFrame = () => frame,
      createFrame = () => frame,
      replCodeWrapper = DefaultCodeWrapper,
      scriptCodeWrapper = DefaultCodeWrapper,
      alreadyLoadedDependencies = Nil
    ) {} // '{}' required to get the crash
  }
}
```

~I've not been able to reproduce that without using those Ammonite classes yet.~

## Output

Running it:
```text
$ scala-cli Test.scala
Exception in thread "main" java.lang.ClassCastException: class ammonite.compiler.Parsers$ cannot be cast to class scala.Function0 (ammonite.compiler.Parsers$ and scala.Function0 are in unnamed module of loader 'app')
	at Test$$anon$1.<init>(Test.scala:16)
	at Test$.main(Test.scala:25)
	at Test.main(Test.scala)
```

## Expectation

No crash at runtime

Note that running this with Scala `3.1.3` requires slightly different dependencies. The header needs to be changed to
```scala
//> using lib "com.lihaoyi:ammonite-cross-3.1.3-interp_2.13.7:2.5.5-17-df243e14"
//> using lib "com.lihaoyi:ammonite-compiler_3.1.3:2.5.5-17-df243e14"
//> using scala "3.1.3"
```

**Comment by alexarchambault** [comment]
Bisecting using nightlies, it seems the regression happened between `3.2.0-RC1-bin-20220415-8037f3b-NIGHTLY` (no runtime crash) and `3.2.0-RC1-bin-20220416-53f5531-NIGHTLY` (runtime crash).

**Comment by odersky** [comment]
I tried this standalone without a publishing step (i.e. compile Lib, compile App) and it ran OK. So not sure what goes on here.
