### ISSUE TITLE
Class casting error not properly caught inside `Try`

### ISSUE THREAD

**Issue by xinbinhuang** [lampepfl/dotty#16365]
I'm not sure if this's a bug or just a language caveat/limitations?

## Compiler version

scalaVersion := "3.2.0

## Minimized code

Snippet link: https://scastie.scala-lang.org/vey5EKyOQ1iBzJWpiZ5QWg
```Scala
import scala.util.Try
import java.io._

case class Test(errField: Option[Int])

val wrongCast = Try {
  Some("asf").asInstanceOf[Option[Int]]
}

assert(wrongCast.isSuccess)

val test = Test(wrongCast.get)


test.errField.getOrElse(1)
```

## Output

```scala
java.lang.ExceptionInInitializerError
	at Main$.&lt;clinit&gt;(main.scala:19)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
	at Playground$.&lt;clinit&gt;(main.scala:15)
	... 17 more
```

## Expectation

The casting exception is caught inside the `Try`, not when the element inside `Option` is accessed.

**Comment by sjrd** [comment]
That is expected. The explicitly written cast *succeeds*, because it only checks `Option`, not `Option[Int]`. The cast to `Int` happens later, outside the `Try`.

In general, you cannot rely on CCEs to be thrown when there are generic types.

**Comment by SethTisue** [comment]
> I'm not sure if this's a bug or just a language caveat/limitations?

it's better to start at https://users.scala-lang.org in these situations
