### ISSUE TITLE
`scalatest` community build fails on Java 16

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#16423]
Currently, there is a failure publishing `scalatest` in the `community_build_a` GitHub action when we use Java 16. We should pull the latest version of `scalatest`  and try to upgrade to Java 16 (and then 17).

<details>
<summary>
Failure with Java 16
</summary>

Full CI log: https://github.com/lampepfl/dotty/actions/runs/3546329029/jobs/5955260081

```
[error] java.util.ConcurrentModificationException
[error] 	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:742)
[error] 	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:558)
[error] 	at aQute.bnd.osgi.Jar.putResource(Jar.java:259)
[error] 	at aQute.bnd.osgi.Jar$1.visitFile(Jar.java:186)
[error] 	at aQute.bnd.osgi.Jar$1.visitFile(Jar.java:167)
[error] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
[error] 	at aQute.bnd.osgi.Jar.buildFromDirectory(Jar.java:166)
[error] 	at aQute.bnd.osgi.Jar.<init>(Jar.java:109)
[error] 	at aQute.bnd.osgi.Jar.<init>(Jar.java:138)
[error] 	at aQute.bnd.osgi.Analyzer.setClasspath(Analyzer.java:1465)
[error] 	at com.typesafe.sbt.osgi.Osgi$.bundleTask(Osgi.scala:57)
[error] 	at com.typesafe.sbt.osgi.SbtOsgi$.$anonfun$defaultOsgiSettings$1(SbtOsgi.scala:55)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] (scalacticDotty / osgiBundle) java.util.ConcurrentModificationException
[error] Total time: 22 s, completed Nov 25, 2022, 9:22:06 AM
[error] Test dotty.communitybuild.CommunityBuildTestA.scalatest failed: java.lang.RuntimeException: Publish command exited with code 1 for project scalatest. Project details:
Error:  SbtCommunityProject(scalatest,scalacticDotty/clean; scalacticDottyJS/clean; set scalatestTestDotty / Test / managedSources ~= (_.filterNot(_.getName == "GeneratorSpec.scala").filterNot(_.getName == "FrameworkSuite.scala").filterNot(_.getName == "WaitersSpec.scala").filterNot(_.getName == "TestSortingReporterSpec.scala").filterNot(_.getName == "JavaFuturesSpec.scala").filterNot(_.getName == "ParallelTestExecutionSpec.scala").filterNot(_.getName == "TimeLimitsSpec.scala").filterNot(_.getName == "DispatchReporterSpec.scala").filterNot(_.getName == "TestThreadsStartingCounterSpec.scala").filterNot(_.getName == "SuiteSortingReporterSpec.scala").filterNot(_.getName == "CommonGeneratorsSpec.scala").filterNot(_.getName == "PropCheckerAssertingSpec.scala").filterNot(_.getName == "ConductorMethodsSuite.scala").filterNot(_.getName == "EventuallySpec.scala")); set scalacticTestDotty / Test / managedSources ~= (_.filterNot(_.getName == "NonEmptyArraySpec.scala")); set genRegularTests4 / Test / managedSources ~= (_.filterNot(_.getName == "FrameworkSuite.scala").filterNot(_.getName == "GeneratorSpec.scala").filterNot(_.getName == "CommonGeneratorsSpec.scala").filterNot(_.getName == "ParallelTestExecutionSpec.scala").filterNot(_.getName == "DispatchReporterSpec.scala").filterNot(_.getName == "TestThreadsStartingCounterSpec.scala").filterNot(_.getName == "EventuallySpec.scala")); scalacticTestDotty/test; scalatestTestDotty/test; scalacticDottyJS/compile; scalatestDottyJS/compile,List(),List(SbtCommunityProject(scala-xml,xml/test,List(),List(),dotty.communitybuild.SbtCommunityProject$$$Lambda$54/0x0000000800ccede0@552ed60b,xml/publishLocal,xml/doc,List(-Xcheck-macros, -Ysafe-init),false)),dotty.communitybuild.projects$$$Lambda$58/0x0000000800cd7a90@4940755a,scalacticDotty/publishLocal; scalatestDotty/publishLocal; scalacticDottyJS/publishLocal; scalatestDottyJS/publishLocal,;scalacticDotty/doc,List(-Xcheck-macros, -Ysafe-init),false), took 176.812 sec
Error:      at dotty.communitybuild.CommunityProject.publish(projects.scala:64)
Error:      at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$$anonfun$1(projects.scala:52)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
Error:      at scala.collection.immutable.List.foreach(List.scala:333)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies(projects.scala:52)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publishDependencies(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publish(projects.scala:58)
Error:      at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
Error:      at dotty.communitybuild.CommunityBuildRunner$.run$$anonfun$2(CommunityBuildRunner.scala:24)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
Error:      at scala.collection.immutable.List.foreach(List.scala:333)
Error:      at dotty.communitybuild.CommunityBuildRunner$.run(CommunityBuildRunner.scala:24)
Error:      at dotty.communitybuild.CommunityBuildTestA.scalatest(CommunityBuildTest.scala:21)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.lang.reflect.Method.invoke(Method.java:567)
Error:      ...
```
</details>

See #16412

To make the CI faster when updating this project, include the following in the PR description: `[skip test] [skip test_windows_fast] [skip test_sbt] [skip mima] [skip docs] [skip community_build_b] [skip community_build_c]`

**Comment by nicolasstucki** [comment]
Updating `scalatest` did not help https://github.com/lampepfl/dotty/actions/runs/3565037571/jobs/5989711063

**Comment by smarter** [comment]
> [error] java.util.ConcurrentModificationException
[error] 	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:742)
[error] 	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:558)
[error] 	at aQute.bnd.osgi.Jar.putResource(Jar.java:259)

That looks like what https://github.com/dotty-staging/scalatest/commit/af55496b7de8139b092a93f1c6dee50259f34190 was meant to fix
