### ISSUE TITLE
`munit` community build fails on Java 16

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#16422]
Currently, there is a failure publishing `munit` in the `community_build_b` GitHub action when we use Java 16. We should pull the latest version of `munit`  and try to upgrade to Java 16 (and then 17).

<details>
<summary>
Failure with Java 16
</summary>

Full CI log: https://github.com/lampepfl/dotty/actions/runs/3546329029/jobs/5955259852

```
Publishing munit
sbt -sbt-version 1.7.1 -Dsbt.supershell=false -Ddotty.communitybuild.dir=/__w/dotty/dotty/community-build --addPluginSbtFile=/__w/dotty/dotty/community-build/sbt-injected-plugins clean; set Global/logLevel := Level.Error; set Global/updateOptions ~= (_.withLatestSnapshots(false)); set Global/scalacOptions ++= List("-Xcheck-macros","-Ysafe-init");++3.3.0-RC1-bin-SNAPSHOT!; munitJVM/publishLocal; munitJS/publishLocal; munitScalacheckJVM/publishLocal; munitScalacheckJS/publishLocal; junit/publishLocal
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
copying runtime jar...
mkdir: cannot create directory ‘’: No such file or directory
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error:  Test dotty.communitybuild.CommunityBuildTestB.http4s failed: java.lang.RuntimeException: Publish command exited with code 1 for project munit. Project details:
Error:  SbtCommunityProject(munit,testsJVM/test;testsJS/test;,List(),List(SbtCommunityProject(scalacheck,coreJVM/test;coreJS/test,List(),List(),dotty.communitybuild.SbtCommunityProject$$$Lambda$56/0x0000000800ccb858@6df6ab2c,coreJVM/publishLocal;coreJS/publishLocal,null,List(-Xcheck-macros, -Ysafe-init),false)),dotty.communitybuild.SbtCommunityProject$$$Lambda$56/0x0000000800ccb858@6e2ad423,munitJVM/publishLocal; munitJS/publishLocal; munitScalacheckJVM/publishLocal; munitScalacheckJS/publishLocal; junit/publishLocal,junit/doc; munitJVM/doc,List(-Xcheck-macros, -Ysafe-init),false), took 90.419 sec
Error:      at dotty.communitybuild.CommunityProject.publish(projects.scala:64)
Error:      at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$$anonfun$1(projects.scala:52)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
Error:      at scala.collection.immutable.List.foreach(List.scala:333)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies(projects.scala:52)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publishDependencies(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publish(projects.scala:58)
Error:      at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$$anonfun$1(projects.scala:52)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
Error:      at scala.collection.immutable.List.foreach(List.scala:333)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies(projects.scala:52)
Error:      at dotty.communitybuild.CommunityProject.publishDependencies$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publishDependencies(projects.scala:104)
Error:      at dotty.communitybuild.CommunityProject.publish(projects.scala:58)
Error:      at dotty.communitybuild.CommunityProject.publish$(projects.scala:35)
Error:      at dotty.communitybuild.SbtCommunityProject.publish(projects.scala:104)
Error:      at dotty.communitybuild.CommunityBuildRunner$.run$$anonfun$1(CommunityBuildRunner.scala:23)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
Error:      at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
Error:      at scala.collection.immutable.List.foreach(List.scala:333)
Error:      at dotty.communitybuild.CommunityBuildRunner$.run(CommunityBuildRunner.scala:23)
Error:      at dotty.communitybuild.CommunityBuildTestB.http4s(CommunityBuildTest.scala:55)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.lang.reflect.Method.invoke(Method.java:567)
Error:      ...
```
</details>

See #16412

To make the CI faster when updating this project, include the following in the PR description: `[skip test] [skip test_windows_fast] [skip test_sbt] [skip mima] [skip docs] [skip community_build_a] [skip community_build_c]`

**Comment by dwijnand** [comment]
Need to pull in https://github.com/scalameta/munit/pull/440.

**Comment by mbovel** [comment]
It seems this issue was fixed by ee4e842bea5b08865008ff12d87392a123ba0a8f. Is that correct?
