### ISSUE TITLE
Range with size over Int.MaxValue can be intialized, but crashes upon use

### ISSUE THREAD

**Issue by MarkovChainmail** [lampepfl/dotty#16600]
## Compiler version

3.2.0

## Minimized code
```scala
val range = BigInt("0") until BigInt("1000000000000")
println(range.take(10).toList)
```

## Output

```scala
java.lang.ExceptionInInitializerError
	at Main$.&lt;clinit&gt;(main.scala:8)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: More than Int.MaxValue elements.
	at scala.collection.immutable.NumericRange$.check$1(NumericRange.scala:324)
	at scala.collection.immutable.NumericRange$.count(NumericRange.scala:334)
	at scala.collection.immutable.NumericRange.length$lzycompute(NumericRange.scala:75)
	at scala.collection.immutable.NumericRange.length(NumericRange.scala:75)
	at scala.collection.immutable.NumericRange.take(NumericRange.scala:143)
	at Playground$.&lt;clinit&gt;(main.scala:4)
	... 17 more
```

See also https://scastie.scala-lang.org/BalmungSan/J36g8PSjTuy0i284aMMw1A/1

## Expectation
https://scala-lang.org/api/3.x/scala/collection/immutable/Range.html
Documentation says an exception will be thrown when a collection is created with too many elements, or asked to index beyond Int.MaxValue will thrown an exception. However, shown code example arguably does not access elements beyond Int.MaxValue?

Scala2 bug repository suggests an IllegalArgumentException should be thrown if the initialized range is too large https://github.com/scala/bug/issues/4308 https://github.com/scala/bug/issues/4042

**Comment by prolativ** [comment]
That will require an upstream fix in scala 2.13 standard library. There already seems to be an issue for that https://github.com/scala/bug/issues/12706
