### ISSUE TITLE
crash with scala.MatchError: Skolem...

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1662]
$ cat abc.scala
```
class Lift {
  def apply(f: F0)
  class F0
  object F0 { implicit def f2f0(String): F0 = ??? }
  (new Lift)("")
}
```

$ dotc abc.scala
```
-- [E018] Syntax Error: abc.scala --------------------------------------------------------------------------------------
3 |  def apply(f: F0)
  |                  ^
  |                  missing return type

longer explanation available when compiling with `-explain`
-- Error: abc.scala ----------------------------------------------------------------------------------------------------
5 |  object F0 { implicit def f2f0(String): F0 = ??? }
  |                                      ^
  |                                      ':' expected but ')' found

exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" scala.MatchError: Skolem(529116035) (of class dotty.tools.dotc.core.Types$CachedSkolemType)
        at dotty.tools.dotc.ast.tpd$.singleton(tpd.scala:343)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:328)
        at dotty.tools.dotc.ast.tpd$.singleton(tpd.scala:344)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:328)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$26.apply(Implicits.scala:602)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$26.apply(Implicits.scala:600)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:132)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
```

**Comment by liufengyun** [comment]
Thanks for reporting @helloqirun, it's confirmed !

@odersky : I see a lot of crashes resulted from the fact that the code is not syntactically correct. Can we simply stop compilation if there are parsing errors?

**Comment by odersky** [comment]
@liufengyun 

> Can we simply stop compilation if there are parsing errors?

This would be problematic, at least for IDEs. We need to get types for e.g. navigation even if there are syntax errors.
