### ISSUE TITLE
NoSuchMethodError when accessing an override val via super

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#16704]
## Compiler version

3.2.0
## Minimized code

```Scala

trait A {
  def f: String
}

trait B extends A {
  def f = "B";
}

trait C extends A {
  override val f = "C"
}

trait D extends A with B {
  def d = super.f
}

object O extends B with C with D

O.f
O.d
```

## Output

```
java.lang.NoSuchMethodError: 'java.lang.String Playground$C.f$(Playground$C)'
	at Playground$O$.Playground$D$$super$f(main.scala:19)
	at Playground$D.d(main.scala:16)
	at Playground$D.d$(main.scala:15)
	at Playground$O$.d(main.scala:19)
	at Playground$.&lt;clinit&gt;(main.scala:22)
	at Main$.&lt;clinit&gt;(main.scala:27)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Note that this bug can be reproduced in Scala 2, too. See https://github.com/scala/bug/issues/12715
## Expectation
No error

**Comment by odersky** [comment]
Observations:

 - The `val` in trait `C` is essential. It works with `def`.
 - The translations of both versions in the transformer pipeline are basically the same. They both produce this implemention of `D$$super$f`:
    ```scala
     def D$$super$f(): String = super[C].f()
     ```
 - It looks like the backend translates the mixin call `super[C]` to a call to an interface method
    ```
    C.f$:(LC;)Ljava/lang/String
    ```
    I did not see a correspondent of this method with either `def` or `val`, so maybe it's the backend that generates the interface method, and fails to do so in the case of `val`?

**Comment by odersky** [comment]
@sjrd Maybe you have an idea about what could be the cause of this?

**Comment by lrytz** [comment]
I can take a look at this one (and its [cousin on Scala 2](https://github.com/scala/bug/issues/12715))

**Comment by sjrd** [comment]
Scala.js has the same issue (most likely from the same cause in an earlier phase):
```
 Referring to non-existent method C.f()java.lang.String
   called from O$.D$$super$f()java.lang.String
   called from D.d()java.lang.String
   called from O$.d()java.lang.String
   called from Main$.main([java.lang.String)void
   called from static Main.main([java.lang.String)void
   called from core module module initializers
 involving instantiated classes:
   O$
   Main$
```

**Comment by Atry** [comment]
By the way, I think an override method that does not include a `super` call should be a lint error, because it silently suppresses the implementation from any super classes, even when the super classes are dynamically determined.

``` scala
trait A {
  def f: String
}

trait C extends A {
  // What is the purpose? Implementing A.f, or transforming A.f?
  override val f = "C" 
}
```
If there is a lint error is raised for the above code, the author of `C` should either removes `override`:

``` scala
trait A {
  def f: String
}

trait C extends A {
  // The purpose is implementing A.f
  val f = "C"
}
```

or add the missing call to super class:

``` scala
trait A {
  def f: String
}

trait C extends A {
  // The purpose is transforming A.f
  abstract override val f = s"${super.f}/C"
}
```

**Comment by lrytz** [comment]
I added a comment here: https://github.com/scala/bug/issues/12715#issuecomment-1385432177
