### ISSUE TITLE
Compiler crashes when a type constructor is applied to a repeated named type argument

### ISSUE THREAD

**Issue by ALPHA-60** [lampepfl/dotty#1679]
Code:

```scala
class A[type T]
object o {
   val x: A[T=Int, T=Int] = ???
}
```
Output:

```
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),A) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class A), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T)
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),A) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class A), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T)

exception occurred while compiling test.s
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:455)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:456)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:512)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:450)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.core.TypeApplications$.appliedTo$extension0(TypeApplications.scala:450)
	at dotty.tools.dotc.typer.Checking$$anon$2.checkValidIfHKApply$1(Checking.scala:98)
	at dotty.tools.dotc.typer.Checking$$anon$2.traverse(Checking.scala:99)
	at dotty.tools.dotc.transform.PostTyper.dotty$tools$dotc$transform$PostTyper$$normalizeTree(PostTyper.scala:109)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:202)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1136)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:265)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.dotty$tools$dotc$transform$MacroTransform$Transformer$$transformStat$1(MacroTransform.scala:43)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:52)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:68)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$super$transform(PostTyper.scala:234)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:234)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:234)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:408)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:233)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1142)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:262)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1159)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1159)
	at scala.collection.immutable.List.loop$1(List.scala:173)
	at scala.collection.immutable.List.mapConserve(List.scala:189)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1159)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1157)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1148)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:292)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:22)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:276)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:274)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:274)
	at dotty.tools.dotc.transform.MacroTransform.runOn(MacroTransform.scala:16)
<snipped>
```

Probably related to #1680.

**Comment by ALPHA-60** [comment]
Code:

```
class A[type T]
object o {
   val x: A[T=Int, T=Int] = ???
}
```
Output:

```
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),A) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class A), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T)
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),A) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class A), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T)

exception occurred while compiling test.s
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:455)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:456)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:512)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:450)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.core.TypeApplications$.appliedTo$extension0(TypeApplications.scala:450)
	at dotty.tools.dotc.typer.Checking$$anon$2.checkValidIfHKApply$1(Checking.scala:98)
	at dotty.tools.dotc.typer.Checking$$anon$2.traverse(Checking.scala:99)
	at dotty.tools.dotc.transform.PostTyper.dotty$tools$dotc$transform$PostTyper$$normalizeTree(PostTyper.scala:109)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:202)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1136)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:265)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.dotty$tools$dotc$transform$MacroTransform$Transformer$$transformStat$1(MacroTransform.scala:43)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:52)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:68)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$super$transform(PostTyper.scala:234)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:234)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:234)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:408)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:233)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1142)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:262)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1159)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1159)
	at scala.collection.immutable.List.loop$1(List.scala:173)
	at scala.collection.immutable.List.mapConserve(List.scala:189)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1159)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1157)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1148)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:292)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:22)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:276)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:274)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:274)
	at dotty.tools.dotc.transform.MacroTransform.runOn(MacroTransform.scala:16)
<snipped>
```

Probably related to #1680.

**Comment by liufengyun** [comment]
Report confirmed, thanks @ALPHA-60 !

**Comment by odersky** [comment]
Named type parameters are currently only partially supported. We need to clarify their status before proceeding here.
