### ISSUE TITLE
Compiler crashes when a type constructor is applied to named type argument of its superclass

### ISSUE THREAD

**Issue by ALPHA-60** [lampepfl/dotty#1680]
Code:

```scala
class A[type T1]
class B[type T2] extends A
object o {
  def m: B[T1=Int, T2=Int] = ???
}
```

Output:

```
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),B) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class B), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T2)
applied type mismatch: TypeRef(ThisType(TypeRef(NoPrefix,<empty>)),B) with underlying ClassInfo(ThisType(TypeRef(NoPrefix,<empty>)), class B), args = List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int)), typeParams = List(type T2)

exception occurred while compiling ./test.s
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:455)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.matchParams$1(TypeApplications.scala:456)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:512)
	at dotty.tools.dotc.core.TypeApplications$$anonfun$appliedTo$extension0$1.apply(TypeApplications.scala:450)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.core.TypeApplications$.appliedTo$extension0(TypeApplications.scala:450)
	at dotty.tools.dotc.typer.Checking$.checkValidIfHKApply$1(Checking.scala:93)
	at dotty.tools.dotc.typer.Checking$.checkAppliedType(Checking.scala:94)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:252)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1147)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$super$transform(PostTyper.scala:217)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$4.apply(PostTyper.scala:222)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$4.apply(PostTyper.scala:222)
	at dotty.tools.dotc.transform.SuperAccessors.wrapDefDef(SuperAccessors.scala:423)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:222)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.dotty$tools$dotc$transform$MacroTransform$Transformer$$transformStat$1(MacroTransform.scala:43)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:52)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:68)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$super$transform(PostTyper.scala:217)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:217)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$3.apply(PostTyper.scala:217)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:408)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:216)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1149)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:242)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1166)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1166)
	at scala.collection.immutable.List.loop$1(List.scala:173)
	at scala.collection.immutable.List.mapConserve(List.scala:189)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1166)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1164)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1155)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:278)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:22)
<snipped>
```

The T1 parameter is found in `ntparams` in `TypeAssigner.assignType` overloaded for [`AppliedTypeTree`](https://github.com/lampepfl/dotty/blob/63f1a3c5d0149d173eb8f65405b5983591752229/src/dotty/tools/dotc/typer/TypeAssigner.scala#L438)

@smarter mentioned in Gitter chat that "maybe we should disallow extending a class without specifying its type parameters".

**Comment by liufengyun** [comment]
@ALPHA-60 thanks for reporting.

I agree with @smarter that we should **disallow extending a class without specifying its type parameters**. WDYT @odersky ?

**Comment by ALPHA-60** [comment]
@smarter mentioned that extending a class without specified type parameters is equivalent to specifying them as their lower bounds. These both work in Scala:

```
class A[T >: Int](x:T); class B(x:Int) extends A(x)
```

and

```
class  A {type T >: Int}; class B extends A {val x:T=10}
```

I haven't looked into DOT calculus, so I don't know if there's a theoretical basis for disallowing these.

**Comment by odersky** [comment]
Awaiting named params spec

**Comment by smarter** [comment]
named type parameters on classes were removed a while ago.
