### ISSUE TITLE
Pickler crash when binding typed pattern to name

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#16843]
## Compiler version

3.3.1-RC1-bin-20230204-a356581-NIGHTLY nad before

## Minimized code

```scala
import scala.quoted.*

case class Foo(x: Int)

inline def foo = ${ fooImpl }

def fooImpl(using Quotes) = 
  val tmp = '{
    1 match
      case x @ (y: Int) => 0
  }

  '{}
```

```scala
val x = foo
```

## Output (click arrow to expand)
<details>

```scala
error] ./MacroTest.scala:1:9: Exception occurred while executing macro expansion.
[error] java.lang.AssertionError: assertion failed: no symbol at Addr(13)
[error]         at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.search$1(TreeUnpickler.scala:1623)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.search$1(TreeUnpickler.scala:1629)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.findOwner(TreeUnpickler.scala:1638)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.symbolAt(TreeUnpickler.scala:268)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readSymRef(TreeUnpickler.scala:261)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readSimpleType$1(TreeUnpickler.scala:423)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:464)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1387)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCase(TreeUnpickler.scala:1502)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCases$$anonfun$2(TreeUnpickler.scala:1493)
[error]         at dotty.tools.tasty.TastyReader.collectWhile(TastyReader.scala:137)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCases(TreeUnpickler.scala:1494)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1337)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1314)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1166)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:113)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.computeRootTrees(DottyUnpickler.scala:62)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees(tpd.scala:1287)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees$(tpd.scala:1276)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.rootTrees(DottyUnpickler.scala:44)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.tree(tpd.scala:1291)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.tree$(tpd.scala:1276)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.tree(DottyUnpickler.scala:44)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:274)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:84)
[error]         at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3084)
[error]         at Macro$package$.fooImpl(Macro.scala:8)
[error] 
[error] val x = foo
[error]         ^^^
```
</details>

**Comment by nicolasstucki** [comment]
The tasty we generate for this quote is

```
Names:
   0: ASTs
   1: Int
   2: scala
   3: x
   4: y
   5: _
   6: Macro_1$package
   7: Macro_1$package[ModuleClass]
   8: <empty>
   9: Positions
  10: tests/pos-macros/i16843/Macro_1.scala

Trees:
start = Addr(0), base = 173, current = Addr(0), end = Addr(47)
47 bytes of AST, base = Addr(0)

     0: INLINED(45)
     2:   MATCH(36)
     4:     TYPED(8)
     6:       INTconst 1
     8:       IDENTtpt 1 [Int]
    10:         TYPEREF 1 [Int]
    12:           TERMREFpkg 2 [scala]
    14:     CASEDEF(24)
    16:       BIND(18) 3 [x]
    19:         TERMREFdirect 21
    21:         BIND(13) 4 [y]
    24:           SHAREDtype 10
    26:           TYPED(8)
    28:             IDENT 5 [_]
    30:               SHAREDtype 10
    32:             IDENTtpt 1 [Int]
    34:               SHAREDtype 10
    36:       BLOCK(2)
    38:         INTconst 0
    40:   IDENTtpt 7 [Macro_1$package[ModuleClass]]
    42:     TYPEREF 7 [Macro_1$package[ModuleClass]]
    44:       THIS
    45:         TYPEREFpkg 8 [<empty>]
    47:

 61 position bytes:
   lines: 11
   line sizes: 21, 0, 34, 0, 38, 4, 18, 28, 3, 0, 0
   positions:
         0: 100 .. 154
         2: 107 .. 150
         6: 108 .. 109
         8: 111 .. 114
        14: 128 .. 150
        16: 133 .. 145
        21: 138 .. 144
        28: 141 .. 141
        32: 141 .. 144
        36: 146 .. 150
        38: 149 .. 150
        40: 100 .. 154
```

It seems that the failure occurs when reading 
```
    19:         TERMREFdirect 21
    21:         BIND(13) 4 [y]
```

where the symbol in 21 is not found when reading 19.
