### ISSUE TITLE
Scaladoc fails to run on code using the new MacroAnnotation

### ISSUE THREAD

**Issue by alexarchambault** [lampepfl/dotty#16875]
## Compiler version

`3.3.0-RC2`

## Minimized code

See [this repository](https://github.com/alexarchambault/dotty-macro-annotation-scaladoc-issue), that basically re-uses the test case from [here](https://github.com/lampepfl/dotty/tree/3d251d6fd1bb1e98d66760ee50b824861a87ca57/tests/run-macros/annot-simple-fib), and runs scaladoc on it.

## Output

```text
-- Error: memoize.scala:26:10 --------------------------------------------------
26 |            else
   |          ^
   |          an identifier expected, but $XMLSTART$< found
-- Error: memoize.scala:32:26 --------------------------------------------------
32 |        List(cacheVal, newFib)
   |                          ^
   |                          Not found: type MacroAnnotation
2 errors found
Following generated file paths might not be compatible with Jekyll:
_empty_/Test
_empty_/Bar
_empty_/memoize
If using GitHub Pages consider adding a ".nojekyll" file.
```

(see README of the reproduction repository above for the full command running scaladoc here)

## Expectation

Scaladoc generation succeeds.

**Comment by som-snytt** [comment]
I was able to maximize the diagnostics.
```
➜  snips scala-cli doc --server=false -S 3.8.0-RC5 -Vprint:ty -f i16875.scala
[[syntax trees at end of                     typer]] // /home/amarki/snips/i16875.scala
package <empty> {
  import scala.annotation.{experimental, MacroAnnotation}
  import scala.quoted.*
  @experimental class memoize() extends scala.annotation.Annotation(),
    scala.annotation.MacroAnnotation {
    def transform(using x$1: scala.quoted.Quotes)(tree: x$1.reflect.Definition,
      companion: Option[x$1.reflect.Definition]): List[x$1.reflect.Definition]
       = ???
  }
}

Skipping unused scalacOptions: -Vprint
Option -classpath was updated
-- Error: i16875.scala:36:0 ----------------------------------------------------
36 |
   |^
   |an identifier expected, but $XMLSTART$< found
-- Error: i16875.scala:45:12 ---------------------------------------------------
45 |
   |            ^
   |            Not found: type MacroAnnotation
-- Warning: i16875.scala:6:6 ---------------------------------------------------
6 |  def transform(using Quotes)(tree: quotes.reflect.Definition, companion: Option[quotes.reflect.Definition]): List[quotes.reflect.Definition] = ???
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |java.lang.ArrayIndexOutOfBoundsException: Index 59 out of bounds for length 46
  |     at dotty.tools.dotc.util.SourceFile.lineToOffset(SourceFile.scala:193)
  |     at dotty.tools.scaladoc.snippets.SnippetCompiler.$anonfun$3(SnippetCompiler.scala:67)
  |     at scala.collection.immutable.List.map(List.scala:240)
  |     at scala.collection.immutable.List.map(List.scala:238)
2 warnings found
2 errors found
[error]  Scaladoc generation failed (exit code: 1)
```
with trailing whitespace.
```
import scala.annotation.{experimental, MacroAnnotation}
import scala.quoted._

@experimental
class memoize extends MacroAnnotation {
  def transform(using Quotes)(tree: quotes.reflect.Definition, companion: Option[quotes.reflect.Definition]): List[quotes.reflect.Definition] = ???





































}
```
I did not investigate. The whitespace can trail the RBRACE.
