### ISSUE TITLE
 java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by pshirshov** [lampepfl/dotty#16881]
It seems like the compiler might produce incorrect bytecode in some cases which leads to really cryptic stacktraces in run time.

This only reproduces on [Microsoft JVM](https://www.microsoft.com/openjdk) 17, 11 works just fine. I haven't tested on other vendor's JDKs.

I don't have an isolated repro yet.

The build log: https://github.com/7mind/izumi/actions/runs/4145278506/jobs/7169427138#step:3:34787
A commit where the failure reproduces: https://github.com/7mind/izumi/commit/9d3aacbab6e669bf681a9c3199073b25c463b0ca , the commit itself is irrelevant, the issue manifested before.

```
Error:  java.lang.VerifyError: Bad type on operand stack
Error:  Exception Details:
Error:    Location:
Error:      izumi/functional/lifecycle/Lifecycle$LiftF.<init>(Lscala/Function0;Lizumi/functional/quasi/QuasiApplicative;)V @25: invokedynamic
Error:    Reason:
Error:      Type uninitializedThis (current frame, stack[1]) is not assignable to 'izumi/functional/lifecycle/Lifecycle$LiftF'
Error:    Current Frame:
Error:      bci: @25
Error:      flags: { flagThisUninit }
Error:      locals: { uninitializedThis, 'scala/Function0', 'izumi/functional/quasi/QuasiApplicative' }
Error:      stack: { uninitializedThis, uninitializedThis, 'scala/Function0' }
Error:    Bytecode:
Error:      0000000: b200 2711 0f55 1229 b600 2db2 0027 110f
Error:      0000010: 5412 29b6 002d 2a2a 2bba 0040 0000 032c
Error:      0000020: b700 42b1                              
Error:  
Error:  	at izumi.functional.lifecycle.Lifecycle$.liftF(Lifecycle.scala:313)
Error:  	at izumi.distage.model.Injector.produceCustomF(Injector.scala:230)
Error:  	at izumi.distage.model.Injector.produceCustomF$(Injector.scala:22)
Error:  	at izumi.distage.InjectorDefaultImpl.produceCustomF(InjectorDefaultImpl.scala:22)
Error:  	at izumi.distage.model.Injector.produce(Injector.scala:190)
Error:  	at izumi.distage.model.Injector.produce$(Injector.scala:22)
Error:  	at izumi.distage.InjectorDefaultImpl.produce(InjectorDefaultImpl.scala:22)
```

**Comment by smarter** [comment]
I tried switching to 3.2.1 but the compiler crashed when compiling distage-core-api, so it never got to running the failing test I saw with 3.2.2

**Comment by smarter** [comment]
`LiftF` has a secondary constructor which constructs a lambda:
https://github.com/7mind/izumi/blob/9d3aacbab6e669bf681a9c3199073b25c463b0ca/fundamentals/fundamentals-bio/src/main/scala/izumi/functional/lifecycle/Lifecycle.scala#L669

When code coverage is disabled, the [HoistSuperArgs](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/HoistSuperArgs.scala) phase of the compiler recognizes that this is a construct that isn't allowed in a secondary constructor and moves it into into a separate static method. 

But when code coverage is enabled (which adds some calls to `Invoker.invoked(...)` into the constructor), this phase no longer detects the problem which leads to invalid bytecode being generated.

It seems that HoistSuperArgs assumes that the first statement in a constructor is always the super-call, which isn't the case when code coverage is enabled, e.g.:
https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/HoistSuperArgs.scala#L213

/cc @TheElectronWill, do you think you could have a look at that?

**Comment by pshirshov** [comment]
Thanks for the explanation. My bad, I forgot about code coverage :)

**Comment by TheElectronWill** [comment]
I'll finally have time to take a look :smile:
I wonder if it would be simpler to move `InstrumentCoverage` later in the compilation pipeline, to avoid issues like this that potentially require tweaking the coverage with many conditions that depends on the implementation of later phases :thinking:

**Comment by smarter** [comment]
> I wonder if it would be simpler to move InstrumentCoverage later in the compilation pipeline

That could make sense yes, I think the only issue is that it means we could potentially generate a lot more instrumentation calls for synthetic nodes that don't show up in the coverage report, I see there's already logic to avoid instrumenting trees when `span.isZeroExtent` so that might not be too bad in practice?

**Comment by TheElectronWill** [comment]
Synthetic nodes are (should) always be marked with the `Synthetic` flags, aren't they?

**Comment by sjrd** [comment]
Tree nodes do not have flags. Only definitions (symbols) have.

**Comment by TheElectronWill** [comment]
Oh, right! Sorry ^^ I'll check the span, then.
