### ISSUE TITLE
crash on compilable code: assertion failed: Cannot create ClassBType for phantom type Lscala/Null

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1688]
scalac compiles but dotc crashes.

$ cat abc.scala
```
package scala
sealed trait Null
```

$ dotc abc.scala
```
java.lang.AssertionError: assertion failed: Cannot create ClassBType for phantom type Lscala/Null;
	at scala.Predef$.assert(Predef.scala:165)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.checkInfoConsistency(BTypes.scala:620)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.info_$eq(BTypes.scala:607)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.scala$tools$nsc$backend$jvm$BTypesFromSymbols$$setClassInfo(BTypesFromSymbols.scala:142)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:63)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:57)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:57)
	at scala.tools.nsc.backend.jvm.BCodeHelpers$BCInnerClassGen$class.getClassBTypeAndRegisterInnerClass(BCodeHelpers.scala:243)
<snipped>
```

**Comment by felixmulder** [comment]
@helloqirun - thanks, confirmed as bug which crashes the shared backend

**Comment by DarkDimius** [comment]
Note that this source code tries to redefine a synthetic class in `scala` package. I wouldn't consider this a bug but I agree that the error message should be prettier.
