### ISSUE TITLE
Enabling coverage breaks `synchronized` blocks

### ISSUE THREAD

**Issue by mohe2015** [lampepfl/dotty#16940]
## Compiler version

3.2.2

## Minimized code

https://github.com/mohe2015/coverage-synchronized-bug

`scala -coverage-out coverage src/main/scala/Main.scala`

```Scala
import concurrent.ExecutionContext.Implicits.global
import scala.concurrent.*
import scala.concurrent.duration.*

var test = 0

def brokenSynchronizedBlock(option: Boolean): Future[Unit] = Future {
  if (option) {
    Thread.sleep(500)
  }
  synchronized {
    val tmp = test
    Thread.sleep(1000)
    test = tmp + 1
  }
}

@main def main: Unit = {
  Await.result(Future.sequence(Seq(brokenSynchronizedBlock(false), brokenSynchronizedBlock(true))).map(result => {
    println(test)
    assert(test == 2)
  }), 3.seconds)
}
```

## Output

```
1
java.util.concurrent.ExecutionException: Boxed Exception
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
        at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:444)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:506)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.AssertionError: assertion failed
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
        at Main$package$.$anonfun$1(Main.scala:21)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        ... 6 more
```

## Expectation

```
2
```

**Comment by Martomate** [comment]
I have a similar problem. I get an `IllegalMonitorStateException` when running this code with `sbt coverage test`.

```scala
val lockedFiles: mutable.Set[String] = mutable.Set.empty
val path = "file.txt"

def submit() =
  lockedFiles.synchronized {
    while lockedFiles.contains(path) do lockedFiles.wait()
    lockedFiles += path
  }
  // do stuff
```

Looking at the bytecode it seems to represent something more like this:

```scala
val lockedFiles: mutable.Set[String] = mutable.Set.empty
val path = "file.txt"

def submit() =
  while lockedFiles.contains(path) do lockedFiles.wait()
  lockedFiles += path

  lockedFiles.synchronized {}
  // do stuff
```

The synchronized block has been moved to the end!

I use Scala 3.3.0, but have checked that it's also broken on 3.3.1-RC4.

**Comment by KacperFKorban** [comment]
fixed in https://github.com/lampepfl/dotty/pull/16941
