### ISSUE TITLE
crash on compilable code: at dotty.tools.dotc.core.Denotations$SingleDenotation

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1704]
scalac compiles but dotc crashes.

Maybe it's related to issue #605, because it does not crash when I turn on ```-Ystop-after:pickler```.

$ cat abc.scala
```
trait AnyRef {
  val StringMatch = new AnyRef {}
  trait Something { (AnyRef) match { case (StringMatch) => } }
}
```

$ dotc abc.scala
```
exception occurred while compiling abc.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:767)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1436)
	at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1420)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1408)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:237)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:148)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:913)
	at dotty.tools.dotc.ast.tpd$EnclosingMethodTraverser.apply(tpd.scala:909)
<snipped>
```

**Comment by liufengyun** [comment]
Thanks for reporting, @helloqirun .

Compiling with `-Ycheck:all` shows that both scalac and dotc throw exceptions after `mixin`.

**Comment by odersky** [comment]
I verified that this is fixed in master.
