### ISSUE TITLE
crash on compilable code:at dotty.tools.dotc.core.Contexts$FreshContext.setOwner

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1708]
scalac can compile it but dotc crashes.

$ cat abc.scala
```
package foo { trait identifier }
package foo { package identifier {} }
```

$ dotc abc.scala
```
exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at dotty.tools.dotc.core.Contexts$FreshContext.setOwner(Contexts.scala:451)
	at dotty.tools.dotc.core.Contexts$Context.superOrThisCallContext(Contexts.scala:359)
	at dotty.tools.dotc.core.Contexts$Context.superCallContext(Contexts.scala:337)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1200)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1198)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1198)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1434)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1482)
<snipped>
```

**Comment by liufengyun** [comment]
Thanks @helloqirun , report confirmed.

Note that, following code compiles (no crash):

```Scala
package foo { trait identifier }
package foo { class B }
package foo { package C {} }
```
```Scala
package foo { trait identifier }
package foo { class identifier }
```

The problem is related to the duplicate name between a trait and package.
