### ISSUE TITLE
Runtime java.lang.AbstractMethodError when combining opaque type erasure, value class erasure, and generic type erasure

### ISSUE THREAD

**Issue by dzanot** [lampepfl/dotty#17281]
## Compiler version

3.2.2

## Minimized code

https://scastie.scala-lang.org/unEBGxDySmuG89C934iOfw

## Output
```
Hello
withoutBaz
java.lang.AbstractMethodError: Receiver class Main$$anon$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object withBaz(int, java.lang.String, long)' of interface InnerThing.
	at OuterThingImpl.maybeBaz$$anonfun$2(main.scala:17)
	at OuterThingImpl.maybeBaz$$anonfun$adapted$1(main.scala:17)
	at scala.Option.fold(Option.scala:263)
	at OuterThingImpl.maybeBaz(main.scala:17)
	at Main$.$init$$$anonfun$2(main.scala:33)
	at cats.effect.IO.$greater$greater$$anonfun$1(IO.scala:143)
	at cats.effect.IOFiber.succeeded(IOFiber.scala:1177)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:966)
	at cats.effect.IOFiber.execR(IOFiber.scala:1324)
	at cats.effect.IOFiber.run(IOFiber.scala:118)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:555)
```
## Expectation

No `AbstractMethodError`. This works as expected if you do any one of:
- drop the `extends AnyVal`: https://scastie.scala-lang.org/zwJDsakKR9Gay9W8IW8GoQ
- don't have `F[_]` parameter: https://scastie.scala-lang.org/rbzCBBe9T92uGrFdqU7UUQ
- eliminate the opaque type: https://scastie.scala-lang.org/B8OTm0PRSvilc7SqayVyfg

**Comment by dzanot** [comment]
Here is a zero dependency repro: https://scastie.scala-lang.org/qKxuNuqCSTStwGErK1UdWw

**Comment by dzanot** [comment]
@nicolasstucki does this need more information?

**Comment by dzanot** [comment]
Tested with `3.3.0` release, updated the repro

**Comment by sjrd** [comment]
Further minimization:
```scala
type IO[T] = T

opaque type NonNegLong = Long

object NonNegLong {
  def apply(l: Long): NonNegLong = l
}

class Baz(value: NonNegLong) extends AnyVal

trait InnerThing[F[_]] {
  def withBaz(baz: Baz): F[Unit]
}

class InnerThingImpl extends InnerThing[IO] {
  override def withBaz(baz: Baz): IO[Unit] = println("withBaz")
}

object Test {
  def main(args: Array[String]): Unit = {
    val testInnerImpl: InnerThing[IO] = new InnerThingImpl

    println("Hello")
    val nnl = new Baz(NonNegLong(1L))
    testInnerImpl.withBaz(nnl)
    println("Goodbye")
  }
}
```
* Replacing `F[Unit]` by `Any` and `IO[Unit]` by `Unit` makes it work.
* Removing the explicit type `: InnerThing[IO]` makes it work (because `InnerThingImpl` gets inferred and therefore we directly call its more specific `withBaz`).
* Making `NonNegLong` a non-opaque type alias makes it work.
* Making `Baz` a non-`AnyVal` makes it work.
