### ISSUE TITLE
FromSymbol.definitionFromSym bug

### ISSUE THREAD

**Issue by nau** [lampepfl/dotty#17283]
## Compiler version

Scala 3

## Output

I get this 
```
Exception occurred while executing macro expansion.
[error]     |scala.MatchError: DefDef(given_FromData ...
...
at dotty.tools.dotc.quoted.reflect.FromSymbol$.valDefFromSym(FromSymbol.scala:50)
[error]     |   at dotty.tools.dotc.quoted.reflect.FromSymbol$.definitionFromSym(FromSymbol.scala:22)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2528)
[error]     |   at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2528)
```

where
```scala
given FromData[...] = (d: Data) => {...}
```

Looks like this code is not correct:

```scala
def definitionFromSym(sym: Symbol)(using Context): tpd.Tree = {
    assert(sym.exists, "Cannot get tree of no symbol")
    assert(!sym.is(Package), "Cannot get tree of package symbol")
    if (sym.isClass) classDef(sym.asClass)
    else if (sym.isType && sym.is(Case)) typeBindFromSym(sym.asType)
    else if (sym.isType) typeDefFromSym(sym.asType)
    else if (sym.is(Method)) defDefFromSym(sym.asTerm)
    else if (sym.is(Case, butNot = ModuleVal | EnumVal)) bindFromSym(sym.asTerm)
    else valDefFromSym(sym.asTerm)
  }
```

I assume it probably should be this instead, but I'm not sure
```scala
else if (sym.isOneOf(GivenMethod)) defDefFromSym(sym.asTerm)
```

**Comment by nicolasstucki** [comment]
I could not reproduce the issue. I tried with:
```scala
// tests/run-macros/i17283/Macro_1.scala
import scala.quoted.*

inline def trees[T] =
  ${ treesImpl[T] }

def treesImpl[T](using Quotes, Type[T]) =
  import quotes.reflect.*
  val trees =
    TypeRepr.of[T].typeSymbol.declarations
      .map(_.tree.show)
      .mkString("\n")
  println(trees)
  Expr(trees)
```
```scala
// tests/run-macros/i17283/Defs_1.scala
trait A:
  def apply(x: Int): Int
trait B[T]:
  def apply(x: T): T
class C:
  given a: Int = 1
  given b(using x: Int): Int = 1
  given c[T]: Int = 1
  given d[T](using x: T): Int = 1
  given A with { def apply(x: Int): Int = 1 }
  given B[Int] = (x: Int) => x
  given [U]: B[U] = (x: U) => x
```
```scala
@main def Test =
  println(trees[C])
```

**Comment by nicolasstucki** [comment]
Not all givens are defs, `sym.isOneOf(GivenMethod)` would not be correct. The question is what did a symbol that does not have `method` contained (internally i the compiler API) a `tree` that is a `DefDef`.

**Comment by nau** [comment]
`e.symbol.flags.show` gives `flats: Flags.Final | Flags.Given | Flags.Lazy`

**Comment by nau** [comment]
Ah, and also it's a top level given.
```scala
given Data.FromData[...] = (d: Data) => {}
```

**Comment by nau** [comment]
I changed it to `implicit def fromData(d: Data) = {}` and it worked, but it's definitely a bug.

**Comment by nicolasstucki** [comment]
What is in the `[...]`?

**Comment by nau** [comment]
`type FromData[A] = Data => A`
`given FromData[BigInt] = (d: Data) => BigInt(1)`
