### ISSUE TITLE
unhelpful error message when overloading apply without return type

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1731]
`dotty`:
```scala
scala> case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) } 
-- Error: <console> ----------------------------------------------------------------------
6 |case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
  |                                                       ^^^
  |                                                       object Foo does not take parameters
```

The solution is to write `def apply[T](): Foo[T]` but good luck figuring that out from our error message, contrast with `scalac`:
```scala
scala> case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
<console>:15: error: overloaded method apply needs result type
       case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
                                                                 ^
```

**Comment by bbarker** [comment]
I have a tentative fix for this, should have something up to review in the next couple of days.

**Comment by bbarker** [comment]
Just trying to wrap this up by adding a new test like this:

```scala
    checkMessagesAfter("frontend") {
      """
        |case class Foo[T](x: T)
        |object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
      """.stripMargin
    }.expect { (ictx, messages) =>
      implicit val ctx: Context = ictx

      assertMessageCount(1, messages)
      val OverloadedOrRecursiveMethodNeedsResultType(treeName2) :: Nil = messages
      assertEquals("Foo", treeName2)
    }
```

This results in:

```
error] Test dotty.tools.dotc.reporting.ErrorMessagesTests.overloadedMethodNeedsReturnType failed: java.lang.AssertionError: assertion failed: denotation module _root_ invalid in run 2. ValidFor: Period(1..2, run = 3), took 0.024 sec
[error]     at scala.Predef$.assert(Predef.scala:170)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:727)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:783)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:406)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.isType(Symbols.scala:429)
[error]     at dotty.tools.dotc.core.Scopes$MutableScope.enter(Scopes.scala:270)
[error]     at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:134)
[error]     at dotty.tools.DottyTest$class.checkCompile(DottyTest.scala:60)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.checkCompile(ErrorMessagesTests.scala:12)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTest$class.checkMessagesAfter(ErrorMessagesTest.scala:60)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.checkMessagesAfter(ErrorMessagesTests.scala:12)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.overloadedMethodNeedsReturnType(ErrorMessagesTests.scala:219)
```

I assume I'm doing something incorrect with which phase I'm picking, but having tried a few with no change of results (other than the phase apparently not being supported), wanted to check here for any insight.

**Comment by smarter** [comment]
No clue, /cc @felixmulder who wrote `checkMessagesAfter`. You can submit your PR with the test disabled until this is fixed.

**Comment by felixmulder** [comment]
Looking into it for @bbarker's PR, I think the assertion is run using the wrong context.

**Comment by felixmulder** [comment]
Nope, it works fine to run the commented out `checkMessagesAfter`

**Comment by smarter** [comment]
The original example in #1731 now shows:
```scala
overloaded or recursive method Foo needs return type
```
But this is incorrect, `Foo` is a class, not a method, the method is called `apply`.

**Comment by allanrenucci** [comment]
The PR was reverted
