### ISSUE TITLE
AbstractMethodError on break.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1732]
```scala
object Test {
  import scala.util.control.Breaks
  def main(args: Array[String]): Unit = {
    Breaks.breakable {
      Breaks.break
    }
  }
}
```

```
Exception in thread "main" java.lang.AbstractMethodError: Test$$$Lambda$1/1018081122.apply$mcV$sp()V
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at Test$.main(Test.scala:6)
	at Test.main(Test.scala)
```

**Comment by odersky** [comment]
I would think this should be higher priority?

**Comment by nicolasstucki** [comment]
Note that this only happens if the break is an expression inside the breakable. I don't remember right now if it also fails in inner expressions.
I also did not try to call the break without a breakable.

**Comment by odersky** [comment]
In fact, the reason for the breakage is that the anonymous function passed to `breakable` has a `Nothing` result type. Here's the code after flatten:

    package <empty> {
      final lazy module val Test: Test$ = new Test$()
      @scala.annotation.internal.SourceFile("i1732.scala") final module class Test$
         extends
       Object { 
        def <init>(): Unit = 
          {
            super()
            ()
          }
        def main(args: String[]): Unit = 
          {
            util.control.Breaks.breakable(
              {
                closure(Test.$anonfun:Function0)
              }
            )
          }
        private def $anonfun(): Nothing = 
          {
            util.control.Breaks.break()
          }
      }
    }

If I insert a () after `break` it works OK. @DarkDimius, where are we supposed to handle `Nothing` types? Is that in the backend or before?

**Comment by DarkDimius** [comment]
@odersky, I think the best place would be FunctionalInterfaces. It already has special logic in handling closures returning Unit, and it should be used here.

**Comment by odersky** [comment]
@DarkDimius But we need to also map all other uses of Nothing and Null, not just return types of closures. Is that done already? If yes, where?

**Comment by odersky** [comment]
It looks like this is a deeper problem. FunctionalInterfaces as it is set up can't handle this. The closure has type ()Nothing, so is not specialized. But the expected type of breakable is ()Unit, which demands specialization. Problem is, FunctionalInterfaces, can't see the expected type. Only Typer and Erasure can, but one is too early and the other too late.

**Comment by odersky** [comment]
In the end it was something completely different. It turns out normal closures are already handled correctly, because the typer propagates the expected type. The problem was restricted to by-name args, and could be fixed by a change to ElimByName.
