### ISSUE TITLE
Line number off-by-1 in stack trace

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#17425]
## Compiler version

`3.3.1-RC1-bin-20230504-0e00420-NIGHTLY`

## Minimized code

```Scala
package com.example

object Bar {

  def void(): Unit =
    throw new Exception

  def main(args: Array[String]): Unit = {
    this
      .void() // this is line 10
  }
}
```

## Output

```scala
Exception in thread "main" java.lang.Exception
        at com.example.Bar$.void(test.scala:6)
        at com.example.Bar$.main(test.scala:9)
        at com.example.Bar.main(test.scala)
```

## Expectation

`at com.example.Bar$.main(test.scala:9)` would ideally be `at com.example.Bar$.main(test.scala:10)`, right?

**Comment by som-snytt** [comment]
Same backend behavior in Scala 2.

It's not off-by-one, but the whole tree gets the same line number.

```
thing
  .self
  .bomb()
```

**Comment by armanbilge** [comment]
> but the whole tree gets the same line number.

What is the "whole tree"? For example consider:

```scala
package com.example

object Bar {

  def self(x: Any): Bar.type =
    this

  def void(): Unit =
    throw new Exception

  def main(args: Array[String]): Unit = {
    this
      .self((x: Int) => x)
      .void() // this is line 14
  }
}
```

```
Exception in thread "main" java.lang.Exception
        at com.example.Bar$.void(test.scala:9)
        at com.example.Bar$.main(test.scala:13)
        at com.example.Bar.main(test.scala)
```

Why is the line number 13 and not 14 or 12?

**Comment by som-snytt** [comment]
Loading any arg persuades it to emit a line, apparently. By whole tree, I meant the `this.x.y` application. I confirmed that `javac` does the obvious thing (complete line info).
