### ISSUE TITLE
crash on compilable code: cyclic reference involving class Visitor

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1750]
scalac can compile but dotc crashes.

$ cat abc.scala
```
trait Lang1 {
  trait Exp
  trait Visitor { def f(left: Exp): Unit }
  class Eval1 extends Visitor { self =>
    def f(left: Exp) = ()
  }
}
trait Lang2 extends Lang1 {
  class Visitor extends Eval1 { Visitor =>
  }
}
```

$ dotc abc.scala
```
exception while transforming () extends Lang2.this.Eval1() {} of class class dotty.tools.dotc.ast.Trees$Template # 174
exception while transforming class Visitor() extends Lang2.this.Eval1() {} of class class dotty.tools.dotc.ast.Trees$TypeDef # 175
exception while transforming () extends Object with Lang1 {
  class Visitor() extends Lang2.this.Eval1() {}
} of class class dotty.tools.dotc.ast.Trees$Template # 176
exception while transforming @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang2() extends

Object with Lang1 {
  class Visitor() extends Lang2.this.Eval1() {}
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 177
exception while transforming package <empty> {
  @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang1()
     extends
   Object {
    <trait> interface trait Exp() extends Object {}
    <trait> interface trait Visitor() extends Object {
      def f(left: Lang1.this.Exp): Unit
    }
    class Eval1() extends Object() with Lang1.this.Visitor {
      def f(left: Lang1.this.Exp): Unit = ()
    }
  }
  @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang2()
     extends
   Object with Lang1 {
    class Visitor() extends Lang2.this.Eval1() {}
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 178

exception occurred while compiling abc.scala
Exception in thread "main" dotty.tools.dotc.core.Types$CyclicReference: cyclic reference involving class Visitor
	at dotty.tools.dotc.core.Types$CyclicReference$.apply(Types.scala:3838)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$baseTypeRefOf$2.apply(SymDenotations.scala:1720)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$baseTypeRefOf$2.apply(SymDenotations.scala:1709)
	at dotty.tools.dotc.reporting.Reporting$class.conditionalTraceIndented(Reporter.scala:132)
	at dotty.tools.dotc.core.Contexts$Context.conditionalTraceIndented(Contexts.scala:57)
	at dotty.tools.dotc.reporting.Reporting$class.debugTraceIndented(Reporter.scala:127)
	at dotty.tools.dotc.core.Contexts$Context.debugTraceIndented(Contexts.scala:57)
<snipped>
```

**Comment by liufengyun** [comment]
The exception happens in the phase `RefChecks`.

**Comment by liufengyun** [comment]
I've been debugging this a little bit last night, this test case is very tricky, it doesn't appear if either:

1. we change `def f(left: Exp): Unit` to `def f(x: Int): Unit`, or
2. we rename `Visitor` to a different name in `lang2`.

The combination of `def f(left: Exp)` and duplicate class name will trigger a very deep `asSeenFrom` in ref-checking overriding of `def f`, which results in a cyclic loop in `baseTypeRefOf`. This is because  `baseTypeRefOf(lang2.this.Visitor)` will cause the parent call `baseTypeRefOf(Lang2.this.Eval1)`,  which in turn triggers the parent call `baseTypeRefOf (Lang2.this.Visitor)` again (NOT `Lang1`, because `asSeenFrom`), thus a cyclic reference is detected.

There is also a specification different from Scala here: Scalac allows overriding of `Visitor`, while Dotty disallows overriding of classes.
