### ISSUE TITLE
 Scala.js backend crashes for `final val` with literal type inside `trait`

### ISSUE THREAD

**Issue by pweisenburger** [lampepfl/dotty#17549]
## Compiler version

3.2.2, 3.3.0-RC3

## Minimized code

The following code crashes the compiler when using the Scala.js backend:

```scala
trait T:
  final val x: 1 = ???
```

Similar for this example:

```scala
trait T:
  def f(): Unit = ()
  final val x: "test" = { f(); "test" }
```

To trigger the issue, the field needs to be in a `trait`, it has to be a `final val`, the field needs a literal type and the right-hand-side needs to different from just being the literal itself (e.g., it compiles for `final val x: 1 = 1`).

## Output

```scala
dotty.tools.FatalError: Illegal tree in gen of genInterface(): private val x: Int
class = trait T extends Object {
  def <init>(): Unit = 
    {
      this.x = ???()
      ()
    }
  private val x: Int
  final def x(): Int = this.x
}
```

**Comment by sjrd** [comment]
The problem is not Scala.js-related. Scala.js is actually sort of "friendlier" than Scala/JVM, because it crashes at compile-time, whereas the JVM crashes at run-time. If we elaborate the test a little bit more to something that should run:
```scala
trait T:
  final val x: 1 =
    println("T.x")
    1
end T

trait U:
  def x: Any

class C extends T with U

object Test:
  def main(args: Array[String]): Unit =
    val c = new C
    println(c.x)

    val u: U = c
    println(u.x)
  end main
end Test
```
we get the following on the JVM:
```
Exception in thread "main" java.lang.ClassFormatError: Illegal field modifiers in class T: 0x12
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at Test$.main(i17549.scala:14)
        at Test.main(i17549.scala)
```
