### ISSUE TITLE
crash on compilable code: assertion failed: Trying to access the this of another class

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1756]
scalac can compile but dotc crashes.

$ cat abc.scala
```
class A { { val x = this } }
class B(x: Int) {
  class C(x: Int)
      extends B({
        val test = this
        x
      }) {
    def this() = {
      this({
        1
      })
    }
  }
}
```

$ dotc abc.scala
```
java.lang.AssertionError: assertion failed: Trying to access the this of another class: tree.symbol = class B, class symbol = class B$C compilation unit: abc.scala
	at scala.Predef$.assert(Predef.scala:165)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:344)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:291)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:90)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder$$anonfun$genNormalBlock$1$1.apply(BCodeBodyBuilder.scala:859)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder$$anonfun$genNormalBlock$1$1.apply(BCodeBodyBuilder.scala:859)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:861)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:893)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:409)
<snipped>
```

**Comment by liufengyun** [comment]
Thanks @helloqirun , report confirmed.

Following minimized version produce the same stack trace:

```Scala
class B(x: Int) {
  class C(x: Int) extends B({val test = this; x})
}
```

Compile with `-Ycheck:all` produce following checking exception after `lambdaLift, elimStaticThis, flatten, restoreScopes`:

```
Exception in thread "main" java.lang.AssertionError: assertion failed: error while typing this, value test is not contained in class B
	at scala.Predef$.assert(Predef.scala:165)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedThis(TreeChecker.scala:358)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1455)
```
