### ISSUE TITLE
Whitelisting scala.sys.SystemProperties crashes the compiler.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1794]
Whitelisting `scala.sys.SystemProperties` will crash the compiler when running `sbt test` and the  
errors are:
```scala
[error] Test dotty.tools.dottydoc.TestWhitelistedCollections.arrayHasDocumentation failed: java.lang.AssertionError: assertion failed, took 8.677 sec
[error]     at scala.Predef$.assert(Predef.scala:151)
[error]     at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:3091)
[error]     at dotty.tools.dotc.core.Types$TypeAlias.<init>(Types.scala:3162)
[error]     at dotty.tools.dotc.core.Types$CachedTypeAlias.<init>(Types.scala:3188)
[error]     at dotty.tools.dotc.core.Uniques$TypeAliasUniques.newAlias$1(Uniques.scala:84)
[error]     at dotty.tools.dotc.core.Uniques$TypeAliasUniques.enterIfNew(Uniques.scala:89)
[error]     at dotty.tools.dotc.core.Types$TypeAlias$.apply(Types.scala:3202)
[error]     at dotty.tools.dotc.core.Types$Type.bounds(Types.scala:1128)
[error]     at dotty.tools.dottydoc.core.DocASTPhase.dotty$tools$dottydoc$core$DocASTPhase$$membersFromSymbol$1(DocASTPhase.scala:47)
```

```scala
[error] Test dotty.tools.dottydoc.TestWhitelistedCollections.traitImmutableHasDocumentation failed: java.lang.AssertionError: assertion failed, took 6.213 sec
[error]     at scala.Predef$.assert(Predef.scala:151)
[error]     at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:3091)
[error]     at dotty.tools.dotc.core.Types$TypeAlias.<init>(Types.scala:3162)
[error]     at dotty.tools.dotc.core.Types$CachedTypeAlias.<init>(Types.scala:3188)
[error]     at dotty.tools.dotc.core.Uniques$TypeAliasUniques.newAlias$1(Uniques.scala:84)
[error]     at dotty.tools.dotc.core.Uniques$TypeAliasUniques.enterIfNew(Uniques.scala:89)
[error]     at dotty.tools.dotc.core.Types$TypeAlias$.apply(Types.scala:3202)
[error]     at dotty.tools.dotc.core.Types$Type.bounds(Types.scala:1128)
[error]     at dotty.tools.dottydoc.core.DocASTPhase.dotty$tools$dottydoc$core$DocASTPhase$$membersFromSymbol$1(DocASTPhase.scala:47)
```

**Comment by nicolasstucki** [comment]
It is the following implicit def that causes the crash:
```scala
implicit def systemPropertiesToCompanion(p: SystemProperties): SystemProperties.type = this
```

**Comment by nicolasstucki** [comment]
The issue comes from [`DocASTPhase.membersFromSymbol`](https://github.com/lampepfl/dotty/blob/master/doc-tool/src/dotty/tools/dottydoc/core/DocASTPhase.scala#L47) in the case the symbol info does not exist (`sym.info.exists`). The symbol is printed as `val <none>` and came from method `DocASTPhase.collect` in [`implicitConversions`](https://github.com/lampepfl/dotty/blob/master/doc-tool/src/dotty/tools/dottydoc/core/DocASTPhase.scala#L29).

@felixmulder Is could you look at this issue.
