### ISSUE TITLE
Capture checking can be escaped by assigning to a var

### ISSUE THREAD

**Issue by clavigne** [lampepfl/dotty#17950]
## Compiler version

3.3.1-RC1-bin-20230503-b8d2966-NIGHTLY

## Minimized code

I'm playing around with capture checking, and following along with [the reference.](https://docs.scala-lang.org/scala3/reference/experimental/cc.html#) Unless I'm using it wrong, it seems that assigning to a var trivially escapes capture checking,

```scala
import java.io.FileOutputStream
import language.experimental.captureChecking
import scala.annotation.{capability, experimental}

@experimental object Logger:
  def usingLogFile[T](op: ({*} FileOutputStream) => T): T =
    val f = new FileOutputStream("tmp")
    val out = op(f)
    f.close()
    out

@experimental object TestCase {
  def main(args: Array[String]): Unit = {
    var escape: FileOutputStream = null

    Logger.usingLogFile{ o =>
      o.write(0)
      escape = o.asInstanceOf[FileOutputStream]
    }
    escape.write(1)
  }
}
```

## Output

The above compiles but fails at runtime,

```
Exception in thread "main" java.io.IOException: Stream Closed
	at java.base/java.io.FileOutputStream.write(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:322)
	at TestCase$.main(main.scala:20)
	at TestCase.main(main.scala)

Process finished with exit code 1
```

## Expectation

A compilation error like 
```
The expression's type ... is not allowed to capture the root capability `*`.
This usually means that a capability persists longer than its allowed lifetime.
    Logger.usingLogFile{ o =>

```

**Comment by clavigne** [comment]
After playing around some more I realized that the issue is the cast through `asInstanceOf`, which can be used to cast from types with capability to those without. That's probably intended?

**Comment by dwijnand** [comment]
Yeah casting makes you break out of the rules.

**Comment by clavigne** [comment]
That makes sense. Are there plans to change that? 

One issue is that while a bad cast usually result in an exception, the captured capabilities are (AFAIK) erased at runtime such that the cast is fine... until the capability is used. This is worrying in particular if capabilities are used to enforce eg native memory access.

Maybe casting capture sets away should require a separate, scarier syntax?
