### ISSUE TITLE
`java.lang.NoClassDefFoundError` when invoking a static Java method inside Expecty macro

### ISSUE THREAD

**Issue by bplommer** [lampepfl/dotty#18046]
A `NoClassDefFoundError` is being raised at runtime when invoking a static Java method inside an [Expecty](https://github.com/eed3si9n/expecty/) assertion, but only under certain conditions - see code below.

## Compiler version

3.3.0, 3.3.2-RC1-bin-20230622-9f15be2-NIGHTLY, 3.1.0, 3.2.0

## Minimized code

**Main.scala**
```Scala
//> using dep com.eed3si9n.expecty::expecty:0.16.0

import com.eed3si9n.expecty.Expecty.assert

object Main extends App {
  assert(new JavaClass != new JavaClass)        // ok, instantiating a Java class
  assert {
    JavaClass.returnTrue()                      // any code here seems to prevent the error
    JavaClass.returnTrue()                      // ok
  }
  assert(java.time.Instant.ofEpochMilli(0L) == 
    java.time.Instant.ofEpochMilli(0L))         // ok (Java stdlib)
  assert(JavaClass.returnTrue())                // java.lang.NoClassDefFoundError: JavaClass$
}
```

**JavaClass.java**
```java
class JavaClass {
    public static boolean returnTrue() { return true; }
}
```

## Output

```
% scala-cli .                  
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
Exception in thread "main" java.lang.NoClassDefFoundError: JavaClass$
        at Main$package$.run(Main.scala:13)
        at run.main(Main.scala:5)
Caused by: java.lang.ClassNotFoundException: JavaClass$
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 2 more
```

## Expectation
The program should run to completion without raising an exception, as it does under Scala 2.

**Comment by odersky** [comment]
This looks like an error in `Expecty.assert`. So the issue should be opened there.

**Comment by bplommer** [comment]
I've opened an issue in Expecty and will try to minimise this further, but I'm not seeing how this could be an Expecty issue - shouldn't Java interop be transparent to library macros?

**Comment by odersky** [comment]
The red flag for me is `JavaClass$`. That illegal reference seems to come from the `assert`.
