### ISSUE TITLE
Two tests fail on Windows

### ISSUE THREAD

**Issue by Roldak** [lampepfl/dotty#1827]
Running `sbt partest-only-no-bootstrap run` gives the output:
```
...
[info] Test run started
CompilerTest is generating tests for partest, log: ..\tests\partest-generated\gen.log
[info] Test dotc.tests.pos_nameddefaults started
[info] Test dotc.tests.pos_tailcall started
[info] Test dotc.tests.neg_tailcall_t3275 started
[info] Test dotc.tests.neg_tailcall_t6574 started
[info] Test dotc.tests.compileIndexedSeq started
java.lang.Exception
	at dotty.tools.dotc.core.Denotations$MissingRef.<init>(Denotations.scala:1054)
	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.recur$1(Denotations.scala:1209)
	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.staticRef(Denotations.scala:1214)
	at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:542)
	at dotty.tools.dotc.core.Symbols$class.requiredPackage(Symbols.scala:341)
	at dotty.tools.dotc.core.Contexts$Context.requiredPackage(Contexts.scala:57)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageVal$lzycompute(Definitions.scala:177)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageVal(Definitions.scala:177)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageClass$lzycompute(Definitions.scala:178)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageClass(Definitions.scala:178)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:878)
	at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:584)
	at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:117)
	at dotty.tools.dotc.Compiler.newRun(Compiler.scala:143)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:25)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.CompilerTest.compileArgs(CompilerTest.scala:282)
	at dotty.tools.dotc.CompilerTest.compileLine(CompilerTest.scala:76)
	at dotc.tests.compileIndexedSeq(tests.scala:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:132)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
creating stub for scalaShadowing, owner = module class <root>#2, file = null
decls = module xsbti#3
  module class xsbti#4
  module scala#5
  module class scala#6
  module sun#7
  module class sun#8
  module com#9
  module class com#10
  module java#11
  module class java#12
  module javax#13
  module class javax#14
  module org#15
  module class org#16
  module jdk#17
  module class jdk#18
  module oracle#19
  module class oracle#20
  module netscape#21
  module class netscape#22
  module javafx#23
  module class javafx#24
  module <empty>#2027
  module class <empty>#2028
  module <special-ops>#2029
  module class <special-ops>#2030

bad symbolic reference. A signature
refers to scalaShadowing$ in package <root> which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.

one error found
[error] Test dotc.tests.compileIndexedSeq failed: java.lang.AssertionError: assertion failed: Wrong # of errors. Expected: 0, found: 1
[error] Files with expected errors: List()
[error] errors:
[error]        , took 1.235 sec
[error]     at scala.Predef$.assert(Predef.scala:165)
[error]     at dotty.tools.dotc.CompilerTest.compileArgs(CompilerTest.scala:290)
[error]     at dotty.tools.dotc.CompilerTest.compileLine(CompilerTest.scala:76)
[error]     at dotc.tests.compileIndexedSeq(tests.scala:215)
[error]     ...
[info] Test dotc.tests.pos_opassign started
[info] Test dotc.tests.tasty_runtime started
[info] Test dotc.tests.tasty_unpickleScala2 started
[info] Test dotc.tests.tasty_runtime_vc started
[info] Test dotc.tests.tasty_dotc_repl started
[info] Test dotc.tests.tasty_dotc_util started
[info] Test dotc.tests.pos_desugar started
[info] Test dotc.tests.pos_valueclasses started
[info] Test dotc.tests.neg_cli_error started
[info] Test dotc.tests.tasty_dotc_printing started
[info] Test dotc.tests.dotc_core started
[info] Test dotc.tests.dotc_util started
[info] Test dotc.tests.dotc_transform started
[info] Test dotc.tests.tasty_new_all started
[info] Test dotc.tests.neg_i1050 started
[info] Test dotc.tests.neg_i1240 started
[info] Test dotc.tests.helloWorld started
[info] Test dotc.tests.pos_templateParents started
[info] Test dotc.tests.pos_assignments started
[info] Test dotc.tests.pos_collections started
[info] Test dotc.tests.pos_overloadedAccess started
[info] Test dotc.tests.neg_typers started
[info] Test dotc.tests.neg_nopredef started
[info] Test dotc.tests.pickle_ast started
[info] Test dotc.tests.pickle_inf started
[info] Test dotc.tests.pos_blockescapes started
[info] Test dotc.tests.pos_typedapply started
[info] Test dotc.tests.pos_inferred started
[info] Test dotc.tests.labels started
[info] Test dotc.tests.dotc_core_nocheck started
[info] Test dotc.tests.pos_companions started
[info] Test dotc.tests.dotc_config started
[info] Test dotc.tests.pos_implicits1 started
[info] Test dotc.tests.tools_io started
[info] Test dotc.tests.pos_packageobject started
[info] Test dotc.tests.pos_selftypes started
[info] Test dotc.tests.java_all started
[info] Test dotc.tests.pos_erasure started
[info] Test dotc.tests.pos_arraycopy started
[info] Test dotc.tests.tasty_tools_io started
[info] Test dotc.tests.dotc_typer started
[info] Test dotc.tests.repl_all started
[info] Test dotc.tests.tasty_dotc_parsing started
[info] Test dotc.tests.pos_859 started
[info] Test dotc.tests.pos_all started
[info] Test dotc.tests.pos_functions1 started
[info] Test dotc.tests.compileStdLib started
[info] Test dotc.tests.rewrites started
[info] Test dotc.tests.pos_packageObj started
[info] Test dotc.tests.tasty_classfile started
[info] Test dotc.tests.dotc_parsing started
[info] Test dotc.tests.pos_Patterns started
[info] Test dotc.tests.neg_autoTupling started
[info] Test dotc.tests.compileMixed started
java.lang.Exception
	at dotty.tools.dotc.core.Denotations$MissingRef.<init>(Denotations.scala:1054)
	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.recur$1(Denotations.scala:1209)
	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.staticRef(Denotations.scala:1214)
	at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:542)
	at dotty.tools.dotc.core.Symbols$class.requiredPackage(Symbols.scala:341)
	at dotty.tools.dotc.core.Contexts$Context.requiredPackage(Contexts.scala:57)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageVal$lzycompute(Definitions.scala:177)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageVal(Definitions.scala:177)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageClass$lzycompute(Definitions.scala:178)
	at dotty.tools.dotc.core.Definitions.ScalaShadowingPackageClass(Definitions.scala:178)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:878)
	at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:584)
	at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:117)
	at dotty.tools.dotc.Compiler.newRun(Compiler.scala:143)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:25)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.CompilerTest.compileArgs(CompilerTest.scala:282)
	at dotty.tools.dotc.CompilerTest.compileLine(CompilerTest.scala:76)
	at dotc.tests.compileMixed(tests.scala:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:132)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
creating stub for scalaShadowing, owner = module class <root>#2, file = null
decls = module xsbti#3
  module class xsbti#4
  module scala#5
  module class scala#6
  module sun#7
  module class sun#8
  module com#9
  module class com#10
  module java#11
  module class java#12
  module javax#13
  module class javax#14
  module org#15
  module class org#16
  module jdk#17
  module class jdk#18
  module oracle#19
  module class oracle#20
  module netscape#21
  module class netscape#22
  module javafx#23
  module class javafx#24
  module <empty>#2027
  module class <empty>#2028
  module <special-ops>#2029
  module class <special-ops>#2030

bad symbolic reference. A signature
refers to scalaShadowing$ in package <root> which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.

one error found
[error] Test dotc.tests.compileMixed failed: java.lang.AssertionError: assertion failed: Wrong # of errors. Expected: 0, found: 1
[error] Files with expected errors: List()
[error] errors:
[error]        , took 0.282 sec
[error]     at scala.Predef$.assert(Predef.scala:165)
[error]     at dotty.tools.dotc.CompilerTest.compileArgs(CompilerTest.scala:290)
[error]     at dotty.tools.dotc.CompilerTest.compileLine(CompilerTest.scala:76)
[error]     at dotc.tests.compileMixed(tests.scala:207)
[error]     ...
[info] Test dotc.tests.pos_approximateUnion started
[info] Test dotc.tests.pos_overrides started
[info] Test dotc.tests.neg_tailcall2 started
[info] Test dotc.tests.neg_tailcall3 started
[info] Test dotc.tests.tasty_dotc_config started
[info] Test dotc.tests.neg_overrideClass started
[info] Test dotc.tests.testNonCyclic started
[info] Test dotc.tests.pos_extmethods started
[info] Test dotc.tests.pos_anonClassSubtyping started
[info] Test dotc.tests.pos_javaOverride started
[info] Test dotc.tests.pos_sigs started
[info] Test dotc.tests.pos_utf8 started
[info] Test dotc.tests.pos_vararg_patterns started
[info] Test dotc.tests.dotc_printing started
[info] Test dotc.tests.pos_t2168_pat started
[info] Test dotc.tests.neg_tailcall started
[info] Test dotc.tests.pos_typedIdents started
[info] Test dotc.tests.pos_t8146a started
[info] Test dotc.tests.pos_typers started
[info] Test dotc.tests.tasty_backend_jvm started
[info] Test dotc.tests.pos_varargs started
[info] Test dotc.tests.neg_noimports started
[info] Test dotc.tests.neg_noimpots2 started
[info] Test dotc.tests.dotc_reporting started
[info] Test dotc.tests.dotc_ast started
[info] Test dotc.tests.tasty_dotc_transform started
[info] Test dotc.tests.pos_Coder started
[info] Test dotc.tests.testIssue_34 started
[info] Test dotc.tests.pos_t5545 started
[info] Test dotc.tests.pos_utf16 started
[info] Test dotc.tests.tasty_core started
[info] Test dotc.tests.tasty_dotc started
[info] Test dotc.tests.tasty_dotc_rewrite started
[info] Test dotc.tests.pos_scala2_all started
[info] Test dotc.tests.pos_subtyping started
[info] Test dotc.tests.run_all started
[info] Test dotc.tests.tasty_dotty started
[info] Test dotc.tests.tasty_tasty started
[info] Test dotc.tests.tasty_tests started
[info] Test dotc.tests.tasty_tools started
[info] Test dotc.tests.tasty_typer started
[info] Test dotc.tests.neg_tailcall_t1672b started
[info] Test dotc.tests.neg_all started
[info] Test dotc.tests.new_all started
[info] Test dotc.tests.tasty_dotc_ast started
[info] Test dotc.tests.pickle_pickleOK started
[info] Test dotc.tests.pos_nullarify started
[info] Test dotc.tests.pos_overloaded started
[info] Test dotc.tests.tasty_bootstrap started
[info] Test dotc.tests.neg_typedIdents started
[info] Test run finished: 2 failed, 0 ignored, 109 total, 29.531s
[error] Failed: Total 109, Failed 2, Errors 0, Passed 107
[error] Failed tests:
[error] 	dotc.tests
[error] (dotty-compiler/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 37 s, completed 18 déc. 2016 22:08:47
```

Apparently, both fails are due to `scalaShadowing` package not being found. We tried with @nicolasstucki to move it around but to no success.

Also maybe this can help, I noticed that these are the only two tests that are defined with `compileLine(...)` in `tests.scala`. And indeed, if I add another one with `compileLine(emptyFile.scala)`, it also fails for the same reason.

**Comment by smarter** [comment]
Thanks for the report! @felixmulder could you have a look?

**Comment by felixmulder** [comment]
Initial thoughts say the path separator is wrong for windows. But, since I don't have windows - it's hard to try. @Roldak - could you try replacing the argument `compileLine` with windows friendly paths? If that's the right thing to do then we should just have a conversion from `List[String] => List[JFile] => List[String]`  in the argument of the function (compileArgs IIRC)

**Comment by Roldak** [comment]
Unfortunately it doesn't solve the problem. In both cases (windows friendly paths or not) the test sources are found, because if I intentionally misspell the path then it says `not found erroneous/path/to/file.scala` and gives two errors instead of one. (So the error is triggered even when nothing gets compiled)

**Comment by liufengyun** [comment]
We do not have partest any more. Meanwhile, a lot of path-fixes have been done for windows. Please create a new issue if you encounter problems on windows.
