### ISSUE TITLE
Non-reducing match types in polymorphic functions may cause a compiler crash

### ISSUE THREAD

**Issue by JensKanstrupLarsen** [lampepfl/dotty#18336]
## Compiler version

3.1.3

## Minimized code

```Scala
type M[A] =
  A match
    case Int => Int

def f[A](m : M[A]) = ()

val n = f[String](Some(1))
```

## Output
<details>

```scala
exception occurred while typechecking minimal.scala
exception occurred while compiling minimal.scala
java.lang.AssertionError: assertion failed: Number(1,Whole(10)) while compiling minimal.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Number(1,Whole(10))
    at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
    at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldMoreCases(Trees.scala:1630)
    at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1625)
    at dotty.tools.dotc.ast.tpd$TreeOps$$anon$5.apply(tpd.scala:1093)
    at dotty.tools.dotc.ast.tpd$TreeOps$$anon$5.apply(tpd.scala:1093)
    at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1516)
    at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1518)
    at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1535)
    at dotty.tools.dotc.ast.tpd$TreeOps$$anon$5.apply(tpd.scala:1093)
    at dotty.tools.dotc.ast.tpd$TreeOps$$anon$5.apply(tpd.scala:1093)
    at dotty.tools.dotc.ast.tpd$TreeOps$.existsSubTree$extension(tpd.scala:1095)
    at dotty.tools.dotc.typer.ProtoTypes$FunProto.hasInnerErrors(ProtoTypes.scala:375)
    at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:395)
    at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:470)
    at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
    at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
    at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
    at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:622)
    at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
    at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
    at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
    at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1065)
    at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
    at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:117)
    at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:911)
    at dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:991)
    at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3104)
    at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1002)
    at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1040)
    at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
    at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
    at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2832)
    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
    at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
    at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1480)
    at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1470)
    at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1480)
    at dotty.tools.dotc.typer.Namer.typedAheadRhs$1$$anonfun$1(Namer.scala:1733)
    at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
    at dotty.tools.dotc.typer.Namer.typedAheadRhs$1(Namer.scala:1733)
    at dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:1741)
    at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1759)
    at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1760)
    at dotty.tools.dotc.typer.Namer.inferredResultType(Namer.scala:1771)
    at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1519)
    at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1526)
    at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:781)
    at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:920)
    at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:808)
    at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
    at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
    at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
    at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:369)
    at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2773)
    at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2798)
    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
    at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
    at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
    at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2476)
    at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2820)
    at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2824)
    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2894)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
    at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2986)
    at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3036)
    at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2603)
    at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2865)
    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2895)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2960)
    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2964)
    at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3080)
    at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:43)
    at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:50)
    at scala.Function0.apply$mcV$sp(Function0.scala:39)
    at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:414)
    at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:50)
    at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:84)
    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
    at scala.collection.immutable.List.foreach(List.scala:333)
    at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:84)
    at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:225)
    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
    at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
    at dotty.tools.dotc.Run.runPhases$1(Run.scala:236)
    at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:244)
    at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:253)
    at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
    at dotty.tools.dotc.Run.compileUnits(Run.scala:253)
    at dotty.tools.dotc.Run.compileSources(Run.scala:186)
    at dotty.tools.dotc.Run.compile(Run.scala:170)
    at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
    at dotty.tools.dotc.Driver.process(Driver.scala:195)
    at dotty.tools.dotc.Driver.process(Driver.scala:163)
    at dotty.tools.dotc.Driver.process(Driver.scala:175)
    at dotty.tools.dotc.Driver.main(Driver.scala:205)
    at dotty.tools.MainGenericCompiler$.run$1(MainGenericCompiler.scala:162)
    at dotty.tools.MainGenericCompiler$.main(MainGenericCompiler.scala:186)
    at dotty.tools.MainGenericCompiler.main(MainGenericCompiler.scala)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at coursier.bootstrap.launcher.a.a(Unknown Source)
    at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```
</details>

## Description

Using a match type to type a parameter in a polymorphic function (e.g. `f[A](x : M[A])`) causes a compiler crash if the function is called with a type argument that does not reduce the match type and the term argument is not a basic type (e.g. `f[String](Some(1))` or `f[String](List(1))`).

Error is reported as normal if the argument _is_ a basic type (e.g. `f[String](1)`):

```scala
-- Error: minimal.scala:7:18 ---------------------------------------------------
7 |val n = f[String](1)
  |                  ^
  |                  Match type reduction failed since selector  String
  |                  matches none of the cases
  |
  |                      case Int => Int
```

**Comment by dwijnand** [comment]
Doesn't crash on 3.3.0.
