### ISSUE TITLE
Syntactically invalid code crashes dotty: assertion failed at Types$TypeBounds (Types.scala:3096)

### ISSUE THREAD

**Issue by b-studios** [lampepfl/dotty#1845]
Trying to compile the following syntactically incorrect file, in addition to the expected error messages the compiler crashes.

```scala
object Test {
  type X = FooBar.this
}
```
Stacktrace:

```
-- Error: examples/bug.scala ---------------------------------------------
3 |}
  |^
  |`.' expected
-- [E025] Syntax Error: examples/bug.scala -------------------------------
2 |  type X = FooBar.this
  |           ^^^^^^^^^^^
  |           identifier expected

longer explanation available when compiling with `-explain`

exception occurred while typechecking examples/bug.scala

exception occurred while compiling examples/bug.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:3096)
	at dotty.tools.dotc.core.Types$TypeAlias.<init>(Types.scala:3167)
	at dotty.tools.dotc.core.Types$CachedTypeAlias.<init>(Types.scala:3193)
	at dotty.tools.dotc.core.Uniques$TypeAliasUniques.newAlias$1(Uniques.scala:84)
	at dotty.tools.dotc.core.Uniques$TypeAliasUniques.enterIfNew(Uniques.scala:89)
	at dotty.tools.dotc.core.Types$TypeAlias$.apply(Types.scala:3207)
	at dotty.tools.dotc.typer.Namer.typeDefSig(Namer.scala:1114)
	at dotty.tools.dotc.typer.Namer$TypeDefCompleter.typeSig(Namer.scala:699)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:671)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:650)
	...
```

**Comment by felixmulder** [comment]
Is this the full code or is there an instance of `FooBar` floating around somewhere?

Cheers,
Felix

**Comment by b-studios** [comment]
This is the full code. `FooBar` is an arbitrary identifier.

**Comment by felixmulder** [comment]
Great, thanks for the report!
