### ISSUE TITLE
Failing CI on WUnused tests

### ISSUE THREAD

**Issue by szymon-rd** [lampepfl/dotty#18512]
Tests started failing after merging https://github.com/lampepfl/dotty/pull/18468 to main.

```
[info] Test dotty.tools.dotc.CompilationTests.negAll started

Wrong number of errors encountered when compiling tests/neg/i15503a.scala
expected: 22, actual: 21
Unfulfilled expectations:
tests/neg/i15503a.scala:245
Unexpected errors:

-> following the errors:
 at 5: unused import
 at 6: unused import
 at 7: unused import
 at 10: unused import
 at 25: unused import
 at 35: unused import
 at 39: unused import
 at 55: unused import
 at 67: unused import
 at 72: unused import
 at 83: unused import
 at 91: unused import
 at 109: unused import
 at 123: unused import
 at 152: unused import
 at 164: unused import
 at 177: unused import
 at 183: unused import
 at 189: unused import
 at 229: unused import
 at 251: unused import
Error:  Test dotty.tools.dotc.CompilationTests.negAll failed: java.lang.AssertionError: Neg test should have failed, but did not, took 114.789 sec
Error:      at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkExpectedErrors(ParallelTesting.scala:1044)
Error:      at dotty.tools.dotc.CompilationTests.negAll(CompilationTests.scala:127)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
Error:      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.lang.reflect.Method.invoke(Method.java:567)
Error:      ...
```

**Comment by szymon-rd** [comment]
Changes reverted on main
