### ISSUE TITLE
selectDynamic doesn't work with @targetName

### ISSUE THREAD

**Issue by hamzaremmal** [lampepfl/dotty#18922]
## Compiler version

3.3.1

## Minimized code

```Scala
import scala.annotation.targetName

class X extends scala.reflect.Selectable:
	@targetName("hello")
	val `+` = "1"

val x = X()
x.selectDynamic("+")
```

## Output

```scala
java.lang.ExceptionInInitializerError
	at Main$.&lt;clinit&gt;(main.scala:14)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Run.run(Run.scala:128)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:32)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: Playground$X.+()
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at scala.reflect.Selectable.applyDynamic(Selectable.scala:38)
	at scala.reflect.Selectable.applyDynamic$(Selectable.scala:11)
	at Playground$X.applyDynamic(main.scala:5)
	at scala.reflect.Selectable.selectDynamic(Selectable.scala:28)
	at scala.reflect.Selectable.selectDynamic$(Selectable.scala:11)
	at Playground$X.selectDynamic(main.scala:5)
	at Playground$.&lt;clinit&gt;(main.scala:10)
	... 17 more
```

## Expectation

It should resolve to the correct field independently of the presence of the `@targetName` annotation

**Comment by hamzaremmal** [comment]
We will work on this issue in today's Spree

**Comment by bishabosha** [comment]
the other issue does not specifically mention `@targetName`, but the its the same issue - i.e. it doesnt rewrite the access to the name in the bytecode

**Comment by bishabosha** [comment]
as for the solution, should it be the argument to selectDynamic that is rewritten, or should the implementation of reflect.Selectable contain a lookup table from scala method name to bytecode name?

**Comment by hamzaremmal** [comment]
That's me point of opening this second issue

**Comment by bishabosha** [comment]
Ok I've reopened if we consider that the https://github.com/lampepfl/dotty/issues/18612 can be fixed with just name transformer
