### ISSUE TITLE
scaladoc/generateSelfDocumentation does not work on windows

### ISSUE THREAD

**Issue by JD557** [lampepfl/dotty#19078]
## Compiler version

Tested as of https://github.com/lampepfl/dotty/commit/55c20020c24d9edcc8577e9b62c5935e358efbfa

## Minimized code

Just run `sbt scaladoc/generateSelfDocumentation` on Windows

## Output

Multiple warnkings like:
```
-- Warning: docs/_docs/index.md ------------------------------------------------
D:\Projects\dotty\.\docs\_docs\index.md: Unable to resolve link '..\docs\reference\index.html'
```

Eventually failing with
```
java.net.URISyntaxException: Illegal character in path at index 2: ..\..\..\..\index.html
```

<details><summary>"Full" output (Redacted due to GitHub's character limit, but it's all similar)</summary>
<pre>
-- Warning: docs/_docs/internals/gadts.md --------------------------------------
D:\Projects\dotty\.\docs\_docs\internals\gadts.md: Unable to resolve link '..\debug-macros.md'
-- Warning: docs/_docs/internals/gadts.md --------------------------------------
D:\Projects\dotty\.\docs\_docs\internals\gadts.md: Unable to resolve link '..\coverage.md'
-- Warning: docs/_docs/internals/coverage.md -----------------------------------
D:\Projects\dotty\.\docs\_docs\internals\coverage.md: Unable to resolve link '..\gadts.md'
-- Warning: docs/_docs/internals/coverage.md -----------------------------------
D:\Projects\dotty\.\docs\_docs\internals\coverage.md: Unable to resolve link '..\..\..\blog\index.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/new-types/intersection-types.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/new-types/intersection-types.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/new-types/union-types.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/enums/adts.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/enums/desugarEnums.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/contextual/by-name-context-parameters.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/other-new-features/trait-parameters.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/contextual/context-functions.html'
-- Warning: docs/_docs/release-notes-0.1.2.md ----------------------------------
D:\Projects\dotty\.\docs\_docs\release-notes-0.1.2.md: Unable to resolve link 'reference/metaprogramming/inline.html'
-- Warning: docs/_blog/index.html ----------------------------------------------
D:\Projects\dotty\.\docs\_blog\index.html: Unable to resolve link '..\..\docs\internals\coverage.md'
-- Warning: docs/_blog/index.html ----------------------------------------------
D:\Projects\dotty\.\docs\_blog\index.html: Unable to resolve link '..\2021\06\25\scala301-rc2.md'
java.net.URISyntaxException: Illegal character in path at index 2: ..\..\..\..\index.html
        at java.base/java.net.URI$Parser.fail(URI.java:2963)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3134)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3216)
        at java.base/java.net.URI$Parser.parse(URI.java:3175)
        at java.base/java.net.URI.<init>(URI.java:628)
        at dotty.tools.scaladoc.renderers.Locations.resolveLink(Locations.scala:85)
        at dotty.tools.scaladoc.renderers.Locations.resolveLink$(Locations.scala:12)
        at dotty.tools.scaladoc.renderers.Renderer.resolveLink(Renderer.scala:20)
        at dotty.tools.scaladoc.renderers.SiteRenderer.asAsset$1$$anonfun$1(SiteRenderer.scala:60)
        at scala.Option$.when(Option.scala:41)
        at dotty.tools.scaladoc.renderers.SiteRenderer.asAsset$1(SiteRenderer.scala:60)
        at dotty.tools.scaladoc.renderers.SiteRenderer.processLocalLink$1$$anonfun$2(SiteRenderer.scala:72)
        at scala.Option.orElse(Option.scala:477)
        at dotty.tools.scaladoc.renderers.SiteRenderer.processLocalLink$1(SiteRenderer.scala:72)
        at dotty.tools.scaladoc.renderers.SiteRenderer.processLocalLinkWithGuard$1(SiteRenderer.scala:85)
        at dotty.tools.scaladoc.renderers.SiteRenderer.siteContent$$anonfun$2(SiteRenderer.scala:102)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at dotty.tools.scaladoc.renderers.SiteRenderer.siteContent(SiteRenderer.scala:102)
        at dotty.tools.scaladoc.renderers.SiteRenderer.siteContent$(SiteRenderer.scala:21)
        at dotty.tools.scaladoc.renderers.Renderer.siteContent(Renderer.scala:20)
        at dotty.tools.scaladoc.renderers.Renderer.renderContent(Renderer.scala:136)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.pageContent(HtmlRenderer.scala:13)
        at dotty.tools.scaladoc.renderers.Renderer.renderPage(Renderer.scala:165)
        at dotty.tools.scaladoc.renderers.Renderer.renderPage$$anonfun$1(Renderer.scala:166)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.collection.immutable.List.flatMap(List.scala:79)
        at dotty.tools.scaladoc.renderers.Renderer.renderPage(Renderer.scala:166)
        at dotty.tools.scaladoc.renderers.Renderer.renderPage$$anonfun$1(Renderer.scala:166)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at scala.collection.immutable.List.flatMap(List.scala:79)
        at dotty.tools.scaladoc.renderers.Renderer.renderPage(Renderer.scala:166)
        at dotty.tools.scaladoc.renderers.Renderer.$anonfun$8(Renderer.scala:153)
        at scala.collection.immutable.List.map(List.scala:250)
        at scala.collection.immutable.List.map(List.scala:79)
        at dotty.tools.scaladoc.renderers.Renderer.render(Renderer.scala:153)
        at dotty.tools.scaladoc.renderers.HtmlRenderer.render(HtmlRenderer.scala:49)
        at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:239)
        at dotty.tools.scaladoc.Scaladoc$.run$$anonfun$1(Scaladoc.scala:69)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.Option.map(Option.scala:242)
        at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:73)
        at dotty.tools.scaladoc.Main.run(Main.scala:8)
        at dotty.tools.scaladoc.Main$.main(Main.scala:14)
        at dotty.tools.scaladoc.Main.main(Main.scala)
</pre>
</details>

## Expectation

It should not fail.

Also, I think the CI pipeline should be configured to catch errors like this.

### Resolve Link

When performing an early investigation, I noticed a problem in the code (that does not completely solve the problem):

https://github.com/lampepfl/dotty/blob/55c20020c24d9edcc8577e9b62c5935e358efbfa/scaladoc/src/dotty/tools/scaladoc/renderers/Locations.scala#L84-L85

should be wrapped in a `Try`, like:

```scala
  def resolveLink(dri: DRI, url: String): String =
    if Try(URI(url)).fold(_ => false, _.isAbsolute) then url else resolveRoot(dri, url)
```

See

https://github.com/lampepfl/dotty/blob/55c20020c24d9edcc8577e9b62c5935e358efbfa/scaladoc/src/dotty/tools/scaladoc/renderers/SiteRenderer.scala#L54-L79

When `asValidURL` fails due to an invalid URL, `asAsset` is used as fallback, which will call `resolveLink` with an invalid URL and throw. I believe it should go to the next fallback instead.

### Path

I believe the actual error is related to the default site root being `./docs` and `SiteRenderer#processLocalLink` (or somewhere around that) getting the wrong separator, so some of the strip prefix logic gets broken.

Unfortunately, I couldn't actually fix this, as it's a bit hard for me to follow the whole path logic without more context.

**Comment by SolalPirelli** [comment]
It works right now (main = 1082b3dda3). Only `generateReferenceDocumentation` fails because it tries to run a shell script (and I ran this from sbt inside PowerShell).
