### ISSUE TITLE
Regression in `thoughtworksinc / binding.scala`

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#19191]
Regression found in Open Community Build for `thoughtworksinc/binding.scala` [build logs](https://github.com/VirtusLab/community-build3/actions/runs/7066140788/job/19237708565)

## Compiler version
Last good release: 3.4.0-RC1-bin-20230726-97677cc-NIGHTLY
First bad release: 3.4.0-RC1-bin-20230727-ac69c66-NIGHTLY
Works in 3.3.1
Affects Scala 3.3.2 LTS backports

Bisect was not accurate enough, the commit of bisect result failed with other errors when building compiler
Regression candidate commits:
ac69c66ec84171b13e86dd4b4197bd86fd930c62 **(bad)** Ondřej Lhoták : add test for issue #17997 affecting the global object initialization checker (#18141)
d903d35eb0a697a8182e16e88cd28b840a70d8d9 Nicolas Stucki: Add regression test (#18287)
cb73f0b35b239f626152cd260442cc6172cc122d EnzeXing: Add test for modifying this to AndType
c04d2db43a23d18d895878eedb02784c2eabf830 Jędrzej Rochala: Update scala3-presentation-compiler to 39e349e (#18296)
989c55c83a282756595307515512b85ce73384a1 **(bad)** Jan Chyb : Fix regression #17245: Overloaded methods with ClassTags (#18286)
4b67b34dcb05c5b5efd9548087607a5d73f772c4 **(bad, other error)** Nicolas Stucki : Set missing expansion span for copied inlined node (#18229)
182331b6dfec1fc987ef3c7a923d936a0d22936a **(good)** Nicolas Stucki : Support polymorphic functions with erased parameters (#18293)
56251079218efae3d8fc9dd618ad009e7a396a86 Nicolas Stucki: Support polymorphic functions with erased parameters
f22f9db9fc4c971ebc862521a22bcd4551f64d02 **(bad, other error)** Julien Richard-Foy : Set missing expansion span for copied inlined node
101ce3afca2a0a6c41783fa7cbf1fdf1be2281c6 Jan Chyb: Fix regression with Overloaded methods returning Functions
f5313ae761d8c086705e29d6d41296b6a1c58e4c EnzeXing: add fix for issue #17997 affecting the global object initialization checker
96ca0b6bc8504a26359e9fab897f2d79b861028f Ondrej Lhotak: add test for issue #17997 affecting the global object initialization checker

## Minimized code

```Scala
// main.scala
trait Binding[+A]:
  def value: A = ???
object Binding:
  inline def apply[A](inline a: A): Binding[A] = ???
  final case class Constant[+A](override val value: A) extends Binding[A]

extension [A](inline binding: Binding[A])
    transparent inline def bind: A = null.asInstanceOf[A]

trait Vars[A] extends BindingSeq[A]
trait BindingSeq[+A]:
  def foreachBinding[U](f: A => Binding[U]): Binding[Unit] = ???

extension [A](inline bindingSeq: BindingSeq[A])
  transparent inline def foreach[U](inline f: A => U): Unit = ${ Macros.foreach('bindingSeq, 'f) }

@main def Test = {
  val vars: Vars[Int] = ???

  val works = vars.foreach { v => () }
  val fails = for (v <- vars) ()
}

```

```scala
// macros.scala
import scala.compiletime._
import scala.deriving._
import scala.quoted._
import scala.annotation.meta.field

object Macros{
    private def bindingFunctionBody[A: quoted.Type, B: quoted.Type](f: quoted.Expr[A => B])(using Quotes) =
      import quoted.quotes.reflect.*
      f.asTerm match
        case inlined @ Inlined(
              call,
              bindings,
              block @ Block(
                List(
                  defDef @ DefDef(
                    name,
                    paramss @ List(TermParamClause(List(param @ ValDef(paramName, paramTpt, _)))),
                    tpt,
                    Some(rhs)
                  )
                ),
                closureIdent
              )
            ) =>
          Inlined
            .copy(inlined)(
              call,
              bindings,
              '{ (a: A) =>
                ${
                  Block(
                    List(
                      ValDef
                        .copy(param)(paramName, paramTpt, Some('a.asTerm))
                        .changeOwner(Symbol.spliceOwner)
                    ),
                    '{
                      Binding(${ rhs.changeOwner(Symbol.spliceOwner).asExprOf[B] })
                    }.asTerm.changeOwner(Symbol.spliceOwner)
                  )
                    .asExprOf[Binding[B]]
                }: Binding[B]
              }.asTerm
            )
            .asExprOf[A => Binding[B]]
        case _ =>
          '{ (a: A) => Binding.Constant($f(a)): Binding[B] }
      end match
    end bindingFunctionBody

    def foreach[A: quoted.Type, U: quoted.Type](self: quoted.Expr[BindingSeq[A]], f: quoted.Expr[A => U])(using
        qctx: Quotes
    ): quoted.Expr[Unit] = '{ $self.foreachBinding(${ bindingFunctionBody(f) }).bind }
}
```

## Output

```scala
-- Error: /Users/wmazur/projects/dotty/bisect/main.scala:21:14 -----------------
21 |  val fails = for (v <- vars) ()
   |              ^^^^^^^^^^^^^^^^^^
   |Exception occurred while executing macro expansion.
   |java.lang.Exception: Expr cast exception: ((a: scala.Int) => ({
   |  val v: scala.Int = a
   |  Binding.apply[scala.Unit](())
   |}: Binding[scala.Unit]))
   |of type: scala.Function1[scala.Int, scala.Unit]
   |did not conform to type: scala.Function1[scala.Int, Binding[scala.Unit]]
   |
   |    at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:76)
   |    at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:119)
   |    at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:118)
   |    at Macros$.bindingFunctionBody(macros.scala:45)
   |    at Macros$.foreach$$anonfun$1(macros.scala:53)
   |    at Macros$.foreach$$anonfun$adapted$1(macros.scala:53)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:110)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1563)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1632)
   |    at scala.collection.immutable.List.mapConserve(List.scala:472)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1632)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1529)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1632)
   |    at scala.collection.immutable.List.mapConserve(List.scala:472)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1632)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1529)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:152)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:88)
   |    at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3170)
   |    at Macros$.foreach(macros.scala:53)
   |
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from main.scala:15
15 |  transparent inline def foreach[U](inline f: A => U): Unit = ${ Macros.foreach('bindingSeq, 'f) }
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ----------------------------------------------------------------------------
```

## Expectation
Should compile

**Comment by Kordyjan** [comment]
I withdrew the backport for https://github.com/lampepfl/dotty/pull/18229 from the 3.3.2 queue and it fixed the problem.
[Reference](https://virtuslab.github.io/community-build3/2023/12/08/3.3.2-rc1-bin-ff0f22359fe81fbc0c7091ef4573759ba6a46cd1-snapshot.html)
