### ISSUE TITLE
Type recursion not detected in opaque types, leads to `genBCode` crash

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#19372]
## Compiler version
All Scala 3 versions 

## Minimized code

```Scala
trait Ptr[T]

object aliases:
  import structs.*
  type UCharIteratorReserved = Ptr[UCharIterator]
  object UCharIteratorReserved: 
    def iterator: UCharIterator = ???

object structs:
  import aliases.{*, given}
  opaque type UCharIterator = Ptr[UCharIteratorReserved]
  object UCharIterator:
    def reservedFn: UCharIteratorReserved = ???
```

## Output (click arrow to expand)

<details>

```scala
Error while emitting main.scala
java.lang.StackOverflowError while running genBCode on /Users/wmazur/projects/sandbox/main.scala
java.lang.StackOverflowError while compiling /Users/wmazur/projects/sandbox/main.scala
Exception in thread "main" java.lang.StackOverflowError
        at dotty.tools.dotc.core.Types$Type.dealias1(Types.scala:1384)
        at dotty.tools.dotc.core.Types$Type.dealias(Types.scala:1407)
        at dotty.tools.dotc.transform.GenericSignatures$.jsig$1(GenericSignatures.scala:238)
        at dotty.tools.dotc.transform.GenericSignatures$.boxedSig$1(GenericSignatures.scala:68)
        at dotty.tools.dotc.transform.GenericSignatures$.argSig$1(GenericSignatures.scala:195)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$1$$anonfun$1(GenericSignatures.scala:229)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$1(GenericSignatures.scala:229)
        at dotty.tools.dotc.transform.GenericSignatures$.jsig$1(GenericSignatures.scala:288)
        at dotty.tools.dotc.transform.GenericSignatures$.boxedSig$1(GenericSignatures.scala:68)
        at dotty.tools.dotc.transform.GenericSignatures$.argSig$1(GenericSignatures.scala:195)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$1$$anonfun$1(GenericSignatures.scala:229)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
       ...
```
</details>

## Related issue

When types are defined in the same scope, the incremental compilation would fail  
```scala
// Fails with    : `scala-cli compile main.scala`
// Compiles with : `scala-cli compile main.scala --server=false`

trait Ptr[T]
type UCharIteratorReserved = Ptr[UCharIterator]
opaque type UCharIterator = Ptr[UCharIteratorReserved]
```

<details>

```scala
Error: Encountered a StackOverflowError coming from the compiler. You might need to restart your Bloop build server:
dotty.tools.dotc.sbt.ExtractAPICollector.computeType(ExtractAPI.scala:466)
dotty.tools.dotc.sbt.ExtractAPICollector.apiType$$anonfun$1(ExtractAPI.scala:463)
scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
dotty.tools.dotc.sbt.ExtractAPICollector.apiType(ExtractAPI.scala:463)
dotty.tools.dotc.sbt.ExtractAPICollector.processArg$1(ExtractAPI.scala:501)
dotty.tools.dotc.sbt.ExtractAPICollector.$anonfun$10(ExtractAPI.scala:505)
scala.collection.immutable.List.map(List.scala:246)
dotty.tools.dotc.sbt.ExtractAPICollector.computeType(ExtractAPI.scala:505)
dotty.tools.dotc.sbt.ExtractAPICollector.apiType$$anonfun$1(ExtractAPI.scala:463)
...
Error compiling project (Scala 3.3.0, JVM (17))
```
</details>

**Comment by WojciechMazur** [comment]
@indoorvivants It can happen when creating bindings using sn-bindgen  for icu4c

https://github.com/unicode-org/icu/blob/539e8f41a35fec30fba4cfb3a65ea4db67978f85/icu4c/source/common/unicode/uiter.h#L341C22-L341C22 

https://github.com/unicode-org/icu/blob/539e8f41a35fec30fba4cfb3a65ea4db67978f85/icu4c/source/common/unicode/uiter.h#L233C1-L234

**Comment by nicolasstucki** [comment]
### Minimized 

```scala
type A = List[bar.B]
def foo: A = ???
object bar:
  opaque type B = A
```


### Alternative version that loops infinitely without crashing

```scala
type A = bar.B
def foo: A = ???
object bar:
  opaque type B = A
```
