### ISSUE TITLE
Internal match errors in runtime staging

### ISSUE THREAD

**Issue by christophkoch** [lampepfl/dotty#19437]
## Compiler version

3.3.1

## Minimized code

import  scala.quoted.*

given staging.Compiler = {
  object Savior  // :P
  staging.Compiler.make(Savior.getClass.getClassLoader)
}

def id(f: Expr[Int] => Expr[Option[Int]])(x: Expr[Int])(using Quotes) : Expr[Option[Int]] = {

  f(x) match {
    case '{Some(${(y: Expr[Int])})} => '{ Some(${y}) }
    case '{None}                    => '{None}
  }
}

def id2(f: Expr[Int] => Expr[Option[Int]])(using Quotes)(x: Expr[Int]) : Expr[Option[Int]] = '{

  ${f(x)} match {
    case Some(y) => Some(y)
    case None    => None
  }
}

def some(i: Expr[Int])(using Quotes) : Expr[Some[Int]] = '{Some(${i})}

val crashes = staging.run { '{(i : Int) => ${id(id2(some))('{i})}} }

/*
// use any way you like to get crashes evaluated...
object Main {
  def main(args: Array[String]) : Unit = {

    println(crashes(1).toString)
  }
}
*/

## Output

scala.MatchError: scala.quoted.runtime.impl.ExprImpl@14d053a5 (of class scala.quoted.runtime.impl.ExprImpl)
  at StagedExt$package$.id(StagedExt.scala:12)
  at StagedExt$package$.$init$$$anonfun$1$$anonfun$1$$anonfun$1(StagedExt.scala:31)
  at StagedExt$package$.$init$$$anonfun$1$$anonfun$1(StagedExt.scala:31)
  at StagedExt$package$.$init$$$anonfun$1$$anonfun$adapted$1(StagedExt.scala:31)
  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:110)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1538)
  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformBlock(Trees.scala:1603)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1518)
  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1570)
  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1605)
  at scala.collection.immutable.List.mapConserve(List.scala:472)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1605)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1601)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformBlock(Trees.scala:1603)
  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1518)
  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:135)
  at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:152)
  at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:88)
  at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3143)
  at StagedExt$package$.$init$$$anonfun$1(StagedExt.scala:31)
  at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn$$anonfun$1(QuoteCompiler.scala:83)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn(QuoteCompiler.scala:98)
  at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
  at dotty.tools.dotc.Run.runPhases$1(Run.scala:262)
  at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:270)
  at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:279)
  at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
  at dotty.tools.dotc.Run.compileUnits(Run.scala:279)
  at dotty.tools.dotc.Run.compileUnits(Run.scala:200)
  at scala.quoted.staging.QuoteCompiler$ExprRun.compileExpr(QuoteCompiler.scala:118)
  at scala.quoted.staging.QuoteDriver.run(QuoteDriver.scala:43)
  at scala.quoted.staging.Compiler$$anon$1.run(Compiler.scala:38)
  at scala.quoted.staging.package$.run(staging.scala:19)
  at StagedExt$package$.<clinit>(StagedExt.scala:31)
  ... 42 elided

**Comment by nicolasstucki** [comment]
This is a bug in the application in `staging.run { '{(i : Int) => ${id(id2(some))('{i})}} }`.

`id2(some)('{i})` will return
```scala
'{ 
  scala.Some.apply[scala.Int](i) match {
  case scala.Some(y) =>
    scala.Some.apply[scala.Int](y)
  case scala.None =>
    scala.None
  } 
}
```

note that the intent in `id2` is to stage the evaluation of the match. Therefore it must not be reduced yet.

But then `id(...)` tries to match the previous result against an explicit `Some(..)` or `None`, but the code is a `match`.

**Comment by nicolasstucki** [comment]
Ideally, we should be able to show a better match error message by default.
