### ISSUE TITLE
Doc generation: bad scaladoc syntax causes java.lang.StringIndexOutOfBoundsException warning

### ISSUE THREAD

**Issue by raquo** [lampepfl/dotty#19804]
## Compiler version

3.3.1, 3.4.0

(Scala 2.13.2 does not print any warning)

## Minimized example

(Partial reproduction – see below)

```Scala
object Example {

  trait Foo {
    /** @throws the error */
    protected def now(): Int = 1
  }

  trait StrictFoo extends Foo {
    override def now(): Int = super.now()
  }
}
```

## Output Error/Warning message

Running the `doc` command:

```scala
[warn] -- Warning: src/main/scala/path/to/Example.scala:7:18 --------
[warn] 7 |    protected def now(): Int = 1
[warn]   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]   |java.lang.StringIndexOutOfBoundsException: endIndex: 1 out of range: [2, 3]
[warn]   |	at com.vladsch.flexmark.util.sequence.SequenceUtils.validateStartEnd(SequenceUtils.java:1159)
[warn]   |	at com.vladsch.flexmark.util.sequence.SegmentedSequenceTree.subSequence(SegmentedSequenceTree.java:126)
[warn]   |	at com.vladsch.flexmark.ext.wikilink.WikiNode.setLinkChars(WikiNode.java:204)
[warn]   |	at com.vladsch.flexmark.ext.wikilink.WikiNode.<init>(WikiNode.java:98)
[warn] -- Warning: src/main/scala/path/to/Example.scala:11:17 -------
[warn] 11 |    override def now(): Int = super.now()
[warn]    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |java.lang.StringIndexOutOfBoundsException: endIndex: 1 out of range: [2, 3]
[warn]    |	at com.vladsch.flexmark.util.sequence.SequenceUtils.validateStartEnd(SequenceUtils.java:1159)
[warn]    |	at com.vladsch.flexmark.util.sequence.SegmentedSequenceTree.subSequence(SegmentedSequenceTree.java:126)
[warn]    |	at com.vladsch.flexmark.ext.wikilink.WikiNode.setLinkChars(WikiNode.java:204)
[warn]    |	at com.vladsch.flexmark.ext.wikilink.WikiNode.<init>(WikiNode.java:98)
[warn] two warnings found
```

## Why this Error/Warning was not helpful

The root cause is that the user's scaladoc `@throws the error` is not valid scaladoc syntax: it needs to include the type of error, e.g. `@throws Exception the error`. The warnings do point to the offending method, but don't provide the real reason for the warning, and because the warnings are just raw `StringIndexOutOfBoundsException`-s, it's hard to tell if the warnings are legitimate, or a bug in some tool.

Also – The snippet above reproduces only a **part** of the problem. In real-life [non-minimized example](https://github.com/raquo/Airstream/blob/f01513ebf1d63c1b4b2359390591c05e7632d434/src/main/scala/com/raquo/airstream/state/StrictSignal.scala#L14), the situation is a bit worse, because I only get **one** of the warnings, the one that's pointing to the `override` method. That method has no scaladoc, so a scaladoc warning for it is surprising at first. I do **not** get the warning that points to the super `now` method that actually has the offending scaladoc. I'm not sure how to reproduce this in a minimized manner – when minimizing, I always seem to get both errors. For the record, in the Airstream repo, it can be reproduced by checking out the linked commit (f01513e), and running `sbt doc`. Here is what I get there:

```scala
[warn] -- Warning: src/main/scala/com/raquo/airstream/state/StrictSignal.scala:14:15 --
[warn] 14 |  override def now(): A = super.now()
[warn]    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |java.lang.StringIndexOutOfBoundsException: endIndex: 1 out of range: [2, 3]
[warn]    |	at com.vladsch.flexmark.util.sequence.SequenceUtils.validateStartEnd(SequenceUtils.java:1159)
[warn]    |	at com.vladsch.flexmark.util.sequence.SegmentedSequenceTree.subSequence(SegmentedSequenceTree.java:126)
[warn]    |	at com.vladsch.flexmark.ext.wikilink.WikiNode.setLinkChars(WikiNode.java:204)
[warn]    |	at com.vladsch.flexmark.ext.wikilink.WikiNode.<init>(WikiNode.java:98)
[warn] one warning found
```

## Suggested improvement

I'm not sure how much control we have over these warnings, since they seem to be coming from Flexmark. But it would nice if the warning said something about the super method's scaladoc being invalid.

**Comment by som-snytt** [comment]
Updating the dependency is blocked until Scala upgrades to JDK 17 but I confirmed it still happens after upgrading.
