### ISSUE TITLE
Transient failure: `ClassFormatError: Truncated class file`

### ISSUE THREAD

**Issue by mbovel** [lampepfl/dotty#20314]
Is this a flaky CI issue?

Failed run: https://github.com/scala/scala3/actions/runs/8909891046/job/24468041106

```
Test 'tests/run/i5350.scala' failed with output:                                
java.lang.ClassFormatError: Truncated class file
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:29)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Exception in thread "main" java.lang.ClassFormatError: Truncated class file
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:29)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
```

cc @hamzaremmal

**Comment by sadaaithal** [comment]
@mbovel 

we hit a similar problem on one of our internal apps, along with this piece of stacktrace:
`Suppressed: java.io.IOException: CRC error while extracting entry from JAR file
	at sun.misc.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:1023)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	... 14 more
`

We were scratching our head when we decided to ask around (incl. chatgpt) 
One of the responses was about "corrupted, or inconsistent" jar that contained the class under question.
Sure enough - the class we were trying to load (lets call it foo.bar.Sample) was part of a jar (lets call it abc.jar) and it was rightly on the classpath. 

decompiler showed foo.bar.Sample entry was present
but `jar -tvf abc.jar` showed there were 2 entries of foo.bar.Sample class

we think there's an issue somewhere in our gradle builds that creates this abc.jar uberjar. 
investigations are underway, but maybe it helps you in your issue.

good day!

**Comment by mbovel** [comment]
@sadaaithal thanks for your comment. This instance of the error happens on our CI only from time to time, it might be due concurrent access to the same class file which would corrupt it.

**Comment by mbovel** [comment]
Got it again today: https://github.com/scala/scala3/actions/runs/13242917509/job/36962276025 for https://github.com/scala/scala3/pull/22574.

**Comment by sadaaithal** [comment]
@mbovel from https://github.com/scala/scala3/actions/runs/13242917509/job/36962276025 I see the exception is
` java.lang.ClassFormatError: Truncated class file
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:29)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)`

I see the source for ChildJVMMain here https://github.com/michelou/scala3/blob/main/compiler/test/dotty/tools/vulpix/ChildJVMMain.java

I can't see how the we can trigger a concurrent classload of the "Test" class. 

It would help if you could point me in the right direction .. 
tx!

**Comment by som-snytt** [comment]
This is because of vulpix parallelization + aggregating tests in the same directory, `tests/run`. The second set with legacy lazy vals is mediated by an "allow list" which includes `i5350.scala`.

```scala
  @Test def runAll: Unit = {
    implicit val testGroup: TestGroup = TestGroup("runAll")
    aggregateTests(
      compileFilesInDir("tests/run", defaultOptions.and("-Wsafe-init")),
      compileFilesInDir("tests/run-deep-subtype", allowDeepSubtypes),
      compileFilesInDir("tests/run-custom-args/captures", allowDeepSubtypes.and("-language:experimental.captureChecking", "-language:experimental.separationChecking", "-source", "3.8")),
      // Run tests for legacy lazy vals.
      compileFilesInDir("tests/run", defaultOptions.and("-Wsafe-init", "-Ylegacy-lazy-vals", "-Ycheck-constraint-deps"), FileFilter.include(TestSources.runLazyValsAllowlist)),
    ).checkRuns()
  }
```
