### ISSUE TITLE
Nested methods inside static methods doesn't work

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2054]
The following code compiles fine, but it generates run-time exception.

```Scala
import scala.annotation.static

class Test

object Test {
  @static def test(n: Int): Int =  {
    List(3).map(_ + 2)
    n
  }

  def main(args: Array[String]): Unit = test(3)
}
```

Error logs:

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method Test$.$anonfun$test$1(I)I from class Test
	at Test.test(static.scala:7)
	at Test$.main(static.scala:11)
	at Test.main(static.scala)
Caused by: java.lang.IllegalAccessError: tried to access method Test$.$anonfun$test$1(I)I from class Test
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1392)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1748)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 3 more
```

**Comment by DarkDimius** [comment]
@liufengyun nice bug. Thank you!)
