### ISSUE TITLE
VerifyError on recursive val declaration.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#2150]
```scala
object Main {
  def main(args: Array[String]): Unit = {
    val x: Nothing = x
    println(x)
  }
}
```

Causes:
```
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Main$.main([Ljava/lang/String;)V @0: aload_2
  Reason:
    Type top (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Main$', '[Ljava/lang/String;' }
    stack: { }
  Bytecode:
    0x0000000: 2c4d b200 172c bf00 00bf bf            
  Stackmap Table:
    full_frame(@7,{},{Object[#33]})
    same_locals_1_stack_item_frame(@10,Object[#33])

	at Main.main(app.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Run with:
```
> scalaVersion
[info] 0.1.1-20170214-606e36b-NIGHTLY
```

**Comment by alexknvl** [comment]
Does not apply to the latest master Git version.
