### ISSUE TITLE
Type uninitializedThis is not assignable

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2163]
In [b1801a4f](https://github.com/dotty-staging/dotty/blob/b1801a4fd320a87ff039669ed098aa4cde1c7a33/compiler/test/dotty/tools/dotc/reporting/TestReporter.scala#L108-L126). The backend explodes with:

```
[error] Test dotty.tools.dotc.transform.PatmatExhaustivityTest.patmatExhaustivity failed: java.lang.VerifyError: Bad type on operand stack
[error] Exception Details:
[error]   Location:
[error]     dotty/tools/dotc/reporting/TestReporter$$anon$18.<init>(Ljava/io/PrintWriter;)V @7: invokedynamic
[error]   Reason:
[error]     Type uninitializedThis (current frame, stack[1]) is not assignable to 'dotty/tools/dotc/reporting/TestReporter$$anon$18'
[error]   Current Frame:
[error]     bci: @7
[error]     flags: { flagThisUninit }
[error]     locals: { uninitializedThis, 'java/io/PrintWriter' }
[error]     stack: { uninitializedThis, uninitializedThis }
[error]   Bytecode:
[error]     0x0000000: 2a2b b500 122a 2aba 0025 0000 b200 29ba
[error]     0x0000010: 0035 0000 04b7 0038 b1                 
[error] , took 0.01 sec
[error]     at dotty.tools.dotc.reporting.TestReporter$.simplifiedReporter(TestReporter.scala:126)
[error]     at dotty.tools.dotc.transform.PatmatExhaustivityTest.compileFile(PatmatExhaustivityTest.scala:20)
[error]     at dotty.tools.dotc.transform.PatmatExhaustivityTest.$anonfun$176(PatmatExhaustivityTest.scala:74)
[error]     at scala.collection.immutable.List.map(List.scala:273)
[error]     at dotty.tools.dotc.transform.PatmatExhaustivityTest.patmatExhaustivity(PatmatExhaustivityTest.scala:75)
[error]     ...
```

**Comment by DarkDimius** [comment]
@felixmulder, could you please try to minimize?

**Comment by felixmulder** [comment]
No, I really don't want to 😢 

But I'll do it, for you...maybe on Monday :joy:

**Comment by DarkDimius** [comment]
Does it happen on the bootstrapped version or during the bootstrap itself?
Was it fine before https://github.com/dotty-staging/dotty/commit/058771ad548433625e398acbaec57ad67321c7ca ?

**Comment by felixmulder** [comment]
It fails on that commit: http://dotty-ci.epfl.ch/lampepfl/dotty/1529/2

and it's fine at: db6fb45c in http://dotty-ci.epfl.ch/lampepfl/dotty/1514/2

**Comment by DarkDimius** [comment]
The bug has nothing to do with backend. Lamda lift is to blame.
It Moved a lambda defined in a super-call into a private method in the class containing this supercall. 
This makes method inaccessible in supercall.

**Comment by liufengyun** [comment]
Minimal code to reproduce the problem:

```Scala
class Base(f: Int => Int) {
  f(3)
}

class Child(x: Int) extends Base(y => x + y)

object Test {
  def main(args: Array[String]): Unit = new Child(4)
}
```
