### ISSUE TITLE
Error while typing inlined call in object parent.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2265]
```scala
object Test {
  def main(args: Array[String]): Unit = Foo.foo
}

object Foo extends Bar {
  inline def foo: Unit = bar
}

class Bar {
  def bar: Unit = println("bar")
}
```

```
exception while typing /* inlined from Foo*/ pleted (0/1, 1s)
  {
    final lazy module val Foo: Foo = Foo
    Foo.bar
  } of class class dotty.tools.dotc.ast.Trees$Inlined # 139
exception while typing def main(args: Array[String]): Unit = 
  /* inlined from Foo*/ 
    {
      final lazy module val Foo: Foo = Foo
      Foo.bar
    } of class class dotty.tools.dotc.ast.Trees$DefDef # 172
exception while typing @scala.annotation.internal.SourceFile("/Users/nicolas.stucki/GitHub/dotty/compiler/../tests/run/inline-1.scala")
   
final module class Test() extends Object() { 
  def main(args: Array[String]): Unit = 
    /* inlined from Foo*/ 
      {
        final lazy module val Foo: Foo = Foo
        Foo.bar
      }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 175
exception while typing package <empty> {
  final lazy module val Test: Test = new Test()
  @scala.annotation.internal.SourceFile(
    "/Users/nicolas.stucki/GitHub/dotty/compiler/../tests/run/inline-1.scala"
  ) final module class Test() extends Object() { 
    def main(args: Array[String]): Unit = 
      /* inlined from Foo*/ 
        {
          final lazy module val Foo: Foo = Foo
          Foo.bar
        }
  }
  final lazy module val Foo: Foo = new Foo()
  @scala.annotation.internal.SourceFile(
    "/Users/nicolas.stucki/GitHub/dotty/compiler/../tests/run/inline-1.scala"
  ) final module class Foo() extends Bar() { 
    @Foo.bar inline def foo: Unit = Foo.bar
  }
  @scala.annotation.internal.SourceFile(
    "/Users/nicolas.stucki/GitHub/dotty/compiler/../tests/run/inline-1.scala"
  ) class Bar() extends Object() { 
    def bar: Unit = println("bar")
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 201
*** error while checking /Users/nicolas.stucki/GitHub/dotty/compiler/../tests/run/inline-1.scala after phase classOf ***
    Compilation failed for: '../tests/run/inline-1.scala'  
```

**Comment by nicolasstucki** [comment]
The error happens after `TailRec`.

**Comment by smarter** [comment]
Could you post the stacktrace?

**Comment by DarkDimius** [comment]
Aside from the bug:

```scala
def main(args: Array[String]): Unit = 
    /* inlined from Foo*/ 
      {
        final lazy module val Foo: Foo = Foo
        Foo.bar
      }
} 
```

`final lazy module val` combination looks very strange:
 - should it be lazy? Shouldn't Foo should be initialized before inlined member of Foo is called?
 - should it have `module` flag?
 - `final` local val?

Apparently the module itself was inlined and now we have multiple

**Comment by nicolasstucki** [comment]
Stacktrace is:
```
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:100)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:270)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1588)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1588)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:255)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1644)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:131)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:105)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:283)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:281)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:281)
	at dotty.tools.dotc.transform.TreeChecker.runOn(TreeChecker.scala:46)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:76)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:73)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:73)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:67)
	at dotty.tools.dotc.Run.compileSources(Run.scala:64)
	at dotty.tools.dotc.Run.compile(Run.scala:48)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:377)
	at dotty.tools.vulpix.ParallelTesting$RunTest$$anon$4$$anonfun$checkTestSource$2.apply$mcV$sp(ParallelTesting.scala:542)
	at dotty.tools.vulpix.ParallelTesting$Test.tryCompile(ParallelTesting.scala:311)
	at dotty.tools.vulpix.ParallelTesting$RunTest$$anon$4.checkTestSource(ParallelTesting.scala:530)
	at dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable$class.run(ParallelTesting.scala:212)
	at dotty.tools.vulpix.ParallelTesting$RunTest$$anon$4.run(ParallelTesting.scala:529)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by smarter** [comment]
@nicolasstucki No, that doesn't look right. Here's the stacktrace I get, with an assertion error which is helpful in figuring out what's going on:
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: bad owner; object Foo has owner package <empty>, expected was method main
owner chain = object Foo, package <empty>, package <root>, ctxOwners = method main, object Test, object Test, object Test, package <empty>, package <root>, package <root>, package <root>, package <root>, package <root>, package <root>, package <root>, <none>, <none>, <none>, <none>
        at scala.Predef$.assert(Predef.scala:165)
        at dotty.tools.dotc.transform.TreeChecker$Checker.dotty$tools$dotc$transform$TreeChecker$Checker$$checkOwner(TreeChecker.scala:375)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedStats$1.apply(TreeChecker.scala:444)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedStats$1.apply(TreeChecker.scala:443)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:443)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:605)
        at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:996)
        at dotty.tools.dotc.transform.TreeChecker$Checker.dotty$tools$dotc$transform$TreeChecker$Checker$$super$typedInlined(TreeChecker.scala:433)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedInlined$1.apply(TreeChecker.scala:433)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedInlined$1.apply(TreeChecker.scala:433)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:116)
        at dotty.tools.dotc.core.Decorators$ListDecorator$$anonfun$foldRightBN$extension$1.apply(Decorators.scala:117)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSym(TreeChecker.scala:173)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSyms$1.apply(TreeChecker.scala:181)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSyms$1.apply(TreeChecker.scala:181)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:117)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:181)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined(TreeChecker.scala:433)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1545)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1572)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:96)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:270)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1588)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1588)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:255)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1644)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:1241)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:1223)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1223)
        at dotty.tools.dotc.transform.TreeChecker$Checker.dotty$tools$dotc$transform$TreeChecker$Checker$$super$typedDefDef(TreeChecker.scala:417)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedDefDef$1$$anonfun$apply$6.apply(TreeChecker.scala:417)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedDefDef$1$$anonfun$apply$6.apply(TreeChecker.scala:406)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:116)
        at dotty.tools.dotc.core.Decorators$ListDecorator$$anonfun$foldRightBN$extension$1.apply(Decorators.scala:117)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:116)
        at dotty.tools.dotc.core.Decorators$ListDecorator$$anonfun$foldRightBN$extension$1.apply(Decorators.scala:117)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSym(TreeChecker.scala:173)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSyms$1.apply(TreeChecker.scala:181)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSyms$1.apply(TreeChecker.scala:181)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:117)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:181)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSymss$1.apply(TreeChecker.scala:184)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$withDefinedSymss$1.apply(TreeChecker.scala:184)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:117)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSymss(TreeChecker.scala:184)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedDefDef$1.apply(TreeChecker.scala:406)
        at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedDefDef$1.apply(TreeChecker.scala:406)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.foldRightBN$extension(Decorators.scala:116)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:181)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:405)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1514)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1571)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:96)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:270)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1588)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1588)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:255)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1612)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1632)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:448)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1323)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1271)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1271)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:401)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1517)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1571)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:96)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:270)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1588)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1588)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:255)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1612)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1632)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:448)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1432)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1419)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1419)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1556)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1572)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:96)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:270)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1590)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1588)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:136)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1588)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:255)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1644)
        at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:131)
        at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:105)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:283)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:281)
        at scala.collection.immutable.List.map(List.scala:273)
        at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:281)
        at dotty.tools.dotc.transform.TreeChecker.runOn(TreeChecker.scala:46)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:76)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:73)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:73)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:67)
        at dotty.tools.dotc.Run.compileSources(Run.scala:64)
        at dotty.tools.dotc.Run.compile(Run.scala:48)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
        at dotty.tools.dotc.Driver.process(Driver.scala:124)
        at dotty.tools.dotc.Driver.process(Driver.scala:93)
        at dotty.tools.dotc.Driver.process(Driver.scala:105)
        at dotty.tools.dotc.Driver.main(Driver.scala:132)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by smarter** [comment]
It seems to be caused by exactly what @DarkDimius remarked, we're inlining the definition of the object in the main method.

**Comment by nicolasstucki** [comment]
My stack trace was wrong

**Comment by DarkDimius** [comment]
My guess: TreeTypeMap has a case that handles static top-level modules.
This "local final module val" looks like a static module val and trips TreeTypeMap.

**Comment by smarter** [comment]
The problem comes from this line in Inliner:
```scala
bindingsBuf += ValDef(selfSym.asTerm, rhs)
```
I find it weird that the ValDefs created for the bindings list reuse the self symbols, I think we should create new symbols with the same info as the self symbols but dropping the flags that don't make sense (final, lazy, module, all the accessors, ...).
