### ISSUE TITLE
Spurious NPE in vulpix SummaryReport

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2279]
```scala
[error] Test dotty.tools.dotc.CompilationTests failed: java.lang.NullPointerException: null, took 0.0 sec
[error]     at dotty.tools.vulpix.SummaryReport$$anonfun$echoSummary$5.apply(SummaryReport.scala:131)
[error]     at dotty.tools.vulpix.SummaryReport$$anonfun$echoSummary$5.apply(SummaryReport.scala:131)
[error]     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error]     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]     at dotty.tools.vulpix.SummaryReport.echoSummary(SummaryReport.scala:131)
[error]     at dotty.tools.dotc.CompilationTests$.cleanup(CompilationTests.scala:331)
[error]     at dotty.tools.dotc.CompilationTests.cleanup(CompilationTests.scala)
```

**Comment by odersky** [comment]
I saw this as well occasionally.
