### ISSUE TITLE
Two examplars of type-dependent type bring REPL to runtime error

### ISSUE THREAD

**Issue by scalasolist** [lampepfl/dotty#2310]
paste into REPL:

    trait Parent {
      sealed trait HNil
      object HNil extends HNil
    }
    
    trait Single extends Parent {
      val u = HNil
    }

Try the following code:

    scala> object X extends Single
    defined module X
    scala> object Y extends Single
    defined module Y
    scala> X.u
    val res0: X.HNil.type = Parent$HNil$@2b14d160
    scala> Y.u

get the error:

    java.lang.IncompatibleClassChangeError: Interface method reference: Parent.HNil()LParent$HNil$;, is in an indirect superinterface of Y$
        at Y$.HNil(<console>:4)
        at Single.initial$u(AbsHList.scala:46)
        at Y$.<init>(<console>:4)
        at Y$.<clinit>(<console>)
        at .<init>(<console>:6)
        at .<clinit>(<console>)
        at RequestResult$.<init>(<console>:3)
        at Reques...

I could not reproduce that error outside REPL in a standalone application

**Comment by 2m** [comment]
Got the same error (still only in the REPL) with the following different sample:
```scala
scala> trait T(x: Int)
defined trait T
scala> trait U extends T
defined trait U
scala> class C extends U with T(22)
defined class C
scala> new C
java.lang.IncompatibleClassChangeError: Interface method reference: T.$init$()V, is in an indirect superinterface of C
        at C.<init>(<console>:6)
        at .<init>(<console>:8)
        at .<clinit>(<console>)
        at RequestResult$.<init>(<console>:3)
        at RequestResult$.<clinit>(<console>)
        at RequestResult$result(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflec...
```
