### ISSUE TITLE
backend crashes with java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2355]
Following code compiles in scalac, but fails in Dotty at backend (`-Ycheck:all` enabled):

```Scala
class Test {
  trait Tree

  def bar(t: Tree): Tree = t match {
    case t => t
  }
}
```

Exception stack:
```
Exception in thread "main" java.lang.AbstractMethodError: scala.tools.nsc.backend.jvm.BackendInterface$SymbolHelper.javaBinaryName()Ljava/lang/Object;
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$class.$init$(BCodeBodyBuilder.scala:1427)
	at dotty.tools.backend.jvm.GenBCodePipeline.<init>(GenBCode.scala:59)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:53)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:283)
	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:281)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:281)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:38)
        ...
```

**Comment by smarter** [comment]
It doesn't crash here, `javaBinaryName` was recently changed in the backend and in dotty, and this method should exist. The only explanation I have is that you have an old forked `scala-compiler` on your classpath somewhere.

**Comment by odersky** [comment]
Maybe missing `git submodule update --init`?

**Comment by smarter** [comment]
@liufengyun You may want to try cleaning everything sbt cached:
```scala
find . -name target -exec rm -r "{}" \;
```

**Comment by liufengyun** [comment]
Thanks for the tip. It looks to be a local environmental problem. I just tried to set up the dev env on my desktop. The problem is that one jar is not properly built, now it works well.
