### ISSUE TITLE
Provide a nice error message if `scala.` isn't found

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2395]
We should check that classes from dotty-library and scala-library can be found and report a nice error.

Current error message:

```
java.lang.Exception
    at dotty.tools.dotc.core.Denotations$MissingRef.<init>(Denotations.scala:1034)
    at dotty.tools.dotc.core.Denotations$MissingRef$.apply(Denotations.scala:1033)
    at dotty.tools.dotc.core.Denotations$DenotationsBase.select$1(Denotations.scala:1183)
creating stub for scala, owner = module class <root>#2, file = null
decls = module sun#3
  module class sun#4
...
bad symbolic reference. A signature
refers to scala[ModuleClass]/T in package <root> which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.
Exception in thread "main" java.lang.UnsupportedOperationException: class dotty.tools.dotc.core.Scopes$EmptyScope$.openForMutations
    at dotty.tools.dotc.util.DotClass.unsupported(DotClass.scala:10)
    at dotty.tools.dotc.core.Scopes$Scope.openForMutations(Scopes.scala:161)
```

**Comment by DarkDimius** [comment]
Experienced by @olafurpg

**Comment by olafurpg** [comment]
To reproduce, here is the command that I ran initially (ERROR) and then the command that worked OK
```
coursier launch ch.epfl.lamp:dotty_0.1:0.1.1-bin-20170507-1014af3-NIGHTLY -M dotty.tools.dotc.Main -- Foo.scala # ERROR
coursier launch ch.epfl.lamp:dotty_0.1:0.1.1-bin-20170507-1014af3-NIGHTLY -M dotty.tools.dotc.Main -- -classpath $(coursier fetch ch.epfl.lamp:dotty-library_0.1:0.1.1-bin-20170507-1014af3-NIGHTLY | paste -sd ":" -) Foo.scala # OK
```
