### ISSUE TITLE
Bad bytecode generated for a partial function.

### ISSUE THREAD

**Issue by valdisxp1** [lampepfl/dotty#2396]
When running the example below, it fails with `java.lang.VerifyError` [Full stack trace](https://github.com/lampepfl/dotty/files/983955/stacktrace.txt)
```scala
class Main {
  val buzz = Some(Bees.Bee("buzz")).collect {
    case Bees.Bee(value) => value
  }
}

object Main {
  def main(args: Array[String]): Unit = {
    new Main
  }
}

object Bees {
  case class Bee(value: String)
}
```

Reproducible in fresh `lampepfl/dotty.g8`
OpenJDK 8 on Ubuntu
```
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by DarkDimius** [comment]
Reproduced. Looking into it.

**Comment by nicolasstucki** [comment]
A simpler version of this issue is:
```scala
class Bees {
  import Test._

  def f: PartialFunction[Bee, Unit] = {
    case Test.Bee(_) => ""
//     case Bee(_) => ""  // This one works
  }

  f(new Bee("buzz"))
}

object Test {
  case class Bee(value: String)
  def main(args: Array[String]): Unit = new Bees
}
```
Note that the issue seems to come from the prefix `Test` in `case Test.Bee(_) `.

**Comment by nicolasstucki** [comment]
A simpler case that exhibits a similar issue is:
```scala
class Bees {
  def f: PartialFunction[Bee, Unit] = {  case Bee(_) => ""  }

  f(new Bee("buzz"))

  case class Bee(value: String)
  // object Bee // With this it works
}

object Test {
  def main(args: Array[String]): Unit = {
    new Bees
  }
}
```
fails with 
```scala
Caused by: java.lang.NullPointerException
	at Bees.Bees$f$$f$$anonfun$1$1(i2396.scala:6)
	at Bees$$anonfun$1.apply(i2396.scala:6)
	at Bees$$anonfun$1.apply(i2396.scala:6)
	at Bees.<init>(i2396.scala:9)
	at Test$.main(i2396.scala:17)
	at Test.main(i2396.scala)
```
where the bytecode has
```java
public class Bees {
    public final Bees.Bee$ Bee$lzy1;

    public Bees() {
        this.f().apply(new Bees.Bee(this, "buzz"));
        this.Bee$lzy1 = new Bees.Bee$(this); // should be lazy
    }

    public final Bees.Bee$ Bee() { return this.Bee$lzy1; }  // should be initialized in here if needed
   ...
}
```

**Comment by DarkDimius** [comment]
@nicolasstucki, the issue you've triggered seems like a different issue.

**Comment by nicolasstucki** [comment]
I will create another issue for it.

**Comment by DarkDimius** [comment]
This is a bug in ElimStaticThis, that was creating references to packages.
Backend was generating bytecode that passed a package on stack...

See `<empty>` in the printount of Xprint below.
```
<static> def Bees$f$$isDefinedAt$1(x$1: Test.Test$Bee): Boolean =
      {
        case val selector2: Test.Test$Bee = x$1: Test.Test$Bee @unchecked
        {
          def case2(): Boolean =
            if
              {
                <empty>.Test
                Test.Bee.unapply(selector2).ne(null)
              }
             then
              {
                case val x2: Test.Test$Bee =
                  {
                    <empty>.Test
                    Test.Bee.unapply(selector2)
                  }
                {
                  case val p2: String = x2._1()
                  true
                }
              }
             else
              {
                def case3(): Boolean =
                  {
                    val _: Test.Test$Bee = selector2
                    false
                  }
                case3()
              }
          case2()
        }
      }
  }
```

**Comment by DarkDimius** [comment]
Fixes available for both problems.
