### ISSUE TITLE
Value Class: Multiple params crash compiler

### ISSUE THREAD

**Issue by ennru** [lampepfl/dotty#2497]
On the following input the compiler crashes
`class MyValue(val i: Int, j: Int) extends AnyVal`

Expected behaviour is to get `value class needs to have exactly one val parameter`.
See Checking.scala checkDerivedValueClass

Is this related to #2470 ?

```
error while transforming package <empty> {
  final lazy module val Scope: Scope = new Scope()
  @scala.annotation.internal.SourceFile("tests/pos/HelloWorld.scala")
    final module
   class Scope() extends Object() { this: Scope.type =>
    final class MyValue(i: Int, j: Int) extends AnyVal() {
      val i: Int
      private[this] val j: Int
    }
    final lazy module val MyValue: Scope.MyValue = new Scope.MyValue()
    final module class MyValue() extends Object() { this: Scope.MyValue.type =>}
  }
}

exception occurred while compiling tests/pos/HelloWorld.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at dotty.tools.dotc.transform.SyntheticMethods.dotty$tools$dotc$transform$SyntheticMethods$$valueHashCodeBody$1(SyntheticMethods.scala:189)
```

**Comment by ennru** [comment]
Oops, was related to my own changes. :-)

**Comment by felixmulder** [comment]
It happens 😄
