### ISSUE TITLE
Dottyc crashes for refined type

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#2527]
``` scala
class Base

// OK
val widen = {
  class Inner extends Base
  val f: () => Inner = { () => new Inner }
  f()
}

// Crash
val leak = {
  class Inner extends Base
  val f: (() => Inner){ def apply(): Inner } = { () => new Inner }
  f()
}
```

```
dotty.tools.dotc.core.Types$TypeError: unexpected parent type: RefinedType(RefinedType(TypeRef(ThisType(TypeRef(NoPrefix,scala)),Function0), scala$Function0$$R, TypeAlias(TypeRef(NoPrefix,Inner), 1)), apply, MethodType(List(), List(), TypeRef(NoPrefix,Inner)))

dotty.tools.dotc.core.Types$TypeError: unexpected parent type: RefinedType(RefinedType(TypeRef(ThisType(TypeRef(NoPrefix,scala)),Function0), scala$Function0$$R, TypeAlias(TypeRef(NoPrefix,Inner), 1)), apply, MethodType(List(), List(), TypeRef(NoPrefix,Inner)))
	at dotty.tools.dotc.core.TypeOps.fail$5(TypeOps.scala:339)
	at dotty.tools.dotc.core.TypeOps.normalizeToRef$1(TypeOps.scala:359)
	at dotty.tools.dotc.core.TypeOps.$anonfun$249(TypeOps.scala:363)
	at scala.collection.immutable.List.map(List.scala:288)
	at dotty.tools.dotc.core.TypeOps.normalizeToClassRefs(TypeOps.scala:363)
	at dotty.tools.dotc.core.Symbols$$anon$56.complete(Symbols.scala:125)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:219)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.unforcedDecls(SymDenotations.scala:352)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.enter(SymDenotations.scala:1509)
	at dotty.tools.dotc.core.Symbols$Symbol.entered(Symbols.scala:452)
	at dotty.tools.dotc.ast.tpd$.AnonClass(tpd.scala:268)
	at dotty.tools.dotc.transform.ExpandSAMs.transformBlock(ExpandSAMs.scala:43)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goBlock(TreeTransform.scala:672)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1052)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1051)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:965)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1182)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1208)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$718(TreeTransform.scala:1212)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$5(Decorators.scala:62)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1050)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:965)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1182)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1208)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$718(TreeTransform.scala:1212)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$5(Decorators.scala:62)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1153)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:983)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1182)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1208)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$718(TreeTransform.scala:1212)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$5(Decorators.scala:62)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1162)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.op$55(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1174)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:555)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:473)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$2(Phases.scala:283)
	at scala.collection.immutable.List.map(List.scala:284)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:285)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:82)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:90)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:95)
	at dotty.tools.dotc.Run.compileSources(Run.scala:64)
	at dotty.tools.dotc.Run.compile(Run.scala:48)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:63)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:53)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:885)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:877)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:875)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

https://scastie.scala-lang.org/Atry/FOuNoMj6TFmxIPZNstW9Gg

**Comment by nicolasstucki** [comment]
This code can be reduced to 
```scala
object Foo {
  val f: Function0[Int]{ def apply(): Int } = () => 42
}
```

**Comment by nicolasstucki** [comment]
The issue seems to come from the cast in the closure where the type we are casting to is the function with the refinement.
```scala
object Foo {
  val f: Function0[Int]{ def foo(): Int } = () => 42
}
```

```scala
exception while transforming {
  def $anonfun(): Int = 42
  closure($anonfun:(() => Int){foo: ()Int})
} of class class dotty.tools.dotc.ast.Trees$Block # 100
exception while transforming val f: (() => Int){foo: ()Int} = 
  {
    def $anonfun(): Int = 42
    closure($anonfun:(() => Int){foo: ()Int})
  } of class class dotty.tools.dotc.ast.Trees$ValDef # 101
exception while transforming () extends Object() { 
  val f: (() => Int){foo: ()Int} = 
    {
      def $anonfun(): Int = 42
      closure($anonfun:(() => Int){foo: ()Int})
    }
} of class class dotty.tools.dotc.ast.Trees$Template # 103
exception while transforming @scala.annotation.internal.SourceFile("foo.scala") final module class Foo()
   extends
 Object() { 
  val f: (() => Int){foo: ()Int} = 
    {
      def $anonfun(): Int = 42
      closure($anonfun:(() => Int){foo: ()Int})
    }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 104
exception while transforming package <empty> {
  final lazy module val Foo: Foo$ = new Foo$()
  @scala.annotation.internal.SourceFile("foo.scala") final module class Foo()
     extends
   Object() { 
    val f: (() => Int){foo: ()Int} = 
      {
        def $anonfun(): Int = 42
        closure($anonfun:(() => Int){foo: ()Int})
      }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 105
```

**Comment by DarkDimius** [comment]
@nicolasstucki, the code in your last commit should not compile. It's neither a SAM, nor does the RHS conform to expected type.
