### ISSUE TITLE
Add CI for scripts on Mac, Linux and Windows

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2646]
Currently we only have CI for the brew formula on Mac. It would be nice to introduce the CI for every PR for all the platforms:

- [x] Windows: https://github.com/marketplace/appveyor
- [x] Mac: travis
- [x] Linux: travis

**Comment by liufengyun** [comment]
The `sbt compile` doesn't run on Windows -- the copy of backend files to compiler project failed:

https://ci.appveyor.com/project/liufengyun/dotty/build/8/job/eojkwp9o7eypoby4#L958

I'm now installing Windows on my home PC, trying to debug.

**Comment by liufengyun** [comment]
As an update:

1. By a workaround on the sbt backend source code problem, the Dotty project compiles under Windows Server 2012 RC2 ([logs](https://ci.appveyor.com/project/liufengyun/dotty/build/job/0bdfwvncybaauy1x)).
2. But on Windows 10, scalac crashes: 

```
java.lang.StackOverflowError
        at scala.reflect.internal.TreeInfo.isSelfConstrCall(TreeInfo.scala:296)
        at scala.reflect.internal.TreeInfo.isSelfOrSuperConstrCall(TreeInfo.scala:344)
        at scala.reflect.internal.Trees$UnderConstructionTransformer$class.transform(Trees.scala:1701)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:291)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:457)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:352)
        at scala.reflect.internal.Trees$class.itransform(Trees.scala:1372)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:219)
...
```

**Comment by DarkDimius** [comment]
@liufengyun, standard JVM stack size is smaller on windows. You may want to pass one explicitly

**Comment by DarkDimius** [comment]
Try -Xss4M

**Comment by smarter** [comment]
Hmm, if we need a custom stack size for running dotty, we probably need it in a bunch of places like every client of the language server https://github.com/lampepfl/dotty/blob/master/vscode-dotty/src/extension.ts#L84. That's going to be annoying

**Comment by liufengyun** [comment]
@smarter We need custom stack size to _compile_ dotty, not _run_ dotty, that might be a relief for you.

**Comment by smarter** [comment]
Ah I see, interesting. I wonder what we do in our code that requires so much stack, considering that scalac can compile itself without a custom stack size.

**Comment by DarkDimius** [comment]
> Ah I see, interesting. I wonder what we do in our code that requires so much stack, considering that scalac can compile itself without a custom stack size.

we have a lot of "track"-like methods. Dotty compiled by scalac doesn't have them inlined and they grow stack.

**Comment by liufengyun** [comment]
The CI for Linux, Windows and Mac is now implemented: https://github.com/liufengyun/packtest/pull/1

I'll transfer the repo to `lampepfl`.
