### ISSUE TITLE
Predef.scala + deprecated.scala cannot be compiled twice

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2799]
To reproduce (ignore the weird `fsc` stuff, it's because we don't have a simple way to run the `Bench` main class, whose functionality should just be merged into the regular `Main` class anyway):
```scala
$ FscMain=dotty.tools.dotc.Bench ./bin/dotc -fsc \#runs 2  ./scala2-library/src/library/scala/Predef.scala ./scala2-library/src/library/scala/deprecated.scala

time elapsed: 2800ms
exception while transforming scala.reflect.package.ClassManifest of class class dotty.tools.dotc.ast.Trees$Select # 22080
exception while transforming @deprecated("Use `scala.reflect.ClassTag` instead", "2.10.0") val ClassManifest
  : 
=> scala.reflect.ClassManifestFactory.type(scala.reflect.ClassManifest) = 
  scala.reflect.package.ClassManifest of class class dotty.tools.dotc.ast.Trees$ValDef # 22081
...
exception occurred while compiling ./scala2-library/src/library/scala/Predef.scala, ./scala2-library/src/library/scala/deprecated.scala
Exception in thread "main" dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol; class deprecated#3345 in module class scala, defined in Period(1..6, run = 2), is referred to in run Period(10..10, run = 3)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.staleSymbolError(Denotations.scala:922)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:738)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:782)
        at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:406)
        at dotty.tools.dotc.core.Symbols$.toDenot(Symbols.scala:626)
        at dotty.tools.dotc.core.Annotations$Annotation.matches(Annotations.scala:16)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.dropOtherAnnotations(SymDenotations.scala:331)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.hasAnnotation(SymDenotations.scala:285)
        at dotty.tools.dotc.transform.CheckStatic.transformSelect(CheckStatic.scala:81)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goSelect(TreeTransform.scala:575)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:952)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1184)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1177)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1176)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:967)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1184)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1177)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1176)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1210)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$37.apply(TreeTransform.scala:1214)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$37.apply(TreeTransform.scala:1214)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:62)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1214)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1155)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1185)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1177)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1176)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:985)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1184)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1177)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1176)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1210)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$37.apply(TreeTransform.scala:1214)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$37.apply(TreeTransform.scala:1214)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:62)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1214)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1164)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1185)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1177)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1176)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:557)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:475)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:283)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:281)
        at scala.collection.immutable.List.map(List.scala:284)
        at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:281)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.runOn(TreeTransform.scala:469)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:82)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:79)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:79)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:67)
        at dotty.tools.dotc.Run.compileSources(Run.scala:64)
        at dotty.tools.dotc.Run.compile(Run.scala:48)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
        at dotty.tools.dotc.Bench$.dotty$tools$dotc$Bench$$super$doCompile(Bench.scala:27)
        at dotty.tools.dotc.Bench$$anonfun$doCompile$1.apply(Bench.scala:27)
        at dotty.tools.dotc.Bench$$anonfun$doCompile$1.apply(Bench.scala:25)
        at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:22)
        at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:22)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
        at dotty.tools.dotc.Bench$.ntimes(Bench.scala:22)
        at dotty.tools.dotc.Bench$.doCompile(Bench.scala:25)
        at dotty.tools.dotc.Driver.process(Driver.scala:124)
        at dotty.tools.dotc.Bench$.dotty$tools$dotc$Bench$$super$process(Bench.scala:42)
        at dotty.tools.dotc.Bench$$anonfun$process$1.apply(Bench.scala:42)
        at dotty.tools.dotc.Bench$$anonfun$process$1.apply(Bench.scala:42)
        at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:22)
        at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:22)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
        at dotty.tools.dotc.Bench$.ntimes(Bench.scala:22)
        at dotty.tools.dotc.Bench$.process(Bench.scala:42)
        at dotty.tools.dotc.Driver.process(Driver.scala:93)
        at dotty.tools.dotc.Driver.process(Driver.scala:105)
        at dotty.tools.dotc.Driver.main(Driver.scala:132)
        at dotty.tools.dotc.Bench.main(Bench.scala)
```

**Comment by odersky** [comment]
I don't think this needs fixing. It'd be more a nice to have.
