### ISSUE TITLE
When using structural types,the repl crashes

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#2933]
```scala
scala> val t: {def toString(): String} = new Objectassertion failure for Object{toString: (): String}(t) <:< ?{ toString: ? }, frozen = false
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation.owner(SymDenotations.scala:1816)
	at dotty.tools.dotc.core.Denotations$Denotation.preferSym$1(Denotations.scala:404)
	at dotty.tools.dotc.core.Denotations$Denotation.prefer$1(Denotations.scala:411)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeSingleDenot$1(Denotations.scala:422)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeDenot$1(Denotations.scala:355)
	at dotty.tools.dotc.core.Denotations$Denotation.$amp(Denotations.scala:452)
	at dotty.tools.dotc.core.Types$Type.goRefined$1(Types.scala:581)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:488)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:639)
	at dotty.tools.dotc.core.Types$Type.memberExcluding(Types.scala:467)
	at dotty.tools.dotc.core.Types$Type.op$25(Types.scala:451)
	at dotty.tools.dotc.core.Types$Type.member(Types.scala:450)
	at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy(ProtoTypes.scala:99)
	at dotty.tools.dotc.core.TypeComparer.isMatchedByProto(TypeComparer.scala:1003)
	at dotty.tools.dotc.core.TypeComparer.firstTry(TypeComparer.scala:212)
	at dotty.tools.dotc.core.TypeComparer.op$16(TypeComparer.scala:117)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:108)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:102)
	at dotty.tools.dotc.core.Types$Type.op$36(Types.scala:745)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:744)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2110)
	at dotty.tools.dotc.typer.Typer.adaptInterpolated(Typer.scala:2239)
	at dotty.tools.dotc.typer.Typer.op$125(Typer.scala:1833)
	at dotty.tools.dotc.typer.Typer.op$124(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:1828)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:393)
	at dotty.tools.dotc.typer.Typer.op$84(Typer.scala:427)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:391)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1599)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1664)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Applications.op$56(Applications.scala:660)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:658)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:758)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1618)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:393)
	at dotty.tools.dotc.typer.Typer.op$84(Typer.scala:427)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:391)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1599)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1664)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Applications.op$56(Applications.scala:660)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:658)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:758)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1618)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1654)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.op$93(Typer.scala:667)
	at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:666)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1626)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1654)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:393)
	at dotty.tools.dotc.typer.Typer.op$84(Typer.scala:427)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:391)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1599)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1664)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Applications.op$56(Applications.scala:660)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:658)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:758)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1618)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1654)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.op$92(Typer.scala:624)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:616)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1625)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.op$93(Typer.scala:668)
	at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:666)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1626)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.op$92(Typer.scala:624)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:616)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1625)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$945(ProtoTypes.scala:237)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:215)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:237)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:633)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:633)
	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:413)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:461)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:235)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:551)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:632)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:688)
	at dotty.tools.dotc.typer.Applications.op$56$$anonfun$3(Applications.scala:713)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1745)
	at dotty.tools.dotc.typer.Applications.op$56(Applications.scala:724)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:658)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:758)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1618)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1654)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1654)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.op$92(Typer.scala:624)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:616)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1625)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.Typer.op$115(Typer.scala:1233)
	at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:1227)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1603)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1664)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.traverse$4(Typer.scala:1702)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1725)
	at dotty.tools.dotc.typer.Typer.op$118(Typer.scala:1391)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1321)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1609)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1664)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.traverse$4(Typer.scala:1702)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1725)
	at dotty.tools.dotc.typer.Typer.op$120(Typer.scala:1508)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1495)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1648)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1665)
	at dotty.tools.dotc.typer.Typer.op$122(Typer.scala:1680)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1678)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1737)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:64)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:32)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:68)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$5(FrontEnd.scala:93)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:93)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$1(Run.scala:82)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:90)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:95)
	at dotty.tools.dotc.Run.compileSources(Run.scala:64)
	at dotty.tools.dotc.repl.CompilingInterpreter.compileSources(CompilingInterpreter.scala:195)
	at dotty.tools.dotc.repl.CompilingInterpreter$Request.compile(CompilingInterpreter.scala:409)
	at dotty.tools.dotc.repl.CompilingInterpreter.interpret(CompilingInterpreter.scala:220)
	at dotty.tools.dotc.repl.AmmoniteReader.incompleteInput$$anonfun$1(AmmoniteReader.scala:19)
	at dotty.tools.dotc.repl.CompilingInterpreter.delayOutputDuring(CompilingInterpreter.scala:103)
	at dotty.tools.dotc.repl.AmmoniteReader.incompleteInput(AmmoniteReader.scala:19)
	at dotty.tools.dotc.repl.AmmoniteReader.dotty$tools$dotc$repl$AmmoniteReader$multilineFilter$$isDefinedAt$14(AmmoniteReader.scala:31)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$480.isDefinedAt(AmmoniteReader.scala:32)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$480.isDefinedAt(AmmoniteReader.scala:30)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$480.applyOrElse(AmmoniteReader.scala:30)
	at dotty.tools.dotc.repl.AmmoniteReader$$anonfun$480.applyOrElse(AmmoniteReader.scala:30)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at dotty.tools.dotc.repl.ammonite.terminal.Filter$$anon$86.$init$$$anonfun$67$$anonfun$1(Filter.scala:21)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.find(Iterator.scala:942)
	at scala.collection.AbstractIterator.find(Iterator.scala:1334)
	at dotty.tools.dotc.repl.ammonite.terminal.Filter$$anon$86.$init$$$anonfun$67(Filter.scala:21)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.readChar$1(Terminal.scala:267)
	at dotty.tools.dotc.repl.ammonite.terminal.Terminal$.readLine(Terminal.scala:299)
	at dotty.tools.dotc.repl.AmmoniteReader.readLine(AmmoniteReader.scala:74)
	at dotty.tools.dotc.repl.InterpreterLoop.repl$default$1(InterpreterLoop.scala:75)
	at dotty.tools.dotc.repl.InterpreterLoop.repl(InterpreterLoop.scala:77)
	at dotty.tools.dotc.repl.InterpreterLoop.run(InterpreterLoop.scala:202)
	at dotty.tools.dotc.repl.REPL.doCompile(REPL.scala:43)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.Driver.process(Driver.scala:105)
	at dotty.tools.dotc.Driver.main(Driver.scala:132)
	at dotty.tools.dotc.repl.Main.main(Main.scala)

```

**Comment by smarter** [comment]
Fixed in master (you can try out a nightly build with `scalaVersion := "0.3.0-bin-20170727-3d9080c-NIGHTLY"`)
