### ISSUE TITLE
REPL crashing on OR types

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3041]
```scala
Starting dotty REPL...
scala> val a: Int | String = 4  
Exception in thread "main" scala.MatchError: OrType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala)/withSig(Signature(List(),)),Int),TypeRef(TermRef(ThisType(TypeRef(NoPrefix,scala)),Predef)/withSig(Signature(List(),)),String)) (of class dotty.tools.dotc.core.Types$CachedOrType)
	at dotty.tools.repl.UserFacingPrinter.toText(UserFacingPrinter.scala:144)
	at dotty.tools.repl.UserFacingPrinter.dclText(UserFacingPrinter.scala:74)
	at dotty.tools.repl.package$ShowUser$.showUser$extension(package.scala:28)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:72)
	at dotty.tools.repl.ReplDriver.displayMembers$1$$anonfun$3(ReplDriver.scala:262)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dotty.tools.repl.ReplDriver.displayMembers$1(ReplDriver.scala:262)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1$$anonfun$2(ReplDriver.scala:289)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1(ReplDriver.scala:289)
	at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
	at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:36)
	at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:294)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$3(ReplDriver.scala:219)
	at scala.util.Either.fold(Either.scala:188)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:220)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:187)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:140)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by felixmulder** [comment]
Fixed in: https://github.com/lampepfl/dotty/pull/3032
