### ISSUE TITLE
Crash when trying to emit switch when matching on an Any

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3588]
```scala
class Foo {
  val a: Any = 3
  a match {
    case 1 =>
    case 2 =>
    case 3 =>
    case _ =>
  }
}
```
 Crashes in the backend with

```
java.lang.AssertionError: assertion failed: Cannot emit primitive conversion from Ljava/lang/Object; to I
	at scala.Predef$.assert(Predef.scala:219)
	at scala.tools.nsc.backend.jvm.BCodeIdiomatic$JCodeMethodN.emitT2T(BCodeIdiomatic.scala:260)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.adapt(BCodeBodyBuilder.scala:900)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:435)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genMatch(BCodeBodyBuilder.scala:805)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:422)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:861)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:861)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:602)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:635)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:506)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$1(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$1$adapted(BCodeSkelBuilder.scala:508)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:116)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:218)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:171)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:379)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:345)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:66)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:289)
....
```

**Comment by allanrenucci** [comment]
There is this [function](https://github.com/lampepfl/dotty/blob/f1bb59042424059df07a151b7e473e382bf2fe40/compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala#L794) that is never called. I think it was meant to reject this pattern.

**Comment by nicolasstucki** [comment]
The issue is in PatternMatcher when deciding to emit the switch.
