### ISSUE TITLE
Code with incorrect override crashes in substution done before RefChecks (where the incorrect override is detected)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#3657]
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait ModuleSig {
      type F[_, _]
      type G[_]
      type H[_]

      trait FooSig {
        type Type = F[G[Int], H[Int]]
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooSig
    }
    val Module: ModuleSig = new ModuleSig {
      type F[x[_]] = Int

      val Foo: FooSig = new FooSig {
        // type Type = Int
        def subst[F[_]](fa: F[Int]): F[Type] = fa
      }
    }
  }
}
```

Dies with
```scala
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at scala.collection.immutable.Nil$.head(List.scala:425)
	at dotty.tools.dotc.core.Types$TypeMap.mapArgs$1(Types.scala:3825)
	at dotty.tools.dotc.core.Types$TypeMap.mapArgs$1(Types.scala:3827)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:3833)
	at dotty.tools.dotc.core.Substituters.substDealias(Substituters.scala:101)
	at dotty.tools.dotc.core.Substituters.substDealias$(Substituters.scala:76)
	at dotty.tools.dotc.core.Contexts$Context.substDealias(Contexts.scala:68)
	at dotty.tools.dotc.core.Substituters.substDealias(Substituters.scala:91)
	at dotty.tools.dotc.core.Substituters.substDealias$(Substituters.scala:76)
	at dotty.tools.dotc.core.Contexts$Context.substDealias(Contexts.scala:68)
	at dotty.tools.dotc.core.Substituters$SubstDealiasMap.apply(Substituters.scala:214)
	at dotty.tools.dotc.core.Types$TypeMap.$anonfun$mapOver$6(Types.scala:3825)
	at dotty.tools.dotc.core.Types$VariantTraversal.atVariance(Types.scala:3747)
	at dotty.tools.dotc.core.Types$TypeMap.mapArgs$1(Types.scala:3825)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:3833)
	at dotty.tools.dotc.core.Substituters.substDealias(Substituters.scala:101)
	at dotty.tools.dotc.core.Substituters.substDealias$(Substituters.scala:76)
	at dotty.tools.dotc.core.Contexts$Context.substDealias(Contexts.scala:68)
	at dotty.tools.dotc.core.Substituters$SubstDealiasMap.apply(Substituters.scala:214)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda$1(Types.scala:3862)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:3864)
	at dotty.tools.dotc.core.Substituters.substDealias(Substituters.scala:101)
	at dotty.tools.dotc.core.Substituters.substDealias$(Substituters.scala:76)
	at dotty.tools.dotc.core.Contexts$Context.substDealias(Contexts.scala:68)
	at dotty.tools.dotc.core.Types$Type.substDealias(Types.scala:1296)
	at dotty.tools.dotc.transform.FullParameterization.mapClassParams$1(FullParameterization.scala:116)
	at dotty.tools.dotc.transform.FullParameterization.$anonfun$fullyParameterizedType$11(FullParameterization.scala:129)
	at dotty.tools.dotc.transform.FullParameterization.$anonfun$fullyParameterizedType$4(FullParameterization.scala:110)
	at dotty.tools.dotc.core.Types$MethodType.<init>(Types.scala:2729)
```

**Comment by smarter** [comment]
If we try to run:
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait ModuleSig {
      type F[_, _]
      type G[_]
      type H[_]

      trait FooSig {
        type Type = F[G[Int], H[Int]]
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooSig
    }
    val Module: ModuleSig = new ModuleSig {
      type F[x[_]] = Int

      val Foo: FooSig = ???
    }
  }
}
```

```scala
16 |      type F[x[_]] = Int
   |           ^
   |error overriding type F in trait ModuleSig with bounds <: [_$1, _$2] => Any;
   | type F, which equals [x <: [_$6] => Any] => Int has incompatible type
```

This check is done in RefChecks which is now done rather late in the compiler pipeline (https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/Compiler.scala). We either need to make FullParameterization resistant to broken overrides or move the check earlier.

**Comment by allanrenucci** [comment]
Can be reproduced with `-Yforce-sbt-phases`
