### ISSUE TITLE
Test quote-run-large.scala timing out

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3827]
This test timed out at least once (http://dotty-ci.epfl.ch/lampepfl/dotty/2518/6):
```scala
failed because test ../tests/run-special/quote-run-large.scala timed out        
[error] Test dotty.tools.dotc.CompilationTests.runAll failed: java.lang.AssertionError: Run test failed, but should not, reasons:
[error]   - test '../tests/run-special/quote-run-large.scala' timed out, took 87.203 sec
[error]     at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkRuns(ParallelTesting.scala:925)
[error]     at dotty.tools.dotc.CompilationTests.runAll(CompilationTests.scala:207)
[error] ...
```
The CI was under heavy stress at that time. We may need to increase the timeout value, either globally or just for this test?

**Comment by smarter** [comment]
Happened again in http://dotty-ci.epfl.ch/lampepfl/dotty/2525/4

**Comment by smarter** [comment]
The timeout happened again: http://dotty-ci.epfl.ch/lampepfl/dotty/2603

**Comment by nicolasstucki** [comment]
Currently that tests is in `tests/pending`
