### ISSUE TITLE
Missing hole in quote

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3847]
```scala
import scala.quoted._
import scala.reflect.ClassTag
object Arrays {
  implicit def ArrayIsLiftable[T: Liftable](implicit t: Type[T], ct: Expr[ClassTag[T]]): Liftable[Array[T]] = (arr: Array[T]) => '{
    new Array[~t](~(arr.length: Expr[Int]))(~ct)
    // TODO add elements
  }
}
```
fails with
```scala
assertion failed: unresolved symbols: value t when pickling Foo.scala
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:635)
	at dotty.tools.dotc.core.quoted.PickledQuotes$.pickle(PickledQuotes.scala:74)
	at dotty.tools.dotc.core.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:24)
	at dotty.tools.dotc.transform.ReifyQuotes$Reifier.quotation(ReifyQuotes.scala:272)
	at dotty.tools.dotc.transform.ReifyQuotes$Reifier.$anonfun$transform$3(ReifyQuotes.scala:320)
```

when trying to pickle the quote
```
dotty.runtime.Arrays.newGenericArray[t.unary_~]([[0| ]])([[1| ]])
```

Note that there should be a hole in place of `t.unary_~`.

**Comment by nicolasstucki** [comment]
02f88fe16f617a35161e653b6765706a63ddb3c6 contains two tests for this.

**Comment by nicolasstucki** [comment]
The second test is identical to the original one except that the `~t` is nested into the type. In this case `new Array[List[~t]](~(arr.length: Expr[Int]))(~ct)`

**Comment by biboudis** [comment]
@nicolasstucki what is the current status of this? I don't get unresolved symbols on master.

**Comment by nicolasstucki** [comment]
I got this on master
```
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: value t when pickling Foo.scala
        at scala.Predef$.assert(Predef.scala:219)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:629)
        at dotty.tools.dotc.core.quoted.PickledQuotes$.pickle(PickledQuotes.scala:89)
        at dotty.tools.dotc.core.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:28)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.quotation(ReifyQuotes.scala:269)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.$anonfun$transform$2(ReifyQuotes.scala:317)
        at dotty.tools.dotc.reporting.trace$.op1$2(trace.scala:25)
        at dotty.tools.dotc.reporting.trace$.apply(trace.scala:26)
        at dotty.tools.dotc.reporting.trace$.apply(trace.scala:36)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.transform(ReifyQuotes.scala:307)
        at dotty.tools.dotc.transform.MacroTransformWithImplicits$ImplicitsTransformer.transform(MacroTransformWithImplicits.scala:84)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.super$transform(ReifyQuotes.scala:309)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.mapOverTree$1(ReifyQuotes.scala:309)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.$anonfun$transform$2(ReifyQuotes.scala:338)
        at dotty.tools.dotc.reporting.trace$.op1$2(trace.scala:25)
        at dotty.tools.dotc.reporting.trace$.apply(trace.scala:26)
        at dotty.tools.dotc.reporting.trace$.apply(trace.scala:36)
        at dotty.tools.dotc.transform.ReifyQuotes$Reifier.transform(ReifyQuotes.scala:307)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.$anonfun$transform$6(Trees.scala:1225)
        ...
```
