### ISSUE TITLE
NoClassDefFoundError: scala/$repeated$ when using varargs and default arguments

### ISSUE THREAD

**Issue by max-leuthaeuser** [lampepfl/dotty#4073]
With Scala 2.12.4 the following works:

```scala
class DynImpl extends Dynamic {
  def applyDynamic(name: String)(args: Any*)(implicit implicitArg: String = "foo"): String =
    s"method '$name' called with arguments ${args.mkString("'", "', '", "'")} and implicit argument '$implicitArg'"
}

object Main {
  def main(args:Array[String]): Unit = {
    val d = new DynImpl

    println(d.some())

    println(d.ints(1, 2, 3))

    println(d.strings("a", "b", "c"))
  }
}
```

The exact same code with Dotty (0.6 or latest) fails with:

```scala
sbt: [error] (run-main-d5) java.lang.NoClassDefFoundError: scala/$repeated$
sbt: java.lang.NoClassDefFoundError: scala/$repeated$
	at Main$.main(main.scala:10)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: scala.$repeated$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main$.main(main.scala:10)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by nicolasstucki** [comment]
Minimized:
```scala
object Main {
  def main(args:Array[String]): Unit = println(foo(1, 2, 3))
  def foo(args: Any*)(arg: String = "foo"): String = arg
}
```

The code that reaches the backend is:
```
package <empty> {
  @scala.annotation.internal.SourceFile("Foo.scala") final module class Main$
     extends
   Object { 
    def <init>(): Unit = 
      {
        super()
        ()
      }
    def main(args: String[]): Unit = 
      println(
        {
          val args$1: <repeated> = 
            Predef.genericWrapArray(
              [scala.Int.box(1),scala.Int.box(2),scala.Int.box(3) : Object]
            ).asInstanceOf[<repeated>]: <repeated>
          {
            closure(args$1 | this.main$$anonfun$1)
          }
        }
      )
    def foo(args: scala.collection.Seq, arg: String): String = arg
    def foo$default$2(args: scala.collection.Seq): String = "foo"
    private def main$$anonfun$1(args$1$1: <repeated>, arg: String): String = 
      Main.foo(args$1$1, arg)
  }
  final lazy module val Main: Main$ = new Main$()
}
```

There are two issues with this code
- The type of the lifted `args$1` is `<repeated>`
-  The application `foo(1, 2, 3)` becomes a closure even if `arg` has a default value.
