### ISSUE TITLE
Crash when running `npm run test`

### ISSUE THREAD

**Issue by jendrikw** [lampepfl/dotty#4109]
I was trying to do a PR for vscode-dotty, but I cannot run the tests.

Note that `/home/jendrik/dev/scala/dotty` is the folder which contains this repo.

```
$ cd vscode-dotty && npm run test

> dotty@0.1.3 test /home/jendrik/dev/scala/dotty/vscode-dotty
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###
Current working directory: /home/jendrik/dev/scala/dotty/vscode-dotty
Running extension tests: /home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/code /home/jendrik/dev/scala/dotty/vscode-dotty/test --extensionDevelopmentPath=/home/jendrik/dev/scala/dotty/vscode-dotty --extensionTestsPath=/home/jendrik/dev/scala/dotty/vscode-dotty/test
[main 23:30:34] update#setState idle

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

[main 23:31:04] update#setState checking for updates

Error: Error: Cannot find module '/home/jendrik/dev/scala/dotty/vscode-dotty/test'
	at t.handleExtensionTests (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:716:507)
	at /home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:712:854
	at Object.g [as _notify] (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:69:202)
	at Object.enter (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:556)
	at n.Class.derive._oncancel._run (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:74:380)
	at n.Class.derive._oncancel._completed (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:823)
	at c (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:267)
	at q.then.o.(anonymous function) (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:481)
	at Object.g [as _notify] (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:69:202)
	at Object.enter (/home/jendrik/dev/scala/dotty/vscode-dotty/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:556)

[main 23:31:07] update#setState idle

Tests exited with code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotty@0.1.3 test: `node ./node_modules/vscode/bin/test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dotty@0.1.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jendrik/.cache/npm/_logs/2018-03-12T22_31_10_662Z-debug.log
```

**Comment by smarter** [comment]
There's no tests for vscode-dotty currently, that's why this command fails.

**Comment by jendrikw** [comment]
Should the script in `vscode-dotty` be removed then? Can I do a PR?

**Comment by smarter** [comment]
I think it makes sense to keep it in case we add tests at some point.

**Comment by smarter** [comment]
Of course it'd be nicer to not have it crash, maybe by adding a dummy test.

**Comment by jendrikw** [comment]
I don't have experience in writing vs code plugins, but I will try to write one.
