### ISSUE TITLE
Test fail because of _JAVA_OPTIONS

### ISSUE THREAD

**Issue by jendrikw** [lampepfl/dotty#4143]
I have set up _JAVA_OPTIONS in `/etc/environment` to fix font rendering IntelliJ.
```
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#

# java font anti aliasing
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
```

For example, running `testCompilation enum-List1` fails, because there is an extra line in stderr.
```
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
[info] Test run started
[info] Test dotty.tools.dotc.CompilationTests.runAll started
Output from 'tests/run/enum-List1.scala' did not match check file.
Diff (expected on the left, actual right):
Cons(1,Cons(2,Cons(3,Nil())))  |  Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
EOF                            |  Cons(1,Cons(2,Cons(3,Nil())))
                               |  EOF

[=======================================] completed (1/1, 51s)  
[error] Test dotty.tools.dotc.CompilationTests.runAll failed: java.lang.AssertionError: Run test failed, but should not, reasons:
[error] , took 53.515 sec
[error]     at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkRuns(ParallelTesting.scala:993)
[error]     at dotty.tools.dotc.CompilationTests.runAll(CompilationTests.scala:199)
[error]     ...
[info] Test dotty.tools.dotc.CompilationTests.compileNeg started
No files matched "enum-List1" in test                                           
[info] Test dotty.tools.dotc.CompilationTests.compilePos started
No files matched "enum-List1" in test                                           
[info] Test dotty.tools.dotc.CompilationTests.testPickling started
No files matched "enum-List1" in test                                           
[info] Test dotty.tools.dotc.CompilationTests.tastyBootstrap started
No files matched "enum-List1" in test                                           
No files matched "enum-List1" in test                                           
No files matched "enum-List1" in test                                           
No files matched "enum-List1" in test                                           
[info] Test dotty.tools.dotc.CompilationTests.posTwice started
No files matched "enum-List1" in test                                           
[info] Test dotty.tools.dotc.CompilationTests.genericJavaSignatures started
No files matched "enum-List1" in test                                           

================================================================================
Test Report
================================================================================

0 passed, 1 failed, 1 total
    tests/run/enum-List1.scala failed


--------------------------------------------------------------------------------
Note - reproduction instructions have been dumped to log file:
    /home/jendrik/dev/scala/dotty/testlogs/tests-2018-03-20/tests-2018-03-20-09:18:29.log
--------------------------------------------------------------------------------
[info] Test run finished: 1 failed, 0 ignored, 7 total, 62.838s
[error] Failed: Total 7, Failed 1, Errors 0, Passed 6
[error] Failed tests:
[error] 	dotty.tools.dotc.CompilationTests
[error] (dotty-compiler/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 97 s, completed 20-Mar-2018 09:19:31
```

I browsed the issues and found #1712, which is basically the same. A filter file like discussed in that issue would fix this, but it looks like the filter is not applied for compilationTest.

**Comment by nicolasstucki** [comment]
We cannot disable remove the eviroment variable from within the JVM instance. A simple workaround  ([like we did in the past for the CI](https://github.com/lampepfl/dotty/pull/1715/files#diff-eef4506987470790e9f51de18990a80cR18)) is to unset it before launching SBT.

```
> unset _JAVA_OPTIONS
> sbt
```

**Comment by jendrikw** [comment]
It is not possible to remove these lines from the output before comparing them?

**Comment by nicolasstucki** [comment]
That could be a possibility.
