### ISSUE TITLE
IDE doesn't work if the project has no sources

### ISSUE THREAD

**Issue by Duhemm** [lampepfl/dotty#4268]
## Steps

- Create an empty project with `sbt-dotty` plugin
- `launchIDE`
- In VS Code, create an empty file `Hello.scala`

## Problems

No help from the IDE. The following is shown in the logs:

```
Starting server
Apr 06, 2018 3:10:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///Users/martin/Desktop/empty/Hello.scala",
      "languageId": "scala",
      "version": 1,
      "text": ""
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:219)
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:211)
	at scala.collection.mutable.HashMap$$anon$3.next(HashMap.scala:154)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at dotty.tools.languageserver.DottyLanguageServer.driverFor(DottyLanguageServer.scala:114)
	at dotty.tools.languageserver.DottyLanguageServer.didOpen(DottyLanguageServer.scala:180)
	... 16 more
```

**Comment by Duhemm** [comment]
@smarter Why is it necessary to filter out projects that have no sources?

https://github.com/lampepfl/dotty/blob/2f94916e38da198024d0162fb5ab6638aa51b203/sbt-dotty/src/dotty/tools/sbtplugin/DottyIDEPlugin.scala#L208-L211

**Comment by smarter** [comment]
I don't think it's actually necessary, try leaving it out and see what happens! One problem though is that when we add a source file after launchIDE, we don't know which sub-project it belongs to and just choose one at random.
Anyway, hopefully this is all fixed once we have the bsp and can just ask the build tool "which build targets is this file part of?"

**Comment by Duhemm** [comment]
I indeed has some issues after changing that with Dotty IDE on the Dotty codebase. I think this is a non-issue, since the IDE should rather start when editing a file with `language:scala`.

Thanks for the answers!
