### ISSUE TITLE
Cannot unpickle secondary constructors in quotes

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#4313]
```
val q = '{
  class Foo(a: Int) {
    def this() = this(6)
  }
  ()
}
q.show
```

fails with

```
wrong number of arguments at <no phase> for (): Foo: ((): Foo)(Foo.this.<init>), expected: 0, found: 1
```

**Comment by bishabosha** [comment]
I tested this and still fails at runtime:
```scala
Exception in thread "main" class dotty.tools.dotc.reporting.Diagnostic$Error at sandbox/staging.scala:<301..302>: wrong number of arguments at <no phase> for (): Foo: (Foo.this.<init> : (): Foo), expected: 0, found: 1
	at dotty.tools.dotc.report$.error(report.scala:71)
	at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:34)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:285)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:20)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:103)
	at dotty.tools.dotc.ast.tpd$.Apply(tpd.scala:46)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1130)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1289)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:988)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats$$anonfun$1(TreeUnpickler.scala:1026)
	at dotty.tools.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1026)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:1030)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1142)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1289)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.readRhs$2$$anonfun$2$$anonfun$1(TreeUnpickler.scala:811)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1426)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy(Trees.scala:967)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy$(Trees.scala:962)
	at dotty.tools.dotc.ast.Trees$ValOrDefDef.forceIfLazy(Trees.scala:377)
	at dotty.tools.dotc.ast.Trees$ValOrDefDef.rhs(Trees.scala:382)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1547)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1585)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$2.traverse(PickledQuotes.scala:198)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1459)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1461)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1554)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1585)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$2.traverse(PickledQuotes.scala:198)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1551)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1585)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$2.traverse(PickledQuotes.scala:198)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1459)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1461)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1492)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1585)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$2.traverse(PickledQuotes.scala:198)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1584)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1512)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1465)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1585)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$2.traverse(PickledQuotes.scala:198)
	at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:199)
	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:57)
	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2893)
	at Test$.main$$anonfun$1(staging.scala:10)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.quoted.staging.package$.dummyRun$1(staging.scala:39)
	at scala.quoted.staging.package$.withQuotes$$anonfun$1(staging.scala:42)
	at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn$$anonfun$1(QuoteCompiler.scala:82)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn(QuoteCompiler.scala:97)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
	at scala.quoted.staging.QuoteCompiler$ExprRun.compileExpr(QuoteCompiler.scala:117)
	at scala.quoted.staging.QuoteDriver.run(QuoteDriver.scala:39)
	at scala.quoted.staging.Compiler$$anon$1.run(Compiler.scala:38)
	at scala.quoted.staging.package$.withQuotes(staging.scala:42)
	at Test$.main(staging.scala:16)
	at Test.main(staging.scala)

```
