### ISSUE TITLE
NoSuchElementException in typing anonymous function with quotes

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#4380]
The problem doesn't appear when I remove quotes or the `new Producer` or the `val adv` in line 17 or try to type the `step` method outside the `new Producer`🤔. However, it can be minimized further I think.

```scala
import scala.quoted._

object Test {

  trait Producer[A] { self =>
    def step(k: (A => Expr[Unit])): Expr[Unit]
  }

  trait Foo[A]
  case class Bar[A, B](producer: Producer[B], nestedf: B => Expr[Unit]) extends Foo[A]

  def meth[A](stream: Foo[Expr[A]]): Producer[Expr[A]] = {
    stream match {
      case Bar(producer, nestedf) => {
        new Producer[Expr[A]] {
          def step(k: Expr[A] => Expr[Unit]): Expr[Unit] = '{
            val adv: Unit => Unit = { _ => ~producer.step((el) => nestedf(el))}
          }
        }
      }
    }
  }
}
```

```scala
java.util.NoSuchElementException: key not found: method $anonfun while traversing nestedf
java.util.NoSuchElementException: key not found: method $anonfun while traversing nestedf.apply
java.util.NoSuchElementException: key not found: method $anonfun while traversing nestedf.apply(el)
java.util.NoSuchElementException: key not found: method $anonfun while traversing nestedf.apply(el).asInstanceOf
java.util.NoSuchElementException: key not found: method $anonfun while traversing nestedf.apply(el).asInstanceOf[scala.quoted.Expr]
java.util.NoSuchElementException: key not found: method $anonfun while traversing def $anonfun(el: Object): scala.quoted.Expr =
  nestedf.apply(el).asInstanceOf[scala.quoted.Expr]
java.util.NoSuchElementException: key not found: method $anonfun while traversing {
  def $anonfun(el: Object): scala.quoted.Expr =
    nestedf.apply(el).asInstanceOf[scala.quoted.Expr]
  closure($anonfun:Function1)
}
.....
Exception in thread "main" java.util.NoSuchElementException: key not found: method $anonfun
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at dotty.tools.dotc.transform.LambdaLift$Lifter.narrowLiftedOwner(LambdaLift.scala:99)
	at .....
```

**Comment by nicolasstucki** [comment]
There is a wrong owner for an anonymous function after `ReifyQuotes`. `-Ycheck:all` shows which one.

**Comment by nicolasstucki** [comment]
Minimized to 
```
import scala.quoted._

object Test {
  def step(k: (String => Expr[Unit])): Expr[Unit] = '()
  def meth(): Unit = '{
    (i: Int) => ~step(el => '() )
  }
}
```

fails with `-Ycheck:all`

**Comment by nicolasstucki** [comment]
The optimization done in bf13d5b611cc13e1589ad9350d589e77c56b32a3 broke some owners.
