### ISSUE TITLE
REPL: values that fail to initialise should not be accessible in later runs

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4416]
```scala
scala> val x = 1 / 0 
java.lang.ArithmeticException: / by zero
	at rs$line$5$.<init>(rs$line$5:1)
	at rs$line$5$.<clinit>(rs$line$5)
	at rs$line$5.xShow(rs$line$5)
        ...

scala> def foo = x // should not compile
def foo: Int

scala> x // should not compile
java.lang.NoClassDefFoundError: Could not initialize class rs$line$5$
	at rs$line$8$.<init>(rs$line$8:1)
	at rs$line$8$.<clinit>(rs$line$8)
	at rs$line$8.res3Show(rs$line$8)
```

**Comment by allanrenucci** [comment]
Good analysis! I suggest you patch `displayDefinitions`
https://github.com/lampepfl/dotty/blob/17c4497455de59f56c4704053608599fa4f225b4/compiler/src/dotty/tools/repl/ReplDriver.scala#L249

It should probably return the old state if a failure occurs during evaluation. I think `renderVal` should return a `Try[String]`
https://github.com/lampepfl/dotty/blob/17c4497455de59f56c4704053608599fa4f225b4/compiler/src/dotty/tools/repl/Rendering.scala#L73

**Comment by allanrenucci** [comment]
Ideally, I think we should decouple rendering and evaluation. But it's probably best implemented as another PR

**Comment by Blaisorblade** [comment]
Just run today into a likely variant:
```
scala> val 行 = 1; val D = 3; val (行, D) = (1, 2)
scala.MatchError: (1,2) (of class scala.Tuple2)
	at rs$line$2$.<init>(rs$line$2:1)
	at rs$line$2$.<clinit>(rs$line$2)
	at rs$line$2.行(rs$line$2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:56)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:56)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:85)
	at dotty.tools.repl.ReplDriver.displayMembers$3$$anonfun$3(ReplDriver.scala:271)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dotty.tools.repl.ReplDriver.displayMembers$7(ReplDriver.scala:271)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$3$$anonfun$2(ReplDriver.scala:300)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1(ReplDriver.scala:300)
	at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
	at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:37)
	at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:305)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:229)
	at scala.util.Either.fold(Either.scala:187)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:229)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:184)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:129)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:132)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:192)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:163)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:145)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:132)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)

java.lang.NoClassDefFoundError: Could not initialize class rs$line$2$
	at rs$line$2.D(rs$line$2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:56)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:56)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:85)
	at dotty.tools.repl.ReplDriver.displayMembers$3$$anonfun$3(ReplDriver.scala:271)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dotty.tools.repl.ReplDriver.displayMembers$7(ReplDriver.scala:271)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$3$$anonfun$2(ReplDriver.scala:300)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1(ReplDriver.scala:300)
	at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
	at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:37)
	at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:305)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:229)
	at scala.util.Either.fold(Either.scala:187)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:229)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:184)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:129)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:132)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:192)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:163)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:145)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:132)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
