### ISSUE TITLE
REPL doesn't work on Windows

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4587]
I heard mentions of this, but I wasn't sure and couldn't find an issue for this (only discussion in #2524). I only thought support was limited, not that things crashed right away.

This is inside the Mingw/MSYS2-based "Git Bash" from https://gitforwindows.org/ on an official Win 10 VM. We should also support the standard terminal I guess (well, as well as scala does), but bash scripts don't work in it — IIRC Scala 2 provides .BAT files for that reason.

Output:
```scala
$ dotr
Starting dotty REPL...
bash: /dev/tty: No such device or address
Exception in thread "main" java.lang.NullPointerException
        at dotty.tools.repl.terminal.Terminal$.initialConfig$1(Terminal.scala:30                                                                                                                                   2)
        at dotty.tools.repl.terminal.Terminal$.readLine(Terminal.scala:313)
        at dotty.tools.repl.AmmoniteReader.prompt(AmmoniteReader.scala:125)
        at dotty.tools.repl.ReplDriver.readLine(ReplDriver.scala:194)
        at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:140)
        at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:                                                                                                                                   154)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$                                                                                                                                   1(ReplDriver.scala:163)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withErr(Console.scala:192)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDrive                                                                                                                                   r.scala:163)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withOut(Console.scala:163)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:163                                                                                                                                   )
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:154)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by smarter** [comment]
Known issue: https://github.com/lampepfl/dotty/issues/4309
