### ISSUE TITLE
Stale $companion symbol

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#460]
Compiling the following file

    object o {
        class A
        class B
        val x: A => Unit = ???
     }

twice gives a staleSymbol error:

java dotty.tools.dotc.Bench #runs 2 staleSymbol.scala
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenMapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$MapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenSetFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$SetFactory$$CC; assuming they are invariant
four warnings found
time elapsed: 2153ms
dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol; val companion$class#11674 in module class Predef$$ArrowAssoc$, defined in Period(1..21, run = 2), is referred to in run Period(33..33, run = 3)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.staleSymbolError(Denotations.scala:641)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:509)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:536)
	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:362)
	at dotty.tools.dotc.core.Scopes$Scope.denotsNamed(Scopes.scala:119)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.companionClass(SymDenotations.scala:795)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.linkedClass(SymDenotations.scala:839)
	at dotty.tools.backend.jvm.DottyBackendInterface$$anon$9.linkedClass(DottyBackendInterface.scala:510)
	at dotty.tools.backend.jvm.DottyBackendInterface$$anon$9.linkedClass(DottyBackendInterface.scala:395)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.scala$tools$nsc$backend$jvm$BTypesFromSymbols$$setClassInfo(BTypesFromSymbols.scala:115)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:63)

**Comment by DarkDimius** [comment]
@odersky I guess I know where this comes from. Let me have a look.

**Comment by DarkDimius** [comment]
Running on #458 I cannot reproduce the problem.
```
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{refchecks, elimRepeated, normalizeFlags, extmethods, tailrec}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{LazyVals, seqLiterals, intercepted, literalize, getters, elimByName, resolveSuper}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{mixin, memoize, capturedVars, constructors}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{lambdaLift, flatten, restoreScopes}
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenMapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$MapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenSetFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$SetFactory$$CC; assuming they are invariant
four warnings found
time elapsed: 1397ms
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{refchecks, elimRepeated, normalizeFlags, extmethods, tailrec}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{LazyVals, seqLiterals, intercepted, literalize, getters, elimByName, resolveSuper}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{mixin, memoize, capturedVars, constructors}
checking ./tests/pos/companions-twice.scala after phase TreeTransform:{lambdaLift, flatten, restoreScopes}
time elapsed: 89ms
```

**Comment by odersky** [comment]
Doh. I ran it without my stale symbol fixes. Good that you noticed!
