### ISSUE TITLE
Compiler crash: Implicit Function types + SAM

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4611]
```scala
trait Responder[T] {
  def responseFor(value: T): implicit Request => T
}

object Responder {
  val responseResponder: Responder[Response] =
    response => response
}

class Response
class Request
```
```
exception occurred while compiling tests/allan/Test.scala
Exception in thread "main" scala.MatchError: ArrayBuffer(<SingleDenotation of type MethodType(List(value), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)), AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class ImplicitFunction1),List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Request), TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response))))>, <SingleDenotation of type MethodType(List(value), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)), MethodType(List(x$0), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Request)), TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)))>) (of class scala.collection.mutable.ArrayBuffer)
	at dotty.tools.dotc.transform.ExpandSAMs.transformBlock(ExpandSAMs.scala:46)
	at dotty.tools.dotc.transform.MegaPhase.goBlock(MegaPhase.scala:668)
        ...
```
Initially reported by @jeffmay on Gitter

**Comment by jeffmay** [comment]
Woah, nice simplification!

Also, my dotty version was `0.9.0-bin-20180529-be6ae0e-NIGHTLY` and the full project (on a branch) is https://github.com/jeffmay/context-in-dotty/tree/sam-compiler-bug
