### ISSUE TITLE
simple file does not pass Ycheck after restoreScopes

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#462]
```
package foo
object Bar {
}
```
running on 6c6177c
```
> runMain dotty.tools.dotc.Bench #runs 2 ./tests/pos/empty-foo.scala -Ycheck:all
[info] Running dotty.tools.dotc.Bench #runs 2 ./tests/pos/empty-foo.scala -Ycheck:all
[info] checking ./tests/pos/empty-foo.scala after phase frontend
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{firstTransform, synthetics}
[info] checking ./tests/pos/empty-foo.scala after phase superaccessors
[info] checking ./tests/pos/empty-foo.scala after phase pickler
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{refchecks, elimRepeated, normalizeFlags, extmethods, tailrec}
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{patternMatcher, explicitOuter, splitter}
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{LazyVals, seqLiterals, intercepted, literalize, getters, elimByName, resolveSuper}
[info] checking ./tests/pos/empty-foo.scala after phase erasure
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{mixin, memoize, capturedVars, constructors}
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] [error] class defined twice module class Bar$ 7259 5238
[info] checking ./tests/pos/empty-foo.scala after phase TreeTransform:{lambdaLift, flatten, restoreScopes}
[info] exception while typing new foo.Bar$() of class class dotty.tools.dotc.ast.Trees$Apply # 91
[info] exception while typing final lazy module val Bar: foo.Bar$ = new foo.Bar$() of class class dotty.tools.dotc.ast.Trees$ValDef # 92
[info] exception while typing package foo {
[info]   final lazy module val Bar: foo.Bar$ = new foo.Bar$()
[info]   final module class Bar$ extends Object { this: <notype> =>
[info]     def <init>(): foo.Bar$ = {
[info]       Bar$.super()
[info]       ()
[info]     }
[info]   }
[info] } of class class dotty.tools.dotc.ast.Trees$PackageDef # 117
[info] *** error while checking after phase restoreScopes ***
[error] Exception in thread "main" java.lang.AssertionError: assertion failed: non member selection of constructor Bar$ in object Bar$ from foo.Bar$
[error] 	at scala.Predef$.assert(Predef.scala:165)
[error] 	at dotty.tools.dotc.transform.FirstTransform.checkPostCondition(FirstTransform.scala:43)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedUnadapted$1.apply(TreeChecker.scala:183)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker$$anonfun$typedUnadapted$1.apply(TreeChecker.scala:183)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:183)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1088)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1086)
[error] 	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:147)
[error] 	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:51)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1086)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1125)
[error] 	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:516)
[error] 	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:512)
[error] 	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
[error] 	at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:512)
[error] 	at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:578)
[error] 	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:58)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1038)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1078)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:93)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:166)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1088)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1086)
[error] 	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:147)
[error] 	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:51)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1086)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1125)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:880)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:874)
[error] 	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
[error] 	at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:874)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1023)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1076)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:93)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:166)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1088)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1086)
[error] 	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:147)
[error] 	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:51)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1086)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1110)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1121)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:275)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:969)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:960)
[error] 	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:960)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1066)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1078)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:93)
[error] 	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:166)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1088)
[error] 	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1086)
[error] 	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:147)
[error] 	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:51)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1086)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1125)
[error] 	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:100)
[error] 	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:78)
[error] 	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:266)
[error] 	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:264)
[error] 	at scala.collection.immutable.List.map(List.scala:273)
[error] 	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:264)
[error] 	at dotty.tools.dotc.transform.TreeChecker.runOn(TreeChecker.scala:38)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileSources$1$$anonfun$apply$mcV$sp$3.apply(Run.scala:50)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileSources$1$$anonfun$apply$mcV$sp$3.apply(Run.scala:47)
[error] 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply$mcV$sp(Run.scala:47)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply(Run.scala:42)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply(Run.scala:42)
[error] 	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:68)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:41)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:32)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:20)
[error] 	at dotty.tools.dotc.Bench$.dotty$tools$dotc$Bench$$super$doCompile(Bench.scala:38)
[error] 	at dotty.tools.dotc.Bench$$anonfun$doCompile$1.apply(Bench.scala:38)
[error] 	at dotty.tools.dotc.Bench$$anonfun$doCompile$1.apply(Bench.scala:36)
[error] 	at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:30)
[error] 	at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:30)
[error] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
[error] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
[error] 	at scala.collection.immutable.Range.foreach(Range.scala:166)
[error] 	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
[error] 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
[error] 	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:136)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at dotty.tools.dotc.Bench$.ntimes(Bench.scala:30)
[error] 	at dotty.tools.dotc.Bench$.doCompile(Bench.scala:36)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:31)
[error] 	at dotty.tools.dotc.Bench$.dotty$tools$dotc$Bench$$super$process(Bench.scala:53)
[error] 	at dotty.tools.dotc.Bench$$anonfun$process$1.apply(Bench.scala:53)
[error] 	at dotty.tools.dotc.Bench$$anonfun$process$1.apply(Bench.scala:53)
[error] 	at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:30)
[error] 	at dotty.tools.dotc.Bench$$anonfun$ntimes$1.apply(Bench.scala:30)
[error] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
[error] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
[error] 	at scala.collection.immutable.Range.foreach(Range.scala:166)
[error] 	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
[error] 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
[error] 	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:136)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at dotty.tools.dotc.Bench$.ntimes(Bench.scala:30)
[error] 	at dotty.tools.dotc.Bench$.process(Bench.scala:53)
[error] 	at dotty.tools.dotc.Driver.main(Driver.scala:40)
[error] 	at dotty.tools.dotc.Bench.main(Bench.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last dotty/compile:runMain for the full output.
[error] (dotty/compile:runMain) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed Apr 4, 2015 2:02:27 AM
```

**Comment by DarkDimius** [comment]
Please also see #461. This file sometimes fails to compile in hard-to-reproduce cases.

**Comment by DarkDimius** [comment]
Cannot reproduce anymore.
