### ISSUE TITLE
Completion on self type crashes Dotty IDE

### ISSUE THREAD

**Issue by Duhemm** [lampepfl/dotty#4646]
# Steps:

1. `launchIDE`
2. Open a file, `NameBuffer.scala` for instance.
3. Add a new class before `class NameBuffer`:
   ```scala
   class MyClass { self => }
   ```
4. Change it to:
   ```scala
   class MyClass { self: M => }
   ```
5. As soon as the `M` is typed, the following stack trace appears:
```
[Error - 10:24:04 AM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.AssertionError: assertion failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:35)
	at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:350)
	at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
	at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
	at dotty.tools.dotc.interactive.Interactive$.completions(Interactive.scala:103)
	at dotty.tools.languageserver.DottyLanguageServer.completion$$anonfun$1(DottyLanguageServer.scala:232)
	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

**Comment by gberlanga** [comment]
This has the same issue.

https://github.com/lampepfl/dotty/issues/4836

**Comment by allanrenucci** [comment]
> This has the same issue.

I think it is two separate issues. The stack trace is not the same:
```
Caused by: java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:35)
	at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:350)
```
vs
```
Caused by: java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
	at dotty.tools.dotc.util.Positions$Position$.start$extension(Positions.scala:40)
```

**Comment by Duhemm** [comment]
I can still reliably reproduce on current HEAD: 1d24eaaeff847b8b67fa914b56a8005c8cf4a094

**Comment by Duhemm** [comment]
This test reproduces the crash:

```scala
  @Test def completeSelfType: Unit = {
    code"""class Foo { self: Fo${m1} => }""".withSource
      .completion(m1, Set(("Foo", CompletionItemKind.Class, "Object{...}")))
  }
```

To be pasted in `language-server/test/dotty/tools/languageserver/CompletionTest.scala`, and run with:

```
sbt:dotty> dotty-language-server/testOnly dotty.tools.languageserver.CompletionTest -- --tests=completeSelfType
```

```
[info] Compiling 1 Scala source to /Users/martin/Documents/Projects.nosync/Duhemm/dotty/language-server/../out/bootstrap/dotty-language-server/scala-0.10/test-classes ...
[info] Done compiling.
[info] Test dotty.tools.languageserver.CompletionTest.completion0 ignored
[info] Test dotty.tools.languageserver.CompletionTest.completionWithImplicitConversion ignored
[info] Test run started
[info] Test dotty.tools.languageserver.CompletionTest.completeSelfType started
java.lang.AssertionError: assertion failed
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
        at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:350)
        at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
        at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
        at dotty.tools.dotc.interactive.Interactive$.completions(Interactive.scala:103)
        at dotty.tools.languageserver.DottyLanguageServer.completion$$anonfun$1(DottyLanguageServer.scala:232)
        at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
        at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Test dotty.tools.languageserver.CompletionTest.completeSelfType failed: java.util.concurrent.ExecutionException: java.lang.AssertionError: assertion failed, took 1.857 sec
[error]     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
[error]     at dotty.tools.languageserver.util.actions.CodeCompletion.execute$direct(CodeCompletion.scala:23)
[error]     at dotty.tools.languageserver.util.CodeTester.doAction(CodeTester.scala:121)
[error]     at dotty.tools.languageserver.util.CodeTester.completion(CodeTester.scala:80)
[error]     at dotty.tools.languageserver.CompletionTest.completeSelfType(CompletionTest.scala:25)
[error]     ...
[error] Caused by: java.lang.AssertionError: assertion failed
[error]     at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
[error]     at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:350)
[error]     at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
[error]     at dotty.tools.dotc.interactive.Interactive$.contextOfPath(Interactive.scala:335)
[error]     at dotty.tools.dotc.interactive.Interactive$.completions(Interactive.scala:103)
[error]     at dotty.tools.languageserver.DottyLanguageServer.completion$$anonfun$1(DottyLanguageServer.scala:232)
[error]     at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
[error]     at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
[error]     at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[error]     at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[error]     at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
[error]     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] Test run finished: 1 failed, 0 ignored, 1 total, 1.863s
[error] Failed: Total 3, Failed 1, Errors 0, Passed 0, Skipped 2
[error] Failed tests:
[error]         dotty.tools.languageserver.CompletionTest
[error] (dotty-language-server / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Aug 30, 2018 1:35:23 PM
```
