### ISSUE TITLE
VS Code: CompletionException caused by AssertionError

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#4836]
Got this in the output console while starting to explore the dotty repo using VS Code:
```
[Error - 10:07:29 AM] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.AssertionError: assertion failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
	at dotty.tools.dotc.util.Positions$Position$.start$extension(Positions.scala:40)
	at dotty.tools.dotc.util.SourcePosition.start(SourcePosition.scala:45)
	at dotty.tools.dotc.util.SourcePosition.startLine(SourcePosition.scala:46)
	at dotty.tools.languageserver.DottyLanguageServer$.range(DottyLanguageServer.scala:411)
	at dotty.tools.languageserver.DottyLanguageServer$.location(DottyLanguageServer.scala:417)
	at dotty.tools.languageserver.DottyLanguageServer$.symbolInfo(DottyLanguageServer.scala:508)
	at dotty.tools.languageserver.DottyLanguageServer.documentSymbol$$anonfun$2$$anonfun$1(DottyLanguageServer.scala:364)
	at dotty.tools.languageserver.DottyLanguageServer$$Lambda$1044/240053627.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:287)
	at dotty.tools.languageserver.DottyLanguageServer.documentSymbol$$anonfun$1(DottyLanguageServer.scala:364)
	at dotty.tools.languageserver.DottyLanguageServer$$Lambda$1040/653571007.apply(Unknown Source)
	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
	at dotty.tools.languageserver.DottyLanguageServer$$Lambda$27/547571630.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```
in case that's enough info to understand anything.

FTR, the HEAD of my dotty repo is 18fa15e1502c11c290960fe1a519f00091ac3c50.

**Comment by smarter** [comment]
It would help to know on which file this happened, otherwise it's basically impossible to reproduce

**Comment by sjrd** [comment]
I was typing random code in `Trees.scala` at the time. But it comes up a lot for me.

**Comment by smarter** [comment]
Fixed a while back by https://github.com/lampepfl/dotty/pull/5151
