### ISSUE TITLE
Crash when extending a type alias to a trait with implicit parameter

### ISSUE THREAD

**Issue by Medowhill** [lampepfl/dotty#4837]
I found this issue while trying to write some tests for issue #4582. PR #4827 is related.
```scala
trait T[X]
type Foo[X, Y] = T[X]
class D[X] extends Foo[X, Unit]
```
```scala
trait T[X: Numeric]
type Foo[X] = T[X]
class D[X: Numeric] extends Foo[X]
```
Two above examples were compiled.
```scala
trait T[X: Numeric]
type Foo[X, Y] = T[X]
class D[X: Numeric] extends Foo[X, Unit]
```
However, this one resulted the following crash:
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: missing parameters for trait T from ($outer: C, implicit evidence$2: scala.math.Numeric) extends Object() with T {
  private implicit val evidence$2: scala.math.Numeric
  private val $outer: C
  private <accessor> def $outer(): C = this.$outer
  final def C$D$$$outer(): C = D.this.$outer()
} should have been caught in typer
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.transform.Mixin.nextArgument$1(Mixin.scala:209)
	at dotty.tools.dotc.transform.Mixin.$anonfun$transformTemplate$12(Mixin.scala:235)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at dotty.tools.dotc.transform.Mixin.traitInits$1(Mixin.scala:217)
	at dotty.tools.dotc.transform.Mixin.$anonfun$transformTemplate$17(Mixin.scala:263)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at dotty.tools.dotc.transform.Mixin.transformTemplate(Mixin.scala:262)
	at dotty.tools.dotc.transform.Mixin.transformTemplate(Mixin.scala:98)
	at dotty.tools.dotc.transform.MegaPhase.goTemplate(MegaPhase.scala:922)
```

**Comment by Medowhill** [comment]
Further investigation

1st code:
```scala
// after frontend
class D[X >: Nothing <: Any]() extends Object() with C.this.Foo[D.this.X, Unit] {
// after erasure
class D($outer: C, implicit evidence$2: scala.math.Numeric) extends Object() with T {
```
2nd code:
```scala
// after frontend
class D[X >: Nothing <: Any](implicit evidence$2: Numeric[X])
  extends Object() with T[D.this.X]()(evidence$2) {
// after erasure
class D($outer: C, implicit evidence$2: scala.math.Numeric) extends Object() with T(evidence$2) {
```
3rd code:
```scala
// after frontend
class D[X >: Nothing <: Any](implicit evidence$2: Numeric[X])
  extends Object () with C.this.Foo[D.this.X, Unit] {
// after erasure
class D($outer: C) extends Object() with T {
```

and another crash
```scala
trait T(x: Int)
type Foo[X] = T
class D extends Foo[Int]
```
It should be rejected by the typer but it passed the phase and resulted the same crash.

**Comment by Medowhill** [comment]
I think changing `Typer.scala` as the following would be a valid fix for this issue.
line 1478:
`typedExpr(untpd.New(ref, Nil))(superCtx)` ->
`typedExpr(untpd.New(untpd.TypedSplice(ref), Nil))(superCtx)`
line 1495:
`val psym = result.tpe.typeSymbol` ->
`val psym = result.tpe.dealias.typeSymbol`
However, it needs a correct implementation of `untpd.New`. Therefore, I'll make a PR after #4798 is merged to the master branch.

**Comment by allanrenucci** [comment]
> However, it needs a correct implementation of untpd.New. Therefore, I'll make a PR after #4798 is merged to the master branch.

You can make a PR based on the #4798 branch and rebase once it's merged. Or wait, up to you! 😄
