### ISSUE TITLE
NoClassDefFoundError with transparent and repeated arguments

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4852]
```scala
scala> transparent def foo[T](t : T*) : Any = t
erased val foo[T](t: T*): Any

scala> foo(1, "hi", false)
Exception in thread "main" java.lang.NoClassDefFoundError: scala/$repeated$
[...]
```

Instigated by @soronpo in https://github.com/lampepfl/dotty/pull/4616#issuecomment-408142653.

**Comment by Blaisorblade** [comment]
@nicolasstucki Can you check if this is something in your purview, or is this something for Martin?

**Comment by nicolasstucki** [comment]
The issue only appears in the REPL.

This issue is related to the inlining:
```scala
scala> @forceInline def foo[T](t : T*) : Any = t
def foo[T](t: T*): Any

scala> foo()                                                                           
Exception in thread "main" java.lang.NoClassDefFoundError: scala/$repeated$
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:54)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:85)
	at dotty.tools.repl.ReplDriver.$anonfun$displayDefinitions$8(ReplDriver.scala:263)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	...
```

It is unrelated to `erased` as the following works:
```scala
scala> erased def foo[T](t : T*) : Any = t                        
erased val foo[T](t: T*): Any

scala> foo()                                                                           
1 |foo()
  |^^^
  |method foo is declared as erased, but is in fact used

scala> erased val a = foo()

scala>
```
