### ISSUE TITLE
AbstractMethodError with abstract override and super accessors

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4943]
Compiling and running
```scala
object Main {

  def main(args: Array[String]): Unit = {
    val obj = new Combined
    println(s"obj: ${obj}")
  }

  class Combined extends SuppressToString with WrapToString

  abstract class SuppressToString {
    override def toString(): String
  }

  trait WrapToString {
    override def toString(): String = "WrapToString: " + super.toString
  }
}
```

gives an `AbstractMethodError`:

```
Exception in thread "main" java.lang.AbstractMethodError: Main$SuppressToString.toString()Ljava/lang/String;
	at Main$Combined.Main$WrapToString$$super$toString(abstract.scala:7)
	at Main$WrapToString.toString(abstract.scala:14)
	at Main$Combined.toString(abstract.scala:7)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at Main$.main(abstract.scala:4)
	at Main.main(abstract.scala)
```

The same code fails in Scalac as well (https://github.com/scala/bug/issues/11075). The code should either use the default `toString` or fail to compile, I forget which was the specified behavior (and if it's the same as in Scala 2).

**Comment by Blaisorblade** [comment]
Both Scala and Dotty give the same behavior, and apparently the bug is not even superaccessor-specific. One of the super calls seems to resolve to an abstract method. I'm not sure what the JVM specifies here.

Here's a disassembly (with pieces omitted). The crashing call is from superaccessor `Combined.Main$WrapToString$$super$toString()` to `super[Main$SuppressToString].toString()`, which is indeed `abstract`.

```
// Decompiled by Jad v1.5.8g.
// Jad home page: http://www.kpdus.com/jad.html

public final class Main {
    public static class Combined extends SuppressToString implements WrapToString {

        public String Main$WrapToString$$super$toString() {
            return super.toString();
        //    0    0:aload_0         
        //    1    1:invokespecial   #23  <Method String Main$SuppressToString.toString()>
        //    2    4:areturn         
        }

        public String toString() {
            return super.toString();
        //    0    0:aload_0         
        //    1    1:invokespecial   #24  <Method String Main$WrapToString.toString()>
        //    2    4:areturn         
        }
    }

    public static abstract class SuppressToString {
        public abstract String toString();
    }

    public static interface WrapToString
    {
        public abstract String Main$WrapToString$$super$toString();

        public String toString()
        {
            return (new StringBuilder()).append("WrapToString: ").append(Main$WrapToString$$super$toString()).toString();
        //    0    0:new             #13  <Class StringBuilder>
        //    1    3:dup             
        //    2    4:invokespecial   #17  <Method void StringBuilder()>
        //    3    7:ldc1            #19  <String "WrapToString: ">
        //    4    9:invokevirtual   #23  <Method StringBuilder StringBuilder.append(String)>
        //    5   12:aload_0         
        //    6   13:invokeinterface #25  <Method String Main$WrapToString$$super$toString()>
        //    7   18:invokevirtual   #23  <Method StringBuilder StringBuilder.append(String)>
        //    8   21:invokevirtual   #27  <Method String StringBuilder.toString()>
        //    9   24:areturn         
        }
    }
}
```
