### ISSUE TITLE
Minimize and fix compiler crash on pdbp.github.io

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4974]
Compiling @PDBP https://github.com/PDBP/pdbp.github.io with a snapshot after the fix of #4721 gives the following:

```scala
[error] java.lang.AssertionError: assertion failed
[error] 	at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
[error] 	at dotty.tools.dotc.core.Types$MethodType.<init>(Types.scala:2941)
[error] 	at dotty.tools.dotc.core.Types$CachedMethodType.<init>(Types.scala:2958)
[error] 	at dotty.tools.dotc.core.Types$MethodTypeCompanion.apply(Types.scala:3026)
[error] 	at dotty.tools.dotc.core.Types$MethodTypeCompanion.apply(Types.scala:3025)
[error] 	at dotty.tools.dotc.core.Types$LambdaType.newLikeThis(Types.scala:2768)
[error] 	at dotty.tools.dotc.core.Types$LambdaType.derivedLambdaType(Types.scala:2763)
[error] 	at dotty.tools.dotc.transform.ShortcutImplicits$.directInfo(ShortcutImplicits.scala:178)
[error] 	at dotty.tools.dotc.transform.ShortcutImplicits$.directInfo(ShortcutImplicits.scala:177)
[error] 	at dotty.tools.dotc.transform.ShortcutImplicits$.dotty$tools$dotc$transform$ShortcutImplicits$$$newShortcutMethod(ShortcutImplicits.scala:188)
[error] 	at dotty.tools.dotc.transform.ShortcutImplicits$.shortcutMethod$$anonfun$2(ShortcutImplicits.scala:197)
[error] 	at dotty.tools.dotc.core.Symbols$Symbol.orElse(Symbols.scala:575)
[error] 	at dotty.tools.dotc.transform.ShortcutImplicits$.shortcutMethod(ShortcutImplicits.scala:197)
[error] 	at dotty.tools.dotc.transform.Bridges.add(Bridges.scala:129)
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:700)
[error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1565)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1809)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1931)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1965)
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:702)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:664)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:667)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1825)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1976)
[error] 	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1462)
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:595)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1806)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1931)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1965)
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:702)
[error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1565)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1809)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1931)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1965)
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:702)
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1675)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1848)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1976)
[error] 	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:99)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:298)
[error] 	at scala.collection.immutable.List.map(List.scala:287)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:300)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:175)
[error] 	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
[error] 	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:187)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:195)
[error] 	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:202)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:137)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:121)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:31)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:134)
[error] 	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:61)
[error] 	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:51)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:35)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1430)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1404)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Blaisorblade** [comment]
Closing in favor of minimized #5212.
