### ISSUE TITLE
AssertionError somewhere in the typer (parser stability)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5003]
```scala
class i0 {
  def i1[](i2): i3 = i1(i1) =>
}
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: inconsistent: no typevars were added to committable constraint  constrained types = PolyType(List(<error>), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), MethodType(List(i2), List(TypeParamRef(<error>)), dotty.tools.dotc.core.Types$$anon$8@6fd83fc1))
List(PolyType(List(<error>), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), MethodType(List(i2), List(TypeParamRef(<error>)), dotty.tools.dotc.core.Types$$anon$8@6fd83fc1)))
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.typer.ProtoTypes$.constrained(ProtoTypes.scala:456)
	at dotty.tools.dotc.typer.ProtoTypes$.constrained(ProtoTypes.scala:488)
	at dotty.tools.dotc.typer.ProtoTypes$.normalize(ProtoTypes.scala:531)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.typeMismatch(ErrorReporting.scala:88)
	at dotty.tools.dotc.typer.Typer.adaptType$1(Typer.scala:2531)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:2580)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2131)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:312)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:435)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:473)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:256)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:565)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:663)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:693)
	at dotty.tools.dotc.typer.Applications.realApply$4$$anonfun$3(Applications.scala:693)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1984)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:693)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:794)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1818)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
```
AE-0f507ab5caa669b2d1d924604ba4143f5322ce9d

**Comment by smarter** [comment]
Already fixed, and the test is in https://github.com/lampepfl/dotty/blob/master/tests/fuzzy/AE-0f507ab5caa669b2d1d924604ba4143f5322ce9d.scala
