### ISSUE TITLE
AssertionError due to recursive inheritance from a case class extending AnyVal.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5005]
```scala
case class i0 (i0: i1) extends AnyVal
trait i1 extends i0
```
```scala
no sig for TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class i0) because of ()
failure while taking result signature of (i0: i1): i0: i0
cannot take signature of (i0: i1): i0

Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:37)
	at dotty.tools.dotc.core.TypeErasure$ErasedValueType$.apply(TypeErasure.scala:89)
	at dotty.tools.dotc.core.TypeErasure.eraseDerivedValueClassRef(TypeErasure.scala:475)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:527)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:138)
	at dotty.tools.dotc.core.Signature$.apply(Signature.scala:128)
	at dotty.tools.dotc.core.Types$MethodicType.resultSignature(Types.scala:2660)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2951)
	at dotty.tools.dotc.core.Types$SignatureCachingType.signature(Types.scala:2648)
	at dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:2799)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:696)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.matches(Denotations.scala:1078)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.filterDisjoint(Denotations.scala:1086)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:1090)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:1087)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.collect$1(SymDenotations.scala:1594)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.collect$1(SymDenotations.scala:1594)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeNPMembersNamed(SymDenotations.scala:1594)
```
AE-6ab2b244fffa7fe885bf03d6e195c8740dd8748f

**Comment by Blaisorblade** [comment]
The description had tricked me, but this code should actually not compile, and scalac explains why:
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

case class i0 (i0: i1) extends AnyVal
trait i1 extends i0

// Exiting paste mode, now interpreting.

<pastie>:11: error: value class may not wrap another user-defined value class
case class i0 (i0: i1) extends AnyVal
               ^
<pastie>:12: error: illegal inheritance from final class i0
trait i1 extends i0
                 ^
```

Then 
```
case class i0 (i0: Int) extends AnyVal // or without case
trait i1 extends i0
```
is rejected because value classes are apparently final.

**Comment by alexknvl** [comment]
I believe this is another example of the same bug:

```scala
trait F[x] extends AnyVal
case class G[x](a: F[x]) extends F[x]
```
