### ISSUE TITLE
RuntimeError in backend / erasure

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5006]
```scala
object i0 {
  // Adding anything in front of asInstanceOf,
  // i0 or this, makes the error go away.
  def i1: Int = asInstanceOf[Int].toInt
}
```

```scala
Erasure should have added an unboxing operation to prevent this cast. Tree: TypeApply(Ident(asInstanceOf),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)]))
exception occurred while compiling RE-96bd93de803119f21ab5d429b0ce0793869d86c5.scala
Exception in thread "main" java.lang.RuntimeException: Erasure should have added an unboxing operation to prevent this cast. Tree: TypeApply(Ident(asInstanceOf),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)]))
	at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:394)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:599)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:428)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:268)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genPrimitiveOp(BCodeBodyBuilder.scala:257)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:711)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:337)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:602)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:635)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:506)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:508)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:116)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:213)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:179)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:419)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:385)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:53)
```
RE-96bd93de803119f21ab5d429b0ce0793869d86c5

**Comment by alexknvl** [comment]
I am using a slightly modified Dotty:
```scala
diff --git a/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala b/compiler/src/dotty/tools
index 606c820..fe441d2 100644
--- a/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala
+++ b/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala
@@ -505,7 +505,7 @@ class DottyBackendInterface(outputDirectory: AbstractFile, val superCallsMap: Ma
     import scala.tools.asm.util.CheckClassAdapter
     def wrap(body: => Unit): Boolean =
       try { body; true }
-      catch { case ex: Throwable => println(ex.getMessage); false }
+      catch { case ex: Throwable => println(ex.getMessage); throw ex; false }
 
     val valid = wrap {
       if (sym.is(Flags.Method)) {
diff --git a/compiler/src/dotty/tools/backend/jvm/GenBCode.scala b/compiler/src/dotty/tools/backend/jvm/
index ffae0c2..d7a2cba 100644
--- a/compiler/src/dotty/tools/backend/jvm/GenBCode.scala
+++ b/compiler/src/dotty/tools/backend/jvm/GenBCode.scala
@@ -181,6 +181,7 @@ class GenBCodePipeline(val entryPoints: List[Symbol], val int: DottyBackendInter
               case ex: Throwable =>
                 ex.printStackTrace()
                 ctx.error(s"Error while emitting ${int.sourceFileFor(item.cunit)}\n${ex.getMessage}")
+                throw ex
             }
           }
         }
@@ -323,6 +324,7 @@ class GenBCodePipeline(val entryPoints: List[Symbol], val int: DottyBackendInter
               case ex: Throwable =>
                 ex.printStackTrace()
                 ctx.error(s"Error while emitting ${item.plain.classNode.name}\n${ex.getMessage}")
+                throw ex
             }
           }
         }
```
but this should not affect the error, only the reporting.

**Comment by Blaisorblade** [comment]
Reminds me of #3539/#4958, which sadly have no link to when they were fixed.

**Comment by Blaisorblade** [comment]
BTW I suspect we should accept/write such patches under a `-Y` option, similar to `-Yshow-suppressed-errors` and `-Yno-decode-stacktraces` (advocated by @smarter).

**Comment by alexknvl** [comment]
This is probably the same bug:
```scala
object i0 {
  val i1 = asInstanceOf[Int]
}
```

```scala
Error while emitting RE-d341ba7adb385e80fb9955ca9161dd8f86ad3584.scala
Erasure should have added an unboxing operation to prevent this cast. Tree: TypeApply(Ident(asInstanceOf),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)]))
exception occurred while compiling RE-d341ba7adb385e80fb9955ca9161dd8f86ad3584.scala
Exception in thread "main" java.lang.RuntimeException: Erasure should have added an unboxing operation to prevent this cast. Tree: TypeApply(Ident(asInstanceOf),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)]))
	at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:394)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genTypeApply(BCodeBodyBuilder.scala:599)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:428)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:77)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$2$$anonfun$1(BCodeBodyBuilder.scala:860)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:860)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:602)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:635)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:506)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:508)
```
RE-d341ba7adb385e80fb9955ca9161dd8f86ad3584

**Comment by Blaisorblade** [comment]
Ah, looks like `TypeTestCasts.interceptTypeApply` needs to use `desugarIdent` (see fix).

That's why `asInstanceOf[Int]` crashes while `this.asInstanceOf[Int]` doesn't — you sadly need to desugar on usage (#1686, #3925), lest you want to transform each identifier into a huge selection tree (for types we can do it, but types have no position and can be aggressively hash-consed).

**Comment by smarter** [comment]
@Blaisorblade Do you remember why you didn't end up making a PR for https://github.com/dotty-staging/dotty/commit/6cc105cd9159c3a1578001abf56ec6bbaaa5f028  which should fix this ?

**Comment by Blaisorblade** [comment]
@smarter I'm not sure; I think I ran out of steam on revising those fixes for inclusion :-|. But feel free to cherry-pick that commit...

**Comment by smarter** [comment]
OK, I'll have a  look.
