### ISSUE TITLE
RuntimeError in backend when with implicit conversions on super

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5007]
```scala
class I0 {
  super.+("")
}
```

```scala
Unexpected tree in genLoad: Super(This(Ident()),Ident())/class dotty.tools.dotc.ast.Trees$Super at: [11..16]
exception occurred while compiling RE-341cc574ffab7ad1cca7c0683c727f4cd8ca9f68.scala
Exception in thread "main" java.lang.RuntimeException: Unexpected tree in genLoad: Super(This(Ident()),Ident())/class dotty.tools.dotc.ast.Trees$Super at: [11..16]
	at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:394)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:430)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments$$anonfun$1(BCodeBodyBuilder.scala:1018)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1018)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalMethodCall$1(BCodeBodyBuilder.scala:725)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:754)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:337)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:290)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:89)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$2$$anonfun$1(BCodeBodyBuilder.scala:860)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:860)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:89)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$2$$anonfun$1(BCodeBodyBuilder.scala:860)
```

RE-341cc574ffab7ad1cca7c0683c727f4cd8ca9f68

**Comment by nicolasstucki** [comment]
The issue is that we try to find an implicit conversion for the tree of `super` to have the method `+`. Placing `super` as argument which is not a correct tree.

```scala
class I0 {
  implicit def foo(any: Any): String = ()
  super.+("")
}
```

```scala
result of Foo.scala after frontend:
package <empty> {
  class I0() extends Object() { 
    implicit def foo(any: Any): String = this.foo(())
    this.foo(super).+("")
  }
}
```

I imagine that we simply should not try to do implicit conversions on `Super` trees.

**Comment by alexknvl** [comment]
https://github.com/lampepfl/dotty/blob/master/tests/untried/neg/t5063.scala
It looks like the same snippet was imported from scala/tests back in 2014 but was never tried.

**Comment by Blaisorblade** [comment]
@alexknvl Thanks for the pointer!

> I imagine that we simply should not try to do implicit conversions on Super trees.

That's indeed the [scalac fix](https://github.com/scala/scala/commit/bed3304bf86#diff-4eab1aad4533a31c10565971e90f73eaR1161) to https://github.com/scala/bug/issues/5063#issuecomment-292398706.
