### ISSUE TITLE
TypeError when a class extends from Function0

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5010]
```scala
class i0 extends Function0
```
```scala
Exception in thread "main" dotty.tools.dotc.core.TypeError: bad parameter reference i0.this.R at tryCatchPatterns
the parameter is type R in trait Function0 but the prefix i0(i0.this)
does not define any corresponding arguments.
	at dotty.tools.dotc.core.Types$NamedType.argDenot(Types.scala:1841)
	at dotty.tools.dotc.core.Types$NamedType.fromDesignator$1(Types.scala:1756)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1774)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1730)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1719)
	at dotty.tools.dotc.core.Types$$anon$5.apply(Types.scala:2860)
	at dotty.tools.dotc.core.Types$$anon$5.apply(Types.scala:2853)
	at dotty.tools.dotc.core.Types$TermLambda.dotty$tools$dotc$core$Types$TermLambda$$depStatus(Types.scala:2870)
	at dotty.tools.dotc.core.Types$TermLambda.dependencyStatus(Types.scala:2884)
	at dotty.tools.dotc.core.Types$TermLambda.resultType(Types.scala:2827)
	at dotty.tools.dotc.core.Types$MethodType.resultType(Types.scala:2931)
	at dotty.tools.dotc.printing.PlainPrinter.toText$$anonfun$8$$anonfun$6(PlainPrinter.scala:180)
	at dotty.tools.dotc.printing.Printer.atPrec(Printer.scala:41)
	at dotty.tools.dotc.printing.Printer.changePrec(Printer.scala:70)
	at dotty.tools.dotc.printing.PlainPrinter.toText$$anonfun$1(PlainPrinter.scala:182)
	at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:28)
	at dotty.tools.dotc.printing.PlainPrinter.toText(PlainPrinter.scala:215)
	at dotty.tools.dotc.printing.RefinedPrinter.toText$$anonfun$1(RefinedPrinter.scala:243)
	at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:28)
	at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:244)
	at dotty.tools.dotc.core.Types$Type.toText(Types.scala:1419)
	at dotty.tools.dotc.printing.Printer.toTextGlobal$$anonfun$1(Printer.scala:149)
	at dotty.tools.dotc.printing.Printer.atPrec(Printer.scala:41)
	at dotty.tools.dotc.printing.Printer.toTextGlobal(Printer.scala:149)
	at dotty.tools.dotc.printing.PlainPrinter.toTextRHS$$anonfun$1(PlainPrinter.scala:335)
	at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:28)
	at dotty.tools.dotc.printing.PlainPrinter.toTextRHS(PlainPrinter.scala:341)
	at dotty.tools.dotc.printing.PlainPrinter.toTextRHS(PlainPrinter.scala:306)
	at dotty.tools.dotc.printing.PlainPrinter.dclTextWithInfo(PlainPrinter.scala:410)
	at dotty.tools.dotc.printing.PlainPrinter.dclText(PlainPrinter.scala:406)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.showDcl(Denotations.scala:1053)
	at dotty.tools.dotc.typer.RefChecks$.undefined$1(RefChecks.scala:514)
	at dotty.tools.dotc.typer.RefChecks$.checkNoAbstractMembers$4$$anonfun$3(RefChecks.scala:572)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at dotty.tools.dotc.typer.RefChecks$.checkNoAbstractMembers$1(RefChecks.scala:577)
	at dotty.tools.dotc.typer.RefChecks$.dotty$tools$dotc$typer$RefChecks$$$checkAllOverrides(RefChecks.scala:663)
	at dotty.tools.dotc.typer.RefChecks.transformTemplate(RefChecks.scala:963)
```
TE-a6994c362dfcd98096c0617c171bc54fd30101ff

**Comment by Blaisorblade** [comment]
Scalac forbids `class i0 extends Function0` but allows it for Java-defined parents (as witnessed by `tests/run/t3613.scala`), probably because they're raw types. Maybe worth changing?

**Comment by Blaisorblade** [comment]
So `tests/run/t3613.scala` comes from when `javax.swing.AbstractListModel` had no argument, and now works by inferring a type argument to it. See discussion at https://github.com/scala/bug/issues/11111.
