### ISSUE TITLE
IllegalArgumentException in backend with -Xverify-signatures

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5011]
```scala
// Compile with -Xverify-signatures
class A[B[_] <: Long]
```
```scala
Error while emitting IAE-4a69457e1319217c3bac170110ea4ba58dca11a6.scala
<B:J>Ljava/lang/Object;: ':' expected at index 4
exception occurred while compiling IAE-4a69457e1319217c3bac170110ea4ba58dca11a6.scala
Exception in thread "main" java.lang.IllegalArgumentException: <B:J>Ljava/lang/Object;: ':' expected at index 4
	at scala.tools.asm.util.CheckClassAdapter.checkChar(CheckClassAdapter.java:1018)
	at scala.tools.asm.util.CheckClassAdapter.checkFormalTypeParameter(CheckClassAdapter.java:827)
	at scala.tools.asm.util.CheckClassAdapter.checkFormalTypeParameters(CheckClassAdapter.java:808)
	at scala.tools.asm.util.CheckClassAdapter.checkClassSignature(CheckClassAdapter.java:656)
	at dotty.tools.backend.jvm.DottyBackendInterface.$anonfun$3(DottyBackendInterface.scala:518)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.backend.jvm.DottyBackendInterface.wrap$1(DottyBackendInterface.scala:507)
	at dotty.tools.backend.jvm.DottyBackendInterface.verifySignature(DottyBackendInterface.scala:520)
	at dotty.tools.backend.jvm.DottyBackendInterface.getGenericSignature$$anonfun$2(DottyBackendInterface.scala:571)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:257)
	at dotty.tools.backend.jvm.DottyBackendInterface.getGenericSignature(DottyBackendInterface.scala:571)
	at dotty.tools.backend.jvm.DottyBackendInterface.getGenericSignature$$anonfun$1(DottyBackendInterface.scala:545)
	at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
	at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:36)
	at dotty.tools.backend.jvm.DottyBackendInterface.getGenericSignature(DottyBackendInterface.scala:545)
	at dotty.tools.backend.jvm.DottyBackendInterface.getGenericSignature(DottyBackendInterface.scala:540)
	at scala.tools.nsc.backend.jvm.BCodeHelpers$BCJGenSigGen.getGenericSignature(BCodeHelpers.scala:314)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.initJClass(BCodeSkelBuilder.scala:142)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:100)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:213)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:179)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:419)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:385)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:53)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:298)
```
IAE-4a69457e1319217c3bac170110ea4ba58dca11a6

**Comment by alexknvl** [comment]
Same clarification as in https://github.com/lampepfl/dotty/issues/5006#issuecomment-415870060 applies here as well.
