### ISSUE TITLE
Class scala defined twice (Ycheck:all)

### ISSUE THREAD

**Issue by hobwekiva** [lampepfl/dotty#5033]
```scala
class scala
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: class defined twice class scala 2867 22
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.transform.TreeChecker.testDuplicate(TreeChecker.scala:64)
	at dotty.tools.dotc.transform.TreeChecker.transformSym(TreeChecker.scala:87)
	at dotty.tools.dotc.core.DenotTransformers$SymTransformer.transform(DenotTransformers.scala:68)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:910)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1766)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1730)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:286)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:172)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:198)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:179)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:419)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:385)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:53)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:299)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:301)
```
 AE-86f761cfdd0d96cda748d11fe449910cdd76e935

**Comment by nicolasstucki** [comment]
https://github.com/lampepfl/dotty/blob/master/tests/pending/fuzzy/AE-86f761cfdd0d96cda748d11fe449910cdd76e935.scala

**Comment by nicolasstucki** [comment]
Same happens with 
```scala
class java
```

**Comment by nicolasstucki** [comment]
Same for 
```scala
class foo
```

```scala
package foo
class Bar
```

**Comment by griggt** [comment]
`class java` is ok since 0cabe6f in #9099

`class scala` is ok since fa7698e in #9680

**Comment by TheElectronWill** [comment]
Still crashes with `-Ycheck:all` on main, with this new stacktrace:
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: class defined twice class foo 3064 3060
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.TreeChecker.testDuplicate(TreeChecker.scala:54)
	at dotty.tools.dotc.transform.TreeChecker.transformSym(TreeChecker.scala:77)
	at dotty.tools.dotc.core.DenotTransformers$SymTransformer.transform(DenotTransformers.scala:70)
	at dotty.tools.dotc.core.DenotTransformers$SymTransformer.transform$(DenotTransformers.scala:65)
	at dotty.tools.dotc.transform.TreeChecker.transform(TreeChecker.scala:38)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.goForward$1(Denotations.scala:833)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:882)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:2252)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:2215)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:256)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:145)
	at dotty.tools.dotc.ast.tpd$.localOwner(tpd.scala:576)
	at dotty.tools.dotc.ast.tpd$.localCtx(tpd.scala:580)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1607)
	at dotty.tools.dotc.transform.TreeChecker$$anon$1.apply(TreeChecker.scala:619)
	at dotty.tools.dotc.transform.TreeChecker$$anon$1.apply(TreeChecker.scala:611)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1516)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1518)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1617)
	at dotty.tools.dotc.transform.TreeChecker$$anon$1.apply(TreeChecker.scala:619)
	at dotty.tools.dotc.transform.TreeChecker$$anon$1.apply(TreeChecker.scala:611)
	at dotty.tools.dotc.transform.TreeChecker.assertSelectWrapsNew(TreeChecker.scala:623)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:132)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:110)
        ...
```

**Comment by ckipp01** [comment]
Looking into this, this seems to no longer be the case:

```scala
//> using scala 3.nightly
//> using option -deprecation
//> using option -Ycheck:all

class scala
```

Works fine, as well as with `class java`. I'll go ahead and close this.
