### ISSUE TITLE
AssertionError: unaccounted modifier

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5037]
```scala
class Foo {
abstract override var
}
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unaccounted modifier: Abstract() in Modifiers(mutable abstract override,,List(),List(Abstract(), Override())) when adding List(Abstract(), Override(), Var())
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.ast.untpd$Modifiers.withMods$$anonfun$1(untpd.scala:180)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.ast.untpd$Modifiers.withMods(untpd.scala:182)
	at dotty.tools.dotc.ast.untpd$Modifiers.withAddedMod(untpd.scala:170)
	at dotty.tools.dotc.parsing.Parsers$Parser.addMod(Parsers.scala:1784)
	at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:2110)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq$$anonfun$1(Parsers.scala:2519)
	at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:395)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq(Parsers.scala:2527)
	at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$15(Parsers.scala:2423)
	at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:428)
	at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:436)
	at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:441)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateBody(Parsers.scala:2423)
	at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$14(Parsers.scala:2418)
	at dotty.tools.dotc.parsing.Parsers$Parser.withinEnum(Parsers.scala:340)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateBodyOpt(Parsers.scala:2418)
	at dotty.tools.dotc.parsing.Parsers$Parser.template(Parsers.scala:2393)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateOpt(Parsers.scala:2410)
	at dotty.tools.dotc.parsing.Parsers$Parser.classDefRest(Parsers.scala:2293)
	at dotty.tools.dotc.parsing.Parsers$Parser.classDef(Parsers.scala:2288)
	at dotty.tools.dotc.parsing.Parsers$Parser.tmplDef(Parsers.scala:2270)
	at dotty.tools.dotc.parsing.Parsers$Parser.topStatSeq(Parsers.scala:2468)
	at dotty.tools.dotc.parsing.Parsers$Parser.topstats$2(Parsers.scala:2644)
	at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit$$anonfun$1(Parsers.scala:2649)
	at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:395)
	at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit(Parsers.scala:2654)
	at dotty.tools.dotc.parsing.Parsers$Parser.parse(Parsers.scala:160)
```
AE-51a0a24162ba4b6d7ff8fae378973c5350d2737b

**Comment by nicolasstucki** [comment]
https://github.com/lampepfl/dotty/blob/master/tests/pending/fuzzy/AE-51a0a24162ba4b6d7ff8fae378973c5350d2737b.scala
