### ISSUE TITLE
AssertionError somewhere in the typer (parser stability)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5038]
```scala
object I0{List(I1 I2=>}
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Mode(Type,ImplicitsEnabled)
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.ast.desugar$.apply(Desugar.scala:1138)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:962)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1156)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:717)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:801)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:746)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:237)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:184)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:186)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:343)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1771)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1796)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
```
AE-a0a760f3522486caf279b74367aaaa1ff0085b35

**Comment by nicolasstucki** [comment]
https://github.com/lampepfl/dotty/blob/master/tests/pending/fuzzy/AE-a0a760f3522486caf279b74367aaaa1ff0085b35.scala
