### ISSUE TITLE
Null expanded as a _* with Ycheck:all

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5039]
```scala
// -Ycheck:all
class I0{List(null:_*)}
```
```scala
checking AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala after phase frontend
exception while typing List.apply[Nothing](null: Null) of class class dotty.tools.dotc.ast.Trees$Apply # 110
exception while typing class I0() extends Object() { 
  List.apply[Nothing](null: Null)
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 112
exception while typing package <empty> {
  class I0() extends Object() { 
    List.apply[Nothing](null: Null)
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 113
*** error while checking AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala after phase frontend ***
exception occurred while compiling AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: found:    Null
required: Nothing


tree = null: Null
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.transform.TreeChecker$Checker.adapt(TreeChecker.scala:460)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:312)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$Application.$anonfun$4$$anonfun$1(Applications.scala:465)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.typer.Applications$Application.$anonfun$2(Applications.scala:465)
	at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:1568)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:465)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:256)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:565)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:663)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:723)
	at dotty.tools.dotc.typer.Applications.realApply$4$$anonfun$3(Applications.scala:748)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1984)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:759)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:794)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1818)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
```
AE-c00f7074d074a942f48e3e24845e7f7054b76b69

**Comment by nicolasstucki** [comment]
https://github.com/lampepfl/dotty/blob/master/tests/pending/fuzzy/AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala

**Comment by alexknvl** [comment]
```scala
class I0 { List(null: _*) }
```

New hashcode is AE-00ec91ed75d2dedd53f30f6031fd74064690892f. Not sure what exactly changed there, but this will make it easier for me to find it later.
