### ISSUE TITLE
NullPointerException somewhere in the typer (parser stability)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5040]
```scala
object i0{val i5=(())=>}
```
```scala
-- Error: NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f.scala:1:18 --------------
1 |object i0{val i5=(())=>}
  |                  ^^
  |                  not a legal formal parameter
-- [E018] Syntax Error: NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f.scala:1:23 
1 |object i0{val i5=(())=>}
  |                       ^
  |                       illegal start of simple expression

longer explanation available when compiling with `-explain`
parsed:
package <empty> {
  module object i0 { 
    val i5 = (<error>: ()) => null
  }
}
exception occurred while typechecking NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f.scala
exception occurred while compiling NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f.scala
Exception in thread "main" java.lang.NullPointerException
	at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:354)
	at dotty.tools.dotc.ast.untpd$.ref(untpd.scala:350)
	at dotty.tools.dotc.ast.desugar$.apply(Desugar.scala:1151)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1900)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:962)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1156)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:717)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:801)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:746)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:237)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:184)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:186)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:343)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1771)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1796)
```
NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f

**Comment by nicolasstucki** [comment]
This issue was fixed

https://github.com/lampepfl/dotty/blob/master/tests/fuzzy/NPE-26500d1481be1323d39a46b8d3a3a3afc583f46f.scala
