### ISSUE TITLE
Assertion failed: asTerm called on not-a-Term val <none>

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#5043]
```scala
trait i0 {
  private object i0
  class i0
}
class i1 extends i0 {
  class i1 extends i0 { 
    trait i0[i0] { 
      def i1: i0[i0] = new i0 
    } 
  }
}
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:498)
	at dotty.tools.dotc.typer.TermRefSet.$plus$eq(Implicits.scala:1249)
	at dotty.tools.dotc.typer.ImplicitRunInfo.addRef$1(Implicits.scala:480)
	at dotty.tools.dotc.typer.ImplicitRunInfo.addClassScope$2(Implicits.scala:485)
	at dotty.tools.dotc.typer.ImplicitRunInfo.collectCompanions$1$$anonfun$1(Implicits.scala:488)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.typer.ImplicitRunInfo.collectCompanions$4(Implicits.scala:488)
	at dotty.tools.dotc.typer.ImplicitRunInfo.computeIScope$1(Implicits.scala:507)
	at dotty.tools.dotc.typer.ImplicitRunInfo.iscope$2$$anonfun$1(Implicits.scala:515)
	at scala.collection.mutable.AnyRefMap.getOrElse(AnyRefMap.scala:130)
	at dotty.tools.dotc.typer.ImplicitRunInfo.iscope$1(Implicits.scala:515)
	at dotty.tools.dotc.typer.ImplicitRunInfo.iscopeRefs$1(Implicits.scala:463)
	at dotty.tools.dotc.typer.ImplicitRunInfo.addParentScope$2(Implicits.scala:483)
	at dotty.tools.dotc.typer.ImplicitRunInfo.addClassScope$1$$anonfun$1(Implicits.scala:486)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.typer.ImplicitRunInfo.addClassScope$2(Implicits.scala:486)
	at dotty.tools.dotc.typer.ImplicitRunInfo.collectCompanions$1$$anonfun$1(Implicits.scala:488)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
```
AE-4cadbe221750f15498a87af48f0fce7ebde76246

**Comment by Blaisorblade** [comment]
Appears dup of #5002 (hashes match, sources match up to whitespace). Closing.
