### ISSUE TITLE
Nondeterministic failures in  `dotc.tests.pickle_pickling`

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#508]
I haven't observed such failures on my machine, but I've seen them ~5 times on travis. 
```
[info] Test dotc.tests.pickle_pickling started
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: cannot merge class Ops(in Ordering) in trait Ordering with class Ops(in Numeric) in trait Numeric as members of one type; keeping only class Ops(in Ordering) in trait Ordering
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenMapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$MapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$ImmutableMapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenSetFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$SetFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$ImmutableSetFactory$$CC; assuming they are invariant
[error] Test dotc.tests.pickle_pickling failed: dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol; method putNat#14401288 in class TastyBuffer, defined in Period(1..4, run = 2), is referred to in run Period(1..1, run = 3), took 3.617 sec
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.staleSymbolError(Denotations.scala:646)
[error]     at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1224)
[error]     at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1206)
[error]     at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1194)
[error]     at dotty.tools.dotc.core.Types$NamedType.symbol(Types.scala:1356)
[error]     at dotty.tools.dotc.core.TypeOps$class.simplify(TypeOps.scala:62)
[error]     at dotty.tools.dotc.core.Contexts$Context.simplify(Contexts.scala:51)
[error]     at dotty.tools.dotc.core.Types$Type.simplified(Types.scala:1025)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:821)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:755)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:820)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:777)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:820)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader$$anonfun$readRhs$1$1$$anonfun$apply$6.apply(TreeUnpickler.scala:554)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$TreeReader$$anonfun$readRhs$1$1$$anonfun$apply$6.apply(TreeUnpickler.scala:554)
[error]     at dotty.tools.dotc.core.pickling.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:875)
[error]     at dotty.tools.dotc.ast.Trees$WithLazyField$class.forceIfLazy(Trees.scala:774)
[error]     at dotty.tools.dotc.ast.Trees$DefDef.forceIfLazy(Trees.scala:635)
[error]     at dotty.tools.dotc.ast.Trees$ValOrDefDef$class.rhs(Trees.scala:343)
[error]     at dotty.tools.dotc.ast.Trees$DefDef.rhs(Trees.scala:635)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$25$$anonfun$apply$9.apply(RefinedPrinter.scala:379)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$25$$anonfun$apply$9.apply(RefinedPrinter.scala:378)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.withEnclosingDef(RefinedPrinter.scala:29)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$25.apply(RefinedPrinter.scala:377)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$25.apply(RefinedPrinter.scala:375)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.dclTextOr$1(RefinedPrinter.scala:234)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:375)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.ast.Trees$Tree.toText(Trees.scala:230)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toText$1.apply(PlainPrinter.scala:59)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toText$1.apply(PlainPrinter.scala:59)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.map(List.scala:285)
[error]     at dotty.tools.dotc.printing.PlainPrinter.toText(PlainPrinter.scala:59)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toTextGlobal$2.apply(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toTextGlobal$2.apply(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.Printer.atPrec(Printer.scala:22)
[error]     at dotty.tools.dotc.printing.PlainPrinter.toTextGlobal(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.dotty$tools$dotc$printing$RefinedPrinter$$anonfun$$toTextTemplate$1(RefinedPrinter.scala:259)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$26.apply(RefinedPrinter.scala:394)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2$$anonfun$26.apply(RefinedPrinter.scala:394)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.withEnclosingDef(RefinedPrinter.scala:29)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:394)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.ast.Trees$Tree.toText(Trees.scala:230)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toText$1.apply(PlainPrinter.scala:59)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toText$1.apply(PlainPrinter.scala:59)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.map(List.scala:285)
[error]     at dotty.tools.dotc.printing.PlainPrinter.toText(PlainPrinter.scala:59)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toTextGlobal$2.apply(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.PlainPrinter$$anonfun$toTextGlobal$2.apply(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.Printer.atPrec(Printer.scala:22)
[error]     at dotty.tools.dotc.printing.PlainPrinter.toTextGlobal(PlainPrinter.scala:73)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:414)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:413)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:413)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:413)
[error]     at dotty.tools.dotc.printing.RefinedPrinter$$anonfun$toText$2.apply(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:22)
[error]     at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:159)
[error]     at dotty.tools.dotc.ast.Trees$Tree.toText(Trees.scala:230)
[error]     at dotty.tools.dotc.printing.Showable$class.show(Showable.scala:23)
[error]     at dotty.tools.dotc.ast.Trees$Tree.show(Trees.scala:99)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$.dotty$tools$dotc$core$Decorators$StringInterpolators$$treatSingleArg$1(Decorators.scala:176)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$$anonfun$dotty$tools$dotc$core$Decorators$StringInterpolators$$treatArg$1$1.apply(Decorators.scala:167)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]     at scala.collection.immutable.List.map(List.scala:285)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$.dotty$tools$dotc$core$Decorators$StringInterpolators$$treatArg$1(Decorators.scala:167)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$$anonfun$2.apply(Decorators.scala:184)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$$anonfun$2.apply(Decorators.scala:184)
[error]     at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:46)
[error]     at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:44)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
[error]     at scala.runtime.Tuple2Zipped$.map$extension(Tuple2Zipped.scala:44)
[error]     at dotty.tools.dotc.core.Decorators$StringInterpolators$.i$extension(Decorators.scala:184)
[error]     at dotty.tools.dotc.transform.Pickler$$anonfun$testUnpickler$4.apply(Pickler.scala:84)
[error]     at dotty.tools.dotc.transform.Pickler$$anonfun$testUnpickler$4.apply(Pickler.scala:82)
[error]     at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
[error]     at dotty.tools.dotc.transform.Pickler.testUnpickler(Pickler.scala:82)
[error]     at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:68)
[error]     at dotty.tools.dotc.Run$$anonfun$compileSources$1$$anonfun$apply$mcV$sp$3.apply(Run.scala:50)
[error]     at dotty.tools.dotc.Run$$anonfun$compileSources$1$$anonfun$apply$mcV$sp$3.apply(Run.scala:47)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error]     at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply$mcV$sp(Run.scala:47)
[error]     at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply(Run.scala:42)
[error]     at dotty.tools.dotc.Run$$anonfun$compileSources$1.apply(Run.scala:42)
[error]     at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:68)
[error]     at dotty.tools.dotc.Run.compileSources(Run.scala:41)
[error]     at dotty.tools.dotc.Run.compile(Run.scala:32)
[error]     at dotty.tools.dotc.Driver.doCompile(Driver.scala:20)
[error]     at dotty.tools.dotc.Main$.doCompile(Main.scala:26)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:31)
[error]     at test.CompilerTest.compileArgs(CompilerTest.scala:159)
[error]     at test.CompilerTest.compileDir(CompilerTest.scala:104)
[error]     at dotc.tests.pickle_pickling(tests.scala:49)
[error]     ...
```

**Comment by odersky** [comment]
I have added a handler that lets us reproduce the precise sequence of compiled compilation units. Hopefully this lets us reproduce the error locally should it come up again.

**Comment by DarkDimius** [comment]
Haven't seen such failures for more than one month. Closing.
