### ISSUE TITLE
VS Code integration not working

### ISSUE THREAD

**Issue by tusharmath** [lampepfl/dotty#5089]
I followed the steps as specified over here — https://dotty.epfl.ch/docs/usage/ide-support.html

And tried to make VS Code work with my project. After running `sbt launchIDE` I am getting the following error — 
```error
Sep 08, 2018 9:53:18 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///Users/tushar/Documents/Projects/scala-script/free-monad/7.scala",
      "languageId": "scala",
      "version": 1,
      "text": "import scala.language.higherKinds\nimport scala.language.implicitConversions\n\nobject Main extends App {\n  trait Free[F[_], A]\n  case class FlatMap[F[_], A, B](program: F[A], afb: A \u003d\u003e Free[F, B]) extends Free[F, B]\n  case class Mapped[F[_], A, B](program: F[A], ab: A \u003d\u003e B) extends Free[F, B]\n\n  implicit class ProgramSyntax[F[_], A](program: F[A]) {\n    def flatMap[B](fa: A \u003d\u003e Free[F, B]) \u003d FlatMap(program, fa)\n    def map[B](ab: A \u003d\u003e B) \u003d Mapped(program, ab)\n  }\n\n  class DSL[A] {}\n  case class Tell(statement: String) extends DSL[Unit]\n  case class Ask(question: String) extends DSL[String]\n\n  trait Executor[F[_]] {\n    def apply[A](program: F[A]): A\n  }\n\n  def interpret[F[_], A, B](f: Free[F, A])(execute: Executor[F]): A \u003d f match {\n    case FlatMap(program, afb) \u003d\u003e interpret(afb(execute(program)))(execute)\n    case Mapped(program, ab) \u003d\u003e ab(execute(program))\n    case _ \u003d\u003e throw new Exception(\"WTF!\")\n  }\n\n  def app2() \u003d for {\n    _     \u003c- Tell(\"Greetings!\")\n    name  \u003c- Ask(\"Whats your name?\")\n    _     \u003c- Tell(s\"Welcome to the world of functional programming $name\")\n  } yield ()\n\n  interpret(app2())(new Executor[DSL]{\n    def apply[A](program: DSL[A]): A \u003d program match {\n      case Tell(statement) \u003d\u003e println(statement)\n      case Ask(question) \u003d\u003e {\n        println(question)\n        scala.io.StdIn.readLine()\n      }\n    }\n  })\n}"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:219)
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:211)
	at scala.collection.mutable.HashMap$$anon$3.next(HashMap.scala:154)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at dotty.tools.languageserver.DottyLanguageServer.driverFor(DottyLanguageServer.scala:114)
	at dotty.tools.languageserver.DottyLanguageServer.didOpen(DottyLanguageServer.scala:180)
	... 16 more

java.lang.NullPointerException
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:219)
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:211)
	at scala.collection.mutable.HashMap$$anon$3.next(HashMap.scala:154)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at dotty.tools.languageserver.DottyLanguageServer.driverFor(DottyLanguageServer.scala:114)
	at dotty.tools.languageserver.DottyLanguageServer.documentSymbol$$anonfun$1(DottyLanguageServer.scala:358)
	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Sep 08, 2018 9:53:18 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:219)
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:211)
	at scala.collection.mutable.HashMap$$anon$3.next(HashMap.scala:154)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at dotty.tools.languageserver.DottyLanguageServer.driverFor(DottyLanguageServer.scala:114)
	at dotty.tools.languageserver.DottyLanguageServer.documentSymbol$$anonfun$1(DottyLanguageServer.scala:358)
	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 09:53:18] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:219)
	at scala.collection.mutable.HashTable$$anon$1.next(HashTable.scala:211)
	at scala.collection.mutable.HashMap$$anon$3.next(HashMap.scala:154)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at dotty.tools.languageserver.DottyLanguageServer.driverFor(DottyLanguageServer.scala:114)
	at dotty.tools.languageserver.DottyLanguageServer.documentSymbol$$anonfun$1(DottyLanguageServer.scala:358)
	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:139)
	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:144)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

**Comment by smarter** [comment]
Hi, is the project on which you tried to run `sbt launchIDE` online ? I found https://github.com/tusharmath/scala-scripts but it doesn't have any sbt build file so it doesn't work.

**Comment by tusharmath** [comment]
@smarter Yes! but i din't commit them because it wasn't working.

**Comment by smarter** [comment]
Can you commit it in a separate branch so that I can take a look ?

**Comment by AleksanderBG** [comment]
Closing, since the IDE opens successfully on latest Dotty release.
