### ISSUE TITLE
dotty-language-server tests fail on Windows

### ISSUE THREAD

**Issue by melekhove** [lampepfl/dotty#5124]
Tests fail due to the same old problem of windows path separator and colon in the path.
```
[info] Test run started
[info] Test dotty.tools.languageserver.RenameTest.renameCaseClass started
[error] Test dotty.tools.languageserver.RenameTest.renameCaseClass failed: java.net.URISyntaxException: Illegal character in authority at index 7: file://D:\home\projects\Scala\Dotty\git\language-server\..\out\ide-tests\src/Source0.scala, took 0.621 sec
[error]     at java.net.URI$Parser.fail(URI.java:2848)
[error]     at java.net.URI$Parser.parseAuthority(URI.java:3186)
[error]     at java.net.URI$Parser.parseHierarchical(URI.java:3097)
[error]     at java.net.URI$Parser.parse(URI.java:3053)
[error]     at java.net.URI.<init>(URI.java:588)
[error]     at dotty.tools.languageserver.DottyLanguageServer.didOpen(DottyLanguageServer.scala:180)
[error]     at dotty.tools.languageserver.util.server.TestServer.openCode(TestServer.scala:59)
[error]     at dotty.tools.languageserver.util.CodeTester.$init$$$anonfun$1(CodeTester.scala:20)
[error]     at dotty.tools.languageserver.util.CodeTester.$init$$$anonfun$adapted$1(CodeTester.scala:20)
[error]     at scala.collection.immutable.List.map(List.scala:283)
[error]     at dotty.tools.languageserver.util.CodeTester.<init>(CodeTester.scala:21)
[error]     at dotty.tools.languageserver.util.Code$.withSources(Code.scala:78)
[error]     at dotty.tools.languageserver.RenameTest.testRenameFrom$6(RenameTest.scala:68)
[error]     at dotty.tools.languageserver.RenameTest.renameCaseClass(RenameTest.scala:71)
[error]     ...
```
I'm going to submit a PR with small fix for this issue.

**Comment by smarter** [comment]
Fixed in #5125
