### ISSUE TITLE
ReplCompilerTests fail on Windows

### ISSUE THREAD

**Issue by melekhove** [lampepfl/dotty#5158]
Steps to reproduce one of two fails:
```
sbt:dotty> testOnly dotty.tools.repl.ReplCompilerTests -- *testRes
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-interfaces / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-library / Test / testOnly
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for Test / testOnly
[info] Compiling 7 Scala sources to D:\home\projects\Scala\Dotty\git\compiler\target\scala-2.12\test-classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-sbt-bridge / Test / testOnly
[info] Packaging D:\home\projects\Scala\Dotty\git\compiler\target\scala-2.12\dotty-compiler_2.12-0.10.0-bin-SNAPSHOT-non
bootstrapped.jar ...
[info] Done packaging.
[info] Done compiling.
[info] Test run started
[info] Test dotty.tools.repl.ReplCompilerTests.testRes started
[error] Test dotty.tools.repl.ReplCompilerTests.testRes failed: java.lang.AssertionError: expected:<List(def foo: Int, v
)>, took 1.38 sec 20res0: Int = 2, var y: Int = 5, val res1: Int = 20)> but was:<List(def foo: Int
[error]     at dotty.tools.repl.ReplCompilerTests.$anonfun$testRes$1(ReplCompilerTests.scala:54)
[error]     at dotty.tools.repl.ReplCompilerTests.$anonfun$testRes$1$adapted(ReplCompilerTests.scala:37)
[error]     at dotty.tools.repl.ReplTest.fromInitialState(ReplTest.scala:35)
[error]     at dotty.tools.repl.ReplCompilerTests.testRes(ReplCompilerTests.scala:37)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 1 total, 2.54s
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         dotty.tools.repl.ReplCompilerTests
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-doc / Test / testOnly
[error] (dotty-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 12 s, completed 25.09.2018 11:03:47
sbt:dotty>
```

**Comment by anatoliykmetyuk** [comment]
Cannot reproduce this from my Windows machine, and we are running those tests in CI anyway these days on Windows.
