### ISSUE TITLE
Quiting REPL using Ctrl+C throws exception

### ISSUE THREAD

**Issue by nrjais** [lampepfl/dotty#5250]
```
scala>
Exception in thread "main" org.jline.reader.UserInterruptException
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:579)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:385)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:61)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:115)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:125)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:140)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:192)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:140)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:163)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:140)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by allanrenucci** [comment]
The proper way to quit the REPL is `Ctrl+D` or `:quit`. Interruption in the REPL is currently not supported

**Comment by nrjais** [comment]
@allanrenucci But it should not throw an exception.
I can work on this if `Ctrl+C` needs to be supported as a way to exit REPL.
