### ISSUE TITLE
Crash when selecting ! on block

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#5386]
```scala
object Test {
  inline def assert(assertion: => Boolean): Boolean = !assertion

  def test = assert({println("Boom");true})
}
```

```scala
java.lang.AssertionError: NoDenotation.owner while compiling tests/run-separate-compilation/gestalt-innerclassmacro-inline/InnerClassMacro_1.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:1931)
	at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$1(Erasure.scala:408)
	at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:412)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1863)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1936)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1968)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
```

**Comment by biboudis** [comment]
Ok now this doesn't raise the error.

```scala
val a = assertion
!a
```

**Comment by biboudis** [comment]
New minimization 😮 

```scala
object Test {
  !{
    println("!")
    true
  }
}
```

**Comment by odersky** [comment]
It's a combination of two things: 

 - The expression is constant folded, so its type does not have a symbol.
 - The expression is impure, so it's not reduced to a constant literal.

The problem is that Erasure does not expect to see a Select node with these two properties.

**Comment by biboudis** [comment]
I see. What do you think about the #5387 fix?
