### ISSUE TITLE
Switch with or cases crashes

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5402]
```scala
val a: Int = 4
a match {
  case 1 => println("1")
  case 1 | 2 => println("1 or 2")
}
```

crashes with 
```
duplicate keys in SWITCH, can't pick arbitrarily one of them to evict, see SI-6011.
java.lang.RuntimeException: duplicate keys in SWITCH, can't pick arbitrarily oneof them to evict, see SI-6011.
        at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:390)
        at scala.tools.nsc.backend.jvm.BCodeIdiomatic$JCodeMethodN.emitSWITCH(BCodeIdiomatic.scala:477)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genMatch(BCodeBodyBuilder.scala:909)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:431)
```

**Comment by andrevidela** [comment]
@liufengyun I have a pull request incoming for this fix that I did during last weekend's Scala spree. Could I take care of this?
