### ISSUE TITLE
package object confuses DottyIDE's "Find all references"

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#5573]
DottyIDE thinks that a package object in `semanticdb/input/src/main/scala/example/Flags.scala` conflicts with itself, and that interferes with "Find all references". However, the TypeError appears incorrect (by itself) and it should *not* interfere with navigation operations.

Steps to reproduce:
1. `sbt launchIDE`
2. Go to checkStable in Checking.scala, try to "Find all references"
3. Get no results, and the sbt console lists "dotty.tools.dotc.core.TypeError: package example contains object and package with same name: p" (stacktrace below).
4. Finding all references again finds only the ones in `Checking.scala`.
5. Open Typer.scala, try "Find all references" again, also get the references in Typer.scala.

To confirm `semanticdb/input/src/main/scala/example/Flags.scala` is the offender:

6. In `semanticdb/input/src/main/scala/example/Flags.scala`, rename `p` to whatever you want (`packageObjectsConflictsWithItself`)
7. Retry steps, get `packageObjectsConflictsWithItself` in the error.

## Complete error (after renaming to `packageObjectsConflictsWithItself`)

```
[error] dotty.tools.dotc.core.TypeError: package example contains object and package with same name: packageObjectsConflictsWithItself
[error] one of them needs to be removed from classpath
[error] 	at dotty.tools.dotc.core.SymbolLoaders$.enterPackage(SymbolLoaders.scala:76)
[error] 	at dotty.tools.dotc.core.SymbolLoaders$PackageLoader.doComplete$$anonfun$3(SymbolLoaders.scala:288)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at dotty.tools.dotc.core.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:289)
[error] 	at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:324)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:232)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:338)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:146)
[error] 	at dotty.tools.dotc.core.SymDenotations$ModuleCompleter.complete(SymDenotations.scala:2070)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:232)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.select$1(Denotations.scala:1277)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1307)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$1(Denotations.scala:1309)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:1311)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.trees$1(InteractiveDriver.scala:191)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.treesFromClassName(InteractiveDriver.scala:200)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.$anonfun$1(InteractiveDriver.scala:117)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
[error] 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.sourceTreesContaining(InteractiveDriver.scala:118)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.$anonfun$10$$anonfun$2(DottyLanguageServer.scala:338)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:334)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.$anonfun$11(DottyLanguageServer.scala:341)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:334)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.references$$anonfun$1(DottyLanguageServer.scala:342)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:170)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.computation$1(DottyLanguageServer.scala:175)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:178)
[error] 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[error] 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[error] 	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Dec 06, 2018 5:09:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
[error] SEVERE: Internal error: dotty.tools.dotc.core.TypeError: package example contains object and package with same name: packageObjectsConflictsWithItself
[error] one of them needs to be removed from classpath
[error] java.util.concurrent.CompletionException: dotty.tools.dotc.core.TypeError: package example contains object and package with same name: packageObjectsConflictsWithItself
[error] one of them needs to be removed from classpath
[error] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[error] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[error] 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
[error] 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[error] 	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: dotty.tools.dotc.core.TypeError: package example contains object and package with same name: packageObjectsConflictsWithItself
[error] one of them needs to be removed from classpath
[error] 	at dotty.tools.dotc.core.SymbolLoaders$.enterPackage(SymbolLoaders.scala:76)
[error] 	at dotty.tools.dotc.core.SymbolLoaders$PackageLoader.doComplete$$anonfun$3(SymbolLoaders.scala:288)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at dotty.tools.dotc.core.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:289)
[error] 	at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:324)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:232)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:338)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:146)
[error] 	at dotty.tools.dotc.core.SymDenotations$ModuleCompleter.complete(SymDenotations.scala:2070)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:232)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.select$1(Denotations.scala:1277)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1307)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$1(Denotations.scala:1309)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:1311)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.trees$1(InteractiveDriver.scala:191)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.treesFromClassName(InteractiveDriver.scala:200)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.$anonfun$1(InteractiveDriver.scala:117)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
[error] 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at dotty.tools.dotc.interactive.InteractiveDriver.sourceTreesContaining(InteractiveDriver.scala:118)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.$anonfun$10$$anonfun$2(DottyLanguageServer.scala:338)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:334)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.$anonfun$11(DottyLanguageServer.scala:341)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:334)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.references$$anonfun$1(DottyLanguageServer.scala:342)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.liftedTree1$1(DottyLanguageServer.scala:170)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.computation$1(DottyLanguageServer.scala:175)
[error] 	at dotty.tools.languageserver.DottyLanguageServer.computeAsync$$anonfun$1(DottyLanguageServer.scala:178)
[error] 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[error] 	... 6 more
```

**Comment by abgruszecki** [comment]
@smarter do we still want to keep track of IDE issues?

**Comment by smarter** [comment]
no since we'replacing it with metals.
