### ISSUE TITLE
partest hangs on random test

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#561]
I've already seen several times today, that partest can hang after failed test.
Seems to be some kind of I/O or concurrency issue
```

"main" - Thread t@1
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <6d7ae88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465)
	at scala.tools.partest.package$ExecutorOps.awaitTermination(package.scala:105)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$22.apply(Runner.scala:817)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$22.apply(Runner.scala:817)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.tools.partest.nest.SuiteRunner.runTestsForFiles(Runner.scala:817)
	at scala.tools.partest.nest.ConsoleRunner$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(ConsoleRunner.scala:173)
	at scala.tools.partest.nest.ConsoleRunner$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(ConsoleRunner.scala:169)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at scala.tools.partest.nest.ConsoleRunner$$anonfun$2.apply$mcV$sp(ConsoleRunner.scala:169)
	at scala.tools.partest.nest.ConsoleRunner$$anonfun$2.apply(ConsoleRunner.scala:169)
	at scala.tools.partest.nest.ConsoleRunner.run(ConsoleRunner.scala:168)
	at dotty.partest.DPConsoleRunner.runPartest(DPConsoleRunner.scala:51)
	at dotty.partest.DPConsoleRunner$.main(DPConsoleRunner.scala:36)
	at dotty.partest.DPConsoleRunner.main(DPConsoleRunner.scala)

   Locked ownable synchronizers:
	- None

"Reference Handler" - Thread t@2
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <446d2e82> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

   Locked ownable synchronizers:
	- None

"Thread-1929" - Thread t@1942
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <7b47264d> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <177a3c7e> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <177a3c7e> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.sys.process.BasicIO$$anonfun$processFully$1$$anonfun$apply$6.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$$anonfun$processFully$1$$anonfun$apply$6.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$.readFully$1(BasicIO.scala:178)
	at scala.sys.process.BasicIO$.processLinesFully(BasicIO.scala:188)
	at scala.sys.process.BasicIO$$anonfun$processFully$1.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$$anonfun$processFully$1.apply(BasicIO.scala:163)
	at scala.sys.process.ProcessBuilderImpl$Simple$$anonfun$3.apply$mcV$sp(ProcessBuilderImpl.scala:74)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)

   Locked ownable synchronizers:
	- None

"Thread-1930" - Thread t@1943
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <68a9357f> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <571e4e10> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <571e4e10> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.sys.process.BasicIO$$anonfun$processFully$1$$anonfun$apply$6.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$$anonfun$processFully$1$$anonfun$apply$6.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$.readFully$1(BasicIO.scala:178)
	at scala.sys.process.BasicIO$.processLinesFully(BasicIO.scala:188)
	at scala.sys.process.BasicIO$$anonfun$processFully$1.apply(BasicIO.scala:165)
	at scala.sys.process.BasicIO$$anonfun$processFully$1.apply(BasicIO.scala:163)
	at scala.sys.process.ProcessBuilderImpl$Simple$$anonfun$4.apply$mcV$sp(ProcessBuilderImpl.scala:77)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)

   Locked ownable synchronizers:
	- None

"pool-1-thread-1" - Thread t@11
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <100124c2> (a java.lang.UNIXProcess)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:262)
	at scala.sys.process.ProcessImpl$SimpleProcess.exitValue(ProcessImpl.scala:219)
	at scala.tools.partest.nest.Runner.scala$tools$partest$nest$Runner$$run$1(Runner.scala:196)
	at scala.tools.partest.nest.Runner$$anonfun$scala$tools$partest$nest$Runner$$runCommand$1.apply$mcI$sp(Runner.scala:209)
	at scala.tools.partest.nest.Runner$$anonfun$scala$tools$partest$nest$Runner$$runCommand$1.apply(Runner.scala:209)
	at scala.tools.partest.nest.Runner$$anonfun$scala$tools$partest$nest$Runner$$runCommand$1.apply(Runner.scala:209)
	at scala.sys.process.FileProcessLogger.buffer(ProcessLogger.scala:70)
	at scala.tools.partest.nest.Runner.scala$tools$partest$nest$Runner$$runCommand(Runner.scala:193)
	at scala.tools.partest.nest.Runner$$anonfun$scala$tools$partest$nest$Runner$$execTest$1.apply(Runner.scala:216)
	at scala.tools.partest.nest.Runner$$anonfun$scala$tools$partest$nest$Runner$$execTest$1.apply(Runner.scala:216)
	at scala.tools.partest.nest.Runner.nextTestAction(Runner.scala:129)
	at scala.tools.partest.nest.Runner.scala$tools$partest$nest$Runner$$execTest(Runner.scala:216)
	at scala.tools.partest.nest.Runner$$anonfun$run$2.apply$mcZ$sp(Runner.scala:683)
	at scala.tools.partest.nest.Runner$$anonfun$runTestCommon$1.apply$mcZ$sp(Runner.scala:508)
	at scala.tools.partest.nest.Runner.runInContext(Runner.scala:397)
	at scala.tools.partest.nest.Runner.runTestCommon(Runner.scala:507)
	at scala.tools.partest.nest.Runner.run(Runner.scala:683)
	at dotty.partest.DPSuiteRunner$$anonfun$liftedTree1$1$1.apply(DPConsoleRunner.scala:96)
	at dotty.partest.DPSuiteRunner$$anonfun$liftedTree1$1$1.apply(DPConsoleRunner.scala:96)
	at scala.tools.partest.package$.timed(package.scala:127)
	at dotty.partest.DPSuiteRunner.liftedTree1$1(DPConsoleRunner.scala:96)
	at dotty.partest.DPSuiteRunner.runTest(DPConsoleRunner.scala:96)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$21$$anonfun$apply$6.apply(Runner.scala:814)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$21$$anonfun$apply$6.apply(Runner.scala:814)
	at scala.tools.partest.package$$anon$2.call(package.scala:133)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- locked <1e80bfe8> (a java.util.concurrent.ThreadPoolExecutor$Worker)


```

**Comment by smarter** [comment]
Don't think this still happens, closing.
