### ISSUE TITLE
Some languageserver tests fail on Windows

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#5702]
The following 3 tests fail on Windows (tested on Win 10 Pro with batch files from #5444):

1) Assertion error in test `dotty.tools.languageserver.DefinitionTest.definitionFromTasty`:
```
[error] Test dotty.tools.languageserver.DefinitionTest.definitionFromTasty failed: java.lang.AssertionError:
[error]
[error] // project176\Source-from-tasty-0.scala in project project176
[error] package mypackage
[error]               class A
[error] // project176\Source1.scala in project project176
[error] package mypackage
[error]              object O {
[error]                new A
[error]              }
[error]
[error] while executing action: CodeDefinition([start=(m3,line=2,char=19), end=(m4,line=2,char=20)], List([start=(m1,line=1,char=20), end=(m2,line=1,char=21)]))
[error]
[error]           expected:<List(Location [
[error]   uri = "file:///W:/dotty-batch-files/language-server/../out/ide-tests/src/project176/Source-from-tasty-0.scala"
[error]   range = Range [
[error]     start = Position [
[error]       line = 1
[error]       character = 20
[error]     ]
[error]     end = Position [
[error]       line = 1
[error]       character = 21
[error]     ]
[error]   ]
[error] ])> but was:<ArrayBuffer()>, took 0.271 sec
[error]     at dotty.tools.languageserver.util.actions.CodeDefinition.onMarker$direct(CodeDefinition.scala:23)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct$$anonfun$4(ActionOnRange.scala:30)
[error]     at scala.compat.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
[error]     at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct(ActionOnRange.scala:30)
[error]     at dotty.tools.languageserver.util.CodeTester.doAction(CodeTester.scala:240)
[error]     at dotty.tools.languageserver.util.CodeTester.definition(CodeTester.scala:83)
[error]     at dotty.tools.languageserver.DefinitionTest.definitionFromTasty(DefinitionTest.scala:219)
[error]     ...
```

2) Assertion error in test `dotty.tools.languageserver.ReferencesTest.findReferencesInUntouchedProject`:
```
[error] Test dotty.tools.languageserver.ReferencesTest.findReferencesInUntouchedProject failed: java.lang.AssertionError:
[error]
[error] // project261\Source0.scala in project project261
[error] package hello
[error]              object A { def foo = 1 }
[error] // project262\Source-from-tasty-0.scala in project project262
[error] package hello
[error]               object B { def bar = A.foo }
[error]
[error] while executing action: CodeReferences([start=(m1,line=1,char=28), end=(m2,line=1,char=31)], List([start=(m1,line=1,char=28), end=(m2,line=1,char=31)], [start=(m3,line=1,char=37), end=(m4,line=1,char=40)]), true)
[error]
[error]           expected:<List(Location [
[error]   uri = "file:///W:/dotty-batch-files/language-server/../out/ide-tests/src/project261/Source0.scala"
[error]   range = Range [
[error]     start = Position [
[error]       line = 1
[error]       character = 28
[error]     ]
[error]     end = Position [
[error]       line = 1
[error]       character = 31
[error]     ]
[error]   ]
[error] ], Location [
[error]   uri = "file:///W:/dotty-batch-files/language-server/../out/ide-tests/src/project262/Source-from-tasty-0.scala"
[error]   range = Range [
[error]     start = Position [
[error]       line = 1
[error]       character = 37
[error]     ]
[error]     end = Position [
[error]       line = 1
[error]       character = 40
[error]     ]
[error]   ]
[error] ])> but was:<List(Location [
[error]   uri = "file:///W:/dotty-batch-files/language-server/../out/ide-tests/src/project261/Source0.scala"
[error]   range = Range [
[error]     start = Position [
[error]       line = 1
[error]       character = 28
[error]     ]
[error]     end = Position [
[error]       line = 1
[error]       character = 31
[error]     ]
[error]   ]
[error] ])>, took 0.474 sec
[error]     at dotty.tools.languageserver.util.actions.CodeReferences.onMarker$direct(CodeReferences.scala:30)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct$$anonfun$4(ActionOnRange.scala:30)
[error]     at scala.compat.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
[error]     at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct(ActionOnRange.scala:30)
[error]     at dotty.tools.languageserver.util.CodeTester.doAction(CodeTester.scala:240)
[error]     at dotty.tools.languageserver.util.CodeTester.references(CodeTester.scala:107)
[error]     at dotty.tools.languageserver.ReferencesTest.findReferencesInUntouchedProject(ReferencesTest.scala:216)
[error]     ...
```

3) Assertion error in test `dotty.tools.languageserver.HoverTest.documentationIsFormatted` :
```
[error] Test dotty.tools.languageserver.HoverTest.documentationIsFormatted failed: java.lang.AssertionError:
[error]
[error] // project315\Source0.scala in project project315
[error] class Foo(val x: Int, val y: Int) {
[error]   /**
[error]    * Does something
[error]    *
[error]    * @tparam T A first type param
[error]    * @tparam U Another type param
[error]    * @param fizz Again another number
[error]    * @param buzz A String
[error]    * @param ev   An implicit boolean
[error]    * @return Something
[error]    * @throws java.lang.NullPointerException if you're unlucky
[error]    * @throws java.lang.InvalidArgumentException if the argument is invalid
[error]    * @see java.nio.file.Paths#get()
[error]    * @note A note
[error]    * @example myFoo.bar[Int, String](0, "hello, world")
[error]    * @author John Doe
[error]    * @version 1.0
[error]    * @since 0.1
[error]    * @usecase def bar(fizz: Int, buzz: String): Any
[error]    */
[error]   def bar[T, U](fizz: Int, buzz: String)(implicit ev: Boolean): Any = ???
[error] }
[error]
[error] while executing action: CodeHover([start=(m1,line=20,char=6), end=(m2,line=20,char=9)], Some(```scala
[error] [T, U](fizz: Int, buzz: String)(implicit ev: Boolean): Any
[error] ```
[error] Does something
[error]
[error] **Type Parameters**
[error]  - **T** A first type param
[error]  - **U** Another type param
[error]
[error] **Parameters**
[error]  - **fizz** Again another number
[error]  - **buzz** A String
[error]  - **ev** An implicit boolean
[error]
[error] **Returns**
[error]  - Something
[error]
[error] **Throws**
[error]  - **java.lang.NullPointerException** if you're unlucky
[error]  - **java.lang.InvalidArgumentException** if the argument is invalid
[error]
[error] **See Also**
[error]  - java.nio.file.Paths#get()
[error]
[error] **Examples**
[error]  - ```scala
[error]    myFoo.bar[Int, String](0, "hello, world")
[error]    ```
[error]
[error] **Note**
[error]  - A note
[error]
[error] **Authors**
[error]  - John Doe
[error]
[error] **Since**
[error]  - 0.1
[error]
[error] **Version**
[error]  - 1.0))
[error]
[error]           expected:<...y
[error] ```
[error] Does something[
[error]
[error] **Type Parameters**
[error]  - **T** A first type param
[error]  - **U** Another type param
[error]
[error] **Parameters**
[error]  - **fizz** Again another number
[error]  - **buzz** A String
[error]  - **ev** An implicit boolean
[error]
[error] **Returns**
[error]  - Something
[error]
[error] **Throws**
[error]  - **java.lang.NullPointerException** if you're unlucky
[error]  - **java.lang.InvalidArgumentException** if the argument is invalid
[error]
[error] **See Also**
[error]  - java.nio.file.Paths#get()
[error]
[error] **Examples**
[error]  - ```scala
[error]    myFoo.bar[Int, String](0, "hello, world")
[error]    ```
[error]
[error] **Note**
[error]  - A note
[error]
[error] **Authors**
[error]  - John Doe
[error]
[error] **Since**
[error]  - 0.1
[error] ]
[error] **Version**
[error]  - 1.0> but was:<...y
[error] ```
[error] Does something[
[error]
[error] **Type Parameters**
[error]  - **T** A first type param
[error]  - **U** Another type param
[error]
[error] **Parameters**
[error]  - **fizz** Again another number
[error]  - **buzz** A String
[error]  - **ev** An implicit boolean
[error]
[error] **Returns**
[error]  - Something
[error]
[error] **Throws**
[error]  - **java.lang.NullPointerException** if you're unlucky
[error]  - **java.lang.InvalidArgumentException** if the argument is invalid
[error]
[error] **See Also**
[error]  - java.nio.file.Paths#get()
[error]
[error] **Examples**
[error]  - ```scala
[error]    myFoo.bar[Int, String](0, "hello, world")
[error]    ```
[error]
[error] **Note**
[error]  - A note
[error]
[error] **Authors**
[error]  - John Doe
[error]
[error] **Since**
[error]  - 0.1
]error]
[error] **Version**
[error]  - 1.0>, took 0.088 sec
[error]     at dotty.tools.languageserver.util.actions.CodeHover.onMarker$direct(CodeHover.scala:28)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct$$anonfun$4(ActionOnRange.scala:30)
[error]     at scala.compat.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
[error]     at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]     at dotty.tools.languageserver.util.actions.ActionOnRange.execute$direct(ActionOnRange.scala:30)
[error]     at dotty.tools.languageserver.util.CodeTester.doAction(CodeTester.scala:240)
[error]     at dotty.tools.languageserver.util.CodeTester.hover(CodeTester.scala:72)
[error]     at dotty.tools.languageserver.HoverTest.documentationIsFormatted(HoverTest.scala:130)
[error]     ...
```

**Comment by michelou** [comment]
Close issue since it cannot be reproduced anymore with current releases (0.21+).
