### ISSUE TITLE
REPL will crash when expression SAM converting to abstract class type

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#5733]
```scala
scala> abstract class F {
     |   def f(arg: Any): Unit
     | }
// defined class F

scala> val f: F = println
Exception in thread "main" java.lang.AssertionError: assertion failed: private method $anonfun in rs$line$2 accessed from method f in null
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.transform.ExpandPrivate.ensurePrivateAccessible(ExpandPrivate.scala:86)
	at dotty.tools.dotc.transform.ExpandPrivate.transformSelect(ExpandPrivate.scala:99)
	at dotty.tools.dotc.transform.ExpandPrivate.transformSelect(ExpandPrivate.scala:98)
	at dotty.tools.dotc.transform.MegaPhase.goSelect(MegaPhase.scala:562)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:229)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:391)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:270)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:392)
	at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:245)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:248)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:391)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:400)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:405)
	at scala.collection.immutable.List.mapConserve(List.scala:179)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:405)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:392)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:391)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:400)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:405)
	at scala.collection.immutable.List.mapConserve(List.scala:179)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:405)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:392)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:391)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:400)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:405)
	at scala.collection.immutable.List.mapConserve(List.scala:179)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:405)
	at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:356)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:392)
	at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:411)
	at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:423)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:297)
	at scala.collection.immutable.List.map(List.scala:286)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:299)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:172)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:184)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:192)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:199)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:139)
	at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:151)
	at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:160)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:213)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:182)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:127)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:143)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:143)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:143)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
Crash only occurs when working in REPL.

**Comment by nicolasstucki** [comment]
#5713 seams to fix this
