### ISSUE TITLE
Pattern matching is unsound in the presence of type unions

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#5826]
```scala
scala> def test[A]: List[Int] | A => Int = { case ls: List[Int] => ls.head  case _ => 0 }
def test[A] => List[Int] | A => Int

scala> test(List("oops"))
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
```

The definition of `test` should at least yield a warning like "erased type argument `Int` in type pattern `List[Int]` is unchecked".

**Comment by LPTK** [comment]
Note that even the following passes the type checker without a warning (at least in the REPL):

```scala
scala> def test: List[Int]|List[String] => Int = { case ls: List[Int] => ls.head  case _ => 0 }
def test List[Int] | List[String] => Int

scala> test(List("oops"))
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
```
