### ISSUE TITLE
Illegal field modifiers in class Matchers: 0x9

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#5924]
The following code produces a load-time exception:

```
Exception in thread "main" java.lang.ClassFormatError: Illegal field modifiers in class Matchers: 0x9
	at java.lang.ClassLoader.defineClass1(Native Method)
```

```Scala
trait Matchers {
  object Helper
}

object Matchers extends Matchers

object Test {
  def main(args: Array[String]): Unit = Matchers
}

```

<details>
<summary>show full log</summary>
<pre>
Exception in thread "main" java.lang.ClassFormatError: Illegal field modifiers in class Matchers: 0x9
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Test$.main(inner.scala:10)
	at Test.main(inner.scala)
</pre>
</details>

<br/>

This bug is found when working with @cheeseng on ScalaTest macros. Big thanks to @cheeseng for minimizing the problem.

**Comment by odersky** [comment]
It looks like the culprit is the the following field definition in trait `Matchers`:
```scala
@scala.annotation.static() @scala.annotation.static() val OFFSET$_m_0: Long
       = 
    dotty.runtime.LazyVals.getOffset(
      classOf[Object with Matchers with Serializable{...}]
    , "bitmap$0")
```
The Java spec allows only final static fields in interfaces, but this field is not final. 

I am not sure, unfortunately, how to fix this. /cc @DarkDimius
