### ISSUE TITLE
Creating two generic functions that use called by name parameters crash the compiler

### ISSUE THREAD

**Issue by kikofernandez** [lampepfl/dotty#6045]
The following code crashes the compiler. I do that by running `sbt compile`

```
object Flowing {
  def test1[T](x: => T) = {
    List(x)
  }

  def test1[T](x: => List[T])= {
    x
  }
}
```

The stack trace is included below:

```
dotty.tools.dotc.core.Denotations$$anon$1: 
	at dotty.tools.dotc.core.Denotations$.doubleDefError(Denotations.scala:1179)
	at dotty.tools.dotc.core.Denotations$Denotation.handleDoubleDef$1(Denotations.scala:464)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeSingleDenot$1(Denotations.scala:472)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeDenot$1(Denotations.scala:398)
	at dotty.tools.dotc.core.Denotations$Denotation.$amp(Denotations.scala:501)
	at dotty.tools.dotc.core.Denotations$DenotUnion.toDenot(Denotations.scala:1210)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1707)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:594)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:712)
	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:545)
	at dotty.tools.dotc.core.Types$Type.membersBasedOnFlags$$anonfun$1(Types.scala:815)
	at dotty.tools.dotc.core.Types$Type$$Lambda$7628/1910781160.applyVoid(Unknown Source)
	at dotty.runtime.function.JProcedure2.apply(JProcedure2.java:18)
	at dotty.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at dotty.tools.dotc.core.Types$Type.memberDenots$$anonfun$1(Types.scala:757)
	at dotty.tools.dotc.core.Types$Type$$Lambda$6370/290837707.applyVoid(Unknown Source)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:18)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:757)
	at dotty.tools.dotc.core.Types$Type.membersBasedOnFlags(Types.scala:815)
	at dotty.tools.backend.jvm.DottyBackendInterface$$anon$9.membersBasedOnFlags(DottyBackendInterface.scala:889)
	at dotty.tools.backend.jvm.BCodeHelpers$BCForwardersGen.addForwarders(BCodeHelpers.scala:391)
	at dotty.tools.backend.jvm.BCodeHelpers$JMirrorBuilder.genMirrorClass(BCodeHelpers.scala:495)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:204)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:180)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:510)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:476)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:54)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:309)
	at dotty.tools.dotc.core.Phases$Phase$$Lambda$6451/1411407961.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:286)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:311)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:59)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
	at dotty.tools.dotc.Run$$Lambda$6002/1269696710.applyVoid(Unknown Source)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:18)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
	at dotty.tools.dotc.Run$$Lambda$5964/234182481.apply$mcV$sp(Unknown Source)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
	at dotty.tools.dotc.Run.compileSources(Run.scala:120)
	at dotty.tools.dotc.Run.compile(Run.scala:104)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
	at dotty.tools.dotc.Driver.process(Driver.scala:169)
	at dotty.tools.dotc.Main.process(Main.scala)
	at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
	at xsbt.CompilerInterface.run(CompilerInterface.java:41)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
	at sbt.internal.inc.MixedAnalyzingCompiler$$Lambda$5701/1007013154.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$2160/404582196.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
	at sbt.internal.inc.Incremental$$$Lambda$2199/1674331068.apply(Unknown Source)
	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
	at sbt.internal.inc.Incremental$$$Lambda$2194/761763129.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$2099/2059900490.apply(Unknown Source)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
	at sbt.Defaults$$$Lambda$1238/2102534528.apply(Unknown Source)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at scala.Function1$$Lambda$605/101676975.apply(Unknown Source)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
	at sbt.internal.util.$tilde$greater$$Lambda$1857/1428942383.apply(Unknown Source)
	at sbt.std.Transform$$anon$4.work(System.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
	at sbt.Execute$$Lambda$1874/129010901.apply(Unknown Source)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:278)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
	at sbt.Execute$$Lambda$1865/1196222136.apply(Unknown Source)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1872/1693260012.apply(Unknown Source)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Error while emitting Typeclasses.scala
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed Mar 8, 2019 11:12:41 AM
[IJ]sbt:dotty-simple> 
```

**Comment by smarter** [comment]
This code is actually invalid because both  `=> T` and `=> List[T]` will be erased to `Function0`, so the two overloads cannot be represented on the JVM since they end up with the same type signature. It crashes on the latest release but I fixed this in https://github.com/lampepfl/dotty/pull/6025 a few days ago, so on the next release you'll see this error:
```scala
-- [E120] Duplicate Symbol Error: try/i6045.scala:6:6 --------------------------
6 |  def test1[T](x: => List[T])= {
  |      ^
  |      Double definition:
  |      def test1: [T](x: => T): List[T] in object Flowing at line 2 and
  |      def test1: [T](x: => List[T]): List[T] in object Flowing at line 6
  |      have the same type after erasure.
```
