### ISSUE TITLE
-Ytest-pickler fails with invalid in current run error

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#605]
``` scala
class A
```

``` scala
% ./bin/dotc -Ytest-pickler try/test.scala
exception while transforming [cannot display due to java.lang.AssertionError: assertion failed: denotation module class <empty> invalid in run 2. ValidFor: Period(1..4, run = 3), raw string = PackageDef(Ident(<empty>),List(TypeDef(A,Template(DefDef(<init>,List(),List(List()),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,scala)),Unit)],EmptyTree),List(Apply(Select(New(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,lang)),Object)]),<init>),List())),ValDef(_,EmptyTree,EmptyTree),List()))))] of class class dotty.tools.dotc.ast.Trees$PackageDef # 37
exception occurred while compiling try/test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: denotation module class <root> invalid in run 2. ValidFor: Period(1..4, run = 3)
        at scala.Predef$.assert(Predef.scala:165)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:520)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:556)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:616)
        at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1289)
        at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1276)
        at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1264)
        at dotty.tools.dotc.core.Types$NamedType.symbol(Types.scala:1428)
        at dotty.tools.dotc.core.Types$NamedType.stableInRunSymbol(Types.scala:1437)
        at dotty.tools.dotc.core.Types$ThisType.cls(Types.scala:1752)
        at dotty.tools.dotc.core.Types$Type.isTightPrefix(Types.scala:133)
        at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1291)
        at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1276)
        at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1264)
        at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:263)
        at dotty.tools.dotc.ast.Trees$ProxyTree.denot(Trees.scala:280)
        at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:180)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1190)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:52)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:563)
        at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:480)
        at dotty.tools.dotc.transform.TreeTransforms$MiniPhase$class.run(TreeTransform.scala:165)
        at dotty.tools.dotc.transform.TreeTransforms$MiniPhaseTransform.run(TreeTransform.scala:170)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:270)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:268)
        at scala.collection.immutable.List.map(List.scala:273)
        at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:268)
        at dotty.tools.dotc.transform.TreeTransforms$MiniPhaseTransform.runOn(TreeTransform.scala:170)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:68)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
        at dotty.tools.dotc.Run.compileSources(Run.scala:49)
        at dotty.tools.dotc.Run.compile(Run.scala:33)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:20)
        at dotty.tools.dotc.Main$.doCompile(Main.scala:26)
        at dotty.tools.dotc.Driver.process(Driver.scala:31)
        at dotty.tools.dotc.Driver.main(Driver.scala:40)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by smarter** [comment]
The fix is to stop after pickling when `-Ytest-pickler` is on, it should always imply `-Ystop-after:pickler`

**Comment by smarter** [comment]
Fixed a while ago.
