### ISSUE TITLE
LazyRef assertion error

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6057]
```scala
class i0[i1] {
    type i2 <: i0[i2]
    val i3: i2[i4] {}
}
```

AE-3941289f010a4ba5724b992594fc2e5fdd071db9

---

```scala
assertion failure for LazyRef(...) <:< LazyRef(...), frozen = true
assertion failure for i0[LazyRef(...)] <:< i0[LazyRef(...)], frozen = true
assertion failure for  <: i0[LazyRef(...)] <:<  <: i0[LazyRef(...)], frozen = true
assertion failure for LazyRef(...) <:< LazyRef(...), frozen = true
assertion failure for i0[LazyRef(...)] <:< i0[LazyRef(...)], frozen = true
assertion failure for  <: i0[LazyRef(...)] <:<  <: i0[LazyRef(...)], frozen = true
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
java.lang.AssertionError: assertion failed while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at dotty.tools.dotc.core.Types$LazyRef.ref(Types.scala:2441)
	at dotty.tools.dotc.core.Types$Type.dealias1(Types.scala:1083)
	at dotty.tools.dotc.core.Types$Type.dealias(Types.scala:1091)
	at dotty.tools.dotc.core.Types$Type.isSingleton(Types.scala:257)
	at dotty.tools.dotc.core.TypeComparer.isSingletonBounds$1(TypeComparer.scala:1445)
	at dotty.tools.dotc.core.TypeComparer.singletonInterval(TypeComparer.scala:1447)
	at dotty.tools.dotc.core.TypeComparer.glbArgs(TypeComparer.scala:1571)
	at dotty.tools.dotc.core.TypeComparer.distributeAnd(TypeComparer.scala:1732)
	at dotty.tools.dotc.core.TypeComparer.$anonfun$andType$2(TypeComparer.scala:1663)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.core.TypeComparer.andType(TypeComparer.scala:1662)
```

**Comment by smarter** [comment]
Fixed by https://github.com/lampepfl/dotty/pull/6104
