### ISSUE TITLE
SOE during implicit search.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6058]
```scala
implicit def i1[I2, I3](i4: I2)(implicit i5: I2 => I3): I3 = ( )
```

(will add a hash later)

---

```scala
java.lang.StackOverflowError while compiling test.scala
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.handleRecursive$.apply(TypeErrors.scala:99)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:154)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:162)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:126)
	at dotty.tools.dotc.core.Types$Type.$anonfun$$less$colon$less$1(Types.scala:839)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:839)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:2645)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2718)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:2927)
	at dotty.tools.dotc.typer.Typer.$anonfun$adapt$3(Typer.scala:2344)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.$anonfun$adapt$1(Typer.scala:2343)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2343)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:334)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:753)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:751)
	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:519)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:562)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:340)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:654)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:752)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:814)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$9(Applications.scala:843)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2192)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$1(Applications.scala:844)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:783)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:889)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:781)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:87)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2012)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2066)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2100)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
	at dotty.tools.dotc.typer.Namer.$anonfun$typedAheadExpr$1(Namer.scala:1094)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:1084)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1094)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1262)
	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1325)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:770)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:881)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:796)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:236)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:342)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1964)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1989)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2065)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2100)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2131)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2173)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:701)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedBlock$1(Typer.scala:704)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:703)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2019)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2066)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2100)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
	at dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:977)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedFunction$1(Typer.scala:799)
```

**Comment by odersky** [comment]
@milessabin Should this have been caught in divergence checking?

**Comment by milessabin** [comment]
@odersky yes it should. I'll take a look.
