### ISSUE TITLE
Assertion error: data race? (Yno-double-bindings)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6062]
```scala
def I0[i1[i2] <: i2] : i1[ ] = ?
[I0] : I0.i1
```
```scala
class I0[I1](I1: Int) {
def I1[I1](I1: I1*): I0[I1] }
def I2[I2] = new I0().I1()
```

AE-7e0748e3f70691fd3bfd8841fb70e195598ea3cf

---

(last example)
```scala
assertion failure for I0[I1] <:< ?{ I1: ? }, frozen = false
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
java.lang.AssertionError: assertion failed: data race? overwriting val I1 with method I1 in type TermRef(AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class I0),List(TypeVar(TypeParamRef(I1)))),val I1),
           |last sym id = 3508, new sym id = 4092,
           |last owner = class I0, new owner = class I0,
           |period = frontend at run 2 while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: data race? overwriting val I1 with method I1 in type TermRef(AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class I0),List(TypeVar(TypeParamRef(I1)))),val I1),
           |last sym id = 3508, new sym id = 4092,
           |last owner = class I0, new owner = class I0,
           |period = frontend at run 2
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.core.Types$NamedType.checkSymAssign(Types.scala:1963)
	at dotty.tools.dotc.core.Types$NamedType.setDenot(Types.scala:1945)
	at dotty.tools.dotc.core.Types$NamedType.finish$1(Types.scala:1832)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1860)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1820)
	at dotty.tools.dotc.core.Types$TermRef.isOverloaded(Types.scala:2247)
	at dotty.tools.dotc.core.Types$Type.widenSingleton(Types.scala:1003)
	at dotty.tools.dotc.typer.ProtoTypes$Compatibility.normalizedCompatible(ProtoTypes.scala:48)
	at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.qualifies$1(ProtoTypes.scala:157)
	at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy$$anonfun$1(ProtoTypes.scala:162)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.hasAltWith(Denotations.scala:752)
	at dotty.tools.dotc.core.Denotations$MultiDenotation.hasAltWith(Denotations.scala:1258)
	at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy(ProtoTypes.scala:162)
	at dotty.tools.dotc.core.TypeComparer.isMatchedByProto(TypeComparer.scala:1311)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:274)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:998)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:152)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:162)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:126)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:839)
	at dotty.tools.dotc.core.Types$Type.relaxed_$less$colon$less(Types.scala:871)
```

**Comment by odersky** [comment]
-Yno-double-bindings is an internal option to pinpoint problems for compiling legal programs. If the program is illegal anyway, it's not useful.
