### ISSUE TITLE
Assertion Error (parser stability)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6063]
```scala
object i0 {
trait I1[i0, I1]
def I1[I1[I1]](I1: I1[ ;
I1[I1]
}
```
```scala
object I0 {
trait i2[I1, i2]
def i2[i2[i2]](i2: i2[ ]) = i2
i2[i2]}
```

AE-1f07cbdac4b79265bbf51db49b03e667d95b4cf3

---
```scala
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
java.lang.AssertionError: assertion failed while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:15)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4791)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4802)
	at dotty.tools.dotc.core.Types$$anon$5.apply(Types.scala:3024)
	at dotty.tools.dotc.core.Types$$anon$5.apply(Types.scala:3010)
	at dotty.tools.dotc.core.Types$TermLambda.dotty$tools$dotc$core$Types$TermLambda$$depStatus(Types.scala:3027)
	at dotty.tools.dotc.core.Types$TermLambda.dependencyStatus(Types.scala:3041)
	at dotty.tools.dotc.core.Types$TermLambda.resultType(Types.scala:2984)
	at dotty.tools.dotc.core.Types$MethodType.resultType(Types.scala:3088)
	at dotty.tools.dotc.typer.EtaExpansion$.etaExpand(EtaExpansion.scala:205)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsUnappliedMethod$2(Typer.scala:2606)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2716)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:2927)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2344)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2100)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2151)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2173)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1677)
```

**Comment by odersky** [comment]
Fixed in master
