### ISSUE TITLE
Assertion error during eta conversion / type unification (?)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6064]
```scala
trait Trait[X] {
    def f[C[_]](arg: C[X])
    val a = f[(Int, String)]
}
```

AE-e15bffbe1c7acc58f524073e849a753654ee312a

---

```scala
assertion failure for Tuple2[X] <:< Short, frozen = false
assertion failure for (Int, String)[X] <:< Short, frozen = false
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
java.lang.AssertionError: assertion failed while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:15)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4791)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4802)
	at dotty.tools.dotc.core.Types$$anon$1.apply(Types.scala:128)
	at dotty.tools.dotc.core.Types$$anon$1.apply(Types.scala:110)
	at dotty.tools.dotc.core.Types$Type.testProvisional(Types.scala:133)
	at dotty.tools.dotc.core.Types$Type.isProvisional(Types.scala:106)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.record$1(SymDenotations.scala:1715)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeApplied$1(SymDenotations.scala:1791)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.recur$1(SymDenotations.scala:1794)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseTypeOf(SymDenotations.scala:1850)
	at dotty.tools.dotc.core.Types$Type.baseType(Types.scala:925)
	at dotty.tools.dotc.core.TypeComparer.tryBaseType$1(TypeComparer.scala:656)
	at dotty.tools.dotc.core.TypeComparer.thirdTryNamed$1(TypeComparer.scala:454)
	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:471)
	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:428)
	at dotty.tools.dotc.core.TypeComparer.compareNamed$1(TypeComparer.scala:268)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:272)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:998)
	at dotty.tools.dotc.core.TypeComparer.compareAppliedType1$1(TypeComparer.scala:950)
	at dotty.tools.dotc.core.TypeComparer.fourthTry$1(TypeComparer.scala:692)
	at dotty.tools.dotc.core.TypeComparer.tryBaseType$1(TypeComparer.scala:663)
	at dotty.tools.dotc.core.TypeComparer.thirdTryNamed$1(TypeComparer.scala:454)
	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:471)
	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:428)
```

**Comment by alexknvl** [comment]
I get a feeling that there is already a test case like this. I think my model might have just overfitted...
