### ISSUE TITLE
language server failing

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#6128]
I'm having no joy at all getting visual studio to play nicely with dotty.

It says: "The Dotty server crashed 5 times in the last 3 minutes. The server will not be restarted." Full stacktraces below.

I have downgraded the default java on my system to 8.

```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

I have deleted all my `target` directories and `~/.config/Code`.

I have tried rolling back to the 0.1.13 version of the plugn.

```
Starting server
Exception in thread "main" java.lang.IllegalStateException: Expecting return type of CompletableFuture but was : class java.util.concurrent.CompletableFuture
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:109)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:370)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:381)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:305)
	at dotty.tools.languageserver.Main$.startServer(Main.scala:74)
	at dotty.tools.languageserver.Main$.main$$anonfun$1(Main.scala:35)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.languageserver.Main$.main(Main.scala:36)
	at dotty.tools.languageserver.Main.main(Main.scala)
[Info  - 17:08:40] Connection to server got closed. Server will restart.
Starting server
Exception in thread "main" java.lang.IllegalStateException: Expecting return type of CompletableFuture but was : class java.util.concurrent.CompletableFuture
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:109)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:370)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:381)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:305)
	at dotty.tools.languageserver.Main$.startServer(Main.scala:74)
	at dotty.tools.languageserver.Main$.main$$anonfun$1(Main.scala:35)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.languageserver.Main$.main(Main.scala:36)
	at dotty.tools.languageserver.Main.main(Main.scala)
[Info  - 17:08:40] Connection to server got closed. Server will restart.
Starting server
Exception in thread "main" java.lang.IllegalStateException: Expecting return type of CompletableFuture but was : class java.util.concurrent.CompletableFuture
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:109)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:370)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:381)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:305)
	at dotty.tools.languageserver.Main$.startServer(Main.scala:74)
	at dotty.tools.languageserver.Main$.main$$anonfun$1(Main.scala:35)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.languageserver.Main$.main(Main.scala:36)
	at dotty.tools.languageserver.Main.main(Main.scala)
[Info  - 17:08:41] Connection to server got closed. Server will restart.
Starting server
Exception in thread "main" java.lang.IllegalStateException: Expecting return type of CompletableFuture but was : class java.util.concurrent.CompletableFuture
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:109)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:370)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:381)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:305)
	at dotty.tools.languageserver.Main$.startServer(Main.scala:74)
	at dotty.tools.languageserver.Main$.main$$anonfun$1(Main.scala:35)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.languageserver.Main$.main(Main.scala:36)
	at dotty.tools.languageserver.Main.main(Main.scala)
[Info  - 17:08:41] Connection to server got closed. Server will restart.
Starting server
Exception in thread "main" java.lang.IllegalStateException: Expecting return type of CompletableFuture but was : class java.util.concurrent.CompletableFuture
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:109)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:370)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:381)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:305)
	at dotty.tools.languageserver.Main$.startServer(Main.scala:74)
	at dotty.tools.languageserver.Main$.main$$anonfun$1(Main.scala:35)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at dotty.tools.languageserver.Main$.main(Main.scala:36)
	at dotty.tools.languageserver.Main.main(Main.scala)
[Error - 17:08:42] Connection to server got closed. Server will not be restarted.
```

**Comment by drdozer** [comment]
I cleaned all caches, uninsalled all JVMs except for 8, rebooted, and then tried a whole host of dotty builds. These 4 cross the line from working to failing. So something happened after the nightly on the 17th and 19th of March. 

//  "0.14.0-bin-20190315-a6bab2c-NIGHTLY" // works
//  "0.14.0-bin-20190317-b537220-NIGHTLY" // works
//  "0.14.0-bin-20190319-4e1d3d4-NIGHTLY" // fails
//  "0.14.0-bin-20190320-b213f24-NIGHTLY" // fails

**Comment by smarter** [comment]
Thanks for the detective work! I bisected it down to 6c6443086071774431dae93709b4102ce3c4d15e, and indeed compiling Dotty with `-Xmixin-force-forwarders:junit` fixes the problem, I'll investigate.
