### ISSUE TITLE
Type matches are unsound.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#6314]
```scala
object G {
    final class X
    final class Y

    opaque type Foo = X & Y
    object Foo {
        def apply[F[_]](fa: F[X & Y]): F[Y & Foo] = fa
    }

    type Bar[A] = A match {
        case X & Y => String
        case Y => Int
    }

    def main(args: Array[String]): Unit = {
        val a: Bar[X & Y] = "hello"
        val i: Bar[Y & Foo] = Foo.apply[Bar](a)
        val b: Int = i
        println(b + 1)
    }
}
```

```scala
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
    at G$.main(test.scala:30)
    at G.main(test.scala)
```

**Comment by alexknvl** [comment]
In fact, you do not need the new opaque types:
```scala
object G {
    final class X
    final class Y

    trait FooSig {
        type Type
        def apply[F[_]](fa: F[X & Y]): F[Y & Type]
    }
    val Foo: FooSig = new FooSig {
        type Type = X & Y
        def apply[F[_]](fa: F[X & Y]): F[Y & Type] = fa
    }
    type Foo = Foo.Type

    type Bar[A] = A match {
        case X & Y => String
        case Y => Int
    }

    def main(args: Array[String]): Unit = {
        val a: Bar[X & Y] = "hello"
        val i: Bar[Y & Foo] = Foo.apply[Bar](a)
        val b: Int = i
        println(b + 1)
    }
}
```

**Comment by alexknvl** [comment]
Here is a cleaner example:
```scala
object G {
    final class X
    final class Y

    opaque type Foo = Nothing // or X & Y
    object Foo {
        def apply[F[_]](fa: F[X & Foo]): F[Y & Foo] = fa
    }

    type Bar[A] = A match {
        case X => String
        case Y => Int
    }

    val a: Bar[X & Foo] = "hello"
    val b: Bar[Y & Foo] = 1

    def main(args: Array[String]): Unit = {
        val a: Bar[X & Foo] = "hello"
        val i: Bar[Y & Foo] = Foo.apply[Bar](a)
        val b: Int = i
        println(b + 1)
    }
}
```

**Comment by OlivierBlanvillain** [comment]
Thanks for the bug reports, it's very helpful!

That's clearly a bug, `Bar[Y & Foo]` shouldn't reduce to `Int` in `def main`, given that `Foo` should be treated as an abstract type from there.

**Comment by alexknvl** [comment]
I don't think it's just intersections,
```scala
object G {
    trait Wizzle[L <: Int with Singleton] {
        type Bar[A] = A match {
            case 0 => String
            case L => Int
        }

        def left(fa: String): Bar[0] = fa
        def right(fa: Bar[L]): Int = fa

        def center[F[_]](fa: F[0]): F[L]

        def run: String => Int = left andThen center[Bar] andThen right
    }

    class Wozzle extends Wizzle[0] {
        def center[F[_]](fa: F[0]): F[0] = fa
    }

    def main(args: Array[String]): Unit = {
        val coerce: String => Int = (new Wozzle).run
        println(coerce("hello") + 1)
    }
}
```

**Comment by alexknvl** [comment]
Conceptually,
 * `X = Y => F[X] = F[Y]` always holds
 * Suppose we somehow make `F[X] != F[Y]` and `X = Y`, contradiction.
 * Since type equalities are potentially non-local (i.e. `X` and `Y` might be imported as type parameters), we can never assume that `X != Y`. In particular, `type Bar[X] = X match { case 0 => String; case L => Int}` can not assume that `L != 0`, so `Bar[L]` can not be reduced to `Int` in any context where we don't have a proof of `L != 0`.

**Comment by OlivierBlanvillain** [comment]
Makes perfect sense, this is exactly what the implementation is supposed to do: never "reduce past" a case unless there is proof that the two types (the scrutinee type and the pattern type) are non intersecting.

**Comment by alexknvl** [comment]
After snooping around the code for a bit, I found another example:
```scala
object G {
    type Void <: Nothing
    trait Wizzle {
        type Razzle[+X >: Void]
        type X = 0
        type Y = 1

        type Bar[A] = A match {
            case Razzle[X] => String
            case Razzle[Y] => Int
        }

        def left(fa: String): Bar[Razzle[X]] = fa
        def center[F[_]](fa: F[Razzle[X]]): F[Razzle[Y]]
        def right(fa: Bar[Razzle[Y]]): Int = fa

        def run: String => Int = left andThen center[Bar] andThen right
    }

    class Wozzle extends Wizzle {
        type Razzle[+X >: Void] = Int
        def center[F[_]](fa: F[Razzle[X]]): F[Razzle[Y]] = fa
    }

    def main(args: Array[String]): Unit = {
        val coerce: String => Int = (new Wozzle).run
        println(coerce("hello") + 1)
    }
}
```

This one attacks line https://github.com/dotty-staging/dotty/blob/74168ac13746ef43cc3f626cf183b9d452bdc4da/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1959

**Comment by alexknvl** [comment]
I think the code might be mixing intersections of two kinds: `∃ x: T. T <: A ∧ T <: B` and `∃ T. T <: A ∧ T <: B`. The first condition is stronger than the second since the second one is always satisfiable: `T = A & B`. 

```scala
final class A
final class B

type Select[X] = X match {
    case A => Int
    case B => String
}

type Type

val a : Select[A & Type] = 1
val b : Select[B & Type] = "hey"
```
attacks https://github.com/dotty-staging/dotty/blob/74168ac13746ef43cc3f626cf183b9d452bdc4da/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1931 - `A & (B & Type)` is not inhabited, but that doesn't mean that we can "reduce past" the first `case`, since we are not really interested in inhabitance, but in a subtyping relation. We want to check whether `B & Type <: A` is possible (which it is), which is not directly related to whether their intersection is inhabited.

**Comment by OlivierBlanvillain** [comment]
You nailed it with this last example. I'm now convinced that there is no way to soundly reduce any match types when abstract type are involved.

**Comment by alexknvl** [comment]
There are some cases where it is possible.
```scala
final case class X()
type Y
type Select[X] = X match {
    case List[X] => Int
    case Option[Y] => String
}
```

```scala
final class X
final class Y
type Select[X] = X match {
    case X => Int
    case Y => String
}
type Type <: X

type Foo = Select[X | Type] // can not be a subtype of Y, subtype of X, hence reduces to Int
```

```scala
final class X
final class Y
type Select[X] = X match {
    case X => Int
    case Y => String
}
type Type <: X

type Foo = Select[X & Type] // can not be a subtype of Y, subtype of X, hence reduces to Int
```

If the compiler could use implicit evidence (probably not any time soon):
```scala
final class X
final class Y
type Select[X] = X match {
    case X => Int
    case Y => String
}

type Type
implicit val p: (Type <:< X) => Nothing // a proof that Y is not a subtype of X
type Foo = Select[Y & Type] // safe to reduce to String
```
