### ISSUE TITLE
Backend crash when passing a field projection with a new at an inline method

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6341]
```scala
object Test {
  class Config(val t1: Int)

  inline def m(t2:Int) = t2

  m(new Config(3).t1)
}
```

```scala
Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class Test$)),class Test$Config)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <68..68>
java.lang.RuntimeException: Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class Test$)),class Test$Config)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <68..68>
        at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:390)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:263)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1012)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalMethodCall$1(BCodeBodyBuilder.scala:784)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:816)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:339)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:83)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genBlock$1(BCodeBodyBuilder.scala:920)
...
```

**Comment by biboudis** [comment]
Note to self:

The error is raised when inlining the Ident. To be continued...

```
>>>>Test.Config#t1#1138
>>>>Int(Test.Config#t1)

java.lang.Exception
        at dotty.tools.dotc.ast.Positioned.uniqueId_$eq(Positioned.scala:28)
        at dotty.tools.dotc.ast.Positioned.<init>(Positioned.scala:40)
        at dotty.tools.dotc.ast.Trees$Tree.<init>(Trees.scala:56)
        at dotty.tools.dotc.ast.Trees$DenotingTree.<init>(Trees.scala:266)
        at dotty.tools.dotc.ast.Trees$NameTree.<init>(Trees.scala:292)
        at dotty.tools.dotc.ast.Trees$RefTree.<init>(Trees.scala:298)
        at dotty.tools.dotc.ast.Trees$Select.<init>(Trees.scala:392)
        at dotty.tools.dotc.ast.untpd$.Select(untpd.scala:287)
        at dotty.tools.dotc.ast.tpd$.Select(tpd.scala:33)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:378)
        at dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:95)
        at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:473)
        at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:112)
        at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:2757)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2832)
        at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3041)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$3(Typer.scala:2455)
        at dotty.tools.dotc.reporting.TraceSyntax.apply(trace.scala:56)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$1(Typer.scala:2454)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2454)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2157)
        at dotty.tools.dotc.reporting.TraceSyntax.apply(trace.scala:56)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2150)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2169)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2212)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2234)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedClassDef$1(Typer.scala:1674)
```

**Comment by biboudis** [comment]
@odersky If I comment out this line in `computeParamBindings` https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L288
the test above passes. This line matches `new Config(3).t1` as a SingletonType of `t1`:

```scala
TermRef(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class Test$)),class Config),val t1)
```

Is this the correct SingletonType? Should it be considered even Singleton given that it has an unstable prefix? Should it have been just the ConstantType `3`?

**Comment by odersky** [comment]
Thanks for the diagnostic, which was pinpointing the problem precisely!
