### ISSUE TITLE
compiler crash with tuple type bounds

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#6371]
I edited a method signature from:
```
def (lhs: LineParser[A]) :+ [A, B] (rhs: ParseCS[B]): LineParser[(A, B)] =
```

to

```
def (lhs: LineParser[A]) :+ [A, B <: Tuple] (rhs: ParseCS[B]): LineParser[(A, B)] =
```

and it crashed with

```
(Compile / compileIncremental) java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/Tuple.scala
```

Full message:

```
[info] exception occurred while typechecking /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/columnRecord.scala
[info] exception occurred while compiling /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/biopolymer.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/fasta.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/features.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/residues.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/err.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/random.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/render.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/columnRecord.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/coordinates.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/pdbFormat.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/pdbTypes.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/secondaryStructure.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/blast.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/boulderio.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/primer3.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/tails.scala
java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/Tuple.scala while compiling /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/biopolymer.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/fasta.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/features.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/bio/residues.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/err.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/random.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/ct/render.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/columnRecord.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/coordinates.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/pdbFormat.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/pdbTypes.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/pdb/secondaryStructure.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/blast.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/boulderio.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/primer3.scala, /home/nmrp3/devel/ncl/primer_tails/src/main/scala/primerTails/tails.scala
[error] ## Exception when compiling 16 sources to /home/nmrp3/devel/ncl/primer_tails/target/scala-0.15/classes
[error] /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/Tuple.scala
[error] sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[error] java.nio.file.Files.newByteChannel(Files.java:361)
[error] java.nio.file.Files.newByteChannel(Files.java:407)
[error] java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
[error] java.nio.file.Files.newInputStream(Files.java:152)
[error] dotty.tools.io.File.inputStream(File.scala:51)
[error] dotty.tools.io.PlainFile.input(PlainFile.scala:44)
[error] dotty.tools.io.AbstractFile.toByteArray(AbstractFile.scala:170)
[error] dotty.tools.dotc.util.SourceFile.SourceFile$superArg$1$$anonfun$1(SourceFile.scala:52)
[error] dotty.tools.dotc.util.SourceFile.content(SourceFile.scala:48)
[error] dotty.tools.dotc.util.SourceFile.lineIndices(SourceFile.scala:113)
[error] dotty.tools.dotc.util.SourceFile.offsetToLine(SourceFile.scala:132)
[error] dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:26)
[error] dotty.tools.dotc.reporting.MessageRendering.posStr(MessageRendering.scala:116)
[error] dotty.tools.dotc.reporting.AbstractReporter.posStr(AbstractReporter.scala:8)
[error] dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:146)
[error] dotty.tools.dotc.reporting.AbstractReporter.messageAndPos(AbstractReporter.scala:8)
[error] xsbt.DelegatingReporter.doReport(DelegatingReporter.java:121)
[error] dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:231)
[error] dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:291)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:291)
[error] dotty.tools.dotc.core.TyperState.commit(TyperState.scala:158)
[error] dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:865)
[error] dotty.tools.dotc.typer.Applications.realApply$6$$anonfun$5$$anonfun$2(Applications.scala:871)
[error] scala.Option.getOrElse(Option.scala:138)
[error] dotty.tools.dotc.typer.Applications.realApply$7$$anonfun$6(Applications.scala:872)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2300)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:873)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:908)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:87)
[error] dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:1882)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2149)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1553)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2100)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:700)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:703)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2120)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:976)
[error] dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:798)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2122)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1553)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2100)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1676)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2103)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1676)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2103)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1795)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2143)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:61)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:35)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:65)
[error] dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$2(FrontEnd.scala:89)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:89)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:185)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:120)
[error] dotty.tools.dotc.Run.compile(Run.scala:104)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
[error] dotty.tools.dotc.Driver.process(Driver.scala:170)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:278)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/Tuple.scala
[error]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error]         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[error]         at java.nio.file.Files.newByteChannel(Files.java:361)
[error]         at java.nio.file.Files.newByteChannel(Files.java:407)
[error]         at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
[error]         at java.nio.file.Files.newInputStream(Files.java:152)
[error]         at dotty.tools.io.File.inputStream(File.scala:51)
[error]         at dotty.tools.io.PlainFile.input(PlainFile.scala:44)
[error]         at dotty.tools.io.AbstractFile.toByteArray(AbstractFile.scala:170)
[error]         at dotty.tools.dotc.util.SourceFile.SourceFile$superArg$1$$anonfun$1(SourceFile.scala:52)
[error]         at dotty.tools.dotc.util.SourceFile.content(SourceFile.scala:48)
[error]         at dotty.tools.dotc.util.SourceFile.lineIndices(SourceFile.scala:113)
[error]         at dotty.tools.dotc.util.SourceFile.offsetToLine(SourceFile.scala:132)
[error]         at dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:26)
[error]         at dotty.tools.dotc.reporting.MessageRendering.posStr(MessageRendering.scala:116)
[error]         at dotty.tools.dotc.reporting.AbstractReporter.posStr(AbstractReporter.scala:8)
[error]         at dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:146)
[error]         at dotty.tools.dotc.reporting.AbstractReporter.messageAndPos(AbstractReporter.scala:8)
[error]         at xsbt.DelegatingReporter.doReport(DelegatingReporter.java:121)
[error]         at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:231)
[error]         at dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:291)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:291)
[error]         at dotty.tools.dotc.core.TyperState.commit(TyperState.scala:158)
[error]         at dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:865)
[error]         at dotty.tools.dotc.typer.Applications.realApply$6$$anonfun$5$$anonfun$2(Applications.scala:871)
[error]         at scala.Option.getOrElse(Option.scala:138)
[error]         at dotty.tools.dotc.typer.Applications.realApply$7$$anonfun$6(Applications.scala:872)
[error]         at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2300)
[error]         at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:873)
[error]         at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:908)
[error]         at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:87)
[error]         at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:1882)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2149)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error]         at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1553)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2100)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error]         at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:700)
[error]         at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:703)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2120)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:976)
[error]         at dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:798)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2122)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error]         at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1553)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2100)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error]         at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1676)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2103)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error]         at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1676)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2103)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2166)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2278)
[error]         at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1795)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2143)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2167)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2201)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2213)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2289)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:61)
[error]         at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:35)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:65)
[error]         at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$2(FrontEnd.scala:89)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:89)
[error]         at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error]         at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
[error]         at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
[error]         at dotty.tools.dotc.Run.compileSources(Run.scala:120)
[error]         at dotty.tools.dotc.Run.compile(Run.scala:104)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
[error]         at dotty.tools.dotc.Driver.process(Driver.scala:170)
[error]         at dotty.tools.dotc.Main.process(Main.scala)
[error]         at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/Tuple.scala
```

**Comment by odersky** [comment]
Looks like a bootstrap problem.

**Comment by nicolasstucki** [comment]
It looks like after inlining an error is emitted on a position of the inlined method in `scala/Tuple.scala`. The SourcePosition tries to access this file but it is not available.

**Comment by nicolasstucki** [comment]
It can be reproduced using the following files and commands 
`A.scala`
```scala
object A {
  inline def foo(a: Any): Unit = a match {
    case _: Int => print("int")
    case _ => print("other")
  }
}
```

`B.scala`
```
object B {
  A.foo("aa")
}
```

```bash
dotc A.scala
rm A.scala
dotc -classpath . B.scala
```
