### ISSUE TITLE
Bad operand on stack with Nothing$

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#653]
```
[info] # partest /Users/dark/workspace/dotty/tests/partest-generated/run/elidable-opt.scala
[info] % dotc elidable-opt.scala
[info] % java \
[info]   -classpath \
[info]   /Users/dark/workspace/dotty/tests/partest-generated/run/elidable-opt-run.obj:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/me.d-d/scala-compiler/jars/scala-compiler-2.11.5-20150506-175515-8fc7635b56.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dfile.encoding=UTF-8 \
[info]   -Djava.library.path=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.output=/Users/dark/workspace/dotty/tests/partest-generated/run/elidable-opt-run.obj \
[info]   -Dpartest.lib=/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dpartest.reflect=/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar \
[info]   -Dpartest.comp=/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar \
[info]   -Dpartest.cwd=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.test-path=/Users/dark/workspace/dotty/tests/partest-generated/run/elidable-opt.scala \
[info]   -Dpartest.testname=elidable-opt \
[info]   -Djavacmd=java \
[info]   -Djavaccmd=javac \
[info]   -Duser.language=en \
[info]   -Duser.country=US \
[info]   scala.tools.nsc.MainGenericRunner \
[info]   -usejavacp \
[info]   Test \
[info]   jvm > elidable-opt-run.log
[info] java.lang.VerifyError: Bad type on operand stack
[info] Exception Details:
[info]   Location:
[info]     Test$.$anonfun$$anonfun$main$1$1(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Method; @9: invokevirtual
[info]   Reason:
[info]     Type '[Lscala/runtime/Nothing$;' (current frame, stack[2]) is not assignable to '[Ljava/lang/Class;'
[info]   Current Frame:
[info]     bci: @9
[info]     flags: { }
[info]     locals: { 'Test$', 'java/lang/String', 'java/lang/String' }
[info]     stack: { 'java/lang/Class', 'java/lang/String', '[Lscala/runtime/Nothing$;' }
[info]   Bytecode:
[info]     0x0000000: 2bb8 00e5 2c03 bd00 fab6 00ee b0
[info]
[info]  at Test.main(elidable-opt.scala)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]  at java.lang.reflect.Method.invoke(Method.java:497)
[info]  at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[info]  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
[info]  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
[info]  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
[info]  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
[info]  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
[info]  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
[info]  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

```
[info]
[info] # partest /Users/dark/workspace/dotty/tests/partest-generated/run/elidable.scala
[info] % dotc elidable.scala
[info] % java \
[info]   -classpath \
[info]   /Users/dark/workspace/dotty/tests/partest-generated/run/elidable-run.obj:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/me.d-d/scala-compiler/jars/scala-compiler-2.11.5-20150506-175515-8fc7635b56.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dfile.encoding=UTF-8 \
[info]   -Djava.library.path=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.output=/Users/dark/workspace/dotty/tests/partest-generated/run/elidable-run.obj \
[info]   -Dpartest.lib=/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dpartest.reflect=/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar \
[info]   -Dpartest.comp=/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar \
[info]   -Dpartest.cwd=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.test-path=/Users/dark/workspace/dotty/tests/partest-generated/run/elidable.scala \
[info]   -Dpartest.testname=elidable \
[info]   -Djavacmd=java \
[info]   -Djavaccmd=javac \
[info]   -Duser.language=en \
[info]   -Duser.country=US \
[info]   scala.tools.nsc.MainGenericRunner \
[info]   -usejavacp \
[info]   Test \
[info]   jvm > elidable-run.log
[info] java.lang.VerifyError: Bad type on operand stack
[info] Exception Details:
[info]   Location:
[info]     Test$.$anonfun$$anonfun$main$1$1(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Method; @9: invokevirtual
[info]   Reason:
[info]     Type '[Lscala/runtime/Nothing$;' (current frame, stack[2]) is not assignable to '[Ljava/lang/Class;'
[info]   Current Frame:
[info]     bci: @9
[info]     flags: { }
[info]     locals: { 'Test$', 'java/lang/String', 'java/lang/String' }
[info]     stack: { 'java/lang/Class', 'java/lang/String', '[Lscala/runtime/Nothing$;' }
[info]   Bytecode:
[info]     0x0000000: 2bb8 00e5 2c03 bd00 fab6 00ee b0
[info]
[info]  at Test.main(elidable.scala)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]  at java.lang.reflect.Method.invoke(Method.java:497)
[info]  at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[info]  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
[info]  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
[info]  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
[info]  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
[info]  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
[info]  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
[info]  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by DarkDimius** [comment]
Can't reproduce the bug on current master. The test still fails, but for different reason(assert elision isn't implemented)
