### ISSUE TITLE
For a partitial function defined inside a value class 1 + 2 == 2.

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#659]
```
class Foo(val a: Int) extends AnyVal {
  def foo = { {case x => x + a}: PartialFunction[Int, Int]}
}

object Test extends dotty.runtime.LegacyApp {
  val x = new Foo(1).foo.apply(2)
  assert(x == 3, x)
}
```
```
[info] % dotc t7571.scala
[info] % java \
[info]   -classpath \
[info]   /Users/dark/workspace/dotty/tests/partest-generated/run/t7571-run.obj:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/me.d-d/scala-compiler/jars/scala-compiler-2.11.5-20150506-175515-8fc7635b56.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dfile.encoding=UTF-8 \
[info]   -Djava.library.path=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.output=/Users/dark/workspace/dotty/tests/partest-generated/run/t7571-run.obj \
[info]   -Dpartest.lib=/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dpartest.reflect=/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar \
[info]   -Dpartest.comp=/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar \
[info]   -Dpartest.cwd=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.test-path=/Users/dark/workspace/dotty/tests/partest-generated/run/t7571.scala \
[info]   -Dpartest.testname=t7571 \
[info]   -Djavacmd=java \
[info]   -Djavaccmd=javac \
[info]   -Duser.language=en \
[info]   -Duser.country=US \
[info]   scala.tools.nsc.MainGenericRunner \
[info]   -usejavacp \
[info]   Test \
[info]   jvm > t7571-run.log
[info] java.lang.AssertionError: assertion failed: 2
[info] 	at scala.Predef$.assert(Predef.scala:165)
[info] 	at Test$.<init>(t7571.scala:14)
[info] 	at Test$.<clinit>(t7571.scala)
[info] 	at Test.main(t7571.scala)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] 	at java.lang.reflect.Method.invoke(Method.java:497)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[info] 	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
[info] 	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
[info] 	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
[info] 	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
[info] 	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
[info] 	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
[info] 	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
[info] 	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
[info] 	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by DarkDimius** [comment]
```{case x => x + a}: PartialFunction[Int, Int]```
expands to anonymous class, that closes over `a`.
LambdaLift creates a field for `a`(it's called `$this$2`) but never initializes it: https://github.com/lampepfl/dotty/blob/6ca52b0f23f0c3425d054d0918a149e0e7afb765/src/dotty/tools/dotc/transform/LambdaLift.scala#L396
@odersky over to you
