### ISSUE TITLE
AssertionError: failure to construct path from value ... class does not have an outer accessor

### ISSUE THREAD

**Issue by panacekcz** [lampepfl/dotty#6659]
Seems to happend when
- an enum is nested in a class, and
- the enum does not have type parameters, and
- the case has an extends clause.

Code:
```scala
class C{
  enum E(i: Int){
    case A extends E(2)
  }
}
```

Output:
```
exception while typing C.this.E$.this of class class dotty.tools.dotc.ast.Trees$This # 1295
exception while typing C.this.E$.this.$values of class class dotty.tools.dotc.ast.Trees$Select # 1296
exception while typing C.this.E$.this.$values.register of class class dotty.tools.dotc.ast.Trees$Select # 1301
exception while typing C.this.E$.this.$values.register(this) of class class dotty.tools.dotc.ast.Trees$Apply # 1302
exception while typing final class $anon() extends C.this.E(2), scala.deriving.Mirror.Singleton {
  def $ordinal: Int = 0
  override def toString: String = "A"
  C.this.E$.this.$values.register(this)
  private def $outer: C
  final def C$E$_$$anon$$$outer: C = $outer
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 1513
exception while typing {
  final class $anon() extends C.this.E(2), scala.deriving.Mirror.Singleton {
    def $ordinal: Int = 0
    override def toString: String = "A"
    C.this.E$.this.$values.register(this)
    private def $outer: C
    final def C$E$_$$anon$$$outer: C = $outer
  }
  new C.this.E with scala.deriving.Mirror.Singleton {...}():C.this.E
} of class class dotty.tools.dotc.ast.Trees$Block # 1514
exception while typing case <static> val A: C.this.E =
  {
    final class $anon() extends C.this.E(2), scala.deriving.Mirror.Singleton {
      def $ordinal: Int = 0
      override def toString: String = "A"
      C.this.E$.this.$values.register(this)
      private def $outer: C
      final def C$E$_$$anon$$$outer: C = $outer
    }
    new C.this.E with scala.deriving.Mirror.Singleton {...}():C.this.E
  } of class class dotty.tools.dotc.ast.Trees$ValDef # 1515
exception while typing final module class E$() extends AnyRef(), Serializable,
  scala.deriving.Mirror.Sum
 {
  def values: Array[C.this.E] =
    this.$values.values.toArray[C.this.E](
      scala.reflect.ClassTag.apply[C.this.E](classOf[C.this.E])
    )
  private def $values: scala.runtime.EnumValues[C.this.E] =
    new scala.runtime.EnumValues[C.this.E]()
  def valueOf($name: String): C.this.E =
    try this.$values.fromName.apply($name) catch
      {
        case ex$ @ _:java.util.NoSuchElementException =>
          throw new IllegalArgumentException("key not found: ".concat($name))
      }
  case <static> val A: C.this.E =
    {
      final class $anon() extends C.this.E(2), scala.deriving.Mirror.Singleton {

        def $ordinal: Int = 0
        override def toString: String = "A"
        C.this.E$.this.$values.register(this)
        private def $outer: C
        final def C$E$_$$anon$$$outer: C = $outer
      }
      new C.this.E with scala.deriving.Mirror.Singleton {...}():C.this.E
    }
  type MirroredMonoType = C.this.E
  def ordinal(x$0: C.E.MirroredMonoType): Int = x$0.ordinal
  private def $outer: C
  final def C$E$$$$outer: C = C.E.$outer
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 1519
exception while typing @scala.annotation.internal.SourceFile("enum-class.scala") class C()
   extends
 Object() {
  @scala.annotation.internal.Child[C.this.E(C.E.A)]() sealed abstract class E(
    i: Int
  ) extends Object(), Enum {
    override def ordinal: Int = this.$ordinal
    private val i: Int
    private def $outer: C
    final def C$E$$$outer: C = E.this.$outer
  }
  final lazy module def E: C.this.E$ = new C.this.E$()
  final module class E$() extends AnyRef(), Serializable,
    scala.deriving.Mirror.Sum
   {
    def values: Array[C.this.E] =
      this.$values.values.toArray[C.this.E](
        scala.reflect.ClassTag.apply[C.this.E](classOf[C.this.E])
      )
    private def $values: scala.runtime.EnumValues[C.this.E] =
      new scala.runtime.EnumValues[C.this.E]()
    def valueOf($name: String): C.this.E =
      try this.$values.fromName.apply($name) catch
        {
          case ex$ @ _:java.util.NoSuchElementException =>
            throw new IllegalArgumentException("key not found: ".concat($name))
        }
    case <static> val A: C.this.E =
      {
        final class $anon() extends C.this.E(2), scala.deriving.Mirror.Singleton
           {

          def $ordinal: Int = 0
          override def toString: String = "A"
          C.this.E$.this.$values.register(this)
          private def $outer: C
          final def C$E$_$$anon$$$outer: C = $outer
        }
        new C.this.E with scala.deriving.Mirror.Singleton {...}():C.this.E
      }
    type MirroredMonoType = C.this.E
    def ordinal(x$0: C.E.MirroredMonoType): Int = x$0.ordinal
    private def $outer: C
    final def C$E$$$$outer: C = C.E.$outer
  }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 1521
exception while typing package <empty> {
  @scala.annotation.internal.SourceFile("enum-class.scala") class C(
    )
   extends Object() {
    @scala.annotation.internal.Child[C.this.E(C.E.A)]() sealed abstract class E(
      i: Int
    ) extends Object(), Enum {
      override def ordinal: Int = this.$ordinal
      private val i: Int
      private def $outer: C
      final def C$E$$$outer: C = E.this.$outer
    }
    final lazy module def E: C.this.E$ = new C.this.E$()
    final module class E$() extends AnyRef(), Serializable,
      scala.deriving.Mirror.Sum
     {
      def values: Array[C.this.E] =
        this.$values.values.toArray[C.this.E](
          scala.reflect.ClassTag.apply[C.this.E](classOf[C.this.E])
        )
      private def $values: scala.runtime.EnumValues[C.this.E] =
        new scala.runtime.EnumValues[C.this.E]()
      def valueOf($name: String): C.this.E =
        try this.$values.fromName.apply($name) catch
          {
            case ex$ @ _:java.util.NoSuchElementException =>
              throw
                new IllegalArgumentException("key not found: ".concat($name))
          }
      case <static> val A: C.this.E =
        {
          final class $anon() extends C.this.E(2),
            scala.deriving.Mirror.Singleton
           {
            def $ordinal: Int = 0
            override def toString: String = "A"
            C.this.E$.this.$values.register(this)
            private def $outer: C
            final def C$E$_$$anon$$$outer: C = $outer
          }
          new C.this.E with scala.deriving.Mirror.Singleton {...}():C.this.E
        }
      type MirroredMonoType = C.this.E
      def ordinal(x$0: C.E.MirroredMonoType): Int = x$0.ordinal
      private def $outer: C
      final def C$E$$$$outer: C = C.E.$outer
    }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 1522
exception occurred while compiling enum-class.scala
java.lang.AssertionError: assertion failed: failure to construct path from value <local $anon>/anonymous class C.this.E with scala.deriving.Mirror.Singleton {...}/value A/object E/class C/package <empty>/package <root> to `this` of object E in class C;
class C does not have an outer accessor while compiling enum-class.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: failure to construct path from value <local $anon>/anonymous class C.this.E with scala.deriving.Mirror.Singleton {...}/value A/object E/class C/package <empty>/package <root> to `this` of object E in class C;
class C does not have an outer accessor
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.loop$1(ExplicitOuter.scala:401)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.path$extension(ExplicitOuter.scala:407)
        at dotty.tools.dotc.transform.Erasure$Typer.typedThis(Erasure.scala:498)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2152)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:421)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2131)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:421)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2131)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:539)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2151)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2294)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:711)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:714)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2158)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:1483)
        at dotty.tools.dotc.transform.Erasure$Typer.typedValDef(Erasure.scala:596)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2135)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1802)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2181)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:100)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:316)
        at scala.collection.immutable.List.map(List.scala:286)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:318)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
        at dotty.tools.dotc.Run.compileSources(Run.scala:120)
        at dotty.tools.dotc.Run.compile(Run.scala:104)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:34)
        at dotty.tools.dotc.Driver.process(Driver.scala:172)
        at dotty.tools.dotc.Driver.process(Driver.scala:141)
        at dotty.tools.dotc.Driver.process(Driver.scala:153)
        at dotty.tools.dotc.Driver.main(Driver.scala:180)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by bishabosha** [comment]
I can't reproduce this in `0.20.0-RC1` with `dotc` or in the REPL so I believe its resolved.
