### ISSUE TITLE
AssertionError: NoDenotation.owner on function returning polymorphic function

### ISSUE THREAD

**Issue by panacekcz** [lampepfl/dotty#6678]
Code:
```scala
object O {
  val f = (i:Int) => [T] => (s:String) => 2
  def m = f(1)("a")
}
```
Output:
```
exception while typing O.f.apply(1).apply of class class dotty.tools.dotc.ast.Trees$Select # 1164
exception while typing O.f.apply(1).apply[Any] of class class dotty.tools.dotc.ast.Trees$TypeApply # 1166
exception while typing O.f.apply(1).apply[Any]("a") of class class dotty.tools.dotc.ast.Trees$Apply # 1167
exception while typing def m: Int = O.f.apply(1).apply[Any]("a") of class class dotty.tools.dotc.ast.Trees$DefDef # 1168
exception while typing @scala.annotation.internal.SourceFile("pf.scala") final module class

O$() extends Object(), Serializable {
  private def writeReplace(): AnyRef =
    new scala.runtime.ModuleSerializationProxy(classOf[O.type])
  def f: Int => PolyFunction{apply: [T](s: String): Int} =
    {
      def $anonfun(i: Int): PolyFunction{apply: [T](s: String): Int} =
        {
          final class $anon() extends Object(), PolyFunction {
            def apply[T](s: String): Int = 2
          }
          new Object with PolyFunction {...}():
            PolyFunction{apply: [T](s: String): Int}
        }
      closure($anonfun)
    }
  def m: Int = O.f.apply(1).apply[Any]("a")
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 1275
exception while typing package <empty> {
  final lazy module val O: O$ = new O$()
  @scala.annotation.internal.SourceFile("pf.scala") final module
    class
   O$() extends Object(), Serializable {
    private def writeReplace(): AnyRef =
      new scala.runtime.ModuleSerializationProxy(classOf[O.type])
    def f: Int => PolyFunction{apply: [T](s: String): Int} =
      {
        def $anonfun(i: Int): PolyFunction{apply: [T](s: String): Int} =
          {
            final class $anon() extends Object(), PolyFunction {
              def apply[T](s: String): Int = 2
            }
            new Object with PolyFunction {...}():
              PolyFunction{apply: [T](s: String): Int}
          }
        closure($anonfun)
      }
    def m: Int = O.f.apply(1).apply[Any]("a")
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 1276
exception occurred while compiling pf.scala
java.lang.AssertionError: NoDenotation.owner while compiling pf.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
        at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2113)
        at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$3$$anonfun$2(Erasure.scala:434)
        at dotty.tools.dotc.core.Symbols$Symbol.orElse(Symbols.scala:600)
        at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$1(Erasure.scala:442)
        at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:446)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2131)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:521)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2168)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:539)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2151)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1549)
        at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:631)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2138)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2204)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2270)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2316)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:738)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1802)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2181)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2205)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2239)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2251)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2329)
        at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:100)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:316)
        at scala.collection.immutable.List.map(List.scala:286)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:318)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
        at dotty.tools.dotc.Run.compileSources(Run.scala:120)
        at dotty.tools.dotc.Run.compile(Run.scala:104)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:34)
        at dotty.tools.dotc.Driver.process(Driver.scala:172)
        at dotty.tools.dotc.Driver.process(Driver.scala:141)
        at dotty.tools.dotc.Driver.process(Driver.scala:153)
        at dotty.tools.dotc.Driver.main(Driver.scala:180)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by kubukoz** [comment]
I have another example of this:

```scala
scala> val f: ([A] => A => A) => [B] => B => B = g => [B] => (b:B) => g(b)
val f: PolyFunction{apply: [A](x$1: A): A} =>
  PolyFunction{apply: [B](x$1: B): B} = Lambda$1605/0x0000000841160040@20eb7f95

scala> val identity: [X] => X => X = [X] => (a: X) => a
val identity: PolyFunction{apply: [X](x$1: X): X} = <function1>

scala> f(identity)(10)
exception while typing f.apply(identity).apply of class class dotty.tools.dotc.ast.Trees$Select # 930865
exception while typing f.apply(identity).apply[Int] of class class dotty.tools.dotc.ast.Trees$TypeApply # 930923
exception while typing f.apply(identity).apply[Int](10) of class class dotty.tools.dotc.ast.Trees$Apply # 930924
exception while typing def res1: Int = f.apply(identity).apply[Int](10) of class class dotty.tools.dotc.ast.Trees$DefDef # 930927
exception while typing @scala.annotation.internal.SourceFile("rs$line$16") final module class
  rs$line$16$
() extends Object(), Serializable {
  private def writeReplace(): AnyRef =
    new scala.runtime.ModuleSerializationProxy(classOf[rs$line$16.type])
  def res1: Int = f.apply(identity).apply[Int](10)
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 930929
exception while typing package <empty> {
  final lazy module val rs$line$16: rs$line$16$ = new rs$line$16$()
  @scala.annotation.internal.SourceFile("rs$line$16") final module class
    rs$line$16$
  () extends Object(), Serializable {
    private def writeReplace(): AnyRef =
      new scala.runtime.ModuleSerializationProxy(classOf[rs$line$16.type])
    def res1: Int = f.apply(identity).apply[Int](10)
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 930930
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2253)
	at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$3$$anonfun$2(Erasure.scala:442)
	at dotty.tools.dotc.core.Symbols$Symbol.orElse(Symbols.scala:616)
	at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$1(Erasure.scala:451)
	at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:455)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2131)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2208)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
	at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:530)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2169)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2209)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:548)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2151)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2209)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1679)
	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:635)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2138)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2208)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2281)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2325)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:747)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1812)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2208)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2281)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2325)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:747)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1938)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2182)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2209)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:100)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:134)
	at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:156)
	at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:166)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:229)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:193)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:127)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:148)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by b-studios** [comment]
Potentially related to #8921
