### ISSUE TITLE
f"" string interpolator does not work because it is implemented by a scala.reflect macro

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#687]
```
[info] % dotc t8266-octal-interp.scala
[info] % java \
[info]   -classpath \
[info]   /Users/dark/workspace/dotty/tests/partest-generated/run/t8266-octal-interp-run.obj:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/me.d-d/scala-compiler/jars/scala-compiler-2.11.5-20150619-173733-3bcd390afa.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dfile.encoding=UTF-8 \
[info]   -Djava.library.path=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.output=/Users/dark/workspace/dotty/tests/partest-generated/run/t8266-octal-interp-run.obj \
[info]   -Dpartest.lib=/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dpartest.reflect=/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar \
[info]   -Dpartest.comp=/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar \
[info]   -Dpartest.cwd=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.test-path=/Users/dark/workspace/dotty/tests/partest-generated/run/t8266-octal-interp.scala \
[info]   -Dpartest.testname=t8266-octal-interp \
[info]   -Djavacmd=java \
[info]   -Djavaccmd=javac \
[info]   -Duser.language=en \
[info]   -Duser.country=US \
[info]   scala.tools.nsc.MainGenericRunner \
[info]   -usejavacp \
[info]   Test \
[info]   jvm > t8266-octal-interp-run.log
[info] java.lang.NoSuchMethodError: scala.StringContext.f(Lscala/collection/Seq;)Ljava/lang/String;
[info]  at X.f(t8266-octal-interp.scala:9)
[info]  at Test$.<init>(t8266-octal-interp.scala:20)
[info]  at Test$.<clinit>(t8266-octal-interp.scala)
[info]  at Test.main(t8266-octal-interp.scala)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]  at java.lang.reflect.Method.invoke(Method.java:497)
[info]  at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
[info]  at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
[info]  at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[info]  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
[info]  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
[info]  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
[info]  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
[info]  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
[info]  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
[info]  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
[info]  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by DarkDimius** [comment]
Same with t8091.scala

**Comment by smarter** [comment]
`f` is a macro, so I don't think it'll work: http://www.scala-lang.org/api/current/index.html#scala.StringContext@f[A%3E:Any]%28args:A*%29:String Should we move these tests to `tests/disabled/macro`?

**Comment by odersky** [comment]
yes, let's move to disabled.

**Comment by liufengyun** [comment]
The latest development: https://github.com/alemannosara/f-interpolators-in-Dotty-macros

**Comment by nicolasstucki** [comment]
Now it works using the implementation in https://github.com/lampepfl/dotty/blob/master/library/src-3.x/dotty/internal/StringContext.scala which is functional but does not perform compile-time checks.
There is a WIP that implements all these checks in the current macro framework https://github.com/alemannosara/f-interpolators-in-Dotty-macros which will be used once ready.
