### ISSUE TITLE
t8002.scala: Constructor not found

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#689]
```
[info] % dotc t8002.scala
[info] % java \
[info]   -classpath \
[info]   /Users/dark/workspace/dotty/tests/partest-generated/run/t8002-run.obj:/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar:/Users/dark/.ivy2/cache/me.d-d/scala-compiler/jars/scala-compiler-2.11.5-20150619-173733-3bcd390afa.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dfile.encoding=UTF-8 \
[info]   -Djava.library.path=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.output=/Users/dark/workspace/dotty/tests/partest-generated/run/t8002-run.obj \
[info]   -Dpartest.lib=/Users/dark/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar \
[info]   -Dpartest.reflect=/Users/dark/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar \
[info]   -Dpartest.comp=/Users/dark/workspace/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar \
[info]   -Dpartest.cwd=/Users/dark/workspace/dotty/tests/partest-generated/run \
[info]   -Dpartest.test-path=/Users/dark/workspace/dotty/tests/partest-generated/run/t8002.scala \
[info]   -Dpartest.testname=t8002 \
[info]   -Djavacmd=java \
[info]   -Djavaccmd=javac \
[info]   -Duser.language=en \
[info]   -Duser.country=US \
[info]   scala.tools.nsc.MainGenericRunner \
[info]   -usejavacp \
[info]   Test \
[info]   jvm > t8002-run.log
[info] java.lang.NoSuchMethodError: Test$A$5$1$: method <init>()V not found
[info] 	at Test$A$5$1$.<clinit>(t8002.scala)
[info] 	at Test$.A$lzyINIT1$1(t8002.scala:9)
[info] 	at Test$.Test$a$$A$5(t8002.scala:9)
[info] 	at Test$.<init>(t8002.scala:13)
[info] 	at Test$.<clinit>(t8002.scala)
[info] 	at Test.main(t8002.scala)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] 	at java.lang.reflect.Method.invoke(Method.java:497)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
[info] 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[info] 	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
[info] 	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
[info] 	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
[info] 	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
[info] 	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
[info] 	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
[info] 	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
[info] 	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
[info] 	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by smarter** [comment]
Simplified example:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    object A {
      def a = new A
      def y = 0
    }
    class A { A.y }
    A.a
  }
}
```
The module class A ends up with the following static initializer:
```java
  public static {};
    Code:
       0: new           #2                  // class Test$A$1$
       3: invokespecial #20                 // Method "<init>":()V
       6: return
```
but the only constructor which exists takes a `LazyRef`:
```java
  public Test$A$1$(dotty.runtime.LazyRef);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #23                 // Field A$lzy1$5:Ldotty/runtime/LazyRef;
       5: aload_0
       6: invokespecial #24                 // Method java/lang/Object."<init>":()V
       9: aload_0
      10: putstatic     #26                 // Field MODULE$:LTest$A$1$;
      13: return
```

**Comment by odersky** [comment]
Looks like its related to lazyvals?

**Comment by DarkDimius** [comment]
I believe that's a bug in lambdalift(or in cooperation between lambdalift and lazyVals). After LambaLift we have a top level ` private final module class A$2$1$ ` with constructor that takes arguments. 

First of all there should be no such thing as `private` on top level, 
second GenBCode assumes that all top level module classes have constructors that do not take arguments. 

My guess would be that if lambdaLift lifts class to static scope, it whould strip flags: `&~(Module || Private)`
```
package <empty> {
  final lazy module val Test: Test$ = new Test$()
  final module class Test$ extends Object { this: <notype> =>
    def <init>(): Unit = {
      super()
      ()
    }
    def main(args: String[]): Unit = {
      lazy var A$lzy1: dotty.runtime.LazyRef = new dotty.runtime.LazyRef()
      {
        Test.A$2(A$lzy1).a()
        ()
      }
    }
    private def A$lzyINIT1$1(A$lzy1$1: dotty.runtime.LazyRef): Test$A$2$1$ =
      A$lzy1$1.synchronized(
        if A$lzy1$1.initialized() then A$lzy1$1.value() else {
          A$lzy1$1.initialized_=(true)
          A$lzy1$1.value_=(new Test$A$2$1$(A$lzy1$1))
          A$lzy1$1.value()
        }
      ).asInstanceOf[Test$A$2$1$]
    private final lazy <accessor> module def A$2(A$lzy1$2: dotty.runtime.LazyRef
      )
    : Test$A$2$1$ =
      (if A$lzy1$2.initialized() then A$lzy1$2.value() else
        Test.A$lzyINIT1$1(A$lzy1$2)
      ).asInstanceOf[Test$A$2$1$]
  }
  private class A$1 extends Object {
    def <init>(A$lzy1$3: dotty.runtime.LazyRef): Unit = {
      this.A$lzy1$3 = A$lzy1$3
      super()
      Test.A$2(A$lzy1$3).y()
      ()
    }
    private val A$lzy1$3: dotty.runtime.LazyRef
  }
  private final module class A$2$1$ extends Object { this: <notype> =>
    def <init>(A$lzy1$5: dotty.runtime.LazyRef): Unit = {
      this.A$lzy1$5 = A$lzy1$5
      super()
      ()
    }
    private val A$lzy1$5: dotty.runtime.LazyRef
    def a(): Test$A$1 = new Test$A$1(this.A$lzy1$5)
    def y(): Int = 0
  }
}
```

**Comment by DarkDimius** [comment]
Note, that by doing some time traveling I can fix all this in backend, but generally speaking I believe that top level `private final module class A$2$1$` with non-empty constructor is not a module.
I also believe that printed above code shouldn't typecheck, as the line 
```scala
        Test.A$2(A$lzy1).a() // here
``` 
accesses a member `a` of a `private` class  that it shouldn't have access to.

**Comment by odersky** [comment]
@DarkDimius Privacy is not transitive in Dotty. You can still access a member of a private class if you hold a public reference to the class.

**Comment by DarkDimius** [comment]
> if you hold a public reference to the class.

If you hold a public reference to the class, shouldn't it type be widened to be publicly accessible? Similar to what happens in such code 
```scala
object Foo {
  private class A extends Serializable { def fooBar = 1}
  def foo: A = {
     new A
  }
}
```
This doesn't compile in scalac, but does compile in Dotty.

**Comment by odersky** [comment]
@DarkDimius It's a slightly different problem. We decided that the Scala 2 solution is too fragile and creates too many hassles so we did not do it.

Certainly top-level classes can be `private`. They are then private to the enclosing package. I don't see the problem here. 

I am not sure about stripping `Module`. We can do it, but we need a rule when exactly it should be done. Only for classes with non-empty constructors? Or for all lambda lifted classes? But by what rationale?

**Comment by DarkDimius** [comment]
> Certainly top-level classes can be private. They are then private to the enclosing package. I don't see the problem here. 

If I understood you correctly, this is the very same as `default` visibility modifier in Java. Is it? If yes, should we compile it in the same way in Dotty? At least scalac compiles such code:
```scala
private class C {}
```
to a public class on the bytecode level, with public constructor.

> Only for classes with non-empty constructors? Or for all lambda lifted classes? But by what rationale?

For every module class, lifted into static scope. The rationale is: static modules are singletons(and backend treats them as such). Non top-level modules aren't, as in this example for every invocation of `main` instance of `module A` should be created.

**Comment by odersky** [comment]
@DarkDimius private classes should probably be translated to package-private in Java. Same for the constructor. 

Dropping "module" from lifted classes makes sense. I'll try to do this.
