### ISSUE TITLE
macros: remove or restrict `symbol.tree` to avoid CyclicReference exception

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#7025]
Current macro system exposes `symbol.tree` to get the tree of a symbol. However, its usage in macros easily leads to `CyclicReference` exception.

## minimized code

`Macro_1.scala`:

```Scala
  import scala.quoted._
  import scala.tasty._

  def debugImpl given (qctx: QuoteContext): Expr[Unit] = {
    import qctx.tasty._

    def nearestEnclosingDef(owner: Symbol): Symbol =
      owner match {
        case IsDefDefSymbol(x)   => x
        case IsClassDefSymbol(x) => x
        case _                   => nearestEnclosingDef(owner.owner)
      }

    nearestEnclosingDef(rootContext.owner) match {
        case IsDefDefSymbol(x) =>
          val code = x.tree.show
          '{ println(${code.toExpr}) }
        case _ =>
          '{()}
      }
  }
}
```
`Test_2.scala`:

```Scala
object Test {
  def main(args: Array[String]): Unit = {
    bar("world", 100, true)
  }

  def bar(a1: String, a2: Long, a3: Boolean) = {  // works fine with explicit return type
    debug
  }
}
```

## expectation

The code above leads to `CyclicReference` exception:

<details>
<summary>stack trace</summary>
<pre>
-- Error: Test_2.scala:7:4 ---------------------------------------------------------------------
7 |    debug
  |    ^^^^^
  |Exception occurred while executing macro expansion.
  |dotty.tools.dotc.core.CyclicReference:
  |	at dotty.tools.dotc.core.CyclicReference$.apply(TypeErrors.scala:157)
  |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:249)
  |	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:180)
  |	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:182)
  |	at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:224)
  |	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:221)
  |	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:218)
  |	at dotty.tools.dotc.tastyreflect.FromSymbol$.defDefFromSym(FromSymbol.scala:46)
  |	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.DefDefSymbol_tree(ReflectionCompilerInterface.scala:1644)
  |	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.DefDefSymbol_tree(ReflectionCompilerInterface.scala:1643)
  |	at scala.tasty.reflect.SymbolOps$DefDefSymbolAPI.tree(SymbolOps.scala:217)
  |	at Macros$.debugImpl(Macro_1.scala:24)
  |
  | This location is in code that was inlined at Test_2.scala:7
</pre>
</details>

To avoid such crashes with `symbol.tree`, we may either:

- remove `symbol.tree` in the API (scala2 macros doesn't have such an API)
- only expose the API in black-box macros, and make black-box macros expand in a later phase

**Comment by milessabin** [comment]
shapeless 3's `Typeable` uses `Symbol#tree` [here](https://github.com/milessabin/shapeless/blob/shapeless-3/core/src/main/scala/shapeless/typeable.scala#L393). I'd be happy to change that if there's an alternative.

**Comment by milessabin** [comment]
`Typeable` is blackbox, so the second option might be viable.

**Comment by LPTK** [comment]
How about having `symbol.tree` return `Either[CyclicReference,Tree]`? This way, macro authors are forced to be careful with this feature and have to handle the cases when it's not applicable — they can for example fall back to some alternative macro implementation when it happens, or return an error to the user such as "please provide an explicit type for ...".

Having the ability to examine the trees of symbols sounds extremely useful from a macro author perspective. Scala 2 macros often go through very ugly hacks because they don't have it (including casting their way through to expose internal compiler APIs so they can look at the surrounding trees). As another example, IIRC the [quill library](https://github.com/getquill/quill) has been stashing trees in _annotations_ in order to recover them later, but that's a hack and it has plenty of drawbacks.

**Comment by liufengyun** [comment]
Thanks for sharing the use cases @LPTK @milessabin .

It seems `CyclicReference` is not a good argument to remove `symbol.tree`, as `symbol.signature` may also cause `CyclicReference` exceptions.

```Scala
inline def debug: Unit = ${Macros.debugImpl}

object Macros {
  import scala.quoted._
  import scala.tasty._

  def debugImpl given (qctx: QuoteContext): Expr[Unit] = {
    import qctx.tasty._

    def nearestEnclosingDef(owner: Symbol): Symbol =
      owner match {
        case IsDefDefSymbol(x)   => x
        case IsClassDefSymbol(x) => x
        case _                   => nearestEnclosingDef(owner.owner)
      }

    nearestEnclosingDef(rootContext.owner) match {
        case IsDefDefSymbol(x) =>
          val code = x.signature.toString
          '{ println(${code.toExpr}) }
        case _ =>
          '{()}
      }
  }
}
```

```Scala
object Test {
  def main(args: Array[String]): Unit = {
    bar("world", 100, true)
  }

  def bar(a1: String, a2: Long, a3: Boolean) = {
    debug
  }
}
```

**Comment by nicolasstucki** [comment]
Another approach could be to just not set the trese when expanding white box macros.

**Comment by liufengyun** [comment]
Reopen: the original test is not added.

**Comment by nicolasstucki** [comment]
@liufengyun the original test is incomplete

**Comment by liufengyun** [comment]
@nicolasstucki Updated.

**Comment by LPTK** [comment]
Out of curiosity, what does the [current test](https://github.com/lampepfl/dotty/commit/f4bd25fdeb66d0c22e1ca9ca6da531b014026f95) print? Or does it take the other branch and not print anything?
