### ISSUE TITLE
Misleading error message when implicitly depending on some non-existing packages

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7072]
```scala
scala> def f given foo.Bar: Any = ???  // Good
1 |def f given foo.Bar: Any = ???
  |            ^^^
  |            Not found: foo

scala> def f given scala.foo.Bar: Any = ???  // Bad
1 |def f given scala.foo.Bar: Any = ???
  |            ^
  |            Cyclic reference involving implicit value x$1
```

**Comment by milessabin** [comment]
This isn't specific to core packages,

```scala
scala> object baz
// defined object baz

scala> def f given baz.foo.Bar: Any = ???  // Bad
1 |def f given baz.foo.Bar: Any = ???  // Bad
  |            ^
  |            Cyclic reference involving implicit value x$1

scala>
```

**Comment by anatoliykmetyuk** [comment]
Also:

```scala
object stuff

def f(given stuff.Foo { type A <: String }) = ???

def g = f
```

Gives a crash:

<details><summary>Crash</summary>

```scala
-- [E047] Cyclic Error: ../pg/i5.scala:3:12 ------------------------------------
3 |def f(given stuff.Foo { type A <: String }) = ???
  |            ^
  |            Cyclic reference involving implicit value x$1

longer explanation available when compiling with `-explain`
exception occurred while typechecking ../pg/i5.scala
exception occurred while compiling ../pg/i5.scala
scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$) while compiling ../pg/i5.scala
Exception in thread "main" scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$)
	at dotty.tools.dotc.core.TypeComparer.ensureStableSingleton(TypeComparer.scala:1488)
	at dotty.tools.dotc.core.TypeComparer.compareRec$1(TypeComparer.scala:553)
	at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:556)
	at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:443)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:354)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1069)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:159)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:169)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:126)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:853)
	at dotty.tools.dotc.typer.Implicits.trySpecialCases$1(Implicits.scala:1107)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:1116)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:83)
	at dotty.tools.dotc.typer.Typer.implicitArgs$2(Typer.scala:2557)
	at dotty.tools.dotc.typer.Typer.addImplicitArgs$4(Typer.scala:2580)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$2(Typer.scala:2647)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2818)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3046)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2452)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1211)
	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1201)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1211)
	at dotty.tools.dotc.typer.Namer.rhsType$2(Namer.scala:1346)
	at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1357)
	at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1358)
	at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1369)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1377)
	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1446)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:769)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:886)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:796)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:257)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:182)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:184)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:397)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2013)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2038)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1727)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2051)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1852)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2092)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2117)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2241)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:75)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:41)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:109)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:109)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:184)
	at dotty.tools.dotc.Run.compileSources(Run.scala:121)
	at dotty.tools.dotc.Run.compile(Run.scala:104)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.dotc.Driver.process(Driver.scala:178)
	at dotty.tools.dotc.Driver.process(Driver.scala:147)
	at dotty.tools.dotc.Driver.process(Driver.scala:159)
	at dotty.tools.dotc.Driver.main(Driver.scala:186)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by odersky** [comment]
I now get:
```
-- [E008] Not Found Error: -----------------------------------------------------
1 |def f(using scala.foo.Bar): Any = ??? 
  |            ^^^^^^^^^
  |            value foo is not a member of scala.
  |            Extension methods were tried, but the search failed with:
  |
  |                Cyclic reference involving implicit parameter x$1
1 error found
```
and there is no more crash either.
