### ISSUE TITLE
incremental compilation fails on windows in cmd

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#7135]
When running dotty in sbt from a cmd console in windows, all is initially well. However, when I make any changes, and sbt attempts to recompile, zinc throws an exception at https://github.com/sbt/zinc/blob/f3825fb66ca72eebbbc7ee9a4f96fa919ff522b0/internal/zinc-classpath/src/main/scala/sbt/internal/inc/ScalaInstance.scala#L256

The underlying exception is swallowed, so I don't have more information about the cause of the message. The full error message is

```
[error] ## Exception when compiling 210 sources to C:\Users\marti\scala\dotty\library\..\out\bootstrap\dotty-library-bootstrapped\scala-0.18\classes
[error] Scala instance doesn't exist or is invalid:
[error]     version 0.18.1-bin-SNAPSHOT-nonbootstrapped, library jar: C:\Users\marti\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.13.0.jar, compiler jar: C:\Users\marti\scala\dotty\compiler\target\scala-0.18\dotty-compiler_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, other jars: C:\Users\marti\scala\dotty\library\target\scala-0.18\dotty-library_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\scala\dotty\interfaces\target\dotty-interfaces-0.18.1-bin-SNAPSHOT.jar, C:\Users\marti\scala\dotty\doc-tool\target\scala-0.18\dotty-doc_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\.ivy2\cache\org.scala-lang.modules\scala-asm\bundles\scala-asm-6.0.0-scala-1.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\compiler-interface\jars\compiler-interface-1.2.5.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.2.2.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-reader\jars\jline-reader-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal\jars\jline-terminal-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal-jna\jars\jline-terminal-jna-3.9.0.jar, C:\Users\marti\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.2.2.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark\jars\flexmark-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-util\jars\flexmark-util-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tasklist\jars\flexmark-ext-gfm-tasklist-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-formatter\jars\flexmark-formatter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tables\jars\flexmark-ext-gfm-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-autolink\jars\flexmark-ext-autolink-0.28.32.jar, C:\Users\marti\.ivy2\cache\org.nibor.autolink\autolink\jars\autolink-0.6.0.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-anchorlink\jars\flexmark-ext-anchorlink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-emoji\jars\flexmark-ext-emoji-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-jira-converter\jars\flexmark-jira-converter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-strikethrough\jars\flexmark-ext-gfm-strikethrough-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-tables\jars\flexmark-ext-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-wikilink\jars\flexmark-ext-wikilink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-ins\jars\flexmark-ext-ins-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-superscript\jars\flexmark-ext-superscript-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-yaml-front-matter\jars\flexmark-ext-yaml-front-matter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.dataformat\jackson-dataformat-yaml\bundles\jackson-dataformat-yaml-2.9.8.jar, C:\Users\marti\.ivy2\cache\org.yaml\snakeyaml\bundles\snakeyaml-1.23.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.9.8.jar, C:\Users\marti\.ivy2\cache\nl.big-o\liqp\jars\liqp-0.6.7.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr\jars\antlr-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr-runtime\jars\antlr-runtime-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\ST4\jars\ST4-4.0.7.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\jars\jackson-annotations-2.2.3.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\jars\jackson-databind-2.2.3.jar, C:\Users\marti\.ivy2\cache\org.jsoup\jsoup\jars\jsoup-1.7.2.jar
[error] sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:240)
[error] sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:225)
[error] sbt.internal.inc.ScalaInstance.$anonfun$actualVersion$1(ScalaInstance.scala:88)
[error] scala.Option.getOrElse(Option.scala:121)
[error] sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:86)
[error] sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:85)
[error] sbt.internal.inc.MixedAnalyzingCompiler$.makeConfig(MixedAnalyzingCompiler.scala:203)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:260)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:278)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]
[error] sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid:
[error]     version 0.18.1-bin-SNAPSHOT-nonbootstrapped, library jar: C:\Users\marti\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.13.0.jar, compiler jar: C:\Users\marti\scala\dotty\compiler\target\scala-0.18\dotty-compiler_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, other jars: C:\Users\marti\scala\dotty\library\target\scala-0.18\dotty-library_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\scala\dotty\interfaces\target\dotty-interfaces-0.18.1-bin-SNAPSHOT.jar, C:\Users\marti\scala\dotty\doc-tool\target\scala-0.18\dotty-doc_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\.ivy2\cache\org.scala-lang.modules\scala-asm\bundles\scala-asm-6.0.0-scala-1.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\compiler-interface\jars\compiler-interface-1.2.5.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.2.2.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-reader\jars\jline-reader-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal\jars\jline-terminal-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal-jna\jars\jline-terminal-jna-3.9.0.jar, C:\Users\marti\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.2.2.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark\jars\flexmark-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-util\jars\flexmark-util-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tasklist\jars\flexmark-ext-gfm-tasklist-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-formatter\jars\flexmark-formatter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tables\jars\flexmark-ext-gfm-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-autolink\jars\flexmark-ext-autolink-0.28.32.jar, C:\Users\marti\.ivy2\cache\org.nibor.autolink\autolink\jars\autolink-0.6.0.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-anchorlink\jars\flexmark-ext-anchorlink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-emoji\jars\flexmark-ext-emoji-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-jira-converter\jars\flexmark-jira-converter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-strikethrough\jars\flexmark-ext-gfm-strikethrough-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-tables\jars\flexmark-ext-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-wikilink\jars\flexmark-ext-wikilink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-ins\jars\flexmark-ext-ins-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-superscript\jars\flexmark-ext-superscript-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-yaml-front-matter\jars\flexmark-ext-yaml-front-matter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.dataformat\jackson-dataformat-yaml\bundles\jackson-dataformat-yaml-2.9.8.jar, C:\Users\marti\.ivy2\cache\org.yaml\snakeyaml\bundles\snakeyaml-1.23.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.9.8.jar, C:\Users\marti\.ivy2\cache\nl.big-o\liqp\jars\liqp-0.6.7.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr\jars\antlr-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr-runtime\jars\antlr-runtime-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\ST4\jars\ST4-4.0.7.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\jars\jackson-annotations-2.2.3.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\jars\jackson-databind-2.2.3.jar, C:\Users\marti\.ivy2\cache\org.jsoup\jsoup\jars\jsoup-1.7.2.jar
[error]         at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:240)
[error]         at sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:225)
[error]         at sbt.internal.inc.ScalaInstance.$anonfun$actualVersion$1(ScalaInstance.scala:88)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:86)
[error]         at sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:85)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler$.makeConfig(MixedAnalyzingCompiler.scala:203)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:260)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.Properties
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:233)
[error]         at sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:225)
[error]         at sbt.internal.inc.ScalaInstance.$anonfun$actualVersion$1(ScalaInstance.scala:88)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:86)
[error]         at sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:85)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler$.makeConfig(MixedAnalyzingCompiler.scala:203)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:260)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
sbt:dotty> [error] (dotty-library-bootstrapped / Compile / compileIncremental) sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid:
[error]     version 0.18.1-bin-SNAPSHOT-nonbootstrapped, library jar: C:\Users\marti\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.13.0.jar, compiler jar: C:\Users\marti\scala\dotty\compiler\target\scala-0.18\dotty-compiler_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, other jars: C:\Users\marti\scala\dotty\library\target\scala-0.18\dotty-library_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\scala\dotty\interfaces\target\dotty-interfaces-0.18.1-bin-SNAPSHOT.jar, C:\Users\marti\scala\dotty\doc-tool\target\scala-0.18\dotty-doc_0.18-0.18.1-bin-SNAPSHOT-nonbootstrapped.jar, C:\Users\marti\.ivy2\cache\org.scala-lang.modules\scala-asm\bundles\scala-asm-6.0.0-scala-1.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\compiler-interface\jars\compiler-interface-1.2.5.jar, C:\Users\marti\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.2.2.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-reader\jars\jline-reader-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal\jars\jline-terminal-3.9.0.jar, C:\Users\marti\.ivy2\cache\org.jline\jline-terminal-jna\jars\jline-terminal-jna-3.9.0.jar, C:\Users\marti\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.2.2.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark\jars\flexmark-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-util\jars\flexmark-util-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tasklist\jars\flexmark-ext-gfm-tasklist-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-formatter\jars\flexmark-formatter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-tables\jars\flexmark-ext-gfm-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-autolink\jars\flexmark-ext-autolink-0.28.32.jar, C:\Users\marti\.ivy2\cache\org.nibor.autolink\autolink\jars\autolink-0.6.0.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-anchorlink\jars\flexmark-ext-anchorlink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-emoji\jars\flexmark-ext-emoji-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-jira-converter\jars\flexmark-jira-converter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-gfm-strikethrough\jars\flexmark-ext-gfm-strikethrough-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-tables\jars\flexmark-ext-tables-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-wikilink\jars\flexmark-ext-wikilink-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-ins\jars\flexmark-ext-ins-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-superscript\jars\flexmark-ext-superscript-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.vladsch.flexmark\flexmark-ext-yaml-front-matter\jars\flexmark-ext-yaml-front-matter-0.28.32.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.dataformat\jackson-dataformat-yaml\bundles\jackson-dataformat-yaml-2.9.8.jar, C:\Users\marti\.ivy2\cache\org.yaml\snakeyaml\bundles\snakeyaml-1.23.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.9.8.jar, C:\Users\marti\.ivy2\cache\nl.big-o\liqp\jars\liqp-0.6.7.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr\jars\antlr-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\antlr-runtime\jars\antlr-runtime-3.5.1.jar, C:\Users\marti\.ivy2\cache\org.antlr\ST4\jars\ST4-4.0.7.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\jars\jackson-annotations-2.2.3.jar, C:\Users\marti\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\jars\jackson-databind-2.2.3.jar, C:\Users\marti\.ivy2\cache\org.jsoup\jsoup\jars\jsoup-1.7.2.jar

```
I initially reported against zinc, at https://github.com/sbt/zinc/issues/695 but was told this is an issue in the dotty sbt plugin.

**Comment by smarter** [comment]
> 0.18.1-bin-SNAPSHOT-nonbootstrapped

Don't try to use non bootstrapped versions, they're not tested in the wild, you can publish a bootstrapped compiler by running `dotty-bootstrapped/publishLocal`

**Comment by martijnhoekstra** [comment]
then what is the `dotc` task intended for?

**Comment by smarter** [comment]
The dotc task is used to make the development of Dotty faster, did you experience this crash in the build of Dotty itself?

**Comment by martijnhoekstra** [comment]
the crash occurs when running the `dotc` task any time recompilation of dotty occurs.

**Comment by smarter** [comment]
I guess this is yet another instance of things going wrong on Windows when an open file needs to be deleted/replaced. Did this always happen or is it a recent development?

**Comment by martijnhoekstra** [comment]
It always happened -- so far, I held off reporting so far until something serendipitously fixed it. So far that didn't happen.

I can only reproduce this in cmd, in mingw everything is fine (but I had some issues with sbt there in the past, hence running on cmd)

**Comment by martijnhoekstra** [comment]
I suspect that a class file isn't properly deleted, and then not created, hence the crash in attempting to load the class, but zinc doesn't give any specifics -- it could also be unreadable because of permissions or written out wrong for some platform encoding reason, or just a race condition on delete returning before actually deleting a file, or ...

**Comment by szeiger** [comment]
The fact that it works with MinGW in my opinion indicates a smaller problem. Unless you're using  a MinGW-based JDK (which AFAIK doesn't exist) you're still running the standard Windows Java environment, with possible differences limited to the console, and options for the JVM and scalac that are set by the launcher script. My guess would be that the launcher script tells sbt "you're running on Unix" and sbt does its usual Unix stuff which happens to work better on Windows than the dedicated Windows stuff.

**Comment by martijnhoekstra** [comment]
Unfortunately, I've run into the same issue on MinGW too -- I'm not sure yet what's going on there, and in what cases it does or doesn't happen.

I've also been trying with WSL. That runs into issues with ~compile (which I'm told is likely an sbt issue: https://gitter.im/lampepfl/dotty?at=5d763e3ca08e2b4bd2b4f064 but not yet reported or minimized).

The matrix of variables is big, unfortunately -- launch script/shell/host OS/environment variables/dotty/scala2, which makes it tricky to get to the bottom of it.

I also have the impression there is a large amount of not really caring as long as it works for the core contributors since the ROI is limited.

**Comment by smarter** [comment]
Is this still an issue? I know @sjrd sometimes does work on Windows and I don't think he's encountered that.

**Comment by martijnhoekstra** [comment]
I've switched over my workflow for dotty and scala to WSL2, which has been OK for me. I haven't gotten the IDE to work on WSL, but apart from that it's been fine.

**Comment by smarter** [comment]
Great, closing then until someone reproduces the problem.

**Comment by sjrd** [comment]
I encounter this on a daily basis, several times a day, although only in the dotty repo. Now my workflow is to basically exit and restart sbt (only reloading is not enough) every time I make changes in the compiler and that I want to compile something with the compiler.
