### ISSUE TITLE
Nightly has been failing since 2009

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7190]
The first time it failed was in https://dotty-ci.epfl.ch/lampepfl/dotty/1179/1/8. Where the failure was

```
[error] Failed to close the repository
[error] Activity close started:2019-09-07T01:56:05.628Z, stopped:
[error] Failed: sources-staging, failureMessage:Missing: no sources jar found in folder '/ch/epfl/lamp/dotty-library_0.19/0.19.1-bin-20190905-6ecbd3e-NIGHTLY'
```
<details>
<summary>Stack trace</summary>

```scala
[error] Failed to close the repository
--
285 | [error] Activity close started:2019-09-07T01:56:05.628Z, stopped:
286 | [error] Failed: sources-staging, failureMessage:Missing: no sources jar found in folder '/ch/epfl/lamp/dotty-library_0.19/0.19.1-bin-20190905-6ecbd3e-NIGHTLY'
287 | [error] java.lang.Exception: Failed to close the repository
288 | [error] at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:740)
289 | [error] at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:832)
290 | [error] at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeRelease$1(Sonatype.scala:248)
291 | [error] at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
292 | [error] at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
293 | [error] at sbt.Command$.process(Command.scala:181)
294 | [error] at sbt.MainLoop$.processCommand(MainLoop.scala:151)
295 | [error] at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
296 | [error] at sbt.State$$anon$1.runCmd$1(State.scala:246)
297 | [error] at sbt.State$$anon$1.process(State.scala:250)
298 | [error] at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
299 | [error] at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
300 | [error] at sbt.MainLoop$.next(MainLoop.scala:139)
301 | [error] at sbt.MainLoop$.run(MainLoop.scala:132)
302 | [error] at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
303 | [error] at sbt.io.Using.apply(Using.scala:22)
304 | [error] at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
305 | [error] at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
306 | [error] at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
307 | [error] at sbt.MainLoop$.runLogged(MainLoop.scala:35)
308 | [error] at sbt.StandardMain$.runManaged(Main.scala:138)
309 | [error] at sbt.xMain.run(Main.scala:89)
310 | [error] at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
311 | [error] at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
312 | [error] at xsbt.boot.Launch$.run(Launch.scala:109)
313 | [error] at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
314 | [error] at xsbt.boot.Launch$.launch(Launch.scala:117)
315 | [error] at xsbt.boot.Launch$.apply(Launch.scala:18)
316 | [error] at xsbt.boot.Boot$.runImpl(Boot.scala:56)
317 | [error] at xsbt.boot.Boot$.main(Boot.scala:18)
318 | [error] at xsbt.boot.Boot.main(Boot.scala)
319 | [error] java.lang.Exception: Failed to close the repository
320 | [error] Use 'last' for the full log.


```
</details>

Then all the following days failed with
```
[error] Multiple repositories are found:
[error] [chepfllamp-2069] status:open, profile:ch.epfl.lamp(64287dc9e88633) description: Implicitly created (auto staging).
[error] [chepfllamp-2070] status:open, profile:ch.epfl.lamp(64287dc9e88633) description: Implicitly created (auto staging).
[error] Specify one of the repository ids in the command line
```

* https://dotty-ci.epfl.ch/lampepfl/dotty/1182/1/8
* https://dotty-ci.epfl.ch/lampepfl/dotty/1187/1/8
* https://dotty-ci.epfl.ch/lampepfl/dotty/1198/1/8

**Comment by smarter** [comment]
I've manually closed the open repository on https://oss.sonatype.org/, I've also opened https://github.com/lampepfl/dotty/pull/7193 to hopefully avoid this sort of things in the future.

**Comment by smarter** [comment]
Nightlies are back! https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.19/0.19.0-bin-20190910-54266c1-NIGHTLY/
