### ISSUE TITLE
When summoning from inline match, things go wrong if a type parameter is not bound correctly

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7250]
## minimized code

```Scala
import compiletime.erasedValue

sealed trait Foo
trait B[H] extends Foo

inline given f[T <: Foo]: T = inline erasedValue[T] match
  case _: B[a] => summon[a].asInstanceOf[T]

@main def Test = println(f[B[Int]])
```

<details>
<summary>Error</summary>

```scala
-- Error: ../pg/Main.scala:9:26 ------------------------------------------------
9 |@main def Test = println(f[B[Int]])
  |                         ^^^^^^^^^
  |                       Maximal number of successive inlines (32) exceeded,
  |                       Maybe this is caused by a recursive inline method?
  |                       You can use -Xmax-inlines to change the limit.
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:7
  | This location is in code that was inlined at Main.scala:9
one error found
[error] Nonzero exit code returned from runner: 1
[error] (dotty-compiler / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 9 s, completed Sep 18, 2019 4:01:59 PM
```
</details>

Also:

```scala
import compiletime.erasedValue

sealed trait Foo
trait A extends Foo
trait B[H] extends Foo

inline given f[T <: Foo]: T = inline erasedValue[T] match
  case _: A => new A{}.asInstanceOf[T]
  case _: B[a] => summon[a].asInstanceOf[T]

@main def Test = println(f[B[Int]])
```

Produces:

```scala
Exception in thread "main" java.lang.ClassCastException: Cannot cast to scala.Nothing
	at Main$package$.Test(Main.scala:8)
	at Test.main(Main.scala:11)
```

Line 8 is `case _: A => new A{}.asInstanceOf[T]`.

It looks like `a` is bound to `Nothing` and the summoning of it goes into the first `given` definition it sees.

Possibly related: #6018.

**Comment by odersky** [comment]
What happens is the following:

 - The first search to `B[Int]` will find `f`, and apply the inline match, ending with `a = Int`.
 - The `summon[a]` call will try `f[Int & Foo]`.
  - This apply the inline match again, succeeding with `a = Int & Foo`
 - The `summon[a]` call with try `F[Int & Foo]` again, which gives an infinite loop.

The variant with the added `case _: A => ` succeeds once #7249 is fixed.

**Comment by anatoliykmetyuk** [comment]
> The summon[a] call tries f[Int & Foo].

So `f[Int & Foo]` will inline to:

```scala
erasedValue[Int & Foo] match
  case _: B[a] => summon[a].asInstanceOf[T]
```

Why would an `erasedValue[Int & Foo]` match `B[a]` though? Giving us

```scala
This applies the inline match again, succeeding with a = Int & Foo
```
