### ISSUE TITLE
NoDenotation.owner inside MixinOps.isCurrent

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#737]
Can be reproduced in #735 
Happens during ResolveSuper

```
[error] Test dotc.tests.dotty failed: java.lang.AssertionError: NoDenotation.owner, took 4543.613 sec
[error]     at dotty.tools.dotc.core.SymDenotations$NoDenotation.owner(SymDenotations.scala:1720)
[error]     at dotty.tools.dotc.core.Types$NamedType.denotOfSym(Types.scala:1340)
[error]     at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1295)
[error]     at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1284)
[error]     at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1272)
[error]     at dotty.tools.dotc.core.Types$NamedType.symbol(Types.scala:1436)
[error]     at dotty.tools.dotc.core.Types$Type.widenIfUnstable(Types.scala:730)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:397)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:397)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.member(Types.scala:396)
[error]     at dotty.tools.dotc.core.Types$NamedType.asMemberOf(Types.scala:1418)
[error]     at dotty.tools.dotc.core.Types$NamedType.loadDenot(Types.scala:1406)
[error]     at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1295)
[error]     at dotty.tools.dotc.core.Types$NamedType.denotAt(Types.scala:1284)
[error]     at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1272)
[error]     at dotty.tools.dotc.core.Types$NamedType.symbol(Types.scala:1436)
[error]     at dotty.tools.dotc.core.TypeOps$$anonfun$dotty$tools$dotc$core$TypeOps$$asSeenFrom$2.apply(TypeOps.scala:80)
[error]     at dotty.tools.dotc.core.TypeOps$$anonfun$dotty$tools$dotc$core$TypeOps$$asSeenFrom$2.apply(TypeOps.scala:78)
[error]     at dotty.tools.dotc.reporting.Reporting$class.conditionalTraceIndented(Reporter.scala:141)
[error]     at dotty.tools.dotc.core.Contexts$Context.conditionalTraceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.core.TypeOps$class.dotty$tools$dotc$core$TypeOps$$asSeenFrom(TypeOps.scala:77)
[error]     at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:116)
[error]     at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:2901)
[error]     at dotty.tools.dotc.core.TypeOps$$anonfun$dotty$tools$dotc$core$TypeOps$$asSeenFrom$2.apply(TypeOps.scala:109)
[error]     at dotty.tools.dotc.core.TypeOps$$anonfun$dotty$tools$dotc$core$TypeOps$$asSeenFrom$2.apply(TypeOps.scala:78)
[error]     at dotty.tools.dotc.reporting.Reporting$class.conditionalTraceIndented(Reporter.scala:141)
[error]     at dotty.tools.dotc.core.Contexts$Context.conditionalTraceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.core.TypeOps$class.dotty$tools$dotc$core$TypeOps$$asSeenFrom(TypeOps.scala:77)
[error]     at dotty.tools.dotc.core.TypeOps$class.asSeenFrom(TypeOps.scala:47)
[error]     at dotty.tools.dotc.core.Contexts$Context.asSeenFrom(Contexts.scala:53)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$asSeenFrom$1.apply(Types.scala:589)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$asSeenFrom$1.apply(Types.scala:588)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.asSeenFrom(Types.scala:587)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:802)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:434)
[error]     at dotty.tools.dotc.core.Denotations$PreDenotation$class.asSeenFrom(Denotations.scala:911)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.asSeenFrom(Denotations.scala:434)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1514)
[error]     at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:429)
[error]     at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:494)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:397)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:397)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.member(Types.scala:396)
[error]     at dotty.tools.dotc.transform.MixinOps.isCurrent(MixinOps.scala:38)
[error]     at dotty.tools.dotc.transform.MixinOps.needsForwarder(MixinOps.scala:43)
[error]     at dotty.tools.dotc.transform.ResolveSuper$$anonfun$dotty$tools$dotc$transform$ResolveSuper$$methodOverrides$1$1.apply(ResolveSuper.scala:85)
[error]     at dotty.tools.dotc.transform.ResolveSuper$$anonfun$dotty$tools$dotc$transform$ResolveSuper$$methodOverrides$1$1.apply(ResolveSuper.scala:85)
[error]     at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
[error]     at dotty.tools.dotc.transform.ResolveSuper.dotty$tools$dotc$transform$ResolveSuper$$methodOverrides$1(ResolveSuper.scala:85)
[error]     at dotty.tools.dotc.transform.ResolveSuper$$anonfun$2.apply(ResolveSuper.scala:88)
[error]     at dotty.tools.dotc.transform.ResolveSuper$$anonfun$2.apply(ResolveSuper.scala:88)
[error]     at scala.collection.immutable.List.flatMap(List.scala:327)
[error]     at dotty.tools.dotc.transform.ResolveSuper.transformTemplate(ResolveSuper.scala:88)
[error]     at dotty.tools.dotc.transform.ResolveSuper.transformTemplate(ResolveSuper.scala:46)
```

**Comment by DarkDimius** [comment]
Somehow, by mixin there are two `module AlignedOps` in ScalacPatternExpander. Than code in mixin gets a `MultiDenotation` and is not able to handle it.

**Comment by odersky** [comment]
Where does it get the symbol which will be NoSymbol? Looks like we need a better test here to pick the right denotation.

**Comment by odersky** [comment]
I fixed the problem, it's part of the ycheck-methods PR.
