### ISSUE TITLE
error when emitting method call with backticked argument type 

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7514]
## minimized code

```Scala
class `m9().`
def m9(x: `m9().`) = ???
val foo = m9(null)
```

seems this started appearing after using scala-asm 7

<details>
<summary>Stack trace</summary>

```scala
Error while emitting demo$package$
exception occurred while compiling demo.scala
java.lang.IllegalArgumentException while compiling demo.scala
Exception in thread "main" java.lang.IllegalArgumentException
	at scala.tools.asm.Frame.getAbstractTypeFromDescriptor(Frame.java:367)
	at scala.tools.asm.Frame.push(Frame.java:544)
	at scala.tools.asm.Frame.execute(Frame.java:1035)
	at scala.tools.asm.MethodWriter.visitMethodInsn(MethodWriter.java:1056)
	at scala.tools.asm.tree.MethodInsnNode.accept(MethodInsnNode.java:117)
	at scala.tools.asm.tree.InsnList.accept(InsnList.java:144)
	at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:792)
	at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:690)
	at scala.tools.asm.tree.ClassNode.accept(ClassNode.java:426)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker2.getByteArray$1(GenBCode.scala:432)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker2.addToQ3(GenBCode.scala:438)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker2.run(GenBCode.scala:418)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:517)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:480)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:51)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:55)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:162)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:172)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:180)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:187)
	at dotty.tools.dotc.Run.compileSources(Run.scala:124)
	at dotty.tools.dotc.Run.compile(Run.scala:107)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by bishabosha** [comment]
This is now fixed
