### ISSUE TITLE
Drone CI fails os-lib

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7621]
Drone run failed on community-build for PR #7616 when testing os-lib

https://dotty-ci.epfl.ch/lampepfl/dotty/2676

```scala
-------------------------------- Running Tests -------------------------------- | 1060s
-- | --
18423 | Exception in thread "Thread-1" java.nio.file.NoSuchFileException: /tmp/3/community-build/community-projects/os-lib/out/scratch/watch/WatchTests/tests/singleFolder/folder4/nestedB | 1063s
18424 | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) | 1063s
18425 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) | 1063s
18426 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) | 1063s
18427 | at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) | 1063s
18428 | at java.nio.file.Files.newDirectoryStream(Files.java:457) | 1063s
18429 | at os.list$$anon$1.generate(ListOps.scala:35) | 1063s
18430 | at geny.Generator.foreach(Generator.scala:49) | 1063s
18431 | at geny.Generator.foreach$(Generator.scala:49) | 1063s
18432 | at os.list$$anon$1.foreach(ListOps.scala:33) | 1063s
18433 | at geny.Generator.toBuffer(Generator.scala:127) | 1063s
18434 | at geny.Generator.toBuffer$(Generator.scala:125) | 1064s
18435 | at os.list$$anon$1.toBuffer(ListOps.scala:33) | 1064s
18436 | at geny.Generator.toArray(Generator.scala:131) | 1064s
18437 | at geny.Generator.toArray$(Generator.scala:131) | 1064s
18438 | at os.list$$anon$1.toArray(ListOps.scala:33) | 1064s
18439 | at os.list$.apply(ListOps.scala:21) | 1064s
18440 | at os.list$.apply(ListOps.scala:25) | 1064s
18441 | at os.watch.WatchServiceWatcher.recursiveWatches(WatchServiceWatcher.scala:71) | 1064s
18442 | at os.watch.WatchServiceWatcher.run(WatchServiceWatcher.scala:103) | 1064s
18443 | at os.watch.package$.$anonfun$1(package.scala:39) | 1064s
18444 | at java.lang.Thread.run(Thread.java:748) | 1064s
18445 | X test.os.watch.WatchTests.singleFolder 3191ms | 1064s
18446 | utest.AssertionError: expectedChangedPaths == changedSubPaths | 1064s
18447 | expectedChangedPaths: Set[os.SubPath] = Set(folder3/nestedA/double-nested-file) | 1064s
18448 | changedSubPaths: Set[os.SubPath] = HashSet() | 1064s
18449 | utest.asserts.AssertsCommons.assertImpl(AssertsCommons.scala:30) | 1064s
18450 | utest.asserts.Asserts$.assertImpl(Asserts.scala:17) | 1064s
18451 | test.os.watch.WatchTests$.checkChanges$1(WatchTests.scala:6) | 1064s
18452 | test.os.watch.WatchTests$.checkFileManglingChanges$6(WatchTests.scala:6) | 1064s
18453 | test.os.watch.WatchTests$.$init$$$anonfun$10$$anonfun$9$$anonfun$9(WatchTests.scala:6) | 1064s
18454 | dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15) | 1064s
18455 | dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10) | 1064s
18456 | test.os.TestUtil$.prep(TestUtil.scala:67) | 1064s
18457 | test.os.watch.WatchTests$.$init$$$anonfun$11$$anonfun$10(WatchTests.scala:6) | 1064s
18458 | 1 targets failed
```

**Comment by sjrd** [comment]
This is also visible in #7617.
