### ISSUE TITLE
REPL crash with Eql

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#7644]
I have to admit the reporter was pretty stubborn at misreading the documentation in order to get there, and then trying once more, but anyways...

```Scala
scala> class T extends Eql
1 |class T extends Eql
  |      ^
  |      Cannot extend sealed trait Eql in a different source file
1 |class T extends Eql
  |                ^^^
  |                Missing type parameter for Eql

scala> class T extends Eql
Exception in thread "main" java.lang.AssertionError: assertion failed: denotation module class internal invalid in run 2. ValidFor: Period(1..4, run = 3)
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.updateValidity(Denotations.scala:828)
```

**Comment by liufengyun** [comment]
It works with the master:

```Scala
scala> class T extends Eql
1 | class T extends Eql
  |       ^
  |       Cannot extend sealed trait Eql in a different source file
1 | class T extends Eql
  |                 ^^^
  |                 Missing type parameter for Eql
scala> class T extends Eql
1 | class T extends Eql
  |       ^
  |       Cannot extend sealed trait Eql in a different source file
stale symbol; module class rs$line$1$#2503 in module class <empty>, defined in Period(1..4, run = 2), is referred to in run Period(1..1, run = 3)
stale symbol; class T#3334 in module class rs$line$1$, defined in Period(1..4, run = 2), is referred to in run Period(1..1, run = 3)
1 | class T extends Eql
  |                 ^^^
  |                 Missing type parameter for Eql
```
