### ISSUE TITLE
-YCheck:all error with path dependent types

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7662]
## minimized code

compile with `-Ycheck:all`

```Scala
package tasty

trait ClassSymbolImpl

trait TastyKernel with
  type ClassSymbol
end TastyKernel

trait Tasty with
  private[tasty] val internal: TastyKernel
  type ClassSymbol = internal.ClassSymbol
end Tasty

object TestKernel extends TastyKernel with
  type ClassSymbol = ClassSymbolImpl
end TestKernel

object TestTasty extends Tasty with
  final val internal: TestKernel.type = TestKernel
end TestTasty

class TastyPickler[T <: Tasty](val tasty: T)(rootCls: tasty.ClassSymbol)

class TastyPicklerImpl(rootCls: ClassSymbolImpl) extends TastyPickler(TestTasty)(rootCls)
```

error:
```scala
exception while typing class TastyPicklerImpl(rootCls: tasty.ClassSymbolImpl) extends TastyPickler[
  tasty.TestTasty$
](tasty.TestTasty)(TastyPicklerImpl.this.rootCls) {
  private[this] val rootCls: tasty.ClassSymbolImpl
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 1315
exception while typing package tasty {
  trait ClassSymbolImpl() extends Object {}
  trait TastyKernel() extends Object {
    type ClassSymbol >: Nothing <: Any
  }
  trait Tasty() extends Object {
    private[tasty] val internal: tasty.TastyKernel
    type ClassSymbol = this.internal.ClassSymbol
  }
  final lazy module val TestKernel: tasty.TestKernel$ = new tasty.TestKernel$()
  final module class TestKernel$() extends Object(), tasty.TastyKernel, _root_.
    scala
  .Serializable { this: tasty.TestKernel.type =>
    type ClassSymbol = tasty.ClassSymbolImpl
  }
  final lazy module val TestTasty: tasty.TestTasty$ = new tasty.TestTasty$()
  final module class TestTasty$() extends Object(), tasty.Tasty, _root_.scala.
    Serializable
   { this: tasty.TestTasty.type =>
    final val internal: tasty.TestKernel.type = tasty.TestKernel
  }
  class TastyPickler[T >: Nothing <: tasty.Tasty](tasty: T)(
    rootCls: tasty.ClassSymbol
  ) extends Object() {
    T <: tasty.Tasty
    val tasty: T
    private[this] val rootCls: TastyPickler.this.tasty.ClassSymbol
  }
  class TastyPicklerImpl(rootCls: tasty.ClassSymbolImpl) extends TastyPickler[
    tasty.TestTasty$
  ](tasty.TestTasty)(TastyPicklerImpl.this.rootCls) {
    private[this] val rootCls: tasty.ClassSymbolImpl
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 1316
*** error while checking local/Tasty.scala after phase frontend ***
exception occurred while compiling local/Tasty.scala
java.lang.AssertionError: assertion failed: Types differ
Original type : (tasty: tasty.TestTasty$)
  (rootCls: tasty.ClassSymbol): tasty.TastyPickler[tasty.TestTasty$]
After checking: (tasty: tasty.TestTasty$)
  (rootCls: tasty.internal.ClassSymbol): tasty.TastyPickler[tasty.TestTasty$]
Original tree : new TastyPickler[tasty.TestTasty$]
After checking: new TastyPickler[tasty.TestTasty$]
Why different :
             Subtype trace: while compiling local/Tasty.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Types differ
Original type : (tasty: tasty.TestTasty$)
  (rootCls: tasty.ClassSymbol): tasty.TastyPickler[tasty.TestTasty$]
After checking: (tasty: tasty.TestTasty$)
  (rootCls: tasty.internal.ClassSymbol): tasty.TastyPickler[tasty.TestTasty$]
Original tree : new TastyPickler[tasty.TestTasty$]
After checking: new TastyPickler[tasty.TestTasty$]
Why different :
             Subtype trace:
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:314)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2187)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:286)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2284)
	at dotty.tools.dotc.typer.ReTyper.typedFunPart(ReTyper.scala:72)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:840)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:968)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:82)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2151)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:301)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2187)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:286)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2284)
	at dotty.tools.dotc.typer.ReTyper.typedFunPart(ReTyper.scala:72)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:840)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:968)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:82)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2151)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:301)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2187)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:286)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2284)
	at dotty.tools.dotc.typer.Typer.typedParent$2(Typer.scala:1713)
	at dotty.tools.dotc.typer.Typer.$anonfun$32(Typer.scala:1755)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:63)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:79)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1755)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:415)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2083)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2150)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:301)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2187)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:286)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2226)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2270)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:475)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1885)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2124)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2151)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:123)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:301)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2187)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:286)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2284)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:121)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:94)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:162)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:172)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:180)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:187)
	at dotty.tools.dotc.Run.compileSources(Run.scala:124)
	at dotty.tools.dotc.Run.compile(Run.scala:107)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```

## expectation

no issue with `-Ycheck:all`

To fix this - replace definition of `TastyPicklerImpl` with
```scala
class TastyPicklerImpl(rootCls: ClassSymbolImpl) extends TastyPickler[TestTasty.type](TestTasty)(rootCls)
```

**Comment by SolalPirelli** [comment]
No issue on main.
