### ISSUE TITLE
Sbt phases (-Yforce-sbt-phases) crash when someone declares a _root_.scala package 

### ISSUE THREAD

**Issue by hobwekiva** [lampepfl/dotty#7737]
## minimized code

```Scala
package _root_
package scala
```

What's interesting is that if I declare any other package name (non-existent), I get cryptic error messages:
```scala
package _root_
package a

-- [E006] Unbound Identifier Error: testing/Test.scala:2:8 ---------------------
2 |package a
  |        ^
  |        Not found: a

longer explanation available when compiling with `-explain`
```

```scala
package _root_.a

-- [E008] Member Not Found Error: testing/Test.scala:1:15 ----------------------
1 |package _root_.a
  |        ^^^^^^^^
  |        value a is not a member of <root> - did you mean _root_.com?
1 error found
```

<details>
<summary>Stack trace</summary>

```scala
asserted failed while traversing java
asserted failed while traversing package java {}
asserted failed while traversing package _root_ {package java {}}
exception occurred while compiling testing/Test.scala
java.lang.AssertionError: NoDenotation.owner while compiling testing/Test.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2247)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.nonLocalEnclosingClass$1(ExtractDependencies.scala:263)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.resolveDependencySource(ExtractDependencies.scala:271)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.dotty$tools$dotc$sbt$ExtractDependenciesCollector$$addMemberRefDependency(ExtractDependencies.scala:304)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:357)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1480)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1480)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1456)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1481)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:377)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1480)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1480)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply$$anonfun$1(Trees.scala:1366)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1366)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1456)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1481)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:377)
	at dotty.tools.dotc.sbt.ExtractDependencies.run(ExtractDependencies.scala:68)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:161)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:171)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:179)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:186)
	at dotty.tools.dotc.Run.compileSources(Run.scala:123)
	at dotty.tools.dotc.Run.compile(Run.scala:106)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by odersky** [comment]
I now get
```
-- Warning: i7281.scala:2:8 ----------------------------------------------------
2 |package _root_
  |^
  |No class, trait or object is defined in the compilation unit.
  |The incremental compiler cannot record the dependency information in such case.
  |Some errors like unused import referring to a non-existent class might not be reported.
3 |package scala
1 warning found`
```
