### ISSUE TITLE
Weird type-checking crash (parser stability?)

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#7750]
## minimized code

```Scala
package object A extends runtime.A {
    implicit def a( : ) = 1()
}
```

<details>
<summary>Stack trace</summary>

```scala
-- [E040] Syntax Error: testing/Test.scala:2:20 --------------------------------
2 |    implicit def a( : ) = 1()
  |                    ^
  |                    an identifier expected, but ':' found

longer explanation available when compiling with `-explain`
-- Error: testing/Test.scala:2:17 ----------------------------------------------
2 |    implicit def a( : ) = 1()
  |                 ^
  |           result type of implicit definition needs to be given explicitly
-- [E124] Cyclic Error: testing/Test.scala:2:26 --------------------------------
2 |    implicit def a( : ) = 1()
  |                          ^
  |method a needs result type because its right-hand side attempts implicit search

longer explanation available when compiling with `-explain`
exception occurred while typechecking testing/Test.scala
exception occurred while compiling testing/Test.scala
java.lang.AssertionError: assertion failed while compiling testing/Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.typer.Checking.checkImplicitConversionUseOK(Checking.scala:721)
	at dotty.tools.dotc.typer.Typer.checkImplicitConversionUseOK(Typer.scala:82)
	at dotty.tools.dotc.typer.Typer.adaptToSubType$1(Typer.scala:3010)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$6(Typer.scala:2837)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2889)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3095)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2501)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2193)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2205)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2290)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:454)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:478)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2079)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2156)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2193)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2205)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:1260)
	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1253)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1260)
	at dotty.tools.dotc.typer.Namer$ClassCompleter.parentType$1(Namer.scala:1148)
	at dotty.tools.dotc.typer.Namer$ClassCompleter.checkedParentType$5(Namer.scala:1176)
	at dotty.tools.dotc.typer.Namer$ClassCompleter.$anonfun$2(Namer.scala:1213)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.typer.Namer$ClassCompleter.completeInCreationContext(Namer.scala:1213)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:843)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:258)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:185)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:187)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:398)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeNPMembersNamed(SymDenotations.scala:1819)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.recur$1(SymDenotations.scala:2143)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.computeNPMembersNamed(SymDenotations.scala:2203)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.nonPrivateMembersNamed(SymDenotations.scala:1805)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1792)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1842)
	at dotty.tools.dotc.typer.NamerContextOps.denotNamed(Namer.scala:62)
	at dotty.tools.dotc.core.Contexts$Context.denotNamed(Contexts.scala:75)
	at dotty.tools.dotc.typer.Namer.moduleValSig(Namer.scala:1288)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:810)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:935)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:843)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:258)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:185)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:187)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:398)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2051)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2076)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2156)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2193)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2205)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2232)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2276)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1890)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2130)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2157)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2193)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2205)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2254)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2276)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1890)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2130)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2157)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2193)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2205)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2290)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree9$2(FrontEnd.scala:78)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:83)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:114)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:114)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:161)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:171)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:179)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:186)
	at dotty.tools.dotc.Run.compileSources(Run.scala:123)
	at dotty.tools.dotc.Run.compile(Run.scala:106)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by alexknvl** [comment]
```scala
def main(a: Array[String]): Unit = {
    val a = (x: Int, y: String) => x + + y
    implicit def f[X](x: (X,  String) => String) = (z: X) => (z, null)
    (a(1))
}
```
Same crash.
