### ISSUE TITLE
Pattern match on package object crashes

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#7752]
## minimized code

```Scala
package object A

val x = (null: Any) match {
    case A => ???
}
```

<details>
<summary>Stack trace</summary>

```scala
exception occurred while compiling testing/Test.scala
java.lang.AssertionError: assertion failed: no member A . ==, members = Scope{
  final lazy module package object package: A.package$
  final module package object package$ extends Object with Serializable {this:
    A.package.type
   =>} at (A : A.type)
  class package: <notype>
} while compiling testing/Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: no member A . ==, members = Scope{
  final lazy module package object package: A.package$
  final module package object package$ extends Object with Serializable {this:
    A.package.type
   =>} at (A : A.type)
  class package: <notype>
}
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.ast.tpd$.applyOverloaded(tpd.scala:1156)
	at dotty.tools.dotc.ast.tpd$TreeOps$.equal$extension(tpd.scala:917)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitCondition(PatternMatcher.scala:677)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitCondWithPos$1(PatternMatcher.scala:856)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.$anonfun$11(PatternMatcher.scala:859)
	at scala.collection.immutable.List.foldRight(List.scala:324)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitWithMashedConditions$1(PatternMatcher.scala:860)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:865)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.default$1(PatternMatcher.scala:873)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.maybeEmitSwitch$1(PatternMatcher.scala:879)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:883)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:867)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.translateMatch(PatternMatcher.scala:978)
	at dotty.tools.dotc.transform.PatternMatcher.transformMatch(PatternMatcher.scala:35)
	at dotty.tools.dotc.transform.MegaPhase.goMatch(MegaPhase.scala:746)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:345)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.mapValDef$1(MegaPhase.scala:234)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:238)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
	at scala.collection.immutable.List.mapConserve(List.scala:444)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
	at scala.collection.immutable.List.mapConserve(List.scala:444)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
	at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:356)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:415)
	at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:427)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:161)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:171)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:179)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:186)
	at dotty.tools.dotc.Run.compileSources(Run.scala:123)
	at dotty.tools.dotc.Run.compile(Run.scala:106)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by sjrd** [comment]
This shouldn't even pass typer, or at the latest be intercepted at refchecks. A package term should neverb be allowed anywhere except on the lhs of a Select node. I'm not sure I'm the best person to address this issue.

**Comment by odersky** [comment]
It works with normal objects , just not with package objects.

Since package objects are being deprecated anyway I don't think this is worth fixing.
