### ISSUE TITLE
Public method overriden by private one

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#776]
```java
public static abstract class Types.AndType extends Types..CachedGroundType
implements Types..TermType, Types..ValueTypeOrProto, Types..ValueType, Types..AndOrType, Equals, Product, Product2 {
...
    @Override
    public Types.Type tp1() {
        return this.tp1$$local;
    }
...
}

public static final class Types.CachedAndType
extends Types..AndType {
....
    @Override
    private Types.Type tp1() {
        return super.tp1();
    }
....
}
```

manifests itself as 
```
findMember exception for scala.collection.mutable member StringBuilder
Exception in thread "main" java.lang.IllegalAccessError: dotty.tools.dotc.core.Types$CachedAndType.tp1()Ldotty/tools/dotc/core/Types$Type;
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:2926)
	at dotty.tools.dotc.typer.Checking$CheckNonCyclicMap.apply(Checking.scala:153)
	at dotty.tools.dotc.typer.Checking$CheckNonCyclicMap.checkInfo(Checking.scala:100)
	at dotty.tools.dotc.typer.Checking$.checkNonCyclic(Checking.scala:164)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.parseToCompletion$1(Scala2Unpickler.scala:549)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.$anonfun$complete$9(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler$$Lambda$342/525968792.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler.atReadPos(Scala2Unpickler.scala:326)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.complete(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:170)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:152)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:267)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:100)
	at dotty.tools.dotc.core.TypeOps$$anon$104.complete(TypeOps.scala:379)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:170)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:152)
	at dotty.tools.dotc.core.TypeOps.forwardRef(TypeOps.scala:423)
	at dotty.tools.dotc.core.Contexts$Context.forwardRef(Contexts.scala:53)
	at dotty.tools.dotc.core.TypeOps.$anonfun$$anonfun$38(TypeOps.scala:463)
	at dotty.tools.dotc.core.TypeOps$$Lambda$170/1318180415.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.core.Scopes$MutableScope.foreach(Scopes.scala:367)
	at dotty.tools.dotc.core.TypeOps.$anonfun$forwardRefs$1$1(TypeOps.scala:462)
	at dotty.tools.dotc.core.TypeOps$$Lambda$169/436532993.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.core.TypeOps.forwardRefs$1(TypeOps.scala:461)
	at dotty.tools.dotc.core.TypeOps.$anonfun$normalizeToClassRefs$2(TypeOps.scala:495)
	at dotty.tools.dotc.core.TypeOps$$Lambda$160/1769193365.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure2.apply(JProcedure2.java:18)
	at scala.compat.java8.JProcedure2.apply(JProcedure2.java:10)
	at dotty.tools.dotc.util.SimpleMap$Map2.foreachBinding(SimpleMap.scala:78)
	at dotty.tools.dotc.core.TypeOps.normalizeToClassRefs(TypeOps.scala:495)
	at dotty.tools.dotc.core.Contexts$Context.normalizeToClassRefs(Contexts.scala:53)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$.setClassInfo(Scala2Unpickler.scala:110)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.parseToCompletion$1(Scala2Unpickler.scala:543)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.$anonfun$complete$9(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler$$Lambda$342/525968792.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler.atReadPos(Scala2Unpickler.scala:326)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.complete(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:170)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:152)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1446)
	at dotty.tools.dotc.core.Types$Type.dealias(Types.scala:738)
	at dotty.tools.dotc.core.TypeOps.normalizeToRef$1(TypeOps.scala:470)
	at dotty.tools.dotc.core.TypeOps.$anonfun$204(TypeOps.scala:486)
	at dotty.tools.dotc.core.TypeOps$$Lambda$158/306980751.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.TypeOps.normalizeToClassRefs(TypeOps.scala:486)
	at dotty.tools.dotc.core.Contexts$Context.normalizeToClassRefs(Contexts.scala:53)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$.setClassInfo(Scala2Unpickler.scala:110)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.parseToCompletion$1(Scala2Unpickler.scala:543)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.$anonfun$complete$9(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler$$Lambda$342/525968792.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler.atReadPos(Scala2Unpickler.scala:326)
	at dotty.tools.dotc.core.unpickleScala2.Scala2Unpickler$LocalUnpickler.complete(Scala2Unpickler.scala:569)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:170)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:152)
	at dotty.tools.dotc.transform.TreeTransforms$AnnotationTransformer.transform(TreeTransform.scala:184)
	at dotty.tools.dotc.transform.FirstTransform.transform(FirstTransform.scala:30)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:621)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:657)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:639)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:657)
	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:388)
	at dotty.tools.dotc.core.Scopes$Scope.denotsNamed(Scopes.scala:119)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1464)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1517)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:416)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:493)
	at dotty.tools.dotc.core.Types$Type.$anonfun$member$1(Types.scala:396)
	at dotty.tools.dotc.core.Types$Type$$Lambda$96/1418334255.apply(Unknown Source)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:31)
	at dotty.tools.dotc.core.Types$Type.member(Types.scala:395)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$2(Denotations.scala:972)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:984)
	at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:485)
	at dotty.tools.dotc.core.Symbols.requiredClass(Symbols.scala:350)
	at dotty.tools.dotc.core.Contexts$Context.requiredClass(Contexts.scala:53)
	at dotty.tools.backend.jvm.DottyBackendInterface.requiredClass(DottyBackendInterface.scala:368)
	at dotty.tools.backend.jvm.DottyBackendInterface.requiredClass(DottyBackendInterface.scala:35)
	at scala.tools.nsc.backend.jvm.BackendInterfaceDefinitions.<init>(BackendInterface.scala:720)
	at scala.tools.nsc.backend.jvm.BackendInterface.<init>(BackendInterface.scala:14)
	at dotty.tools.backend.jvm.DottyBackendInterface.<init>(DottyBackendInterface.scala:35)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:41)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$2(Phases.scala:271)
	at dotty.tools.dotc.core.Phases$Phase$$Lambda$414/1810899357.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:273)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:34)
	at dotty.tools.dotc.Run.$anonfun$$anonfun$compileUnits$1$1(Run.scala:59)
	at dotty.tools.dotc.Run$$Lambda$194/957465255.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:57)
	at dotty.tools.dotc.Run$$Lambda$185/288994035.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:58)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:65)
	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	at dotty.tools.dotc.Run.compile(Run.scala:33)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
```

I'm working on this, but I just wanted to share the last stack trace :-). This is Dotty compiled by Dotty.

**Comment by DarkDimius** [comment]
here is a stacktrace of where this tree is created

```
	  at dotty.tools.dotc.ast.Trees$Tree.<init>(Trees.scala:107)
	  at dotty.tools.dotc.ast.Trees$DenotingTree.<init>(Trees.scala:263)
	  at dotty.tools.dotc.ast.Trees$NameTree.<init>(Trees.scala:289)
	  at dotty.tools.dotc.ast.Trees$MemberDef.<init>(Trees.scala:314)
	  at dotty.tools.dotc.ast.Trees$DefDef.<init>(Trees.scala:638)
	  at dotty.tools.dotc.ast.untpd$.DefDef(untpd.scala:146)
	  at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:210)
	  at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:185)
	  at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:182)
	  at dotty.tools.dotc.transform.ParamForwarding.forwarder$1(ParamForwarding.scala:56)
	  at dotty.tools.dotc.transform.ParamForwarding.dotty$tools$dotc$transform$ParamForwarding$$forwardParamAccessor$1(ParamForwarding.scala:58)
	  at dotty.tools.dotc.transform.ParamForwarding$$anonfun$fwd$1$1.apply(ParamForwarding.scala:66)
	  at dotty.tools.dotc.transform.ParamForwarding$$anonfun$fwd$1$1.apply(ParamForwarding.scala:66)
	  at scala.collection.immutable.List.map(List.scala:273)
	  at dotty.tools.dotc.transform.ParamForwarding.fwd$1(ParamForwarding.scala:66)
	  at dotty.tools.dotc.transform.ParamForwarding.forwardParamAccessors(ParamForwarding.scala:69)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:137)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1165)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:146)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.dotty$tools$dotc$transform$MacroTransform$Transformer$$transformStat$1(MacroTransform.scala:43)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer$$anonfun$transformStats$1.apply(MacroTransform.scala:47)
	  at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
	  at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:47)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$super$transform(PostTyper.scala:139)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$2.apply(PostTyper.scala:139)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer$$anonfun$transform$2.apply(PostTyper.scala:139)
	  at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:413)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:138)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1165)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:146)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at scala.collection.immutable.List.loop$1(List.scala:173)
	  at scala.collection.immutable.List.mapConserve(List.scala:189)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1180)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1171)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:160)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at scala.collection.immutable.List.loop$1(List.scala:173)
	  at scala.collection.immutable.List.mapConserve(List.scala:189)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1180)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1171)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:160)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1182)
	  at scala.collection.immutable.List.loop$1(List.scala:173)
	  at scala.collection.immutable.List.mapConserve(List.scala:189)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1182)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1180)
	  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1171)
	  at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	  at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:160)
	  at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:22)
	  at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:271)
	  at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:269)
	  at scala.collection.immutable.List.map(List.scala:277)
	  at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:269)
	  at dotty.tools.dotc.transform.MacroTransform.runOn(MacroTransform.scala:16)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
	  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	  at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	  at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
	  at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
	  at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	  at dotty.tools.dotc.Run.compile(Run.scala:33)
	  at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	  at dotty.tools.dotc.Driver.process(Driver.scala:44)
	  at test.CompilerTest.compileArgs(CompilerTest.scala:184)
	  at test.CompilerTest.compileDir(CompilerTest.scala:121)
	  at dotc.tests.dotty(tests.scala:159)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:497)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.junit.runners.Suite.runChild(Suite.java:127)
	  at org.junit.runners.Suite.runChild(Suite.java:26)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
```

**Comment by DarkDimius** [comment]
I am making a minimal fix, but I have general questions of why this phase exists and what it does: #783
