### ISSUE TITLE
@unchecked ascription leads to MatchError in runtime

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#7995]
## minimized code

```Scala
object Main {
  def main(args: Array[String]): Unit = {
    val x1 = if (2 + 2 == 5) "" else null
    val x2 : @unchecked = if (2 + 2 == 5) "" else null
    
    def f: String = null
    
    val y1 = f
    val y2 : @unchecked = f
  }  
}
```

<details>
<summary>Runtime output</summary>

```scala
scala.MatchError: null
	at Main$.main(main.scala:9)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

## expectation
no runtime error occurs, it's not quite clear why `@unchecked` should make the code to fail for `val y2 : @unchecked = f`

**Comment by odersky** [comment]
@unchecked always translates into a type-check that the right-hand side matches the type of the left hand side. The right hand side is `null` which does not match the declared type `String`. I.e. `null.isInstanceof[String]` is `false`.

**Comment by unkarjedy** [comment]
@odersky 
I am trying to understand the motivation to always do that check. E.g. in the example above.
I would accept that runtime error if `f` was declared in Java and we had `-Yexplicit-nulls` flag.
Until that is the case `null` seems to be a perfectly valid value for `String` type, isn't it?
Also not quite clear how `val x2 : @unchecked = ...` is much different from `val y2 : @unchecked = ...`?  (`x2` doesn't fail)
