### ISSUE TITLE
AbstractMethodError with outer links

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#809]
Dotty compiled by dotty has compiled hello world, so I am looking now into more complicated phases: 
```
Exception in thread "main" java.lang.AbstractMethodError: dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.dotty$tools$dotc$transform$PatternMatcher$Translator$MatchTranslator$$$outer()Ldotty/tools/dotc/transform/PatternMatcher$Translator;
```

**Comment by DarkDimius** [comment]
How to reproduce: compile dotty by dotty(is part of test suite).
Than compile such file:

```scala
object A {
  def main(args: Array[String]): Unit = {
       args match { case Array() => println("empty"); case _ => println(args)}
  }
}
```

```
Exception in thread "main" java.lang.AbstractMethodError: dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.dotty$tools$dotc$transform$PatternMatcher$Translator$MatchTranslator$$$outer()Ldotty/tools/dotc/transform/PatternMatcher$Translator;
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator.translateMatch(PatternMatcher.scala:1166)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translateMatch(PatternMatcher.scala:75)
	at dotty.tools.dotc.transform.PatternMatcher.transformMatch(PatternMatcher.scala:51)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goMatch(TreeTransform.scala:724)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1114)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1087)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1004)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1238)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$662(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$690/596470015.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1183)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1011)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1212)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStat$2(TreeTransform.scala:1238)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$662(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$690/596470015.apply(Unknown Source)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$4(Decorators.scala:51)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.liftedTree7$1(TreeTransform.scala:1213)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$anonfun$transform$10(TreeTransform.scala:1205)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$Lambda$689/746074699.apply(Unknown Source)
	at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:563)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:480)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$2(Phases.scala:271)
	at dotty.tools.dotc.core.Phases$Phase$$Lambda$604/1293677337.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:273)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:273)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.runOn(TreeTransform.scala:474)
	at dotty.tools.dotc.Run.$anonfun$$anonfun$compileUnits$1$1(Run.scala:59)
	at dotty.tools.dotc.Run$$Lambda$194/388357135.applyVoid(Unknown Source)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:57)
	at dotty.tools.dotc.Run$$Lambda$185/501187768.apply$mcV$sp(Unknown Source)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:58)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:65)
	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	at dotty.tools.dotc.Run.compile(Run.scala:33)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
```
