### ISSUE TITLE
AssertionError on given declaration in refinement

### ISSUE THREAD

**Issue by panacekcz** [lampepfl/dotty#8150]
## minimized code

```Scala
trait A
trait B
type T = {given(given a: A) as B}
```

## Crash output (click arrow to expand)
<details>

```
exception occurred while typechecking given-refinement.scala
exception occurred while compiling given-refinement.scala
java.lang.AssertionError: assertion failed: given class  with (private[this] given val a: A) extends B {} > class given_B with (a: A) extends Object(), B {
  private[this] given val a: A
}, final given def given_B with (a: A): <refinement>.this.given_B = 
  new <refinement>.this.given_B().with(a) while compiling given-refinement.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: given class  with (private[this] given val a: A) extends B {} > class given_B with (a: A) extends Object(), B {
  private[this] given val a: A
}, final given def given_B with (a: A): <refinement>.this.given_B = 
  new <refinement>.this.given_B().with(a)
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.typer.Typer.typedRefinedTypeTree(Typer.scala:1399)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2175)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2209)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:1264)
	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1257)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1264)
	at dotty.tools.dotc.typer.Namer.typeDefSig(Namer.scala:1538)
	at dotty.tools.dotc.typer.Namer$TypeDefCompleter.typeSig(Namer.scala:970)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:935)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:843)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:258)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:185)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:187)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:398)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2103)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2128)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2208)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2281)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2325)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1812)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2141)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2208)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2281)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2325)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1938)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2182)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2209)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$2(FrontEnd.scala:78)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:83)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:114)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:114)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
	at dotty.tools.dotc.Run.compileSources(Run.scala:129)
	at dotty.tools.dotc.Run.compile(Run.scala:112)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

**Comment by nicolasstucki** [comment]
@odersky I noticed that a fix was pushed to `staging/master` but there is not PR to `dotty/master`. What is the status of this fix?
