### ISSUE TITLE
ClassSymbol not behaving consistently in ReadTasty

### ISSUE THREAD

**Issue by gzoller** [lampepfl/dotty#8233]
## Issue
Working with ReadTasty.compilationUnit(cls:Symbol).  Inside this function I want to look at flags on the symbol.  If I attempt to read a Java file, say java.util.UUID, I can successfully look at cls.flags and see if JavaDefined is set.

However if I look at a non-tasty Scala class like scala.collection.immutable.RedBlackTree I get an java.lang.UnsupportedOperationException when I access cls.flags.  In both cases cls' type is dotty.tools.dotc.core.Symbols$ClassSymbol.

These should behave the same.  **I notice that cls.info is also different.**  Good info on Java classes.  Same exception on non-tasty Scala classes.

***PLEASE***:  Whoever attempts to fix this, please allow cls.flags to be set and readable for Java classes.  I'm trying to detect and report back when the user erroneously tries to read a Java class or non-tasty Scala class.  Right now this information disappears into warnings, which isn't useful IMO, and are basically ignored up the chain like in Reflection.

```Scala
      // ReadTasty.scala
      def compilationUnit(cls: Symbol): Option[CompilationUnit] = cls match {
        case cls: ClassSymbol =>
          (cls.rootTreeOrProvider: @unchecked) match {
            case unpickler: tasty.DottyUnpickler =>
              if (cls.rootTree.isEmpty) None
              else {
                val unit = CompilationUnit(cls, cls.rootTree, forceTrees = true)
                unit.pickled += (cls -> unpickler.unpickler.bytes)
                Some(unit)
              }
            case tree: Tree[?] =>
              println("Flags: "+cls.flags)
              alreadyLoaded()
            case _ =>
              cannotUnpickle(s"its class file does not have a TASTY attribute")
          }
        case _ => None
      }
```

## Stack trace

```
java.lang.UnsupportedOperationException: complete while compiling scala.collection.immutable.RedBlackTree
[error] (run-main-c) java.lang.UnsupportedOperationException: complete
[error] java.lang.UnsupportedOperationException: complete
[error] 	at dotty.tools.package$.unsupported(package.scala:25)
[error] 	at dotty.tools.dotc.core.SymDenotations$NoCompleter.complete(SymDenotations.scala:2320)
[error] 	at dotty.tools.dotc.core.NoLoader.complete(SymbolLoaders.scala:426)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:259)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:185)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:187)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:399)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:158)
[error] 	at dotty.tools.dotc.fromtasty.ReadTasty.compilationUnit$1(ReadTasty.scala:58)
[error] 	at dotty.tools.dotc.fromtasty.ReadTasty.readTASTY(ReadTasty.scala:87)
[error] 	at dotty.tools.dotc.fromtasty.ReadTasty.runOn$$anonfun$1(ReadTasty.scala:24)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:265)
[error] 	at dotty.tools.dotc.fromtasty.ReadTasty.runOn(ReadTasty.scala:24)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:134)
[error] 	at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:10)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:189)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:158)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:170)
[error] 	at scala.tasty.inspector.TastyInspector.inspect(TastyInspector.scala:64)
[error] 	at co.blocke.dotty_reflection.impl.TastyClassInspector.inspect(TastyClassInspector.scala:9)
[error] 	at co.blocke.dotty_reflection.Reflector$.reflectOn$$anonfun$1(Reflector.scala:19)
[error] 	at scala.collection.mutable.HashMap.getOrElse(HashMap.scala:416)
[error] 	at co.blocke.dotty_reflection.Reflector$.reflectOn(Reflector.scala:21)
[error] 	at co.blocke.dotty_reflection.RunMe$package$.runme(RunMe.scala:59)
[error] 	at co.blocke.dotty_reflection.runme.main(RunMe.scala:15)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
```

**Comment by nicolasstucki** [comment]
Now Scala2 and Java defined symbols are handled before we reach this code.
