### ISSUE TITLE
Constraints on value class parameters are not checked early enough

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#826]
While value classes with one value parameter all compile, the following illegal examples all produce unexpected output:
- `class Foo(y: Int) extends AnyVal` produces `error: value y in class Foo does not take parameters`
- `class Foo(y: String, z: String) extends AnyVal` crashes the compiler
- `class Foo(val y: String, val z: String) extends AnyVal` crashes the compiler
- `case class Foo(y: String, z: String) extends AnyVal` crashes the compiler

Typical output (from the last example) looks like this:

```
error while transforming (y: String, z: String) extends AnyVal() { 
  val y: String
  val z: String
}
error while transforming final class Foo(y: String, z: String) extends AnyVal() { 
  val y: String
  val z: String
}
error while transforming package <empty> {
  final class Foo(y: String, z: String) extends AnyVal() { 
    val y: String
    val z: String
  }
}
exception occurred while compiling test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:151)
        at dotty.tools.dotc.transform.SyntheticMethods.dotty$tools$dotc$transform$SyntheticMethods$$valueHashCodeBody$1(SyntheticMethods.scala:137)
        at dotty.tools.dotc.transform.SyntheticMethods$$anonfun$syntheticRHS$1$1.apply(SyntheticMethods.scala:83)
        at dotty.tools.dotc.transform.SyntheticMethods$$anonfun$syntheticRHS$1$1.apply(SyntheticMethods.scala:83)
        at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:215)
        at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:185)
        at dotty.tools.dotc.transform.SyntheticMethods.syntheticDef$1(SyntheticMethods.scala:92)
        at dotty.tools.dotc.transform.SyntheticMethods.dotty$tools$dotc$transform$SyntheticMethods$$syntheticDefIfMissing$1(SyntheticMethods.scala:69)
        at dotty.tools.dotc.transform.SyntheticMethods$$anonfun$syntheticMethods$1.apply(SyntheticMethods.scala:189)
        at dotty.tools.dotc.transform.SyntheticMethods$$anonfun$syntheticMethods$1.apply(SyntheticMethods.scala:189)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at dotty.tools.dotc.transform.SyntheticMethods.syntheticMethods(SyntheticMethods.scala:189)
        at dotty.tools.dotc.transform.SyntheticMethods.addSyntheticMethods(SyntheticMethods.scala:194)
        at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:171)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1163)
        at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
        at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:181)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1180)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap$$anonfun$transform$2.apply(Trees.scala:1180)
        at scala.collection.immutable.List.loop$1(List.scala:173)
        at scala.collection.immutable.List.mapConserve(List.scala:189)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1180)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1178)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1169)
        at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
        at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:195)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:22)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:271)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:269)
        at scala.collection.immutable.List.map(List.scala:273)
        at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:269)
        at dotty.tools.dotc.transform.MacroTransform.runOn(MacroTransform.scala:16)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
        at dotty.tools.dotc.Run.compileSources(Run.scala:49)
        at dotty.tools.dotc.Run.compile(Run.scala:33)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
        at dotty.tools.dotc.Driver.process(Driver.scala:44)
        at dotty.tools.dotc.Driver.main(Driver.scala:48)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by smarter** [comment]
Yes, we haven't spent much time on error checking for value classes because it's not yet clear what will or will not be allowed for value classes, all of your examples might compile and do something reasonable some day :).

**Comment by propensive** [comment]
Ok, that would be even better!

**Comment by odersky** [comment]
In the meantime, assigning to @smarter so that it does not get lost.

**Comment by smarter** [comment]
All fixed a while ago!
