### ISSUE TITLE
explicit "PolyFunction" type annotation cause ClassCastException

### ISSUE THREAD

**Issue by xuwei-k** [lampepfl/dotty#8299]
## minimized code

dotty version: `0.23.0-bin-20200211-5b006fb-NIGHTLY`

```Scala
package example

object Main {
  def main(a: Array[String]): Unit = {
    val p: PolyFunction = [A] => (xs: List[A]) => xs.headOption
  }
}
```

## `sbt run` log

```scala
[error] (run-main-5) java.lang.ClassCastException: example.Main$$anon$1 cannot be cast to scala.PolyFunction
[error] java.lang.ClassCastException: example.Main$$anon$1 cannot be cast to scala.PolyFunction
[error] 	at example.Main$.main(A.scala:5)
[error] 	at example.Main.main(A.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
```

## expectation

compile error or no Exception.

**Comment by exoego** [comment]
This seems resolved,
It compiles without error on `3.0.0` and `3.0.1`.

**Comment by xuwei-k** [comment]
```
$ scala --version
Scala code runner version 3.0.1 -- Copyright 2002-2021, LAMP/EPFL
$ scala
scala> val p: PolyFunction = [A] => (xs: List[A]) => xs.headOption
java.lang.ClassCastException: repl$.rs$line$1$$anon$1 cannot be cast to scala.PolyFunction
  at repl$.rs$line$1$.<clinit>(rs$line$1:1)
  at repl$.rs$line$1.p(rs$line$1)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:115)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.Rendering.valueOf(Rendering.scala:115)
  at dotty.tools.repl.Rendering.renderVal(Rendering.scala:152)
  at dotty.tools.repl.ReplDriver.$anonfun$13(ReplDriver.scala:323)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.collection.immutable.List.flatMap(List.scala:79)
  at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:323)
  at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:346)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:349)
  at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:268)
  at scala.util.Either.fold(Either.scala:189)
  at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:285)
  at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:212)
  at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:146)
  at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:149)
  at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:168)
  at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:149)
  at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:115)
  at dotty.tools.repl.Main$.main(Main.scala:6)
  at dotty.tools.repl.Main.main(Main.scala)
```

**Comment by exoego** [comment]
Ah, sorry. 
It compiles, but throws on `run`.

**Comment by xuwei-k** [comment]
https://github.com/lampepfl/dotty/pull/18457#issuecomment-1868201071

please re-open this issue. or should I create new issue? 👀

**Comment by som-snytt** [comment]
@xuwei-k 
```
Welcome to Scala 3.4.0-RC1-bin-SNAPSHOT-git-beaf7b4 (21, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val p: PolyFunction = [A] => (xs: List[A]) => xs.headOption
-- Error: --------------------------------------------------------------------------------------------------------------
1 |val p: PolyFunction = [A] => (xs: List[A]) => xs.headOption
  |       ^^^^^^^^^^^^
  |       PolyFunction subtypes must refine the apply method
1 error found
```
