### ISSUE TITLE
ClassFormatError: Illegal field modifiers 0x1A on @SerialVersionUID trait

### ISSUE THREAD

**Issue by ohze** [lampepfl/dotty#8427]
## minimized code

```Scala
@SerialVersionUID(1L)
trait T
object Test {
  var t: T = _
  def main(args: Array[String]) = println("hi")
}
```

## Compilation output

```scala
$ sbt run
[info] running Test 
[error] (run-main-c) java.lang.ClassFormatError: Illegal field modifiers in class T: 0x1A
[error] java.lang.ClassFormatError: Illegal field modifiers in class T: 0x1A
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
```

**Comment by smarter** [comment]
```scala
@SerialVersionUID(1L)
trait T
```
This is supposed to generate a `static final long serialVersionUID = 1L` field, but you can't have a field in an interface and traits compile to interfaces, so this should be a compile error. Under Scala 2 it looks like it doesn't generate anything and under dotty it generates invalid bytecode.
