### ISSUE TITLE
Typer crash with unknown import and implicit parameter of unknown type

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#866]
The following is sufficient to crash the typer:

```
import nonexistent._
object Foo {
  def bar(implicit x: NonExistent) = ???
  val baz = bar
}
```

An error is correctly emitted for the missing import, but not for the missing implicit type.

**Comment by smarter** [comment]
When reporting a crash, please include the full output you get including the stack trace, it gives a rough idea of where the problem might be, thanks!

**Comment by propensive** [comment]
I tried uploading the stack trace, though I don't have permission (`Attaching documents requires write permission to this repository. Try again with a PNG, GIF, or JPG.`). I guess that means I need to copy/paste it?

**Comment by propensive** [comment]
(Unfortunately, and embarrasingly, since I accidentally deleted several configuration files last week, my terminal has been so broken that I can't copy/paste output into my browser... Hopefully I'll be back up and running again in a few days.) :(

**Comment by smarter** [comment]
Yes, we usually copy-paste them. Here's the output:
```scala
% ./bin/dotc try/i0866.scala
try/i0866.scala:1: error: not found: nonexistent
import nonexistent._
       ^
exception occurred while typechecking try/i0866.scala
exception occurred while compiling try/i0866.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:151)
        at dotty.tools.dotc.ast.Trees$Tree.withType(Trees.scala:149)
        at dotty.tools.dotc.ast.tpd$.TypeTree(tpd.scala:140)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:343)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedIdent$1.apply(Typer.scala:275)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedIdent$1.apply(Typer.scala:78)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Typer.typedIdent(Typer.scala:78)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1104)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1163)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1175)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1173)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1173)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$19.shadowing$lzycompute$1(Implicits.scala:489)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$19.dotty$tools$dotc$typer$Implicits$ImplicitSearch$$anonfun$$anonfun$$shadowing$1(Implicits.scala:488)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$19.apply(Implicits.scala:501)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1$$anonfun$apply$19.apply(Implicits.scala:480)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1.apply(Implicits.scala:480)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch$$anonfun$typedImplicit$1$1.apply(Implicits.scala:480)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch.typedImplicit$1(Implicits.scala:480)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rankImplicits$1(Implicits.scala:519)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicits(Implicits.scala:563)
        at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:568)
        at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1$$anonfun$apply$17.apply(Implicits.scala:430)
        at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1$$anonfun$apply$17.apply(Implicits.scala:425)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1.apply(Implicits.scala:425)
        at dotty.tools.dotc.typer.Implicits$$anonfun$inferImplicit$1.apply(Implicits.scala:420)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Implicits$class.inferImplicit(Implicits.scala:420)
        at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:57)
        at dotty.tools.dotc.typer.Typer$$anonfun$29.apply(Typer.scala:1411)
        at dotty.tools.dotc.typer.Typer$$anonfun$29.apply(Typer.scala:1409)
        at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:46)
        at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:44)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.runtime.Tuple2Zipped$.map$extension(Tuple2Zipped.scala:44)
        at dotty.tools.dotc.typer.Typer.dotty$tools$dotc$typer$Typer$$addImplicitArgs$1(Typer.scala:1409)
        at dotty.tools.dotc.typer.Typer$$anonfun$adaptNoArgs$1$2.apply(Typer.scala:1425)
        at dotty.tools.dotc.typer.Typer$$anonfun$adaptNoArgs$1$2.apply(Typer.scala:1425)
        at dotty.tools.dotc.core.MutableTyperState.tryWithFallback(TyperState.scala:176)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:1425)
        at dotty.tools.dotc.typer.Typer.adaptInterpolated(Typer.scala:1528)
        at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1$$anonfun$apply$21.apply(Typer.scala:1271)
        at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1$$anonfun$apply$21.apply(Typer.scala:1267)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1.apply(Typer.scala:1267)
        at dotty.tools.dotc.typer.Typer$$anonfun$adapt$1.apply(Typer.scala:1267)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:1266)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1175)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1173)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1173)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1212)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:927)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:921)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:921)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1110)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1163)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1175)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1173)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1173)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1197)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1208)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:968)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:951)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:951)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1116)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1163)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1175)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1173)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1173)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1197)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1208)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1056)
        at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1047)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1047)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1153)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1165)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1175)
        at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1173)
        at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1173)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1212)
        at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:42)
        at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:19)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:40)
        at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
        at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:53)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
        at dotty.tools.dotc.Run.compileSources(Run.scala:49)
        at dotty.tools.dotc.Run.compile(Run.scala:33)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
        at dotty.tools.dotc.Driver.process(Driver.scala:44)
        at dotty.tools.dotc.Driver.main(Driver.scala:48)
        at dotty.tools.dotc.Main.main(Main.scala)
```

**Comment by propensive** [comment]
Thanks, Guillaume!
