### ISSUE TITLE
can't try catch using a PartialFunction[Throwable, _]

### ISSUE THREAD

**Issue by ohze** [lampepfl/dotty#8662]
## Minimized code

```Scala
object Main {
  class EThrow extends Exception
  class ECatch extends Exception

  def ok(): Unit =
    try throw new EThrow
    catch { case _: ECatch => }

  def notOk(): Unit = {
    val pf: PartialFunction[Throwable, Unit] = {
      case e: ECatch =>
    }
    try throw new EThrow
    catch pf
  }

  def test(f: => Unit): Unit =
    try f catch {
      case _: EThrow    => println("OK")
      // case e: Throwable => println("! expect an EThrow but got " + e.getClass)
    }

  def main(args: Array[String]): Unit = {
    test { ok() }
    test { notOk() }
  }
}
```

## Runtime output

```scala
[error] Exception in thread "main" scala.MatchError: Main$EThrow (of class Main$EThrow)
[error] 	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:341)
[error] 	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:339)
[error] 	at Main$$anon$1.applyOrElse(Main.scala:11)
[error] 	at Main$$anon$1.applyOrElse(Main.scala:11)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at Main$.notOk(Main.scala:14)
[error] 	at Main$.main$$anonfun$2(Main.scala:25)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at Main$.test(Main.scala:18)
[error] 	at Main$.main(Main.scala:25)
[error] 	at Main.main(Main.scala)
```

## Expectation
running successfully as in scala 2 (println "OK" 2 times)

**Comment by ohze** [comment]
decompile:
+ dotty:
```java
    public void notOk() {
        final PartialFunction pf = (PartialFunction)new Main$$anon.Main$$anon$1();
        try {
            throw new Main.EThrow();
        }
        catch (Throwable ex$) {
            pf.apply((Object)ex$);
        }
    }
```
+ scala 2.13.1:
```java
    public void notOk() {
        final PartialFunction pf = (PartialFunction)new Main$$anonfun.Main$$anonfun$1();
        try {
            throw new Main.EThrow();
        }
        catch (Throwable x$1) {
            final PartialFunction catchExpr$1 = pf;
            if (catchExpr$1.isDefinedAt((Object)x$1)) {
                catchExpr$1.apply((Object)x$1);
                return;
            }
            throw x$1;
        }
    }
```

**Comment by odersky** [comment]
Before, dotty only implemented catch handlers that are plain functions. That was an oversight.
