### ISSUE TITLE
Structural types that return lambdas are not handled correctly

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#8864]
Originally reported in https://github.com/lampepfl/dotty/issues/8736#issuecomment-623092285

```scala
object App extends App {

  trait Rec0[K <: String] {
    private[App] val map: Map[String, Any]
    def get: (k: K) => Any
  }
  def Rec0(map0: Map[String, Any]) = new Rec0[String] {
    val map = map0
    def get: (k: String) => Any = map(_)
  }

  type Rec[K <: String, V0] = Rec0[K] { def get: (k: K) => V0 }
  def field[V](s: String)(v: V): Rec[s.type, V] = Rec0(Map(s -> v)).asInstanceOf[Rec[s.type, V]]

  implicit class RecOps[R <: Rec0[_]](has: R) {
    def +[K1 <: String, V1](that: Rec[K1, V1]): R with Rec[K1, V1] = Rec0(has.map ++ that.map).asInstanceOf[R with Rec[K1, V1]]
  }

  def rec:
    Rec["k", String]
      with Rec["v", Int]
      with Rec["z", Boolean]
    = {
    field("k")("Str") +
      field("v")(0) +
      field("z")(true)
  }
  def res1: String  = rec.get("k")
  def res2: Int     = rec.get("v")
  def res3: Boolean = rec.get("z")
  // error
//  def res4: Boolean = rec.get("nofield")

  println((res1, res2, res3))
}
```

Dotty complained:

```
Found:    (k: ("k" : String)) => String & ((k: ("v" : String)) => Int & ((k: 
  ("k" : String)
 (("v" : String) | ("z" : String))) => Any & (k: ("z" : String)) => Boolean))
Required: Selectable

The following import might fix the problem:

  import reflect.Selectable.reflectiveSelectable
```

I tried adding the import just to see what happened, but it resulted in a _runtime crash_:

```
java.lang.ExceptionInInitializerError
	at App.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: App$$anon$1$$Lambda$17383/1111104806.apply(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at scala.reflect.Selectable$.applyDynamic$extension(Selectable.scala:20)
	at scala.reflect.Selectable.applyDynamic(Selectable.scala:17)
	at App$.res2(main.scala:31)
	at App$.<init>(main.scala:36)
	at App$.<clinit>(main.scala)
	... 12 more
```

The error suggestion was probably misleading, but adding the import should not create unsoundness.

**Comment by smarter** [comment]
Have you checked if this test case can be simplified, e.g. does it still break with just one field?

**Comment by odersky** [comment]
The error suggestion was spot-on: You can't do structural selection without an instance of `Selectable`, and  `reflectiveSelectable` gives you the one which is based on Java reflection. Java reflection cannot do everything we could express in structural types. It seems we missed a case which should be rejected statically.

**Comment by LPTK** [comment]
I wonder why this is considered a structural selection. The `get` method is defined in the `Rec0` trait (even though its _type_ is refined in a structural refinement), so shouldn't the compiler try and call it directly?
