### ISSUE TITLE
Compiler hangs in a match block

### ISSUE THREAD

**Issue by eklavya** [lampepfl/dotty#8922]
## Minimized code

```Scala

case class Token(tokenType: TokenType, lexeme: String, line: Int)

enum TokenType:
  // Single-character tokens.                      
  case MINUS, PLUS, SLASH, STAR, 

  // One or two character tokens.                  
  BANG, BANG_EQUAL,                                
  EQUAL, EQUAL_EQUAL,                              
  GREATER, GREATER_EQUAL,                          
  LESS, LESS_EQUAL

enum Expr {
    case Binary(left: Expr, operator: Token, right: Expr)
}

object Interpreter:
    import Expr._
    import TokenType._

    def eval(expr: Expr): String | Int | Double | Boolean | Unit =
        expr match
            case Binary(left, op, right) =>
                val l = eval(left)
                val r = eval(right)
                (l, r, op.tokenType) match
                    case (l: Double, r: Double, PLUS) => l + r
                    case (l: Int, r: Int, PLUS) => l + r
                    case (l: Double, r: Int, PLUS) => l + r
                    case (l: Int, r: Double, PLUS) => l + r
                    case (l: String, r: String, PLUS) => l + r
                    case (l: Double, r: Double, MINUS) => l - r
                    case (l: Int, r: Int, MINUS) => l - r
                    case (l: Double, r: Int, MINUS) => l - r
                    case (l: Int, r: Double, MINUS) => l - r
                    case (l: Double, r: Double, STAR) => l * r
                    case (l: Int, r: Int, STAR) => l * r
                    case (l: Double, r: Int, STAR) => l * r
                    case (l: Int, r: Double, STAR) => l * r
                    case (l: Double, r: Double, SLASH) => l / r
                    case (l: Int, r: Int, SLASH) => l / r
                    case (l: Double, r: Int, SLASH) => l / r
                    case (l: Int, r: Double, SLASH) => l / r
                    case (l: Double, r: Double, GREATER) => l > r
                    case (l: Int, r: Int, GREATER) => l > r
                    case (l: Double, r: Int, GREATER) => l > r
                    case (l: Int, r: Double, GREATER) => l > r
                    case (l: String, r: String, GREATER) => l > r
                    case (l: Double, r: Double, LESS) => l < r
                    case (l: Int, r: Int, LESS) => l < r
                    case (l: Double, r: Int, LESS) => l < r
                    case (l: Int, r: Double, LESS) => l < r
                    case (l: String, r: String, LESS) => l < r
                    case (l: Double, r: Double, LESS_EQUAL) => l <= r
                    case (l: Int, r: Int, LESS_EQUAL) => l <= r
                    case (l: Double, r: Int, LESS_EQUAL) => l <= r
                    case (l: Int, r: Double, LESS_EQUAL) => l <= r
                    case (l: String, r: String, LESS_EQUAL) => l <= r
                    case (l: Double, r: Double, GREATER_EQUAL) => l >= r
                    case (l: Int, r: Int, GREATER_EQUAL) => l >= r
                    case (l: Double, r: Int, GREATER_EQUAL) => l >= r
                    case (l: Int, r: Double, GREATER_EQUAL) => l >= r
                    case (l: String, r: String, GREATER_EQUAL) => l >= r
                    case _ => println("unsupported operation")
```

## Output

Compiler keeps on consuming RAM and CPU without completing.

## Expectation

Small file should compile rather soonish.

sbt version = 1.3.8
sbt-dotty = 0.4.1
dotty version = 0.24.0-RC1

**Comment by odersky** [comment]
The exhaustivity checker blows up in this example. The compiler cycles for a long time through stacktraces like these:
```
	at dotty.tools.dotc.core.Types$Type.normalize$1(Types.scala:1186)
	at dotty.tools.dotc.core.Types$Type.normalize$1(Types.scala:1190)
	at dotty.tools.dotc.core.Types$Type.normalize$1(Types.scala:1190)
	at dotty.tools.dotc.core.Types$Type.normalize$1(Types.scala:1190)
	at dotty.tools.dotc.core.Types$Type.atoms(Types.scala:1199)
	at dotty.tools.dotc.core.TypeComparer.compareAtoms(TypeComparer.scala:1223)
	at dotty.tools.dotc.core.TypeComparer.comparePaths$2(TypeComparer.scala:752)
	at dotty.tools.dotc.core.TypeComparer.fourthTry$1(TypeComparer.scala:759)
	at dotty.tools.dotc.core.TypeComparer.thirdTryNamed$1(TypeComparer.scala:501)
	at dotty.tools.dotc.core.TypeComparer.compareNamed$1(TypeComparer.scala:274)
	at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:278)
	at dotty.tools.dotc.core.TypeComparer.op$1(TypeComparer.scala:1101)
	at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1120)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:166)
	at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:176)
	at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:132)
	at dotty.tools.dotc.core.Types$Type.$less$colon$less(Types.scala:909)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.isSubType(Space.scala:502)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$3(Space.scala:201)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.intersect(Space.scala:229)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.intersect(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$11$$anonfun$3(Space.scala:199)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1101/1595176476.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$3(Space.scala:199)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.intersect(Space.scala:229)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.intersect(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$18$$anonfun$4(Space.scala:266)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1132/77029509.apply(Unknown Source)
	at scala.collection.immutable.List.exists(List.scala:367)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:266)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$17$$anonfun$3(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1108/1387511555.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:223)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:252)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$16$$anonfun$2(Space.scala:250)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1110/1036606347.apply(Unknown Source)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$4(Space.scala:250)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.minus(Space.scala:275)
	at dotty.tools.dotc.transform.patmat.SpaceEngine.minus(Space.scala:311)
	at dotty.tools.dotc.transform.patmat.SpaceLogic.op$16$$anonfun$2(Space.scala:250)
	at dotty.tools.dotc.transform.patmat.SpaceLogic$$Lambda$1110/1036606347.apply(Unknown Source)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
```
