### ISSUE TITLE
unapply with new implicit parameters

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#8972]
## Minimized code

```Scala
trait Num:
  type Nat

object IsInt:
  def unapply(using num: Num)(sc: num.Nat): Option[Int] = ???

def test(using num: Num)(x: num.Nat) =
  x match
    case IsInt(i) =>
```

## Expectation
This new kind of patterns should be supported.

## Output (click arrow to expand)
<details>

```scala
scala.MatchError: Apply(Select(Ident(IsInt),unapply),List(Ident(num))) (of class dotty.tools.dotc.ast.Trees$Apply) while compiling Foo.scala
Exception in thread "main" scala.MatchError: Apply(Select(Ident(IsInt),unapply),List(Ident(num))) (of class dotty.tools.dotc.ast.Trees$Apply)
        at dotty.tools.dotc.typer.Applications$.unapplyArgs(Applications.scala:155)
        at dotty.tools.dotc.typer.Applications.typedUnApply(Applications.scala:1239)
        at dotty.tools.dotc.typer.Typer.typedUnApply(Typer.scala:84)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2346)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2405)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2444)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2453)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2456)
        at dotty.tools.dotc.typer.Typer.typedPattern(Typer.scala:2571)
        at dotty.tools.dotc.typer.Typer.typedCase(Typer.scala:1386)
        at dotty.tools.dotc.typer.Typer.typedCases$$anonfun$1(Typer.scala:1326)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:63)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:79)
        at dotty.tools.dotc.typer.Typer.typedCases(Typer.scala:1328)
        at dotty.tools.dotc.typer.Typer.$anonfun$18(Typer.scala:1318)
        at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2011)
        at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:84)
        at dotty.tools.dotc.typer.Typer.typedMatchFinish(Typer.scala:1318)
        at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1283)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2359)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2405)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2444)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2453)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2456)
        at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1330)
        at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1320)
        at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1330)
        at dotty.tools.dotc.typer.Namer.rhsType$2(Namer.scala:1461)
        at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1472)
        at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1473)
        at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1484)
        at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1492)
        at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1577)
        at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:814)
        at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:931)
        at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:842)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:259)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:186)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:188)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:446)
        at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2288)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2313)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2404)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2444)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2453)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2456)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2478)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2523)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2004)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2334)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2338)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2404)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2444)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2453)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2456)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2478)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2523)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2130)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2377)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2405)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2444)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2453)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2456)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2567)
        at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:42)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
        at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:114)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:114)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:165)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:175)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:183)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:190)
        at dotty.tools.dotc.Run.compileSources(Run.scala:127)
        at dotty.tools.dotc.Run.compile(Run.scala:110)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
        at dotty.tools.dotc.Driver.process(Driver.scala:194)
        at dotty.tools.dotc.Driver.process(Driver.scala:163)
        at dotty.tools.dotc.Driver.process(Driver.scala:175)
        at dotty.tools.dotc.Driver.main(Driver.scala:202)
        at dotty.tools.dotc.Main.main(Main.scala)```
</details>

**Comment by nicolasstucki** [comment]
This is useful to create extractors on the metaprogramming interface.
