### ISSUE TITLE
Partest flakeyness

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#906]
As we all have experienced, partest has a lot of spurious failures. Failures seem include those categories:
- A missing ref in Scala2Unpickler, where some file is not found, even though it is on the classpath (observed by everyone)
- Some abstract method error (observed by @smarter)
- Failure to allocate memory error (observed by @odersky).

It is super important that we fix this, as it currently ruins the whole developer experience and causes a lot of wasted cycles. 

Possible areas to investigate: Is there a race condition somewhere? Or else some problem with jenkins?

Possible lines of attack: 
1. Better diagnostics: Right now partest gives not enough interesting summary information for failed tests. You get a stack trace but it is the one of the test runner, not the compiler. I want to see a compiler stacktrace there! 
2. Better instrumentation: If the Missing reference strikes in Unpickler, provide all the useful information that exists in the stack trace. Try to find the reference again and instrument every step of the way. Same for the abstract method error.
3. More robustness. If occasional failures remain (e.g. the failure to allocate memory one), maybe we can automatically re-launch the test to avoid manual intervention. Don't do this infinitely often of course.

**Comment by odersky** [comment]
One other thing we could do: Fo back to sequential testing and find out which errors go away. That would indicate a data race as the source for these errors.

**Comment by retronym** [comment]
Here's an recent example:

https://scala-ci.typesafe.com/job/dotty-master-validate-partest/577/consoleFull

```
[error] java.lang.Exception
[error] 	at dotty.tools.dotc.core.Denotations$MissingRef.<init>(Denotations.scala:864)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.recur$1(Denotations.scala:998)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.staticRef(Denotations.scala:1003)
[error] 	at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:485)
[error] 	at dotty.tools.dotc.core.Symbols$class.requiredClass(Symbols.scala:343)
[error] 	at dotty.tools.dotc.core.Contexts$Context.requiredClass(Contexts.scala:53)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser.classNameToSymbol(ClassfileParser.scala:85)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:305)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:337)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser.dotty$tools$dotc$core$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:396)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser$ConstantPool.getType(ClassfileParser.scala:993)
[error] 	at dotty.tools.dotc.core.classfile.ClassfileParser$$anon$1.complete(ClassfileParser.scala:212)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:170)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:152)
[error] 	at dotty.tools.dotc.transform.TreeTransforms$AnnotationTransformer$class.transform(TreeTransform.scala:184)
[error] 	at dotty.tools.dotc.transform.FirstTransform.transform(FirstTransform.scala:30)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:635)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:381)
[error] 	at dotty.tools.dotc.core.Symbols$Symbol.isType(Symbols.scala:400)
[error] 	at dotty.tools.dotc.core.TypeErasure$$anonfun$6.apply(TypeErasure.scala:367)
[error] 	at dotty.tools.dotc.core.TypeErasure$$anonfun$6.apply(TypeErasure.scala:367)
[error] 	at dotty.tools.dotc.core.Scopes$Scope$$anonfun$filteredScope$1.apply(Scopes.scala:133)
[error] 	at dotty.tools.dotc.core.Scopes$Scope$$anonfun$filteredScope$1.apply(Scopes.scala:132)
[error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error] 	at dotty.tools.dotc.core.Scopes$Scope.filteredScope(Scopes.scala:132)
[error] 	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$apply(TypeErasure.scala:367)
[error] 	at dotty.tools.dotc.core.TypeErasure.eraseInfo(TypeErasure.scala:398)
[error] 	at dotty.tools.dotc.core.TypeErasure$.transformInfo(TypeErasure.scala:177)
[error] 	at dotty.tools.dotc.transform.Erasure.transform(Erasure.scala:54)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:635)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:653)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:671)
[error] 	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:381)
[error] 	at dotty.tools.dotc.core.Scopes$Scope.denotsNamed(Scopes.scala:119)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1467)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1520)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:416)
[error] 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:493)
[error] 	at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:396)
[error] 	at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:396)
[error] 	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error] 	at dotty.tools.dotc.core.Types$Type.member(Types.scala:395)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.recur$1(Denotations.scala:991)
[error] 	at dotty.tools.dotc.core.Denotations$DenotationsBase$class.staticRef(Denotations.scala:1003)
[error] 	at dotty.tools.dotc.core.Contexts$ContextBase.staticRef(Contexts.scala:485)
[error] 	at dotty.tools.dotc.core.Symbols$class.requiredClass(Symbols.scala:343)
[error] 	at dotty.tools.dotc.core.Contexts$Context.requiredClass(Contexts.scala:53)
[error] 	at dotty.tools.backend.jvm.DottyBackendInterface.requiredClass(DottyBackendInterface.scala:368)
[error] 	at dotty.tools.backend.jvm.DottyBackendInterface.requiredClass(DottyBackendInterface.scala:35)
[error] 	at scala.tools.nsc.backend.jvm.BackendInterfaceDefinitions.<init>(BackendInterface.scala:721)
[error] 	at scala.tools.nsc.backend.jvm.BackendInterface.<init>(BackendInterface.scala:14)
[error] 	at dotty.tools.backend.jvm.DottyBackendInterface.<init>(DottyBackendInterface.scala:35)
[error] 	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:41)
[error] 	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:271)
[error] 	at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:269)
[error] 	at scala.collection.immutable.List.map(List.scala:273)
[error] 	at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:269)
[error] 	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:34)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:60)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:57)
[error] 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:57)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
[error] 	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
[error] 	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:33)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:44)
[error] 	at dotty.partest.DPDirectCompiler.compile(DPDirectCompiler.scala:30)
[error] 	at scala.tools.partest.nest.Runner.attemptCompile(Runner.scala:421)
```

If I've got my versions lined up, this appears to be failing during the lookup of the class symbol for `j.l.StringBuffer`

```scala
  // BackendDefinitions
  val BoxedBooleanClass: Symbol = requiredClass[java.lang.Boolean]
  val BoxedByteClass: Symbol = requiredClass[java.lang.Byte]
  val BoxedShortClass: Symbol = requiredClass[java.lang.Short]
  val BoxedCharacterClass: Symbol = requiredClass[java.lang.Character]
  val BoxedIntClass: Symbol  = requiredClass[java.lang.Integer]
  val BoxedLongClass: Symbol = requiredClass[java.lang.Long]
  val BoxedFloatClass: Symbol = requiredClass[java.lang.Float]
  val BoxedDoubleClass: Symbol = requiredClass[java.lang.Double]
  val StringClass: Symbol = requiredClass[java.lang.String]
  val StringBuilderClass: Symbol = requiredClass[scala.collection.mutable.StringBuilder]
  val JavaStringBufferClass: Symbol = requiredClass[java.lang.StringBuffer] // :721
```

**Comment by odersky** [comment]
It seems to have been fixed by the change to newTermName.

**Comment by smarter** [comment]
The AbstractMethodError is still here it seems: https://scala-ci.typesafe.com/job/dotty-master-validate-partest/737/console

**Comment by smarter** [comment]
Partest is long gone, and we now live much happier lives.
