### ISSUE TITLE
Compiling product1 with stdlib cases data races

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#907]
It seems namer forces Product1 to be read from classpath before entering it.
```
[error] Test dotc.tests.compileStdLib failed: java.lang.AssertionError: assertion failed: data race? overwriting symbol of Product1 / TypeRef(ThisType(TypeRef(NoPrefix,scala)),Product1) / class dotty.tools.dotc.core.Types$CachedTypeRef / 190 / 4820 / module class scala / module class scala / frontend, took 2.154 sec
[error]     at scala.Predef$.assert(Predef.scala:165)
[error]     at dotty.tools.dotc.core.Types$NamedType.checkSymAssign(Types.scala:1374)
[error]     at dotty.tools.dotc.core.Types$NamedType.setDenot(Types.scala:1402)
[error]     at dotty.tools.dotc.core.Types$NamedType.withDenot(Types.scala:1395)
[error]     at dotty.tools.dotc.core.Types$TypeRef$.apply(Types.scala:1789)
[error]     at dotty.tools.dotc.core.SymDenotations$SymDenotation.typeRef(SymDenotations.scala:1039)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.typeRef(SymDenotations.scala:1270)
[error]     at dotty.tools.dotc.core.Symbols$$anonfun$synthesizeCompanionMethod$1.apply(Symbols.scala:188)
[error]     at dotty.tools.dotc.core.Symbols$$anonfun$synthesizeCompanionMethod$1.apply(Symbols.scala:188)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.orElse(Symbols.scala:447)
[error]     at dotty.tools.dotc.core.Symbols$class.synthesizeCompanionMethod(Symbols.scala:187)
[error]     at dotty.tools.dotc.core.Contexts$Context.synthesizeCompanionMethod(Contexts.scala:53)
[error]     at dotty.tools.dotc.typer.Namer.dotty$tools$dotc$typer$Namer$$createLinks$1(Namer.scala:458)
[error]     at dotty.tools.dotc.typer.Namer$$anonfun$createCompanionLinks$1$2.apply(Namer.scala:466)
[error]     at dotty.tools.dotc.typer.Namer$$anonfun$createCompanionLinks$1$2.apply(Namer.scala:463)
[error]     at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
[error]     at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
[error]     at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
[error]     at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
[error]     at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error]     at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:108)
[error]     at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
[error]     at dotty.tools.dotc.typer.Namer.createCompanionLinks$1(Namer.scala:463)
[error]     at dotty.tools.dotc.typer.Namer.index(Namer.scala:475)
[error]     at dotty.tools.dotc.typer.Namer.indexExpanded(Namer.scala:401)
[error]     at dotty.tools.dotc.typer.Namer.index(Namer.scala:392)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$enterSyms$1.apply$mcV$sp(FrontEnd.scala:36)
[error]     at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:19)
[error]     at dotty.tools.dotc.typer.FrontEnd.enterSyms(FrontEnd.scala:34)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$2.apply(FrontEnd.scala:52)
[error]     at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$2.apply(FrontEnd.scala:52)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
```

**Comment by odersky** [comment]
Needs more context to be reproducible.

**Comment by DarkDimius** [comment]
I can reproduce it locally by simply uncommenting `Product1`. Trying to reproduce it remotely: https://github.com/lampepfl/dotty/pull/932

**Comment by DarkDimius** [comment]
Reproduced on Jenkins: https://scala-ci.typesafe.com/job/dotty-master-validate-junit/630/consoleFull

**Comment by DarkDimius** [comment]
fixed.
