### ISSUE TITLE
enums extending java.lang.Enum are not recognised by reflection

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9105]
## Minimized code

```Scala
Starting dotty REPL...
scala> enum A extends java.lang.Enum[A] { case Foo, Bar }
// defined class A

scala> A.getClass.isEnum                                                                                                
val res1: Boolean = false

scala> A.getClass.getEnumConstants
val res2: Array[? <: A.type] = null
```
## Expectation

the other Enum APIs like `java.lang.Enum.valueOf` and `java.util.EnumSet.allOf` work so not really a priority, but perhaps something relies on the reflection API?

**Comment by sjrd** [comment]
That probably impacts the ability to `switch` on them from Java source code.

**Comment by bishabosha** [comment]
something is definitely wrong,

given this enum:
```scala
package example

enum A extends java.lang.Enum[A] { case Foo, Bar }
```

and this java code to switch on it

```java
package example;

import static example.A.*;

public class UseA {
  public static void useA(A a) {
    switch (a) {
      case Foo:
        System.out.println("foo");
        break;
      case Bar:
        System.out.println("bar");
        break;
      default:
        System.err.println("???");
        break;
    }
  }
}
```

from `jshell` it is perfectly fine to do the following:
```java
jshell> example.UseA.useA(example.A.Foo)
foo
```

but the same from `dotr` crashes:
```scala
scala> example.UseA.useA(example.A.Foo)
java.lang.NullPointerException
	at example.UseA$1.<clinit>(UseA.java:7)
	at example.UseA.useA(UseA.java:7)
	at rs$line$1$.<init>(rs$line$1:1)
	at rs$line$1$.<clinit>(rs$line$1)
	at rs$line$1.res0(rs$line$1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:72)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:72)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:95)
	at dotty.tools.repl.ReplDriver.displayMembers$3$$anonfun$3(ReplDriver.scala:291)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at dotty.tools.repl.ReplDriver.displayMembers$6(ReplDriver.scala:291)
	at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$2(ReplDriver.scala:317)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:317)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:245)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:247)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:193)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:127)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:148)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
however jshell was using jvm 12 whereas dotr was on java 8

**Comment by bishabosha** [comment]
It seems the scala compiled enums do have the ACC_ENUM flag, so something else is preventing registration with reflection

**Comment by bishabosha** [comment]
actually this is a mistake, the getClass would of course call the companion object, we have a test for reflection in `tests/run/enum-java/Test.java`
