### ISSUE TITLE
NoSpan in console

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#9111]
## Minimized example
```scala
sbt:dotty-simple> console
[info] Fetching artifacts of 
https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.25/0.25.0-bin-20200604-2fbefb0-NIGHTLY/dotty-compiler_0.25-0.25.…
  100.0% [##########] 11.9 MiB (104.6 KiB / s)
[info] Fetched artifacts of 
[info] Compiling 13 Scala sources to /Users/vletal/Workspace/Personal/loonyssh/target/scala-0.25/classes ...

scala> enum E:
     |   case A
     | 
[error] (run-main-0) java.lang.AssertionError: assertion failed
[error] java.lang.AssertionError: assertion failed
[error]         at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
[error]         at dotty.tools.dotc.util.Spans$Span$.point$extension(Spans.scala:56)
[error]         at dotty.tools.dotc.util.SourcePosition.point(SourcePosition.scala:23)
[error]         at dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:25)
[error]         at dotty.tools.repl.ReplDriver.$anonfun$5(ReplDriver.scala:258)
[error]         at scala.math.Ordering$$anon$1.compare(Ordering.scala:140)
[error]         at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[error]         at java.base/java.util.TimSort.sort(TimSort.java:220)
[error]         at java.base/java.util.Arrays.sort(Arrays.java:1441)
[error]         at scala.collection.SeqOps.sorted(Seq.scala:703)
[error]         at scala.collection.SeqOps.sorted$(Seq.scala:695)
[error]         at scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
```

**Comment by bishabosha** [comment]
Hi, I tried this on Mac with dotty `0.25.0-bin-20200604-2fbefb0-NIGHTLY` and sbt `1.3.12` on graalvm jdk 8 version 20.0 CE and AdoptOpenJDK 14.0.1+7. I can't replicate this so please may you provide more information?

**Comment by bishabosha** [comment]
@letalvoj I see you are compiling 13 sources, perhaps there is some weird interaction

**Comment by letalvoj** [comment]
@bishabosha will do in the upcoming days, sorry for the delay

**Comment by bishabosha** [comment]
@letalvoj no need to apologise 😀

**Comment by nicolasstucki** [comment]
We made some fixed on that logic recently. It might have fixed it.

**Comment by letalvoj** [comment]
Soooo after stripping my project to bare bones I realized that I have a
```scala
scalacOptions in (Compile, console) += "-Xprint:typer"
```
in `build.sbt`. It works on `0.24.0-RC1`.

**Comment by bishabosha** [comment]
ok thank you, confirmed the dotty example template with version `0.25.0-bin-20200604-2fbefb0-NIGHTLY` and `scalacOptions in (Compile, console) += "-Xprint:typer"` will fail with the given crash in console

**Comment by bishabosha** [comment]
it still crashes on `0.25.0-RC1`

**Comment by letalvoj** [comment]
It is also caused by
```
scalacOptions += "-verbose"
```
