### ISSUE TITLE
ClassTags: failure to compile Array.scala

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#924]
```scala
exception occurred while compiling ./scala-scala/src/library/scala/Array.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation.owner(SymDenotations.scala:1728)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.typeRef(SymDenotations.scala:1039)
	at dotty.tools.dotc.transform.ClassTags.transformTypeApply(ClassTags.scala:60)
```

**Comment by DarkDimius** [comment]
Fixed.
