### ISSUE TITLE
Tastydoc doesn't support refinements with methods

### ISSUE THREAD

**Issue by TheElectronWill** [lampepfl/dotty#9259]
## Minimized code

```scala
object RefinedTypes {
  type RefinedPoly = PolyFunction { def apply[T](x: T): T } // Exception
  type RefinedDef = AnyRef { def method(): Int } // MatchError
}
```

## Output
The first type fails with:
```scala
[error] Test dotty.tastydoc.Tests.testDocumentation failed: java.lang.Exception: Match error in info of Refinement. This should not happen, please open an issue. ConstantReference([T >: scala.Nothing <: scala.Any] => (x: T)T), took 4.022 sec
[error]     at dotty.tastydoc.TastyTypeConverter.inner$1(TastyTypeConverter.scala:49)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeToReference(TastyTypeConverter.scala:115)
[error]     at dotty.tastydoc.representations$.convertTypeToReference(representations.scala:8)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeOrBoundsToReference(TastyTypeConverter.scala:19)
```
There is a `// TOFIX` for type lambdas left in the code, it seems to be related to this issue.

The second one fails with:
```scala
[error] Test dotty.tastydoc.Tests.testDocumentation failed: scala.MatchError: MethodType(List(), List(), TypeRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),module scala),Predef),String)) (of class dotty.tools.dotc.core.Types$CachedMethodType), took 4.151 sec
[error]     at dotty.tastydoc.TastyTypeConverter.inner$1(TastyTypeConverter.scala:106)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeToReference(TastyTypeConverter.scala:115)
[error]     at dotty.tastydoc.representations$.convertTypeToReference(representations.scala:8)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeOrBoundsToReference(TastyTypeConverter.scala:19)
[error]     at dotty.tastydoc.representations$.convertTypeOrBoundsToReference(representations.scala:8)
[error]     at dotty.tastydoc.TastyTypeConverter.inner$1(TastyTypeConverter.scala:45)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeToReference(TastyTypeConverter.scala:115)
[error]     at dotty.tastydoc.representations$.convertTypeToReference(representations.scala:8)
[error]     at dotty.tastydoc.TastyTypeConverter.convertTypeOrBoundsToReference(TastyTypeConverter.scala:19)
```

## Expectation
This should work and produce a valid markdown output.

**Comment by AleksanderBG** [comment]
Thanks again for reporting the issue! For bookkeeping reasons it's better to close this issue (we will be doing heavy changes to Tastydoc), though I'm keeping a list of issues like this one on hand.
