### ISSUE TITLE
Type lambda =>> triggers implicit resolution on uninitialised type

### ISSUE THREAD

**Issue by mario-galic** [lampepfl/dotty#9280]
## Minimized code

```Scala
summon[[X] =>> <:<[A, B]]
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.translate$1(ErrorReporting.scala:137)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.userDefinedErrorString$$anonfun$1(ErrorReporting.scala:142)
	at scala.util.matching.Regex.$anonfun$replaceSomeIn$1(Regex.scala:535)
	at scala.util.matching.Regex.$anonfun$replaceSomeIn$1$adapted(Regex.scala:535)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at scala.util.matching.Regex.replaceSomeIn(Regex.scala:535)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.userDefinedErrorString(ErrorReporting.scala:142)
	at dotty.tools.dotc.typer.Implicits.$anonfun$1(Implicits.scala:865)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.dotc.typer.Implicits.missingArgMsg(Implicits.scala:865)
	at dotty.tools.dotc.typer.Typer.missingArgMsg(Typer.scala:89)
	at dotty.tools.dotc.typer.Typer.issueErrors$1$$anonfun$1$$anonfun$1(Typer.scala:3029)
	at dotty.tools.dotc.reporting.NoExplanation.msg(Message.scala:122)
	at dotty.tools.dotc.reporting.Message.message(Message.scala:80)
	at dotty.tools.dotc.reporting.Message.isNonSensical(Message.scala:92)
	at dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden(HideNonSensicalMessages.scala:16)
	at dotty.tools.repl.package$$anon$1.isHidden(package.scala:8)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:265)
	at dotty.tools.dotc.reporting.Reporting.error(Reporter.scala:129)
	at dotty.tools.dotc.core.Contexts$Context.error(Contexts.scala:79)
	at dotty.tools.dotc.typer.Typer.issueErrors$2$$anonfun$2(Typer.scala:3028)
	at dotty.runtime.function.JProcedure3.apply(JProcedure3.java:15)
	at dotty.runtime.function.JProcedure3.apply(JProcedure3.java:10)
	at scala.collection.LazyZip3.foreach(LazyZipOps.scala:248)
	at dotty.tools.dotc.typer.Typer.issueErrors$3(Typer.scala:3032)
	at dotty.tools.dotc.typer.Typer.addImplicitArgs$3(Typer.scala:3057)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$2(Typer.scala:3074)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3247)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3500)
	at dotty.tools.dotc.typer.Typer.op$3(Typer.scala:2836)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2837)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1361)
	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1351)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1361)
	at dotty.tools.dotc.typer.Namer.rhsType$2(Namer.scala:1493)
	at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1504)
	at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1505)
	at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1516)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1524)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:819)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:940)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:851)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:259)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:445)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2318)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2343)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2536)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2034)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2364)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2368)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2536)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2160)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2408)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.repl.REPLFrontEnd.runOn(ReplFrontEnd.scala:23)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:147)
	at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:156)
	at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:166)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:231)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:195)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:128)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:131)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:150)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:131)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

Also should the following perhaps not attempt implicit resolution

```
scala> summon[[X] =>> X]
1 |summon[[X] =>> X]
  |                 ^
  |no implicit argument of type [X] =>> X was found for parameter x of method summon in object DottyPredef
```

**Comment by odersky** [comment]
I could not reproduce the problem
