### ISSUE TITLE
StackOverflowException/UnsupportedOperationException crash

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#9299]
## Minimized code

```Scala
type F <: F = 1 match {
  case _ => foo.foo
}
def foo(a: Int): Unit = ???
```

## Output (click arrow to expand)
<details>

```scala
-- Error: test.scala:1:10 ------------------------------------------------------
1 |type F <: F = 1 match {
  |          ^
  |Recursion limit exceeded.
  |Maybe there is an illegal cyclic reference?
  |If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
  |A recurring operation is (inner to outer):
  |
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  ...
  |
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
  |  type parameters of  <: F
  |  type parameters of F
java.lang.StackOverflowError while compiling test.scala
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1981)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1974)
	at dotty.tools.dotc.core.Types$TypeRef.underlying(Types.scala:2461)
	at dotty.tools.dotc.core.Types$Type.baseClasses(Types.scala:496)
	at dotty.tools.dotc.core.Types$Type.baseClasses(Types.scala:496)
	at dotty.tools.dotc.core.Types$Type.baseClasses(Types.scala:496)
	at dotty.tools.dotc.core.Types$Type.baseClasses(Types.scala:496)
	at dotty.tools.dotc.core.Types$Type.baseClasses(Types.scala:496)
```
</details>

**Comment by alexknvl** [comment]
## Minimized code

A slightly different variation results in `UnsupportedOperationException`:
```Scala
// UOE-abff262a5e36afa8450fd485c28178c43f0e765a
type T <: foo.a = Int match {
  case "" => foo.b
}
def foo(x: Int): Unit = ???
```

## Output (click arrow to expand)
<details>

```scala
-- [E008] Not Found Error: test.scala:1:14 -------------------------------------
1 |type T <: foo.a = Int match {
  |          ^^^^^
  |          type a is not a member of Int => Unit
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
java.lang.UnsupportedOperationException: tail of empty list while compiling test.scala
Exception in thread "main" java.lang.UnsupportedOperationException: tail of empty list
	at scala.collection.immutable.Nil$.tail(List.scala:631)
	at scala.collection.immutable.Nil$.tail(List.scala:628)
	at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1412)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1524)
	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1609)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:823)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:940)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:851)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:259)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:445)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2318)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2343)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2536)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:853)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:857)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2384)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:1189)
	at dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:971)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2386)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsUnappliedMethod$2(Typer.scala:3130)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3267)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3500)
	at dotty.tools.dotc.typer.Typer.op$3(Typer.scala:2836)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2837)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:545)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:569)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2346)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedType(Typer.scala:2627)
	at dotty.tools.dotc.typer.Typer.caseRest$2(Typer.scala:1430)
	at dotty.tools.dotc.typer.Typer.typedTypeCase(Typer.scala:1436)
	at dotty.tools.dotc.typer.Typer.$anonfun$27(Typer.scala:1715)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:63)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:79)
	at dotty.tools.dotc.typer.Typer.typedMatchTypeTree(Typer.scala:1715)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2404)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:1358)
	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1351)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1358)
	at dotty.tools.dotc.typer.Namer$TypeDefCompleter.typeSig(Namer.scala:1025)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:940)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:851)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:259)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:445)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2318)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2343)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2536)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2034)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2364)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2368)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2536)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2160)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2408)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:114)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:114)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
	at dotty.tools.dotc.Run.compileSources(Run.scala:142)
	at dotty.tools.dotc.Run.compile(Run.scala:124)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
	at dotty.tools.dotc.Driver.process(Driver.scala:194)
	at dotty.tools.dotc.Driver.process(Driver.scala:163)
	at dotty.tools.dotc.Driver.process(Driver.scala:175)
	at dotty.tools.dotc.Driver.main(Driver.scala:202)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>
