### ISSUE TITLE
tab complete on classOf[Foo] assertion failed (AndType.apply of HKTypeLambda)

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9334]
## Minimized code

```Scala
scala> class Foo[T]
// defined class Foo

scala> classOf[Foo].<PRESS TAB>
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Foo & Object / HKTypeLambda(List(T), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module rs$line$1),class Foo),List(TypeParamRef(T)))) & TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object)
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.core.Types$AndType$.apply(Types.scala:2912)
	at dotty.tools.dotc.core.Types$AndType$.make(Types.scala:2931)
	at dotty.tools.dotc.core.Types$AndType.derivedAndType(Types.scala:2894)
	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.derivedAndType(Types.scala:5270)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:4997)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.op$1(TypeOps.scala:108)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:110)
	at dotty.tools.dotc.core.Types$TypeMap.op$4(Types.scala:4935)
	at dotty.tools.dotc.core.Types$TypeMap.mapArgs$1(Types.scala:4935)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:4943)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.op$1(TypeOps.scala:108)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:110)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda$1(Types.scala:4974)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:4976)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.op$1(TypeOps.scala:108)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:110)
	at dotty.tools.dotc.core.TypeOps$.asSeenFrom(TypeOps.scala:55)
	at dotty.tools.dotc.core.Types$Type.asSeenFrom(Types.scala:901)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.derived$1(Denotations.scala:1026)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1030)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1002)
	at dotty.tools.dotc.core.Denotations$PreDenotation.asSeenFrom(Denotations.scala:135)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1982)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:582)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:750)
	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:565)
	at dotty.tools.dotc.core.Types$Type.member(Types.scala:549)
	at dotty.tools.dotc.interactive.Completion$CompletionBuffer.appendMemberSyms$1(Completion.scala:270)
	at dotty.tools.dotc.interactive.Completion$CompletionBuffer.accessibleMembers$$anonfun$2(Completion.scala:272)
	at dotty.runtime.function.JProcedure2.apply(JProcedure2.java:15)
	at dotty.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at dotty.tools.dotc.core.Types$Type.memberDenots$$anonfun$1(Types.scala:795)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:932)
	at scala.collection.immutable.HashSet.foreach(HashSet.scala:939)
	at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:795)
	at dotty.tools.dotc.interactive.Completion$CompletionBuffer.accessibleMembers(Completion.scala:272)
	at dotty.tools.dotc.interactive.Completion$CompletionBuffer.addAccessibleMembers(Completion.scala:280)
	at dotty.tools.dotc.interactive.Completion$CompletionBuffer.addMemberCompletions(Completion.scala:209)
	at dotty.tools.dotc.interactive.Completion$.computeCompletions(Completion.scala:121)
	at dotty.tools.dotc.interactive.Completion$.completions(Completion.scala:47)
	at dotty.tools.repl.ReplDriver.completions$$anonfun$1(ReplDriver.scala:186)
	at scala.util.Either.map(Either.scala:382)
	at dotty.tools.repl.ReplDriver.completions(ReplDriver.scala:187)
	at dotty.tools.repl.ReplDriver.$anonfun$3(ReplDriver.scala:111)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4397)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4363)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4302)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3797)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:71)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:116)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:126)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:131)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:150)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:131)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

**Comment by robmwalsh** [comment]
Nothing to do with completion, but the stack trace looks very similar

```
[error] ## Exception when compiling 18 sources to /home/rob/code/lsp/libs/zio-lsp/js/target/scala-3.2.0/classes
[error] java.lang.AssertionError: assertion failed: R & zio.jsonrpc.RpcReceiver / TypeParamRef(R) & HKTypeLambda(List(Their), List(TypeBounds(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Nothing),TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class zio)),object jsonrpc),JsonRpcMethod))), AppliedType(TypeRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object zio),object jsonrpc),trait RpcReceiver),List(TypeParamRef(Their))))
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.Types$AndType$.apply(Types.scala:3203)
[error] dotty.tools.dotc.core.Types$AndType$.make(Types.scala:3238)
[error] dotty.tools.dotc.core.Types$AndType.derivedAndType(Types.scala:3184)
[error] dotty.tools.dotc.core.Types$ApproximatingTypeMap.derivedAndType(Types.scala:5961)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5689)
[error] dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:109)
[error] dotty.tools.dotc.core.Types$TypeMap.op$proxy16$1(Types.scala:5590)
[error] dotty.tools.dotc.core.Types$TypeMap.mapArgs(Types.scala:5590)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5627)
[error] dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:109)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
[error] dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
[error] dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
[error] dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
[error] dotty.tools.dotc.core.TypeOps$.asSeenFrom(TypeOps.scala:51)
[error] dotty.tools.dotc.core.Types$Type.asSeenFrom(Types.scala:1036)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.derived$1(Denotations.scala:1099)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1125)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1079)
[error] dotty.tools.dotc.core.Denotations$PreDenotation.asSeenFrom(Denotations.scala:134)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:2069)
[error] dotty.tools.dotc.core.Types$Type.go$1(Types.scala:686)
[error] dotty.tools.dotc.core.Types$Type.findMember(Types.scala:879)
[error] dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:669)
[error] dotty.tools.dotc.core.Types$Type.member(Types.scala:653)
[error] dotty.tools.dotc.typer.ProtoTypes$SelectionProto.liftedTree1$1(ProtoTypes.scala:195)
[error] dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy(ProtoTypes.scala:217)
[error] dotty.tools.dotc.core.TypeComparer.isMatchedByProto(TypeComparer.scala:1917)
[error] dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:314)
[error] dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1336)
[error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:194)
[error] dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:204)
[error] dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:128)
[error] dotty.tools.dotc.core.TypeComparer.testSubType(TypeComparer.scala:144)
[error] dotty.tools.dotc.core.TypeComparer$.testSubType(TypeComparer.scala:2767)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:3725)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3822)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4038)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3368)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:646)
[error] dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:684)
[error] dotty.tools.dotc.typer.Typer.tryApply$1(Typer.scala:3194)
[error] dotty.tools.dotc.typer.Typer.tryInsertApplyOrImplicit$$anonfun$2(Typer.scala:3225)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3131)
[error] dotty.tools.dotc.typer.Typer.tryInsertApplyOrImplicit(Typer.scala:3232)
[error] dotty.tools.dotc.typer.Typer.adaptToArgs$1(Typer.scala:3460)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4033)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3368)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:910)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2859)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:646)
[error] dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:684)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2828)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:910)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2859)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1618)
[error] dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1608)
[error] dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1618)
[error] dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1675)
[error] dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1749)
[error] dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:786)
[error] dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:921)
[error] dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:809)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:171)
[error] dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
[error] dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:373)
[error] dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2800)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2825)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
[error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1056)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1060)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2867)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:1464)
[error] dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:1238)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2869)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$7(ProtoTypes.scala:482)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:405)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:483)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
[error] dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:622)
[error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
[error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
[error] dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1077)
[error] dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:117)
[error] dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:923)
[error] dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1003)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3131)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1014)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:117)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2859)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2906)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.Typer.$anonfun$48(Typer.scala:2295)
[error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:248)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2295)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2835)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2500)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2847)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2851)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2500)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2847)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2851)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2921)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3013)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3063)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2629)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2892)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2922)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2987)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2991)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3107)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:43)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:50)
[error] scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:417)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:50)
[error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:84)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:84)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:234)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:245)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:253)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:262)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:262)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:186)
[error] dotty.tools.dotc.Run.compile(Run.scala:170)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]            
[error] stack trace is suppressed; run last zioLspJVM / Compile / compileIncremental for the full output
[error] stack trace is suppressed; run last zioLspJS / Compile / compileIncremental for the full output
[error] (zioLspJVM / Compile / compileIncremental) java.lang.AssertionError: assertion failed: R & zio.jsonrpc.RpcReceiver / TypeParamRef(R) & HKTypeLambda(List(Their), List(TypeBounds(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Nothing),TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class zio)),object jsonrpc),JsonRpcMethod))), AppliedType(TypeRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object zio),object jsonrpc),trait RpcReceiver),List(TypeParamRef(Their))))
```
this project is not yet public, but it will be soon. Error is present in commit 7f78bfe060ecc310a408d72ae2d7cb854940bb5a

**Comment by SethTisue** [comment]
It's not crucial that it be the built-in `classOf`; this also crashes:

```scala
scala> def myClassOf[T]: Class[T] = ???
def myClassOf[T]: Class[T]
                                                                                                    
scala> class Foo[T]
// defined class Foo
                                                                                                    
scala> myClassOf[Foo].
```
