### ISSUE TITLE
Inlined parameter name conflict

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#9342]
```Scala
trait Label[A]:
  def apply(v: A): String

given [A] as Label[A] = _.toString

extension [A](x: A) inline def label(using inline l: Label[A]): String = l(x)

def label1[A](v: A) = v.label  // Compiles fine

def label2[A](l: A) = l.label  // Fails to compile because parameter `l` matches implicit argument name `l`
```

**Comment by nicolasstucki** [comment]
Similar, but fails an assertion
```scala
trait Label[A]:
  def apply(v: A): String

def g[A]: Label[A] = _.toString

inline def label[A](x: A, inline l: Label[A]): String = l(x)

def label1[A](v: A) = label(v, g)  // Compiles fine
def label2[A](l: A) = label(l, g)  // Fails to compile because parameter `l` matches implicit argument name `l`
```

```scala
java.lang.AssertionError: assertion failed: Select(TypedSplice(Typed(Inlined(EmptyTree,List(),TypeApply(Ident(g),List(TypeTree[TypeRef(NoPrefix,type A)]))),TypeTree[AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),trait Label),List(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)))])),apply) while compiling Foo.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Select(TypedSplice(Typed(Inlined(EmptyTree,List(),TypeApply(Ident(g),List(TypeTree[TypeRef(NoPrefix,type A)]))),TypeTree[AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),trait Label),List(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)))])),apply)
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
        at dotty.tools.dotc.typer.Inliner$InlineTyper.typedSelect(Inliner.scala:1198)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2388)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2478)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:124)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2548)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2549)
        at dotty.tools.dotc.typer.Typer.op$4$$anonfun$1(Typer.scala:2832)
        at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2674)
        at dotty.tools.dotc.typer.Typer.op$2(Typer.scala:2834)
        at dotty.tools.dotc.typer.Typer.tryInsertImplicitOnQualifier(Typer.scala:2837)
        at dotty.tools.dotc.typer.Applications.tryWithImplicitOnQualifier$4(Applications.scala:904)
        at dotty.tools.dotc.typer.Applications.realApply$8$$anonfun$7(Applications.scala:958)
        at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2677)
        at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:961)
        at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:999)
        ...
```
