### ISSUE TITLE
Compiler "hangs" for 1+ minutes on a one line input.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#9344]
Found an example that takes "forever" (1-2 minutes) to compile (with an error!)

## Minimized code

```Scala
// TD-184aaea3a529ccf09be73fa770e0aba21f73983c
val I1: Int = 0 * * * 8 * 1 - 1 + 1 +
```

## Output

```scala
sbt:dotty> dotc test.scala
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running (fork) dotty.tools.dotc.Main -classpath /Users/akonovalov/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.3/scala-library-2.13.3.jar:/Users/akonovalov/Documents/projects/dotty-fork/library/../out/bootstrap/dotty-library-bootstrapped/scala-0.26/dotty-library_0.26-0.26.0-bin-SNAPSHOT.jar test.scala
-- Error: test.scala:1:32 ------------------------------------------------------
1 |val I1: Int = 0 * * * 8 * 1 - 1 + 1 +
  |              ^^^^^^^^^^^^^^^^^^^^^
  |postfix operator `+` needs to be enabled
  |by making the implicit value scala.language.postfixOps visible.
  |----
  |This can be achieved by adding the import clause 'import scala.language.postfixOps'
  |or by setting the compiler option -language:postfixOps.
  |See the Scaladoc for value scala.language.postfixOps for a discussion
  |why the feature needs to be explicitly enabled.
1 error found
[error] Nonzero exit code returned from runner: 1
[error] (dotty-compiler / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 119 s (01:59), completed Jul 10, 2020 9:27:33 PM
```

## Expectation
Shouldn't take THAT long to finish.

**Comment by odersky** [comment]
I now see 22 seconds, which is not too outrageously bad given the crazy input.

**Comment by emilypi** [comment]
To add onto this ticket, these input crashes the repl: 

```scala
λ MacBook-Pro ~ → /usr/local/opt/dotty/bin/scala
Starting scala3 REPL...
scala> val I1: Int = 0 * * * 8 * 1 - 1 + 1 +                                    
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.runtime.IntRef.create(IntRef.java:22)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:182)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize$$anonfun$1(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$786/1712635211.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$1$$anonfun$1(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$853/2081703861.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize$$anonfun$1(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$786/1712635211.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at dotty.tools.dotc.ast.Trees$Tree.treeSize(Trees.scala:188)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$2(Trees.scala:184)
	at dotty.tools.dotc.ast.Trees$Tree.addSize$1$$anonfun$1(Trees.scala:185)
	at dotty.tools.dotc.ast.Trees$Tree$$Lambda$853/2081703861.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
λ MacBook-Pro ~ → 
```
