### ISSUE TITLE
MergeError thrown while ref-checking SortedMap

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#942]
```
[error] Test dotc.tests.compileStdLib failed: dotty.tools.dotc.core.Types$MergeError: cannot merge (elem: A)Boolean with (key: A)Boolean as members of type SortedMap.this.DefaultKeySortedSet(DefaultKeySortedSet.this), took 6.197 sec
[error]     at dotty.tools.dotc.core.Denotations$Denotation.mergeDenot$1(Denotations.scala:321)
[error]     at dotty.tools.dotc.core.Denotations$Denotation.$amp(Denotations.scala:334)
[error]     at dotty.tools.dotc.core.Denotations$DenotUnion.toDenot(Denotations.scala:952)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1526)
[error]     at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:416)
[error]     at dotty.tools.dotc.core.Types$Type.goThis$1(Types.scala:456)
[error]     at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:414)
[error]     at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:493)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:396)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:396)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.member(Types.scala:395)
[error]     at dotty.tools.dotc.core.Types$abstractTermNameFilter$.apply(Types.scala:3207)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$memberNames$1.apply(Types.scala:515)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$memberNames$1.apply(Types.scala:515)
[error]     at scala.collection.immutable.HashSet$HashSet1.filter0(HashSet.scala:319)
[error]     at scala.collection.immutable.HashSet$HashTrieSet.filter0(HashSet.scala:935)
[error]     at scala.collection.immutable.HashSet.filter(HashSet.scala:174)
[error]     at scala.collection.immutable.HashSet.filter(HashSet.scala:35)
[error]     at dotty.tools.dotc.core.Types$Type.memberNames(Types.scala:515)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeMemberNames$1$1.apply(SymDenotations.scala:1615)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$computeMemberNames$1$1.apply(SymDenotations.scala:1614)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeMemberNames$1(SymDenotations.scala:1614)
[error]     at dotty.tools.dotc.core.SymDenotations$ClassDenotation.memberNames(SymDenotations.scala:1630)
[error]     at dotty.tools.dotc.core.Types$Type.memberNames(Types.scala:515)
[error]     at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:531)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$abstractTermMembers$1.apply(Types.scala:537)
[error]     at dotty.tools.dotc.core.Types$Type$$anonfun$abstractTermMembers$1.apply(Types.scala:537)
[error]     at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error]     at dotty.tools.dotc.core.Types$Type.abstractTermMembers(Types.scala:536)
[error]     at dotty.tools.dotc.typer.RefChecks$.checkNoAbstractMembers$1(RefChecks.scala:386)
[error]     at dotty.tools.dotc.typer.RefChecks$.dotty$tools$dotc$typer$RefChecks$$checkAllOverrides(RefChecks.scala:533)
[error]     at dotty.tools.dotc.typer.RefChecks$Transform.transformTemplate(RefChecks.scala:802)
[error]     at dotty.tools.dotc.typer.RefChecks$Transform.transformTemplate(RefChecks.scala:768)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.goTemplate(TreeTransform.scala:867)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1184)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1011)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1212)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1238)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1183)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformNamed(TreeTransform.scala:1011)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1212)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1238)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1240)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.dotty$tools$dotc$transform$TreeTransforms$TreeTransformer$$transformStat$1(TreeTransform.scala:1240)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$38.apply(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error]     at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformStats(TreeTransform.scala:1242)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transformUnnamed(TreeTransform.scala:1192)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1213)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer$$anonfun$transform$2.apply(TreeTransform.scala:1205)
[error]     at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error]     at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.transform(TreeTransform.scala:1204)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:563)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:480)
[error]     at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:271)
[error]     at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:269)
[error]     at scala.collection.immutable.List.map(List.scala:277)
[error]     at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:269)
[error]     at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.runOn(TreeTransform.scala:474)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:60)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:57)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:57)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
[error]     at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
[error]     at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
[error]     at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
[error]     at dotty.tools.dotc.Run.compileSources(Run.scala:49)
[error]     at dotty.tools.dotc.Run.compile(Run.scala:33)
[error]     at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
[error]     at dotty.tools.dotc.Driver.process(Driver.scala:44)
[error]     at test.CompilerTest.compileArgs(CompilerTest.scala:184)
[error]     at test.CompilerTest.compileList(CompilerTest.scala:167)
[error]     at dotc.tests.compileStdLib(tests.scala:181)
```

**Comment by odersky** [comment]
It was due to overriding classes in SortedSet and SortedSetLike. I pushed a fix to dotty-library.
