### ISSUE TITLE
java.lang.ClassFormatError: Method foo in class CLibrary has illegal modifiers: 0x101

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#9432]
## Minimized code

```Scala
trait CLibrary {
  @native
  def foo(x: Int): Unit
}

object I9432 {
  def main(args: Array[String]): Unit = {
    new CLibrary {
      override def foo(x: Int): Unit = println(x)
    }.foo(1)
  }
}
```

## Output

```scala
$ java -version
openjdk version "11.0.8" 2020-07-14

$ C:\opt\dotty-0.26.0-RC1\bin\dotc.bat -deprecation -feature -d target\classes src\main\scala\I9432.scala

$ C:\opt\dotty-0.26.0-RC1\bin\dotr.bat -classpath target\classes I9432
Exception in thread "main" java.lang.ClassFormatError: Method foo in class CLibrary has illegal modifiers: 0x101
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at I9432.main(I9432.scala)

$ javap -cp target\classes CLibrary
Compiled from "I9432.scala"
public interface CLibrary {
  public static void foo$(CLibrary, int);
  public native default void foo(int);
}
```

## Expectation

Modifiers `native` and `default` (since Java 8) are mutual exclusive (see above `javap` output).

Source file `src\main\scala\I9432.scala` should not compile.

**Comment by smarter** [comment]
FYI, in scalac this fails with:
> A trait cannot define a native method.

So we're just missing an error check (which could be in RefChecks, like it is in scala 2)

**Comment by michelou** [comment]
Quick code revue gives:
- Scala 2: [RefChecks.scala:1662](https://github.com/scala/scala/blob/a507a5d2026d000fac1d33984600423a30485240/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala#L1662)
- Scala 3: [Checking.scala:467](https://github.com/lampepfl/dotty/blob/86a92e49a6107a5cc46f204a260b60c4fcc572eb/compiler/src/dotty/tools/dotc/typer/Checking.scala#L467)

@smarter In method [`checkWellFormed(sym: Symbol)`](https://github.com/lampepfl/dotty/blob/86a92e49a6107a5cc46f204a260b60c4fcc572eb/compiler/src/dotty/tools/dotc/typer/Checking.scala#L427) most `fail(..)` invocations take a `Message` as argument; what is the rule for adding new error messages like this one (file `messages.scala` is a minefield..) ?!

**NB.** The above minimized code does not provide the whole picture of my original code example which makes use of the [**JNA library**](https://github.com/java-native-access/jna). In my case the Java version works fine and I still have issues with the `native` modifier and varargs when using Dotty.

**Comment by smarter** [comment]
We try to make new message case class for new error messages, but you can instead just pass a String (there's an implicit conversion from String to Message).

**Comment by tudorv91** [comment]
Hi @smarter @michelou . I have created a PR for this issue here: https://github.com/lampepfl/dotty/pull/9799 . Can you have a look?
