### ISSUE TITLE
SBT tests are failing on nightly builds

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#9770]
https://github.com/lampepfl/dotty/runs/1099835380?check_suite_focus=true#step:9:522
```
2020-09-11T03:04:57.4594142Z [error] [info] [launcher] getting org.scala-sbt sbt 1.3.12  (this may take some time)...
2020-09-11T03:04:57.4598902Z [error] :: loading settings :: url = jar:file:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.12/sbt-launch-1.3.12.jar!/org/apache/ivy/core/settings/ivysettings.xml
2020-09-11T03:04:57.4606258Z [error] :: loading settings :: url = jar:file:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.12/sbt-launch-1.3.12.jar!/org/apache/ivy/core/settings/ivysettings.xml
...
```

https://github.com/lampepfl/dotty/runs/1099835380?check_suite_focus=true#step:9:595
```
2020-09-11T03:04:57.4833313Z [info] [error] org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.2 (supported up to: 1.1): /tmp/sbt_e5c891b5/basic/target/scala-0.28/classes/test/Main.sjsir
2020-09-11T03:04:57.4834722Z [info] [error] You may need to upgrade the Scala.js sbt plugin to version 1.2 or later.
2020-09-11T03:04:57.4836380Z [info] [error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceIRVersionNotSupportedException(ScalaJSPluginInternal.scala:83)
2020-09-11T03:04:57.4838690Z [info] [error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$16(ScalaJSPluginInternal.scala:222)
2020-09-11T03:04:57.4840304Z [info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
2020-09-11T03:04:57.4841218Z [info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
2020-09-11T03:04:57.4842065Z [info] [error] 	at sbt.util.Difference.apply(Tracked.scala:323)
2020-09-11T03:04:57.4842851Z [info] [error] 	at sbt.util.Difference.apply(Tracked.scala:303)
2020-09-11T03:04:57.4843689Z [info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
2020-09-11T03:04:57.4844542Z [info] [error] 	at sbt.util.Difference.apply(Tracked.scala:323)
2020-09-11T03:04:57.4845314Z [info] [error] 	at sbt.util.Difference.apply(Tracked.scala:298)
2020-09-11T03:04:57.4846155Z [info] [error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
2020-09-11T03:04:57.4847639Z [info] [error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$13(ScalaJSPluginInternal.scala:232)
2020-09-11T03:04:57.4849133Z [info] [error] 	at scala.Function1.$anonfun$compose$1(Func
```

**Comment by nicolasstucki** [comment]
@sjrd for the second issue we probably missed some version update in #9758. Probably in https://github.com/lampepfl/dotty/tree/master/sbt-dotty/sbt-test.

**Comment by nicolasstucki** [comment]
@smarter for the first issue. Did we update something recently? Or was it just bad luck while fetching the dependencies?

**Comment by sjrd** [comment]
> @sjrd for the second issue we probably missed some version update in #9758. Probably in https://github.com/lampepfl/dotty/tree/master/sbt-dotty/sbt-test.

Indeed! I submitted #9771 to fix that.

**Comment by smarter** [comment]
> @smarter for the first issue. Did we update something recently? Or was it just bad luck while fetching the dependencies?

Looking at https://github.com/lampepfl/dotty/runs/1099835380?check_suite_focus=true#step:9:522 the actual error is the scala.js one (there are messages in red before that but they're not error, I think github action just prints everything on stderr in red)
