### ISSUE TITLE
f-interpolator parity

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#9939]
## Minimized code

```Scala
scala> f"${3.14}%.2f rounds to ${3}%d"
1 |f"${3.14}%.2f rounds to ${3}%d"
  |                          ^
  |                          type mismatch;
  |                           found   : Double
  |                           required: Int
  | This location contains code that was inlined from rs$line$2:1

scala> f"${java.lang.Boolean.valueOf(false)}%b"   // any boxed value
1 |f"${java.lang.Boolean.valueOf(false)}%b"
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |    type mismatch;
  |     found   : Boolean
  |     required: Boolean
  | This location contains code that was inlined from rs$line$17:1

scala> f"${BigInt(120)}%d"
1 |f"${BigInt(120)}%d"
  |    ^^^^^^^^^^^
  |    type mismatch;
  |     found   : math.BigInt
  |     required: Int
  | This location contains code that was inlined from rs$line$27:1

scala> f"${BigDecimal(3.4)}%e"
1 |f"${BigDecimal(3.4)}%e"
  |    ^^^^^^^^^^^^^^^
  |    type mismatch;
  |     found   : math.BigDecimal
  |     required: Double
  | This location contains code that was inlined from rs$line$30:1

scala> f"${3L}%e"
1 |f"${3L}%e"
  |    ^^
  |    type mismatch;
  |     found   : Long
  |     required: Double
  | This location contains code that was inlined from rs$line$31:1
```

## Output

```scala
// as shown
```

## Expectation
```scala
scala 2.13.3> f"${3.14}%.2f rounds to ${3}%d"
val res0: String = 3.14 rounds to 3

scala 2.13.3> f"${java.lang.Boolean.valueOf(false)}%b"
val res0: String = false

scala 2.13.3> f"${BigInt(120)}%d"
val res5: String = 120

scala 2.13.3> f"${BigDecimal(3.4)}%e"
val res8: String = 3.400000e+00

scala 2.13.3> f"${3L}%e"
val res11: String = 3.000000e+00
```

**Comment by som-snytt** [comment]
```scala
scala> f"${0}%n"
val res1: String = "
"
```

**Comment by som-snytt** [comment]
```scala
scala> f"${0}%d"
val res9: String = 0

scala> f"${0}%%d"
val res10: String = %d

scala> f"${0}%%%d"
val res11: String = %0

scala> f"${0}%%%%d"
val res12: String = %%d

scala> f"${0}%%%%%d"
val res13: String = %%0
```
expected
```scala
scala 2.13.3> f"${0}%d"
val res21: String = 0

scala 2.13.3> f"${0}%%d"
val res22: String = 0%d

scala 2.13.3> f"${0}%%%d"
                      ^
              error: conversions must follow a splice; use %% for literal %, %n for newline

scala 2.13.3> f"${0}%%%%d"
val res24: String = 0%%d

scala 2.13.3> f"${0}%%%%%d"
                        ^
              error: conversions must follow a splice; use %% for literal %, %n for newline
```

**Comment by nicolasstucki** [comment]
I guess we should just port the implementation from Scala 2. We can port it in [`StringContextChecker`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/localopt/StringContextChecker.scala#L15-L16).

**Comment by som-snytt** [comment]
I took a few minutes to try these examples from the scala 2 tests, and a minute more to look at fixing. I'll try to make time, modulo day job and pandemic sleep schedule. It's not obvious that keeping the old code is desirable. Also, it's tiresome to hear "String.format is slow." It would be nice to have `ff` or "fast format" interpolator that compiled to pretty printers. The challenge is to support all the format features.

**Comment by b-studios** [comment]
Thanks @som-snytt for looking into it, I assigned you to the issue.

**Comment by som-snytt** [comment]
Compare
```
scala> f"x % y = ${x % y}%d"
java.util.UnknownFormatConversionException: Conversion = 'y'
  at java.base/java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2839)
  at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2865)
  at java.base/java.util.Formatter.parse(Formatter.java:2713)
  at java.base/java.util.Formatter.format(Formatter.java:2655)
  at java.base/java.util.Formatter.format(Formatter.java:2609)
  at java.base/java.lang.String.format(String.java:3292)
  at scala.collection.StringOps$.format$extension(StringOps.scala:968)
  ... 27 elided

scala> f"%y"
1 |f"%y"
  |   ^^
  |   illegal conversion character 'y'
```

**Comment by som-snytt** [comment]
Cf https://github.com/lampepfl/dotty/issues/10315

**Comment by som-snytt** [comment]
Classic example from Scanners:
```
error(f"illegal character '\\u$ch%04x'")
```
Doesn't do escaped slash, doesn't take char as int.

**Comment by som-snytt** [comment]
Noting the efficacy of `[A >: Any]` at the old ticket https://github.com/scala/bug/issues/8512
